### ISSUE TITLE
Can't view directory-listing for folders with index.html

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#1000]
Operation System: Mac OS 10.13.4
Beaker version: f88eef1

It doesn't seem like there is currently an easy way to view the directory-listing for any folder with an `index.html`. As a side-note, there does seem to be some overlap between the directory-listing and the "library-view" of a site. Maybe they should be combined?

![web-root-directory-listing](https://user-images.githubusercontent.com/916253/40397179-cf7df182-5df6-11e8-8228-d49b738d3ef4.gif)

**Comment by webdesserts** [comment]
#1000 🎉

**Comment by pfrazee** [comment]
I'm not sure this should be changed. You can always view the files using the context menu (View files) or the navbar menu (View files). The file-listing there is just designed to give a view when there's no index.html, similar to how Apache does. It would have to do a redirect to the library if we were going to unify them.

**Comment by webdesserts** [comment]
I've thought on this some more and I think my current thoughts align with @pfrazee. I don't think we should change anything (at the moment at least). However, I've dumped out my current thoughts on the matter below:

As for the longer version, I tend to at the idea of exposing these types of internals to the UI. I think my current view of these types of pages are based on my comparisons of the web with native apps. From the pure view of the web as an app platform, the exposure of individual files and directories in the UI of an application is a bit weird. This is something that you would never expect from a real app. If I want to go poke around with the internals of an application on my computer, I intentionally go to file system and browse the files there. Now that Beaker has a pseudo-fs, it really seems like there should be no need to display these types of internals in the UI.

However the web is built on the URL, an internal that is generally hidden or nonexistent for native apps. As long as that internal is exposed, we have to handle the possibility of users directly navigating to files and folders. I don't really think we can merge the "library view" with the "raw file view", or at the very least, I don't think we can merge those routes. Maybe it would be possible to bring the visuals of those two views closer together, but that might also cause confusion.

Lets say that there's two ways to view an archive: the **ui view** and the **fs view**. For applications, the ideal representation of those files would be the **ui view**. For "data dats" and similar, the ideal would probably be the **fs view**. However with todays browsers, we currently have this weird middle-ground we call a "website". They're this weird mix of UI that sometimes leaks bits of its underlying file structure.

It might be nice to cleanly separate these concepts one day. "Apps" could be these routeless, chromeless UIs and data archives could just be a folder on your file system. Just like today's computers, you could browser your apps via the file system. However, I'm going to assume we still have this idea  of a "website" in some form or fashion and as long as that's the case, I think that mix of UI & FS is here to stay.

**Comment by paul90** [comment]
As an aside, this is much the same behaviour that would be seen with a web server that allows directory viewing.

Maybe there should be an option to suppress the directory listing, outside of the library view?

**Comment by webdesserts** [comment]
@paul90 To be clear, I like directory-listings from the perspective of building websites, it's super cool that this is built into the browser now. It's only when you view directory-listings and raw files through the lens of a native-like app that they seem a bit weird.

I had played around with the idea of the `dat.json` having an option to cause directories to 404 so an SPA could use `fallback_page` there instead, but I couldn't really see a reason I would ever want to do this. With SPAs I generally shove everything other than the `index.html` under an `assets` folder and in that case it actually _would_ be nice to go and browse the assets folder if I wanted to quickly view internal js/css.

**Comment by webdesserts** [comment]
I'm going to go ahead and close this, I've pretty much convinced myself that I don't think anything should be changed here. I think that this is just a part of the weirdness of the web. The only thing I think we could possibly do is revisit some of this if y'all decide to move forward with the concept of installable "apps".

**Comment by pfrazee** [comment]
Yeah agreed
