### ISSUE TITLE
Feature Request: Forking Non-DAT Archive Websites

### ISSUE THREAD

**Issue by DTV96Calibre** [beakerbrowser/beaker#1005]
I'd like to be able to access an HTTP website in the same way as I would a DAT archive. Namely, I'd like to have a local copy of the site that I can access even when I don't have a reliable or fast internet connection. A naive approach would be to use a tool like HTTrack (GPL) to clone a website and then convert that into a DAT archive. I think if this is integrated into the UX of beaker in a similar way to the forking of dat sites, this can be a functional solution that takes advantage of the existing DAT archive features.

**Comment by pfrazee** [comment]
Yeah that'd be a pretty nice feature. I'm interested in exploring it.

**Comment by aaronshaf** [comment]
"Save page as Dat archive"

**Comment by julianpistorius** [comment]
I'd love to see this too. Potentially leveraging something like this:

https://github.com/internetarchive/brozzler
https://github.com/internetarchive/warcprox
