### ISSUE TITLE
I can't play tetris

### ISSUE THREAD

**Issue by YngDeeze** [beakerbrowser/beaker#1006]
Operating system: Mac

This is:

- [x ] a bug
- [x ] general feedback

website's don't auto-complete when typing the name (Facebook.com doesn't pop up when I press f for instance ) - Not a bug, just something I find usefull with other browsers.
Flash Player doesn't activate when I try to play tetris :(

**Comment by taravancil** [comment]
Hi there, we do have autocomplete so I’m not sure what’s going on there. As
far as Tetris goes, we don’t support plugins like flash. Sorry!

**Comment by jraspiprojects** [comment]
You could use something like this:
`const {app, BrowserWindow} = require('electron');
const path = require('path');

let mainWindow;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

let ppapi_flash_path;

// Specify flash path.
// On Windows, it might be /path/to/pepflashplayer.dll
// On OS X, /path/to/PepperFlashPlayer.plugin
// On Linux, /path/to/libpepflashplayer.so
if(process.platform  == 'win32'){
  ppapi_flash_path = path.join(__dirname, 'pepflashplayer.dll');
} else if (process.platform == 'linux') {
  ppapi_flash_path = path.join(__dirname, 'libpepflashplayer.so');
} else if (process.platform == 'darwin') {
  ppapi_flash_path = path.join(__dirname, 'PepperFlashPlayer.plugin');
}

app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);

// Specify flash version, for example, v18.0.0.203
app.commandLine.appendSwitch('ppapi-flash-version', '18.0.0.203');

app.on('ready', function() {
  mainWindow = new BrowserWindow({
    'width': 800,
    'height': 600,
    'webPreferences': {'plugins': true}
  });
  mainWindow.loadURL('http://www.adobe.com/software/flash/about/');
});`

**Comment by jraspiprojects** [comment]
I believe i can fly !github is a place for memes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jraspiprojects** [comment]
WHY I AM I DOING THIS I DON't KNOW

**Comment by jraspiprojects** [comment]
sorry that was my friend.

**Comment by pfrazee** [comment]
We'll think about adding pepper but so far we're inclined not to, because it's more overhead and it doesn't fit with how we see the Web (an open platform)

**Comment by jraspiprojects** [comment]
Also, Adobe will stop supporting flash in 2 years.

**Comment by brechtcs** [comment]
For what it's worth, http://htmltetris.com is pretty neat and doesn't require flash.
