### ISSUE TITLE
Copy selected text from file in library view

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1012]
Operation System: macOS
Beaker version: current master (0.8.0-prerelease 6)

When viewing file contents, in library view, it is not possible to copy selected contents.

While copy works if you `Edit file`, it should be possible while simply viewing it.

**Comment by pfrazee** [comment]
Thanks for reporting! I'll check into it.

**Comment by pfrazee** [comment]
Looks like this is a limitation of Ace editor's readonly mode. We either need to switch to another editor, or we need to render readonly mode differently (perhaps using a syntax highlighter).

**Comment by pfrazee** [comment]
CodeMirror seems to work with `readOnly=true` and `.CodeMirror-cursors { visibility: hidden !important }`

**Comment by pfrazee** [comment]
Okay I think I figured out a hack for this. LMK if you still have problems
