### ISSUE TITLE
Updater should not try to download drafts of new versions

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1013]
Operating system: MacOS 10.13.5 Beta

This is:

- [x] a bug
- [ ] general feedback

<img width="485" alt="screen shot 2018-05-30 at 9 26 24 am" src="https://user-images.githubusercontent.com/21236/40733964-e1ceaea8-63eb-11e8-81c5-5da237f38c63.png">

Everything else seems to load fine, probably somethnig with a backend.

**Comment by paul90** [comment]
Looks to be caused by there being a pre-release 6 on the release page, but the expected assets are not there.

Extract from the debug log
```
{ HttpError: 404 Not Found
"method: undefined url: https://github.com/beakerbrowser/beaker/releases/download/0.8.0-prerelease.6/latest-mac.yml
```

**Comment by pfrazee** [comment]
Yeah it's just a draft. The updater is incorrectly picking up on its existence. I'll update this issue to be a todo to fix that.
