### ISSUE TITLE
Circular symlinks crash beaker badly

### ISSUE THREAD

**Issue by icarito** [beakerbrowser/beaker#1014]
Operation System: GNU/Linux Debian Stretch
Beaker version: Git as of about a week ago

My dat archive had a symlink from `/heroe/dav/heroe/` pointing to `/heroe`.

This resulted in beaker leaking memory until system became unresponsive. Also 3GB of storage was consumed. Removing the symlink and restarting beaker restored the disk space.

**Comment by pfrazee** [comment]
Thanks for reporting, I'll check into this.

**Comment by fabricedesre** [comment]
fwiw, web runtimes detect redirect cycles which are quite similar. You may want to look at the data structures they use for that.

**Comment by pfrazee** [comment]
@fabricedesre Hmm well now you're making me actually think about it!

I suppose all you need is a set of visited paths which you can check. If you hit the same path twice, there's a cycle and you should abort. So you just need a memory & perf efficient set implementation, probably using some kind of hash.

**Comment by pfrazee** [comment]
Oh this is even easier than I was thinking. We can use the [inode](https://nodejs.org/api/fs.html#fs_stats_ino). Okay, I'll give cycle detection a shot.

**Comment by pfrazee** [comment]
Looking at https://github.com/soldair/node-walkdir/issues/23. They use `dev` and `ino` which I understand, but also the basename of the file and that I don't. I'll ask the author why.

**Comment by pfrazee** [comment]
I was able to add cycle detection to our base algorithm. Now I need to surface that to the user as an error.

**Comment by pfrazee** [comment]
Okay, fixed! This is what you'll see if this happens again:
![screen shot 2018-06-08 at 2 50 55 pm](https://user-images.githubusercontent.com/1270099/41178155-036cd764-6b2c-11e8-8631-84a4ee8b8e81.png)

**Comment by pfrazee** [comment]
@taravancil you should review that notification UI at some point

**Comment by taravancil** [comment]
Yeah I think I’m going to redo notifications. That’s easy to miss on super
wide screens

**Comment by taravancil** [comment]
Ok it’s red and big so not super easy to miss but I’d rather all of our
notifications be front and center
