### ISSUE TITLE
Swipe left icon stuck while using Mbpr 

### ISSUE THREAD

**Issue by ookangzheng** [beakerbrowser/beaker#1017]
Operation System: 10.13.4
Beaker version: v0.8.0-prerelease.5
<img width="1324" alt="screen shot 2018-06-01 at 17 16 56" src="https://user-images.githubusercontent.com/6301735/40833276-0e84c154-6553-11e8-9c7d-fa2ff49a8f8a.png">

**Comment by pfrazee** [comment]
Thanks for reporting. I'll review the code and see if I can figure out how this happens.

**Comment by msfeldstein** [comment]
@ookangzheng does this consistently reproduce for you?  Does it happen more often than not in certain cases?

**Comment by ookangzheng** [comment]
Sometimes when I use swipe left gesture to go back, it doesn't move, so I do it twice.

**Comment by pfrazee** [comment]
I couldn't reproduce the issue, so I added a 2 second timeout that automatically resets the gesture. Hopefully 2 seconds is long enough for people to finish the gesture. This should make sure it always gets reset, even if this glitch occurs.

LMK if any issue still persists.
