### ISSUE TITLE
Error 404 at Update

### ISSUE THREAD

**Issue by jeanFrancoisHicter** [beakerbrowser/beaker#1019]
Operating system: Windows 7

![image](https://user-images.githubusercontent.com/4332623/40837358-8a4b3ab0-659a-11e8-9efa-bd9297a32215.png)

**Comment by pfrazee** [comment]
Hey thanks for reporting! This is already reported at https://github.com/beakerbrowser/beaker/issues/1013 so I'm closing this as a duplicate
