### ISSUE TITLE
Can't force quit Beaker Browser

### ISSUE THREAD

**Issue by wakest** [beakerbrowser/beaker#1021]
Operation System: macOS 10.12.3
Beaker version: 0.8.0-prerelease.5
Doesn't show up in Activity Viewer or on command line with top. Can't use killall. Only showing up in the macOS dock, not even in command tab switcher. Seems the only way to close it is to restart my computer.

**Comment by pfrazee** [comment]
Are you sure it's active? I can't imagine what would be causing that, especially if it's not showing in the activity viewer.

**Comment by wakest** [comment]
<img width="738" alt="screen shot 2018-06-01 at 7 59 57 pm" src="https://user-images.githubusercontent.com/7890201/40855959-622fb434-65d6-11e8-960f-e81c9c7eee2b.png">

**Comment by pfrazee** [comment]
Huh. Is it possibly listed as "Electron?" What happens when you cmd+click / right-click on the dock icon?

**Comment by wakest** [comment]
"Application Not Responding" and nothing shows up wen searching for "Electron"
also to note I have it it in a folder called " Autonomy" starting with a space so it would be on the top of the list in Applications folder.

**Comment by pfrazee** [comment]
Okay good news (sort of). I managed to reproduce. Investigating now.

**Comment by wakest** [comment]
[I recorded a video of something that was happening that was hard to explain](https://dzwonsemrish7.cloudfront.net/items/3W3i0Q1C3x410Y0o1x2N/Screen%20Recording.mov)
