### ISSUE TITLE
Open this URL in another program dialog is cut off.

### ISSUE THREAD

**Issue by wakest** [beakerbrowser/beaker#1022]
Operation System: macOS 10.12.3
Beaker version: 0.8.0-prerelease.5

Open this URL in another program dialog is cut off, seems the popup width is hard coded?
<img width="552" alt="screen shot 2018-06-01 at 4 34 16 pm" src="https://user-images.githubusercontent.com/7890201/40848905-c99051ee-65c0-11e8-9e19-8b219db8abfa.png">

**Comment by pfrazee** [comment]
Fixed on master
