### ISSUE TITLE
Show percentage of data "given back" to the network

### ISSUE THREAD

**Issue by k-nut** [beakerbrowser/beaker#1023]
Trying to put into writing here what I briefly discussed with @taravancil at the Berlin p2p-event.

The cool thing about Beaker is that by visiting websites you not only consume them but you can also start giving back by seeding them. The way that you are giving back is not very visible yet right now. Other p2p apps such as transmission (see screenshot) show a ratio of the amount downloaded vs the amount uploaded. I think it would be cool to show something like this on a per website basis with beaker, too.

I also think that showing a ratio specifically could be interesting because at the point where you have reached a ratio of 1 you are effectively "giving back" more than you are "taking" which I think can be quite an empowering feeling.

I'd be happy to look into this if you agree that this might be a good idea and have any ideas for where I could start. 

![screen shot 2018-06-02 at 08 12 38](https://user-images.githubusercontent.com/1096357/40871503-084c484e-663d-11e8-9f5d-dac93d0ed170.png)

**Comment by pfrazee** [comment]
Yeah I think this is a cool idea. We'll probably want to track a lot of different stats around each dat's resource usage at some point, so that we can set policies to cap usage. This is something we could include in that.

**Comment by k-nut** [comment]
Glad you like it! Do you have any pointers for where one would start with this? Is this something to be implemented on the beaker level or can you see that there will be changes required in some other library that beaker depends on?

**Comment by pfrazee** [comment]
Yeah I'm happy to describe what I'm thinking if you want to try tackling it.

 - In the dat/library.js, I'd probably add logic for tracking stats on each archive. I'd draw from the [dat-node stats code](https://github.com/datproject/dat-node/blob/master/lib/stats.js) and probably track the transfer rate per archive (not per connection) as well as the total bytes transferred. (Other stats? Not sure.)
 - In the DatArchive Web API implementation of `getInfo()`, I'd put those stats inside the object provided to `beaker://` pages.
 - I'd put those stats somewhere in the network view of the "library-view" builtin page.

**Comment by pfrazee** [comment]
I can also imagine putting those stats in the shell-window's dropdown that shows how many peers there are.

**Comment by taravancil** [comment]
I think you might have closed the wrong issue

**Comment by pfrazee** [comment]
Shoot, yep

**Comment by todrobbins** [comment]
👍 👍 👍

**Comment by k-nut** [comment]
@pfrazee cool, I think I found a way that I can track those stats, essentially by doing something like  `archive.content.on('upload', updateCounterForArchive)`.
The next question that I have is where one would store this information? In the `archives_meta` table? Or is there a better place for it?

**Comment by pfrazee** [comment]
@k-nut yeah check out https://github.com/datproject/hyperdrive-network-speed for some tips (in fact you may be able to use that library)

I suggest just storing the stats in memory for now, and we can look at adding peristence later.

**Comment by k-nut** [comment]
@pfrazee cool, the `hyperdrive-network-speed` lib was actually where I got the snippet from. I somehow missed that it also exposes the `uploadTotal` though. 

I now created a first working version of this here: #1044. Looking forward to the feedback!

**Comment by pfrazee** [comment]
Good deal, thanks! 👍

**Comment by pfrazee** [comment]
This has been added!
![screen shot 2018-09-03 at 3 36 35 pm](https://user-images.githubusercontent.com/1270099/45001077-af3d1480-af8f-11e8-96d6-da58963b6990.png)
