### ISSUE TITLE
Windows Installer - Allow User to set (at least program) directory

### ISSUE THREAD

**Issue by parfish** [beakerbrowser/beaker#1029]
Operation System: Windows 7 Ultimate x64
Beaker version: Version: 0.8.0-prerelease.6 Electron: 2.0.2
User data: C:\Users\xxxxxxxxxxx\AppData\Roaming\Beaker Browser

When i first installed Beaker I noticed it decided for me where I wanted to install the program and from memory it didn't install it in what I regarded as a sensible location. 

I didn't mind it forcing me to use: C:\Users\xxxxxxxxxxx\AppData\Roaming\Beaker Browser for the DAT stuff, but I like to choose where my programs go, so as a test I simply moved the program files to another location and Beaker ran perfectly well from there. 

Now when I update from Version: 0.8.0-prerelease.5 to prerelease.6, Beaker is stuck in a loop whereby the update works and I can use the new version, but on restarting Beaker it reverts to the previous version and tells me there's an update available. 

SOLUTION?

Would it be possible to allow (us Windows) users to choose the location of at least the Beaker program. 
Preferably I'd also like to be able to set where the DAT data goes too.  

Cheers, 
P.

**Comment by pfrazee** [comment]
We use https://github.com/electron-userland/electron-builder to create the installer and I dont know if they support anything like that yet. I'm open to this change but TBH we have a lot of work on the todo list, and I don't think this will get high priority. I'd be open to PRs.

**Comment by parfish** [comment]
No worries. Like you say - it's not urgent. I have to say though: 
C:\Users\xxxxxxxxxxx\AppData\Local\Programs\beaker-browser
Seems an odd choice, when most 64bit software would default to: 
C:\Program Files

P.

**Comment by parfish** [comment]
Just in case anyone else is interested. It seems that the main Beaker program almost runs like a self-contained portable app. I just installed the latest version manually and then cut and pasted the program from:  
C:\Users\xxxxxxxxxxx\AppData\Local\Programs\beaker-browser
to: 
C:\Program Files\PortableApps\Web\Beaker-Browser
leaving alone:
C:\Users\xxxxxxxxxxx\AppData\Roaming\Beaker Browser

And everything works fine. 
So not such a big deal. If you move the program directory the only penalty is that you'll need to "manually" update by downloading and re-installing the later version. 

P.

**Comment by vuori** [comment]
I think installing to user profile dir is good especially in the prerelease phase. However, pushing everything including the cache into `~\AppData\Roaming` will make anyone with a roaming profile very unhappy very fast.

A quick fix would be to install everything into `~\AppData\Local` instead and worry about proper transient/permanent stuff segregation later.
