### ISSUE TITLE
Windows Build 

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#103]
Operation System:OSX
Beaker Version:Latest from Master

Is there a way to build for windows ?

**Comment by pfrazee** [comment]
Hey Fred, it *should* be possible to do by just running `npm run release` on a windows machine. If you run into any surprises, let me know. I havent tried it yet.

**Comment by pfrazee** [comment]
I just glanced at the build docs and noticed that's not right. I'll need to make a release-build command for windows

**Comment by fredhampton** [comment]
Is it possible to build for windows now ?

**Comment by pfrazee** [comment]
You still need to build from source, manually.

**Comment by rocketinventor** [comment]
On the website, it still says mac & Linux only. An actual Windows build or reference would be nice.

**Comment by pfrazee** [comment]
@rocketinventor soon, I hope

**Comment by pmario** [comment]
@fredhampton 

have a look at: https://github.com/beakerbrowser/beaker/issues/55#issuecomment-279546294 ... it's a bit hacky but worked for me. 

The problem is, that depending on your installed software, you may miss more or less dependencies.

**Comment by pfrazee** [comment]
Closing as a duplicate of https://github.com/beakerbrowser/beaker/issues/55
