### ISSUE TITLE
CPU usage of Beaker is very high

### ISSUE THREAD

**Issue by harmvandendorpel** [beakerbrowser/beaker#1030]
Operation System: MacOS 10.13.4
Beaker version: Beaker v0.8.0-prerelease.6
Computer: MacBook Pro (Retina, 15-inch)

CPU usage is peaking into the 90%+, even when Beaker is in the background and not being used.

This is what `top` shows:

<img width="830" alt="screen shot 2018-06-06 at 09 45 10" src="https://user-images.githubusercontent.com/3653507/41024175-cd604c96-696e-11e8-8cd1-c846b71a8239.png">

**Comment by harmvandendorpel** [comment]
* _Did it start after the device slept while Beaker was open?_
No, it was like that from the moment I started Beaker.

* _Do you have any large dats?_
I share one dat file, namely dat://harmvandendorpel.com/

* _Are you syncing any large folders to a dat (your "local sync" folder)?_
As far as I understand correctly, dat://harmvandendorpel.com/ is the only dat I'm syncing.

**Comment by pfrazee** [comment]
I'm fairly certain the cause is that your archive has a lot of history-data. The next version of Dat has performance improvements that should help with this sort of thing, but for now I suggest you create a new archive with the same content and replace it.

**Comment by jraspiprojects** [comment]
Same on windows 
![capture](https://user-images.githubusercontent.com/30187911/42777288-6799d338-88ee-11e8-8e55-a445dbfc3495.PNG)

**Comment by pfrazee** [comment]
@jraspiprojects that looks very much like a memory leak, or some kind of runaway memory usage. There was a fix in the latest build which fixed runaway memory usage when accessing historic versions of archives, which Fritter happened to do a lot. It might be something like that.

If you're able to reproduce it and can run a custom build, [electron supports attaching chrome's remote debugger](https://electronjs.org/docs/tutorial/debugging-main-process) and it'd be really useful if you could isolate where that memory is getting used.

**Comment by pfrazee** [comment]
(The memory leak can lead to heavy CPU usage due to frequent GCs)
