### ISSUE TITLE
Denied permission error when none is set

### ISSUE THREAD

**Issue by NicholasGWK** [beakerbrowser/beaker#1032]
Operation System: Mac OS High Sierra 10.13.3 
Beaker version: v0.8.0-prerelease.6

I seem to be getting an issue trying to use dat://profile-krismuniz.hashbase.io/# to create a Fritter profile page. I get a "user denied permission" error when I haven't done so (shows none set when I check), and I can see the prompt for a permission flashing super quickly but closes before I can click it. 
Screenshots:

<img width="766" alt="screen shot 2018-06-06 at 9 02 06 pm" src="https://user-images.githubusercontent.com/6642497/41072658-3145504a-69cd-11e8-9349-b6c3aa481239.png">
<img width="421" alt="screen shot 2018-06-06 at 8 57 33 pm" src="https://user-images.githubusercontent.com/6642497/41072660-31632b6a-69cd-11e8-8a97-8374913b4900.png">

**Comment by pfrazee** [comment]
Confirmed, was able to reproduce. Thanks for reporting. I'll see what's up here.

**Comment by pfrazee** [comment]
Fixed in master! Thanks for filing

**Comment by NicholasGWK** [comment]
Thanks for the quick fix! @pfrazee what's the best way to contribute? Would love to help with beaker/fritter/make a cool thing so people get pumped about Dat!

**Comment by pfrazee** [comment]
Always happy to have PRs, always happy to have new donors in https://opencollective.com/beaker. Issue reports are super helpful too!
