### ISSUE TITLE
Dark mode UI

### ISSUE THREAD

**Issue by KBeDevel** [beakerbrowser/beaker#1035]
Operating system: Windows 10 Pro x64 | Fedora 31 Workstation
This is: a GUI feedback.

Would be niceful a "dark" theme or mode (like Monokai theme or DuckDuckGo dark theme). BTW, Interface is very clean and simple, I love it. Good job.

**Comment by pfrazee** [comment]
Thanks! We'll put this on the feature requests.

**Comment by RangerMauve** [comment]
Maybe it should be a general "theme" API?

**Comment by pfrazee** [comment]
One thing I've been thinking about is an API/toolset for a site to declare its "settings" via JSON, and then Beaker would be able to provide a settings panel/view for the site. The site-code could pull the settings from a Web API. Themes would be doable within a toolset like that.

**Comment by RangerMauve** [comment]
So this settings API would allow a site to modify Beaker's settings?

**Comment by pfrazee** [comment]
No, it'd be a way for the site to have settings that Beaker can create an interface to. It's a developer convenience that's intended to encourage more configurable sites.

**Comment by LWFlouisa** [comment]
I do like me some dark theme defaults.

**Comment by Pawper** [comment]
Themes are cool but dark mode is also now a pretty standard system setting yeah? Is there any way we can just have Beaker inherit what our system uses, sorta like how this works? https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme Would be nice to ditch the white to help save battery / keep my laptop cooler.

**Comment by pfrazee** [comment]
Yeah this issue is for Beaker to have a dark-mode UI, and I'm +1 to doing what you're suggestion @Pawper. On the roadmap.

**Comment by wuniversales** [comment]
And is it not better to allow downloading themes and plugins for the browser?

Instead of limiting yourself to a theme, anyone who wants to install their own theme can have a firefox or chromium style shop for themes and accessories.

**Comment by Pawper** [comment]
I consider dark/light mode to be more like an accessibility and maybe battery saving solution rather than personalization. Also a single color/pattern theme can (probably should) have both dark and light modes

**Comment by KBeDevel** [comment]
Yes, dark/light modes are being adopted by thousands of programs and applications as an standard way to provide a minimal GUI personalization options (and providing a workspace context, which can be read in the viewport-side). For the other case, a theme is a style scheme. I think this could be easy to handle by using a CSS file (a usual way for browsers) or a JSON schema (as vscode does). This last could be useful to prevent "dirty code".

@wuniversales I think themes, modes and add-ons are in different orders of things. If you create a mode, then the theme should adapt to that mode or, by default, being associated with a mode, something specially useful to create different groups of themes using contexts such as "light", "dark", "high-contrast" and even modes for color vision deficiencies such as Color Blindness (aka Daltonism).

**Comment by KBeDevel** [comment]
Feature added in [pre-release 6](https://github.com/beakerbrowser/beaker/releases/tag/1.0.0-prerelease.6).
