### ISSUE TITLE
loading videos with dat://

### ISSUE THREAD

**Issue by skzap** [beakerbrowser/beaker#1036]
Beaker version: Version: 0.8.0-prerelease.5 Electron: 2.0.0-beta.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

```
<video
    poster="dat://testpic-heimindanger.hashbase.io/bitconnect.jpeg"
    src="dat://test-heimindanger.hashbase.io/file.avi">
</video>
```

When doing something like this, it seems the picture loads from dat:// but the video cant. Using the https link from hashbase for the video instead works as intended. How come it works for pictures but not videos?

**Comment by pfrazee** [comment]
@skzap try updating to 0.8.0-prerelease.6, we fixed a bug in streaming with that release

**Comment by skzap** [comment]
It does work! Thank you and congratulations :+1:
