### ISSUE TITLE
Pin Tabs number limited to 9

### ISSUE THREAD

**Issue by jeanFrancoisHicter** [beakerbrowser/beaker#1041]
Operation System: Windows 7
Beaker version: Beaker v0.8.0-prerelease.6 is up-to-date

**Comment by pfrazee** [comment]
I think this might have been a bug regarding how "too many tabs" are handled when some of them are pinned. Please reopen if you still have issues.

(Note: right now, if you have more tabs than the screen can fit, some of them won't show. We have an open TODO to add a dropdown to select the extra missing tabs.
