### ISSUE TITLE
Bookmark improvement: Show tags at top of page instead of filter

### ISSUE THREAD

**Issue by RangerMauve** [beakerbrowser/beaker#1042]
I've got a bunch of bookmarks with different tags. I've found that clicking on the filter button and then choosing a tag from the menu that pops up is a little annoying when I just want to get to the tags right away.

What do you think about having the tag list at the top of the page (maybe one line with a "see more" button) in order to speed up filtering and to make tags more useful.

**Comment by taravancil** [comment]
Hm, we'll think about it!

**Comment by RangerMauve** [comment]
Some of my reasoning here is that there are no folders for bookmarks, so it's hard to have "grouping at a glance".

However, I really like having a straight up list of bookmarks instead of folders, paired with being able to add multiple tags to them leads to being able to organize by different things at once.

Only pain point is not having the tags available at a glance, though of course the filter is doing a great job of fulfilling that in the meantime.

**Comment by blahah** [comment]
+1 for this, the bookmarking in Beaker is potentially extremely valuable. It's currently missing some key things - personally I think the best way to solve it would be to expose bookmarks as a DatArchive with particular privacy controls so that people can choose to build their own interfaces for it (I've done this as a local hack for now).

**Comment by RangerMauve** [comment]
Storing browser related stuff like settings / bookmarks in a dat is something I've been craving for a while. Then you could easily keep your devices in sync without having to rely on a central authority.

This would probably be blocked by having multiwriter support, though.
