### ISSUE TITLE
Need UI / Screen to change default directory

### ISSUE THREAD

**Issue by sanjayfgeorge** [beakerbrowser/beaker#1043]
Operating system: Windows Version	10.0.16299 Build 16299

This is:
- [x] general feedback

Not able to get the screen where I can change my default directory - which I saw while installing the first time. Tried to uninstall and reinstall many times but to no avail. I don't know where it has installed as a site from where I wish to remove the existing files and clean up my machine before I install it properly in the directory of my choice for which I was searching when the window lost the original path and stayed on the last path I had selected. Rather annoying as I just wanted to install it in the D: directory with the same directory path  or folder names which I lost when I clicked on the  D: drive icon.

Now I don't know if it has installed the server.
If so , I don't know where it has installed it (I want to delete this directory and remove references to it in the configuration files).
When I reinstall the software the dialog window asking me my choice of directory no longer appears.

**Comment by pfrazee** [comment]
What version of Beaker are you using?

Is it possible the default directory control you're thinking about is this?

![screen shot 2018-06-14 at 11 03 40 am](https://user-images.githubusercontent.com/1270099/41424084-b0b711ba-6fc2-11e8-823b-f1749edc8dc3.png)

This is in the settings page, and it's the same control that shows up on first run. It lets you choose where new sites are created, by default, but it doesn't move any existing sites.
