### ISSUE TITLE
Wiki: broken link

### ISSUE THREAD

**Issue by aral** [beakerbrowser/beaker#1046]
On https://github.com/beakerbrowser/beaker/wiki/Is-Dat-a-%22secure%22-protocol%3F – the link for the link that reads “link” (at the bottom of the page) is broken.

It would be better to link the actual text while fixing this. e.g.,

```markdown
There's [a valuable dissection of the state of passive monitoring in Dat](<LINK>) written on the Dat blog: link.
```

**Comment by pfrazee** [comment]
Fixed, thanks!
