### ISSUE TITLE
Donate link feature doesn't support relative URLs

### ISSUE THREAD

**Issue by HughIsaacs2** [beakerbrowser/beaker#1048]
![donate-error](https://user-images.githubusercontent.com/6512122/41510041-d99d34b8-722b-11e8-8ea9-afeed712b53c.png)

If a Dat site has a relative URL set as the Donate link, clicking it sends the user to beaker://shell-window/{the URL}.
So setting it to something like /donate/ sends the user to [beaker://shell-window/donate/](beaker://shell-window/donate/).

**Comment by pfrazee** [comment]
Thanks for filing, I'll get that fixed up

**Comment by pfrazee** [comment]
Fixed

**Comment by figueredo** [comment]
This is broken on master, but now it opens a blank tab that can't be closed. Should I open another issue or should this one be reopened?

Btw, I already have a fix for that :)
