### ISSUE TITLE
Built in pages are missing

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#1049]
Operating System: Mac OS 10.13.5
Beaker Version: No clue can't get to the settings page lol

This is a good one.

<img width="901" alt="screenshot 2018-06-17 17 25 09" src="https://user-images.githubusercontent.com/916253/41512700-aacb486e-7253-11e8-82c9-f0a83e006fd3.png">

<img width="900" alt="screenshot 2018-06-17 17 26 37" src="https://user-images.githubusercontent.com/916253/41512702-ac48d828-7253-11e8-96ee-cdc2f355b72c.png">

**Update** after I restart the browser, everything seems to work again.

**Comment by webdesserts** [comment]
I'll close this as it seems to have resolved itself, feel free to repoen if you're concerned about it.

**Comment by pfrazee** [comment]
Hmm. Was that in a prebuild?

**Comment by webdesserts** [comment]
@pfrazee after a reload I'm on prerelease.6, though I'm pretty sure I've been on that version since it was released.

I went back to trying to use Beaker as my main browser again, so it's been running awhile. Coooould possibly be something related to that.

**Comment by webdesserts** [comment]
@pfrazee If I run into it again I'll reopen. Maybe I can open up the shell window devtools and check for an error there.

**Comment by fwip** [comment]
Currently experiencing this issue, I think. `beaker://library/` loads fine, but `beaker://settings/` is as shown above. Mac version is `10.12.6`, and I /think/ my beaker version is also prerelease 6.

I don't see anything shown in the devtools console, and the two network requests (`font-awesome.css` and `fontawesome-webfont.woff2` are working fine.  I have no other ideas on how to debug it.

**Comment by webdesserts** [comment]
@fwip Have you tried restarting Beaker (that's what worked for me)? Or does it persist across browser sessions?

**Comment by fwip** [comment]
Restarting Beaker did solve the problem, yes.
