### ISSUE TITLE
Search highlighted text loses "non-ascii" characters

### ISSUE THREAD

**Issue by DTV96Calibre** [beakerbrowser/beaker#1050]
Operation System: All of them
Beaker version: Probably the latest
I implemented the original search highlighted text feature in Beaker s while back and realized just now that
`https://duckduckgo.com/?q=C#` loses the `#` when DuckDuckGo performs the search. My implementation just appends the highlighted text after `duckduckgo.com/?q=` so it must also suffer from this shortcoming.
This can be addressed by converting applicable characters into a standard code described here https://www.w3schools.com/html/html_urlencode.asp
I'm at work so I'm leaving this here to address later.

**Comment by DTV96Calibre** [comment]
The best solution seems to be to use the built-in encodeURIComponent function. 
See: 
https://stackoverflow.com/questions/75980/when-are-you-supposed-to-use-escape-instead-of-encodeuri-encodeuricomponent

**Comment by pfrazee** [comment]
Fixed, thanks!
