### ISSUE TITLE
local folder path in the address bar

### ISSUE THREAD

**Issue by davidbenque** [beakerbrowser/beaker#1051]
Operating system: OSX Sierra 10.12.6

This is:

- [ ] a bug
- [x] general feedback

It would be great to have the option to collapse the local folder path in the address bar. It's useful but it gets in the way of when you have a long path.

<img width="747" alt="screen shot 2018-06-19 at 11 35 21" src="https://user-images.githubusercontent.com/11028490/41592637-198ecd04-73b5-11e8-862e-d750a5f64367.png">

**Comment by pfrazee** [comment]
Haha wow. Yeah we'll need to put a length limit on that. Thanks for reporting!

**Comment by pfrazee** [comment]
Fixed with 2ae3c13d1d2b36059b3034dadc71daa73ba39cfb
