### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by xtianjohns** [beakerbrowser/beaker#1053]
Let's add a code of conduct to the Beaker repo! The P2P web community is a big tent, I'm not saying we need to circumscribe acceptable behavior when _using_ Beaker. But a least on engaging in issues, pull requests, events, livestreams, meet ups, etc., I think it makes sense for the community to thoughtfully consider its standards of acceptable behavior.

I'm happy to work on a PR, but perhaps it's better to start a conversation first about what is worth including and in particular what is important to @pfrazee and @taravancil on these questions.

The community already seems great, let's make sure we keep it that way!

Operation System: *
Beaker version: *

**Comment by pfrazee** [comment]
Does anybody have a CoC that they think we should look at? Here are some I found

 - [Nodejs CoC](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md)
 - [Rust CoC](https://www.rust-lang.org/en-US/conduct.html)
 - [Citizen CoC template](http://citizencodeofconduct.org/)

**Comment by xtianjohns** [comment]
Github's CoC template comes from [The Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct). I think it is worth looking at because it is an opportunity to borrow language from a template/standard that many folks on Github would be familiar.

I also checked out CoCs from other browser projects (like [Chromium](https://chromium.googlesource.com/chromium/src/+/master/CODE_OF_CONDUCT.md)), but found that there was lots of language specific to the project or domain. That's probably a good thing, but makes it harder to use them as templates/guides.

FWIW I find a lot to like in Rust's CoC. It is

1. **Explicit.** Using specific language when describing harassment and enforcement helps prevent situations where people feel that the code of conduct is open to interpretation. If the CoC is ambiguous, it can make any maintainers appear to be arbitrary, showing favoritism, or that it insufficiently protects members of socially marginalized groups.

> _We will exclude you from interaction if you insult, demean or harass anyone._

> _We interpret the term “harassment” as...._

> _Private harassment is also unacceptable._

2. **Affirmative.** It is not just a list of what not to do, or a list of punishments for various offenses. It affirms what values are important to the community. This provides a positive statement of values, from which specific statements about harassment or exclusionary behavior can be made.

> _We are committed to providing a friendly, safe and welcoming environment for all...._

> _Whether you’re a regular contributor or a newcomer, we care about making this community a safe place for you and we’ve got your back._

> _In the Rust community we strive to go the extra step to look out for each other._

**Comment by taravancil** [comment]
Yeah same. Most of the unsavory behavior we see comes from passers-by, not active contributors. 

It'd be great in those situations to be able to point to our CoC and say "Hey that's not how we do things around here so please respect that or leave"

**Comment by pfrazee** [comment]
How do we feel about https://github.com/beakerbrowser/beaker/pull/1062 ?

**Comment by pfrazee** [comment]
Done!
