### ISSUE TITLE
Page with video causes "Failed to query stereo recording" error.

### ISSUE THREAD

**Issue by richardmacduff** [beakerbrowser/beaker#1054]
Operation System: Ubuntu 16.04 LTS
Beaker version: Version: 0.8.0-prerelease.6 Electron: 2.0.2 - Chromium: 61.0.3163.100 - Node: 8.9.3

Hello!

Loading this page:

>[Naomi Wu on SubscribeStar](https://www.subscribestar.com/naomi-wu)

causes ths error message to be printed on stderr

> `[5567:0625/214251.444665:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.`

The video is not of the self-starting kind.

No error dialog in the front end. The video can be started and plays without problems.

Thank you.

**Comment by pfrazee** [comment]
We get errors periodically from electron/chromium core in stderr. It never seems to be an issue. Is this creating any problems with the page?

**Comment by richardmacduff** [comment]
well no, the page runs as expected. I was puzzled by the idea of the browser attempting to access recording resources when requested to play a video

**Comment by pfrazee** [comment]
Yeah, I'd have to dig into the electron or chromium internals to figure out why that's happening. I doubt it's something to worry about.

**Comment by EbramTawfik** [comment]
the same issue Mac OS audio can't be captured :
navigator.mediaDevices.getUserMedia( { audio: { mandatory: { chromeMediaSource: 'desktop' } }, video: { mandatory: { chromeMediaSource: 'desktop' } } }

I got this :
ERROR:adm_helpers.cc(73)] Failed to query stereo recording.

**Comment by hidmantra** [comment]
I noticed that this is closed? Just saw the issue today. OSX 10.14.4 using electron quickstart.. to load video from external URL. details:

[95290:0423/143149.593792:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
[95291:0423/143150.550419:ERROR:adm_helpers.cc(73)] Failed to query stereo recording.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

as mentioned by others above, no apparent issue per say but pretty darn scary! I mean it actually attempted to start Jack server and if I hadn't screwed up the Jack installation I feel like audio of me would have went somewhere.
