### ISSUE TITLE
Unicode characters not displaying correctly in log views (e.g. beaker://debug-log)

### ISSUE THREAD

**Issue by aral** [beakerbrowser/beaker#1058]
Operation System: macOS 10.13.5 (17F77)
Beaker version:  v0.7.11 

<img width="1136" alt="screen shot 2018-06-27 at 10 03 02" src="https://user-images.githubusercontent.com/41798/41964415-cbb57874-79f1-11e8-9011-47a04fbfadf7.png">

The highlighted section in the above screenshot should read:

```
description: 'Aral’s notes',
```

**Comment by pfrazee** [comment]
Okay I think I've fixed this in our current working branch (randomly, `draft-mode-rebased`)

**Comment by pfrazee** [comment]
Thanks for reporting! LMK if it comes up again
