### ISSUE TITLE
External links open 2 tabs on Quora.com

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#106]
For some reason, links to other pages on Quora open two tabs. y tho.

**Comment by pfrazee** [comment]
This appears to be caused by the API changes made by electron (http://electron.atom.io/docs/api/window-open/) which ought to be removed.

**Comment by sptechrao** [comment]
Thank you for sharing such a great blog to us. [SAP ABAP training institutes in hyderabad](url) ![ sap course in hyderabad!](url)
