### ISSUE TITLE
dat:// sites time out even with firewall off

### ISSUE THREAD

**Issue by timdisher** [beakerbrowser/beaker#1061]
Operation System: Mac OS 10.13
Beaker version: 0.8.0-prerelease.6

Not able to connect to any dat:// sites from beaker installed in Macbook air (time out). Able to connect from my Windows PC from the same network. Tried allowing beakerbrowser in firewall and even just disabled it entirely but no luck.

**Comment by pfrazee** [comment]
Hmm. Are you able to:

 - On your mac, connect to dat sites hosted on your windows PC on the same network?
 - On your PC, connect to dat sites hosted outside the network?

**Comment by timdisher** [comment]
No to first, yes to second. Also can't connect to dat sites hosted on mac from PC

**Comment by pfrazee** [comment]
@timdisher I hate to make this suggestion but have you tried rebooting your router?

**Comment by timdisher** [comment]
I will try accessing from another network. Accessing through hospital network so rebooting router is slightly less straightforward!




Sent from my Samsung Galaxy smartphone.


-------- Original message --------
