### ISSUE TITLE
Idea: "safe mode" tab

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1065]
Ability to open a "safe-mode" tab with more restricted security policies, eg no javascript, or no third-party domain requests.

Use-case: diagnostically exploring a site that you don't trust. It might be good for "safe browsing" too, and could have similar effects to ad-blockers.

Additional idea: Maybe when you open the safe-mode tab, the tab goes to a start page where you configure how restrictive the policies will be.

**Comment by jraspiprojects** [comment]
Maybe for the slider, it can have the same levels as Tor has: [https://en.wikipedia.org/wiki/Tor_(anonymity_network)#Levels_of_security](https://en.wikipedia.org/wiki/Tor_(anonymity_network)#Levels_of_security)
