### ISSUE TITLE
Dat://DatProject.org / No DNS Record found

### ISSUE THREAD

**Issue by TungBox** [beakerbrowser/beaker#1066]
Operation System: Mac OS X
Beaker version: Beaker v0.8.0-prerelease.6 is up-to-date
Screenshots: https://i.imgur.com/WIYTCB0.png

**Comment by joehand** [comment]
Oop, thats on me =). Forgot to publish a new well-known file when I moved the site. Will update and set a DNS record.

**Comment by jraspiprojects** [comment]
Still doesn't work

**Comment by joehand** [comment]
Oop forgot, just added a txt record. The dat is at `dat://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330`.

**Comment by joehand** [comment]
Also pushed a well-known file for backup.
