### ISSUE TITLE
draft-mode-rebased, tested with ubuntu ... ready for feedback?

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1067]
Operation System: ubuntu 18.04
Beaker version: draft-mode-rebased branch commit d4fe0bcd66fd54a2abec50b72a97fd0634b23319

Is the development far enough to start posting issues, or do you need more time?

**Comment by pfrazee** [comment]
We need more time. Lots of final touches to finish.

**Comment by taravancil** [comment]
Absolutely not ready for feedback. Most of our dev branches are Paul and I
experimenting and iterating.

**Comment by pmario** [comment]
bump?
