### ISSUE TITLE
Rename Finder to Explorer on Windows.

### ISSUE THREAD

**Issue by jraspiprojects** [beakerbrowser/beaker#1068]
Operation System: Windows 10
Beaker version: Latest

You need to change Open in Finder to Open in explorer on windows, because we don't have finder, only explorer.exe

**Comment by pfrazee** [comment]
Good idea, added to our TODOs

**Comment by jraspiprojects** [comment]
Where would "Open in Finder" or the downloads page be in the source?

**Comment by jraspiprojects** [comment]
Just do 
`if (process.platform == "win32"){
 actions = [ actions = [
          yo`
            <span class="link show" onclick=${e => { e.stopPropagation(); downloadsList.showDownload(d) }}>
              Show in Explorer
            </span>
]} else {actions = [
          yo`
            <span class="link show" onclick=${e => { e.stopPropagation(); downloadsList.showDownload(d) }}>
              Show in Finder
            </span>
]}`

**Comment by jraspiprojects** [comment]
Hmm, can't get code formatting to work correctly

**Comment by jraspiprojects** [comment]
@pfrazee I made a PR, feel free to look at it and fix any formatting errors...

**Comment by pfrazee** [comment]
Fixed in master
