### ISSUE TITLE
downloads tab shows empty locked page instead of downloads items

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1070]
Operating system: windows 7/10

This is: when i open "downloads" tab in the browser, it shows nothing(even if i previously downloaded many things).

- [x ] a bug
- [ ] general feedback

**Comment by pfrazee** [comment]
This sounds like a bug that we've been getting random reports of, where builtin pages just fail to load for no apparent reason. We'll keep this one open and see what we can figure out.

Try restarting beaker and see if it still happens.

**Comment by arni077** [comment]
@pfrazee yes,starting beaker again solved it.

**Comment by arni077** [comment]
@pfrazee by the way,  restarting the browser not always solves it. the problem still exist.
there is a second issue here that the user can't choose manually the location of "download" folder which he wants the browser download things.
third issue is a major: the browser never asks for user permission if to download something- many times a uer might click 'redirct' links and beaker download those automatically which is also might be  a dangerous experience.

**Comment by pfrazee** [comment]
I'll open additional issues for the other two problems.

When the page blanks out, do any other builtin pages have the same problem? Start page, library, etc?

**Comment by arni077** [comment]
no.

**Comment by jraspiprojects** [comment]
This also happens to me 1/2 of the time I open beaker://downloads

**Comment by pfrazee** [comment]
Okay I managed to reproduce this. Occasional null reference on the downloads page. I think it's fixed in master. Reopen after the next release if this is still happening.
