### ISSUE TITLE
Zoom feature is missing

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1071]
Operating system: windows 7

This is: critical feature like zooming webpages should have been added.

- [ ] a bug
- [x] general feedback

**Comment by taravancil** [comment]
Not sure what you mean. We do have a zoom feature!

**Comment by arni077** [comment]
If this is true,then,My beaker browser wont show it then.

**Comment by pfrazee** [comment]
What version of beaker are you using, and how are you trying to trigger it?

**Comment by arni077** [comment]
Version: 0.8.0-prerelease.6 Electron: 2.0.2 - Chromium: 61.0.3163.100 - Node: 8.9.3
I'm not sure what you mean by trigger it. anyway, i just simply browse it

**Comment by RangerMauve** [comment]
I've actually got this on my machine at the moment, too.

Version: 0.8.0-prerelease.6 Electron: 2.0.2 - Chromium: 61.0.3163.100 - Node: 8.9.3

I've been having trouble with preserving tabs on reloading, so I'm not going to be able to restart any time soon. :P

I could have sworn it was working before, too.

**Comment by pfrazee** [comment]
@RangerMauve Zoom just doesnt work?

**Comment by pfrazee** [comment]
By trigger it I mean, are you trying cmd/ctrl+`+` ?

**Comment by RangerMauve** [comment]
Oh wow. It seems that zooming _in_ doesn't work. (ctrl + `+`), zooming out (ctrl + `-`) worked for me.

When I was testing, I only tried to zoom in. 😅

Also the usual ctrl + `scroll wheel` doesn't work.

**Comment by RangerMauve** [comment]
I'm on Windows 10 if that makes a difference.

**Comment by arni077** [comment]
@pfrazee the zoom icon do not showing on the browser at all. i tried also ctrl++ to trigger it - it doesnt work either.
![no zoom](https://user-images.githubusercontent.com/40802098/42534155-a2f23db6-8494-11e8-8128-d7b9fe9ac11f.png)

**Comment by taravancil** [comment]
Weird, ctrl ++ is working for me right now. Can you confirm whether View -> Zoom In is working as expected?

**Comment by RangerMauve** [comment]
I don't have anything that says "View" in the hamburger menu, is there supposed to be a menu at the top?

**Comment by fenwick67** [comment]
@arni077 @RangerMauve  I had to use `ctrl`+`shift`+`+` to get it to work (Windows 10). Do that cause zoom to work for you?

**Comment by RangerMauve** [comment]
@fenwick67 Oh wow. So I can zoom in with `ctrl`+`shift`+`+`, but I need to zoom out with `ctrl`+`-`

😅 That's pretty exciting.

**Comment by pfrazee** [comment]
Thanks @fenwick67 for opening the zoom shortcut bug. That's definitely wrong.
