### ISSUE TITLE
unable to print or save page

### ISSUE THREAD

**Issue by RogueAnt** [beakerbrowser/beaker#1075]
Operating system:linux (xubuntu)

This is:

- [X] a bug
- [ ] general feedback

no response to ctl-P or ctl-S

no useful response to right-click choices

**Comment by taravancil** [comment]
Thanks for reporting!

It looks like we definitely haven't enabled Ctrl-P. As a debugging note, Ctrl-S works for me on macOS.

**Comment by pfrazee** [comment]
I've added printing in our dev branch
