### ISSUE TITLE
A loading screen when beaker starts

### ISSUE THREAD

**Issue by jraspiprojects** [beakerbrowser/beaker#1077]
Operation System:
Beaker version: not needed
When beaker starts, i get a black screen, and then the beaker:start page loads.

Instead of the black screen, have a nice loading screen

**Comment by jraspiprojects** [comment]
BeakerBrowser-prerelease 6

**Comment by pfrazee** [comment]
I checked into this and I dont think we have a way to do it. The window is unpaintable (white) until we're loaded.

**Comment by pfrazee** [comment]
I found an alternative that works pretty well - we just dont show the window till it's ready.
