### ISSUE TITLE
Does the beaker browser support PHP?

### ISSUE THREAD

**Issue by jraspiprojects** [beakerbrowser/beaker#1078]
Does the beaker browser dat/web hosting thing support PHP and the mysqli extension with it?

**Comment by pfrazee** [comment]
Nope! And we don't plan to include that. If you want to dynamically render the page, you can do so at runtime using javascript

**Comment by jraspiprojects** [comment]
And by the way beaker browser is eating my cpu usage
![capture2](https://user-images.githubusercontent.com/30187911/42777706-b918ab02-88ef-11e8-99f4-e04acf6ecba0.PNG)

**Comment by pfrazee** [comment]
I responded in another issue, looks like a memory leak
