### ISSUE TITLE
Difficulty connecting to peers

### ISSUE THREAD

**Issue by altneujlm** [beakerbrowser/beaker#1081]
Operation System: Win7 Pro
Beaker version: 0.8.0-prerelease.6

Built DAT site in Beaker Browser. I can see it (locally proly) but no one else can. They get a time out in the connection. Same the other way around, I can't see their files either.

Tried: 
checked it out both with and without WIN firewall (two instances of Beaker incoming connection rule do exist in the frewall listing)
increasing timeout on my site in index.js
built an archive on hashbase.io
restarting router :)

URL of hashbase archive:
https://hashbase.io/altneu/altneu

DAT of the same page:
dat://a8d17b9cf3c3e33f5598de4219788e1e957b9a040d4b42a41fdb79bc067e3404/

*We are tesing it on most basic ISP account(s) and hardware.

P.S. I know there can be a million reasons for this, so I am not looking for a definitive answer, just reporting. ;) Thanks.

**Comment by altneujlm** [comment]
Yah, sync with hashbase worked fine, the archive size is wrong tho, it states 100MB.
My friend and I are testing it from home, as I said, basic ISP, lowest speeds and all that.

**Comment by pfrazee** [comment]
100mb is too large, right? If that's the case, Dat is a versioned protocol, and currently Hashbase retains all history. (That may eventually change.)

Typically dat/beaker work on a home network so I'm not sure what could be happening! Our connection establishment still needs a lot of work, and we're talking about getting some proxy services online to help with the hopeless cases.

**Comment by altneujlm** [comment]
Right! The versions! Forgot about that.
As I said, it can be a million things ;) so no biggy. I'll try it from more machine/ISP combos to see what's up.

 I love the concept BTW, as a long time developer I see the immense potential of this, would love to develop something with it when I get it to work properly. Thanks for the work!

**Comment by RangerMauve** [comment]
Might be related to https://github.com/mafintosh/dns-discovery/issues/16

@altneujlm What's the result of your `ipconfig` command on Windows?

There's a bug with DNS-discovery where it only advertises your first local IP address. So if you have something other than wi-fi as the first network adapter, it'll prevent you from discovering local peers.

**Comment by pfrazee** [comment]
Thanks @RangerMauve. That issue slipped through the cracks on me.

And thanks @altneujlm! I hope we can get the reliability there soon

**Comment by altneujlm** [comment]
i am not on wi-fi, ethernet cable.

**Comment by RangerMauve** [comment]
Is the ethernet interface the first one in the list in `ipconfig`?

**Comment by altneujlm** [comment]
yup, Ethernet adapter Local Area Connection

**Comment by RangerMauve** [comment]
Dang, probably not a problem with local IP, then. 😅

**Comment by altneujlm** [comment]
I may be out of my league here but I thought that maybe Dynamic IPs assigned to us users by the ISP could be the problem?
