### ISSUE TITLE
Determine if a site is saved in a user's library

### ISSUE THREAD

**Issue by nickbytes** [beakerbrowser/beaker#1083]
I'm wondering if it's possible to tell if a user is a peer of a site.

Example: I wanted to create a p2p publication where viewers may only view content (or portions of content) if they are a long-term seeder. 

I imagine this would involve being able to view the user's Library on a high level. 

re: conversation with @pfrazee in IRC, it doesn't sound like this is currently possible, but may be possible soon with an experimental API.

Operation System: not applicable
Beaker version: not applicable

**Comment by pfrazee** [comment]
I'm wondering if we could include this information in the response from https://beakerbrowser.com/docs/apis/dat.html#getinfo. Something like `isSaved`.

We need to figure out whether we consider there to be a risk with including that information.

**Comment by nickbytes** [comment]
> I'm wondering if we could include this information in the response from https://beakerbrowser.com/docs/apis/dat.html#getinfo. Something like isSaved.

I like this idea.

> We need to figure out whether we consider there to be a risk with including that information.

Do you have any initial thoughts on the risk? Is it mostly that conceptually it is an invasion of privacy to expose what a user may/may not wish to save to their library?

**Comment by pfrazee** [comment]
> Is it mostly that conceptually it is an invasion of privacy to expose what a user may/may not wish to save to their library?

Yeah I think so. And also the risk that it could be used to fingerprint the user. It might be okay if the site could only learn that info about itself, ie "have I been saved?"

**Comment by nickbytes** [comment]
Learning info only about itself sounds more reasonable/safer to me.

**Comment by nickbytes** [comment]
Looks like the ability to do this landed in experimental APIs:
- https://beakerbrowser.com/docs/apis/experimental-library#list
- https://beakerbrowser.com/docs/apis/experimental-library#get

I'd like to leave this issue opened for further discussion if possible.

**Comment by pfrazee** [comment]
Sure thing
