### ISSUE TITLE
Configurable DNS-over-HTTPS provider

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1086]
Related: https://github.com/datprotocol/DEPs/issues/37

We should make the Dat DNS-over-HTTPS providers configurable in the settings page. Ideally you could specify multiple endpoints and Beaker would use them at random.

**Comment by da2x** [comment]
Ideally, people should be able to set their own setting and ideally every request should be sent to a randomly selected provider. [datprotocol/dat-dns/pull/11](https://github.com/datprotocol/dat-dns/pull/11) goes some ways towards this by randomly choosing to use either Cloudflare DNS, Google DNS, or Quad9 for the duration of the datDns instance session.

**Comment by skynebula** [comment]
Any new on that topic?
Thanks!

**Comment by pfrazee** [comment]
@da2x's PR with the random providers has been merged. Adding the config page is next.
