### ISSUE TITLE
Running multiple Beaker instances from a non-default directory

### ISSUE THREAD

**Issue by 26000** [beakerbrowser/beaker#1090]
Would be nice to have a command-line argument to use another configuration directory. As for now, I can set `$XDG_CONFIG_HOME` to anything, but this way it looks for GTK3 config and PulseAudio cookies there, which is inconvenient.

**Comment by pfrazee** [comment]
Does BEAKER_USER_DATA_PATH do what you need? https://github.com/beakerbrowser/beaker#env-vars

**Comment by 26000** [comment]
Oh, it does! Sorry for a silly question then, I overlooked it in docs. Thank you!
