### ISSUE TITLE
Ability to increase default seeding duration

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#1093]
By default I'd love to seed/host Dats that I connect to for longer than just when I visit.

**Comment by pfrazee** [comment]
@aaronshaf That's interesting, what might you pick as your default?

**Comment by aaronshaf** [comment]
A day or a week. Something more ... altruistic. :-D 

Another option would be to indefinitely seed/host such sites up to X mb of storage, etc

**Comment by pfrazee** [comment]
Yeah I think those are both neat ideas. We might group them under "seeding policies" or something like that. cc @taravancil

**Comment by RangerMauve** [comment]
I think that the slider used for choosing how long you seed for should be there in the network settings.

So by default it'll be set to "while visitng", but you can go into the settings to change that.
