### ISSUE TITLE
Beaker Browser Crash when Downloading file

### ISSUE THREAD

**Issue by ampersanda** [beakerbrowser/beaker#1096]
Operation System: macOS Mojave 10.14 Beta (18A336e)
Beaker version: 0.8.0-prerelease.7

Here's the video

https://youtu.be/UkPdtbJLWVk

I don't know what to explain more

**Comment by pfrazee** [comment]
Thank you for the video! I'm having trouble reproducing unfortunately, but I'm on 10.12 so it might be related to that.
