### ISSUE TITLE
Beaker fails to start when offline

### ISSUE THREAD

**Issue by rjsteinert** [beakerbrowser/beaker#1098]
Operation System: Mac OS X
Beaker version: v0.8.0-prerelease.7

When starting Beaker offline, it fails to load.

<img width="1280" alt="screen shot 2018-08-01 at 9 33 19 am" src="https://user-images.githubusercontent.com/156575/43528353-bfb8fbf4-9576-11e8-9b26-f810abb49f7f.png">

**Comment by pfrazee** [comment]
I can't seem to reproduce this (Mac OS 10.12) so I'll leave this open, if anybody can reliably trigger it let me know what steps you took

**Comment by rjsteinert** [comment]
This is happening on a Mac with macOS 10.12.6 however not on a mac with 10.13.6. My guess is this is something special I may have done with my installation. I'll try reproduce again later and try to grab some logs.
