### ISSUE TITLE
Keyboard shortcuts for navigation

### ISSUE THREAD

**Issue by pppq** [beakerbrowser/beaker#1100]
Operating System: Windows 10
Beaker version: v0.8.0-prerelease.7

My muscle memory led me to trying `Alt` + `←`/`→` for navigating to recently visited pages. It would be nice if Beaker supported these shortcuts.

**Comment by jraspiprojects** [comment]
i think beaker does and its <code>CTRL</code> and <code>Tab</code>OR<code>Shift-Tab</code>

**Comment by pppq** [comment]
Tab navigation works fine, I think `Ctrl` + `PgUp`/`PgDown` also works for them; the ones I'd like to use should be bound to the first two buttons on the toolbar.

**Comment by pfrazee** [comment]
In beaker we use ctrl/cmd + left/right to navigate

**Comment by pppq** [comment]
OK, thanks. Those keys do work (also `Ctrl` + `[` and `]`).

To make it easier for new users accustomed to mainstream browser UX, these shortcuts could be made platform-dependent; see eg. https://support.google.com/chrome/answer/157179 for Chrome's keybindings list (under the "webpage shortcuts" section). I understand if it is not a priority for the time being (or at all).
