### ISSUE TITLE
sudden uninstall

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1102]
Operation System: windows 7
Beaker version: 0.8.0-prerelease.6

after closing the browser i noticed beaker icon has changed like it was uninstalled suddenly,i clicked the icon and got the response "can't find the location".

**Comment by pfrazee** [comment]
Thanks for reporting. I'll check into this.

**Comment by RangerMauve** [comment]
It could be that the icon in the taskbar was removed because it changed to the new logo.

Try searching for beaker using the file search feature in the start menu.
