### ISSUE TITLE
Maximise on windows does not always fully maximise

### ISSUE THREAD

**Issue by matt1** [beakerbrowser/beaker#1108]
Operation System: Windows 10
Beaker version: Version: 0.8.0-prerelease.7 Electron: 2.0.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

When maximising on windows, the first time you maximise it maximises as expected.  If you then unmaximise, and remaximise again, it does not fully maximise to the top of the screen.   If you unmaximise and remazimise again, it returns to proper maximisation.  This pattern appears to repeat over and over.

**Comment by matt1** [comment]
Might be a problem with electron - other electron apps do the same thing (e.g. github desktop)

**Comment by pfrazee** [comment]
Okay thanks for reporting, I'll check into this.
