### ISSUE TITLE
"No DNS record found"

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beaker#1114]
Operation System: macOS High Sierra 10.13.6
Beaker version: v0.8.0-prerelease.7

### steps to reproduce

go to dat://dcpos.ch in the latest prerelease Beaker

![screen shot 2018-08-08](https://user-images.githubusercontent.com/169280/43833711-8efdfe48-9ac0-11e8-8ae3-e58aa4534499.png)

**i have also reproduced the same problem with dat://hashbase.io**

https://hashbase.io loads - so clearly, Beaker's DNS lookup is working
dat://hashbase.io does not load, displays the error message above

### debugging

- https://dcpos.ch loads correctly in both Chrome and Beaker. in Beaker, it redirects to dat://dcpos.ch from Javascript.
- https://dcpos.ch/.well-known/dat loads in Chrome, in Beaker, and via curl, and returns `dat://36abda5bff5a816b4e69f45e41c6778ebb3c34e45bc6a5e5758e2f047559884b`
- loading that hash URL in Beaker works!

only the friendly URL doesn't work

i don't think it's a DNS issue, despite the error message. i have no guesses as to what's actually going wrong.

**Comment by pfrazee** [comment]
I've been intending to build a DNS diagnostic tool into Beaker precisely because failures are a black box. I'm going to bump that on my todo list.

I dug into it and got a bad SSL response. 

```
.well-known/dat lookup failed for name: dcpos.ch 0 { Error: write EPROTO 140736668861376:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../../vendor/node/deps/openssl/openssl/ssl/s23_clnt.c:802:

    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite (net.js:867:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
```

Internally we're using Node 8.9.3. And... here's the issue: https://github.com/nodejs/node/issues/16196. Setting `require("tls").DEFAULT_ECDH_CURVE = "auto"` solves it. Merging fix into master now.

**Comment by pfrazee** [comment]
BTW, sweet website

**Comment by pfrazee** [comment]
Merged

**Comment by trusktr** [comment]
Hello! Just trying Beaker for the first time. I tried to "See what other people have built" from the intro popup dialog, but I get 

```
No DNS record found for dat://explore.beakerbrowser.com
```

Any ideas?

**Comment by symgryph** [comment]
Same problem sadness. MAC OSX

**Comment by joshumu** [comment]
Same boat. Ubuntu 20.04, Version: 0.8.10 Electron: 8.1.1 - Chromium: 80.0.3987.141 - Node: 12.13.0

**Comment by ElonSatoshi** [comment]
I'm getting the same problem from the flatpak version of Beaker, on Fedora. Version: 0.8.10 Electron: 8.1.1 - Chromium: 80.0.3987.141 - Node: 12.13.0

**Comment by ElonSatoshi** [comment]
@pfrazee Can you reopen this issue, or should we make a new one?
