### ISSUE TITLE
Binary files versioning doesn't work in library viewer.

### ISSUE THREAD

**Issue by ludicrows** [beakerbrowser/beaker#1117]
Operation System: Windows 7 64-bit
Beaker version: 0.8.0-prerelease.7 Electron: 2.0.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

When the binary files are updated (such as PNG pictures, for example), library viewer shows the latest version of them no matter which version of repository is chosen. However, previous versions of them are still viewable through versions dropdown menu, when clicked on the name of updated file.
I would also mention that 'Open file' button always links to the latest version of file too (it doesnt add '+15' to the URL if I view 15th version of the repo, for example), but I don't know if that was intended to be this way or not.

**Comment by pfrazee** [comment]
Thanks for reporting, that is a bug. We'll add it to the todos.
