### ISSUE TITLE
Windows file-sync issues

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1119]
Operation System:windows 7 
Beaker version: Beaker v0.8.0-prerelease.7

every time when i to add files to folders on my archive,beaker adds them but then automatically deletes them after 2-3 minutes ,really frustrating, it happens a lot, remove preventDefault()

**Comment by pfrazee** [comment]
Can you record a video demonstrating this issue? I'm not really clear on how it's happening.

**Comment by pfrazee** [comment]
Yeah there have definitely been some reports that suggest that Windows is having trouble with file sync. I'll check into that.

**Comment by cihapus** [comment]
Update : this seems to be fixed for me after upgrading to Beaker (0.8.0-prerelease.9). Files created with `writeFile` now sync correctly between the local directory and the library.

**Comment by pfrazee** [comment]
@cihapus excellent! Thanks for updating us
