### ISSUE TITLE
Create editable copy from specific version creates copy of latest version

### ISSUE THREAD

**Issue by erangell** [beakerbrowser/beaker#1120]
Operation System: Mac OSX
Beaker version: v0.8.0-prerelease.7 
Create a new website, then edit index.html several times, changing text that indicates the version number of the archive, for example:
<body>
    <h1>Hello world! ver 8</h1>
Then open a previous version - you should see the version number in the URL 
ex: dat://hex...+7/index.html
Make an editable copy.  The copy is built from the latest version of the site, not the version you were browsing.
Use case: branching from a previous version as you experiment with a site change

**Comment by pfrazee** [comment]
Yes thanks for reporting, added to the TODOs.
