### ISSUE TITLE
Blank window on Windows 10

### ISSUE THREAD

**Issue by HughIsaacs2** [beakerbrowser/beaker#1121]
Operation System: Windows 10
Beaker version: 0.8.0-prerelease7

![2018-08-07 2](https://user-images.githubusercontent.com/6512122/44031115-fa034ae0-9ed0-11e8-9290-2d902e579112.png)

I've tested it on a Surface Pro 4 and it installed and ran beautifully, but on my Lenovo Thinkpad it does this.
I'm not sure what the issue is.

**Comment by pfrazee** [comment]
We've run into this on occasion. It seems to be a race condition that leads to a bad reference. Thanks for reporting, we'll try to hit it soon.
