### ISSUE TITLE
Beaker browser creates very big files

### ISSUE THREAD

**Issue by veksha** [beakerbrowser/beaker#1122]
Beaker v0.8.0-prerelease.7
Operating system: Windows 10 x64

This is:

- [x] a bug
- [ ] general feedback

Hello. I noticed that my C:\ drive ran out of free space very quickly.
found 3 big files. 3.3 GB, 1.5 GB, 1.8 GB

C:\Users\yura\AppData\Roaming\Beaker Browser\Dat\Archives\Meta\e5\7214d9837d16b1f07e57707effccb853dc49acd79caa57c4cb5ca2c572d2d9\content\data
C:\Users\yura\AppData\Roaming\Beaker Browser\Dat\Archives\Meta\6d\27e0e07c06a453fd1676ec2fc51417e3bb9f819a62f77185b5e1d68b03f638\content\data
C:\Users\yura\AppData\Roaming\Beaker Browser\Dat\Archives\Meta\69\72ffe4bb8d24c63c92b91ef3aebf400c4899db8d5020adb96d9c8d46d7609c\content\data

Please, fix or tell me what is going on. :)
ps: cache was cleared. And total size of all seeding sites in a Library is not more then 130 MB.

**Comment by pfrazee** [comment]
Is it possible you have some sites that you've created or saved which have a lot of data in them? Currently Beaker retains the history of changes for sites and you may be seeing that.

This is something we need to improve, but haven't had the time to hit yet.

**Comment by veksha** [comment]
i have 3 seeding sites:
1. beakerbrowser.com
2. Radical Networks
3. my own site, very small and new (no history).
I had also some simple html5 game in seeding list, but then removed it.
I have visited some sites that have been listed in "explore-the-p2p-web" list.  but i think that beaker should clear it with cache clear function.
does it download all the "dat history" even if I'm not choosing to seed a site?

ps: sorry for my English.

**Comment by pfrazee** [comment]
> but i think that beaker should clear it with cache clear function.

Yes - it's possible that clear cache isn't working as expected, but I'd want to check first whether there are saved sites that could be causing the problem.

> does it download all the "dat history" even if I'm not choosing to seed a site?

No, only if you seed or create the site.

**Comment by pfrazee** [comment]
@veksha I just deployed a space reducing technique but I'm curious whether it'll apply to your use-case. Could you do this https://github.com/mafintosh/supports-sparse-files#cli and tell me what it says? (I'm curious if your filesystem supports sparse files or not.)

**Comment by veksha** [comment]
C:\Users\yura>supports-sparse-files
Sparse files are supported :)

**Comment by pfrazee** [comment]
Huh okay. 

So I visited each of those sites. 

 - The first one is dat://peer-to-peer-web.com/, which is 2.8GB current and probably more with metadata & history.
 - I can't access the second one
 - The third one is dat://dat-cast.hashbase.io/, which is 1.92GB current.

Just to confirm: Are you sure you're not seeding any of those? And, clearing cache doesn't remove them?

(It's odd that your Beaker would have downloaded those full dats without you having seeding them.)

**Comment by pfrazee** [comment]
Ok cool. Well we have some ways to improve file usage coming (version history management) and we should get some better interfaces for showing your space-usage, but for now this is all working as expected -- those large files were the sites' data -- and I'm not sure there are any signs of bugs, so I'm going to close.

Thanks for reporting. Please do reopen if you think anything's amiss.
