### ISSUE TITLE
Not building from source code

### ISSUE THREAD

**Issue by pandafy** [beakerbrowser/beaker#1127]
Operation System: Xubuntu 18.04.1 32 bit
Beaker version: beaker-0.8.0-prerelease.7

On running `npm start` browser doesn't start. Even used `burnthemall` command but still problem persists.
Debug file says unable to run gulp start script. I have attached debug-log for further analysis. 

[npm-debug.log](https://github.com/beakerbrowser/beaker/files/2310651/npm-debug.log)

**Comment by TheOneAboveAllTitan** [comment]
I have used beaker browser on Xubuntu earlier and it had issues back then too. But it atleast used to run.
#1080

**Comment by jamesthedisciple** [comment]
I have a Debian (MX-Linux) and a Gentoo install if I can help? I could find room for an Xbuntu if you'd prefer.

**Comment by TheOneAboveAllTitan** [comment]
I would prefer room instead of spamming here. 😁
