### ISSUE TITLE
dat://beakerbrowser.com/ does not work

### ISSUE THREAD

**Issue by Khoramyar** [beakerbrowser/beaker#1129]
Operation System: LinuxMint 18.3 ( Ubuntu )
Beaker version: Version: 0.8.0-prerelease.7 Electron: 2.0.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

Beaker browser dat site does not work. Tested with different connections. Other dat sites works, no problem.

Swarm debugger ( beaker://swarm-debugger/beakerbrowser.com/ ) shows no connections. nothing.

**Comment by pfrazee** [comment]
This is interesting, I've been getting sporadic reports of this.

What error do you get? It's not a DNS error, right? Just a "not found" ?

**Comment by Khoramyar** [comment]
Time out error:

![image](https://user-images.githubusercontent.com/12546320/44484517-47f99900-a64e-11e8-9ad5-207446e63bac.png)

**Comment by pfrazee** [comment]
If you restart Beaker, does it work again?

**Comment by Khoramyar** [comment]
- Changing uplink = No results
- Restarting beaker = No results
- Restarting OS = No results
- Deleting beakerbrowser.com from library = No results
- Clearing beaker history from all the time = fixed!

**Comment by millette** [comment]
Does this work?

```
dat dat://beakerbrowser.com testing-dir
```
work for you, @Khoramyar ?

**Comment by pfrazee** [comment]
Hmm that's interesting, you had beakerbrowser.com saved to your library and this was happening?

**Comment by Khoramyar** [comment]
I had it saved, yes. I try to seed dat sites, to contribute to the network. But deleting it from the library did not fix the issue. Clearing history did.

**Comment by pfrazee** [comment]
Very interesting! I'll poke around a little bit.

**Comment by Gozala** [comment]
Same here across multiple machines and multiple networks. Have not tried clearing a browser history yet. And I don't have beakerbrowser.com in my library. Although I have a vague memory of pining it with older version of beaker and older version of site.

@pfrazee Let me know if there is anything you want me to try. I won't clear history in case it turns out to be useful figuring out this issue.

**Comment by pfrazee** [comment]
@Gozala go ahead and try clearing history. That really shouldn't have any effect on this, so if it does, I'd be learning something surprising.

I suspect we're either having a connectivity error or a corrupted feed. Not sure which yet.

**Comment by Gozala** [comment]
It did fix it for me 🤷‍♂️ as well

**Comment by Gozala** [comment]
> 🤔 Now I'm really interested in this bug. Thanks for the updates.

Sadly I did not try loading it ahead of clearing history, so there is a chance that it was a coincidence. I'll be able to try that again on the other machine this evening.

**Comment by pfrazee** [comment]
That'd be a surprising coincidence but it is possible. No less surprising than history having a correlation to this bug.

**Comment by Gozala** [comment]
Ok my other machine is still unable to load dat://beakerbrowser.com/ I did also notice that old faveicon shows up:

![screen shot 2018-08-23 at 8 57 32 pm](https://user-images.githubusercontent.com/21236/44564363-595aa800-a717-11e8-92e5-0a58563cdd1c.png)

It is also worth pointing out that beaker://swarm-debugger/beakerbrowser.com/ is all empty all over.

Then I discovered that I did have it in the library and oddly twice and also one being empty

![screen shot 2018-08-23 at 9 02 50 pm](https://user-images.githubusercontent.com/21236/44564507-26fd7a80-a718-11e8-81cd-522af8b27c45.png)

Deleting those archives did not resolved the problem. Then I removed all history entries related to dat://beakerbrowse.com but this time that did not worked either. Then I restarted beaker and this time around it worked.

I should have restarted beaker between removing from lib and removing from history, but unfortunately I did not so 🤷‍♂️🤷‍♂️🤷‍♂️🤷‍♂️

**Comment by TheOneAboveAllTitan** [comment]
I am facing similar problem with dat://beakerbrowser.com.

Though my browser installation is fresh, hence it is not being seeded from my library neither do clearing history help.

**Comment by pfrazee** [comment]
I wonder if the beakerbrowser.com dat could have corrupted

**Comment by TheOneAboveAllTitan** [comment]
I suspect their is some problem with pinning service(homebase) deployed at your host server. Similar problem is occurring on [https://taravancil.com/](https://taravancil.com/) . I can open the webpage on https but  not on dat. 

It rules out possibility of dat files of [beakerbrowser.com]](https://beakerbrowser.com) being corrupted.
Meanwhile I'll try to find and post more dat archives which are having same problem.

**Comment by brechtcs** [comment]
Hm, if the problem is homebase as @TheOneAboveAllTitan suggests, then it's probably similar to an issue I experienced on my old `dathttpd` setup: https://github.com/beakerbrowser/explore/pull/5. Back then my HTTPS always worked as well, but `dat` sometimes did and sometimes didn't.

I've never seen anything similar on sites seeded through hashbase, so maybe there was already an issue somewhere in the dathttpd code that got 'recycled' into homebase?

**Comment by pfrazee** [comment]
There's definitely been some connectivity issues that we're working through, but I also wonder if there's some strange issues with the locally cached / saved version of the site not loading. Perhaps the archive got into a bad state. Not sure.

**Comment by TheOneAboveAllTitan** [comment]
What if you fork dat archive of beakerbrowser.com and host it with some other name. Ask people to test whether it is working fine. 
If it does works fine, => dat archive is okay
Else =>you need to figure out what is the problem
