### ISSUE TITLE
Types fail to filter correctly in some cases (possible issue with archive type indexer)

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1130]
Operating system:

OSX

This is:

- [x] a bug
- [ ] general feedback

My `dat.json` looked as follows:

```json
{
  "title": "profile: Irakli Gozalishvili",
  "description": "User profile",
  "type": [
    "identity",
    "profile",
    "id.hashbase.io"
  ]
}
```

Turns out that `"id.hashbase.io"` was breaking something in archive filtering. Specifically [`DatArchive.selecetArchive`](https://beakerbrowser.com/docs/apis/dat.html#datarchive-selectarchive) was not showing any matches regardless of `type` being used. Tryied passing same array, single value form that array but selector was still empty. Removing `"id.hashbase.io"` from `dat.json` fixed it so my guess is something about `.` seems to be an issue.

**Comment by Gozala** [comment]
Ok as I was trying to reproducible case I found that issue is not what I suspect. 



First here is the dat that I had (and still have) problem with:
dat://e56c7ad7bb3d27f516970d14ee5cb9d2cfa7eb15184278cf5a2dd5bbccd02a6b/

And here I created a simple app that supposed to be able to select it when select is clicked, but above dat isn't listed
dat://46e320763cff311c38f140319edea0a04004f2cf013b2fc829e4f9f5239db1c1/

#### Now the strange part

I have added "create problematic dat" button to remove necessity for including the first dat, but for some reason created dat with that button does not seem to have same problem. So I'm not sure what is going on.

**Comment by Gozala** [comment]
Starting to suspect there is a typo somewhere I don't see

**Comment by Gozala** [comment]
Hmm if I do fork  dat://e56c7ad7bb3d27f516970d14ee5cb9d2cfa7eb15184278cf5a2dd5bbccd02a6b/ it does appear.

**Comment by pfrazee** [comment]
It sounds like their might be a bug in the types indexer. Adding a new type to the target archive caused it to work, which might be because it triggered a re-indexing.

**Comment by pfrazee** [comment]
I found the issue (https://github.com/beakerbrowser/beaker-core/commit/f00856da87d2e8c02759caedce350ab347e0e121). Fixed!
