### ISSUE TITLE
Experimental Dat Peers API does not use `resolveName`

### ISSUE THREAD

**Issue by nownpl** [beakerbrowser/beaker#1133]
This effectively breaks it's functionality in websites accessed over Dat DNS (such as Hashbase ones)

Operating system: Arch Linux
Beaker version: 0.8.0-prerelease.7

**Comment by pfrazee** [comment]
Yes we've actually fixed this in master, and the fix release has been delayed by some other feature development. (Apologies for that!) We'll get the fix out soon.
