### ISSUE TITLE
Issues using flask app with beaker

### ISSUE THREAD

**Issue by KarlesP** [beakerbrowser/beaker#1136]
So, what I want to do is host a simple flask application using dat, but every time I try to upload my files and run app.py I get a 405 method. Is it because wsgi is not supported or should I do something different?

Operation System: Linux Debian
Beaker version: 0.8.0

**Comment by pfrazee** [comment]
I'm sorry to say that's not possible! Beaker doesn't work like a traditional web server. It doesn't run python or php. You build apps by writing clientside javascript, though!

**Comment by pfrazee** [comment]
Nope. Python isn't supported by any browsers. You'll need a server to run the python.

**Comment by pfrazee** [comment]
Sure, if you run a server, you can do whatever you like on the server
