### ISSUE TITLE
Windows File Sync / Preview Mode

### ISSUE THREAD

**Issue by cihapus** [beakerbrowser/beaker#1142]
Operation System:Windows 10
Beaker version:v0.8.0-prelease-9

Possibly related to #1119.

`writeFile` from local directory now syncs fine with the Beaker library, except when the file is written to a newly-created directory.  The directory is created but shows "no files" in either the local copy or Beaker library copy.  

If I click on the "select version" dropdown in Beaker, the dat://+latest address results in file not found.  CIicking on the prior version resolves the file, e.g.  dat://+5 leads directly to the created .json file, but in dat://+6 the file has been deleted.   The newly-created directory itself stays visible in both versions (and in both the local folder and the beaker library).

I get two new versions in version history showing the file being 'updated' then immediately 'deleted'.  I can write the files fine once the directory has been created - even setting a hefty timeout (500ms) between creating the directory and writing the file results in the files being written successfully. 

Possibly related to #1 - #1140: 

Thank you for all your hard work on this project, it's A Magnificent Thing and hurtling towards all sorts of wonderful places.

**Comment by pfrazee** [comment]
@cihapus Appreciate the kind words at the end! And sorry for the issue. Who could have expected bugs in file sync across multiple platforms!? (Me, I did.)

Could you step me through the exact actions that you took which caused this? You say you did a `writeFile` from the local directory, and this fails if there's a newly-created directory. Could you maybe do a step-by-step set of instructions to recreate?

Thanks!

**Comment by cihapus** [comment]
> Could you maybe do a step-by-step set of instructions to recreate?

Of course not, it works perfectly now and I can't replicate the issue no matter what combination of reads, writes and stats I do.

But I do have a discovery and a theory.  

If I delete a directory in Beaker by right-clicking, I get the [Deleted] message and the directory disappears.  But writing a directory with no checks after this provokes an error, so Beaker clearly thinks the deleted directory is still present.  When I was testing last night I was playing around with cblgh's datradio project, and was deleting and recreating directories and files quite a bit.  It's possible I was catching the 'directory already exists' errors and somehow letting them silently fail (as a firm believer that errors are just, like, the console's opinion).  That would account for the directories persisting but the files not being written, I guess?

If I right-click and delete a directory then hit refresh the deleted directory shows up in the library again - but this time without any of the files within it.  Deleting the actual files works fine, and right-clicking and deleting the directory a second time seems to delete it as expected...

If I find a test-case that disproves the above theory I'll come back and post it.

Anyway, the good news is that files sync fine.  Tonight, anyway.  The bad news is that directories seem to fail to delete when right-clicked in Beaker on Windows.  Tonight, anyway.

**Comment by pfrazee** [comment]
Okay, I was able to reproduce the "right click doesnt delete the folder" issue. I'll dig into that a bit.

**Comment by cihapus** [comment]
Thanks for the response - files still syncing fine once the folder I'm writing to is actually deleted...

**Comment by pfrazee** [comment]
Okay I found that on windows, the file events played out in a different order and gave the bad results. I rewrote the algorithm so that bidirectional sync to be a bit more predictable. If you're able to run from source, try pulling latest and running `npm run burnthemall` to try it.

**Comment by pfrazee** [comment]
The tradeoff of my rewrite is, if changes are made to the archive at the same time as to the local folder, those changes in the archive will be reverted. This is within a 500ms window, so it should be fairly rare, but not impossible.

**Comment by cihapus** [comment]
Thanks!
I can't seem to persuade Beaker to build via windows build tools, but that's almost certainly my incompetence rather than any issue with Beaker, I'll try an alternative method.
cblgh's datradio uses separate archives to act as 'playlists' of music files, so I guess reading in / editing / writing / deleting multiple archives could conceivably lead to the rare-but-not-impossible scenario you mention... Does Beaker generate any kind of error or warning if changes are reverted?  Presumably I can just stat the newly created folder after creating it to double-check it exists?

**Comment by pfrazee** [comment]
@cihapus Beaker doesn't warn you, but it should only happen if you're writing to the archive and to the locally-synced folder at the same time. We can improve on this algorithm at some point.

**Comment by cihapus** [comment]
All good, thanks.
