### ISSUE TITLE
file-editor problem after saving file

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1144]
Operation System: macOS 10.13.6
Beaker version: v0.8.0-prerelease.9

Sometimes, not every time, after saving a file that's been edited the file content display is not correct. Looks like it's being displayed as a single long line, with wrap around, and line breaks on space characters.

![screen shot 2018-09-11 at 11 18 59](https://user-images.githubusercontent.com/1552489/45354545-c4302e00-b5b5-11e8-8611-df0ea4b7b7bc.png)

Refresh the display and the file is displayed correctly.

**Comment by RangerMauve** [comment]
I see every time for new files.

**Comment by pfrazee** [comment]
Thanks for reporting. I'm looking into it.

**Comment by pfrazee** [comment]
I wasn't able to reproduce this unfortunately, but I added some code (see above) which might mitigate the issue. @paul90 are you able to build master to try it? If not, I can close and we'll reopen if it's still active after next release.

**Comment by paul90** [comment]
Tried rebuilding from master (b96cc4f4), but the build errors with an unexpected token. Will look again in the morning...

**Comment by pfrazee** [comment]
@paul90 make sure to pull latest on deps (maybe burnthemall)

**Comment by RangerMauve** [comment]
Just happened to me!

Not sure if these steps are reproducable.

- I had been editing a file for a while
- I saved and went to another tab (looked fine)
- Quickly came back to do an edit and saved within a few seconds
- Went to another tab before it finished (to reload and see the change)
- Went back to the original tab and the saw the bug.
- Seeing a warning for `view.js:531 file-editor setValue() abort: no editor` in the console.

**Comment by pfrazee** [comment]
@RangerMauve okay cool, was that on latest master or latest build?

**Comment by RangerMauve** [comment]
It was on the prerelase still, sorry! 😅

**Comment by paul90** [comment]
Just tried again - using the current master (81bed520). Builds without a problem.

Using this build. I still see the warning `file-editor setup() abort: no editor` in the console, but no longer get the problem with the file view. So, the mitigation works.

Closing this issue.

**Comment by pfrazee** [comment]
Thanks @paul90 !
