### ISSUE TITLE
Fonts are small in Fedora 28

### ISSUE THREAD

**Issue by humanitiesNerd** [beakerbrowser/beaker#1145]
Operation System: Fedora 28 x86_64
Beaker version: 0.8.0-prerelease.7 Electron: 2.0.5 - Chromium: 61.0.3163.100 - Node: 8.9.3

the fonts are too small
How do I enlarge them ?

I can't find any obvious way

thanks

**Comment by pfrazee** [comment]
Hi @humanitiesNerd. Are the fonts too small in the browser UI, or on the web pages? Can you post a screenshot?

**Comment by humanitiesNerd** [comment]
Hi @pfrazee 

this is a screenshot from the "explore the DATverse..." tab

![beaker](https://user-images.githubusercontent.com/283791/45407514-e84d4700-b669-11e8-9a3c-5579c7d015c5.png)

As you can see, the fonts are quite small both in the GUI elements (menus) and in the web content

I have to squint in order to read and after a short while I get tired

**Comment by pfrazee** [comment]
Does this happen in any other applications? I don't have the issue in Ubuntu 16

**Comment by humanitiesNerd** [comment]
> Does this happen in any other applications? I don't have the issue in Ubuntu 16

actually, fonts are too small in Polari too

Polari is an IRC client and it' s a Gnome native app

BUT I can fix Polari with the Gnome Tweak Tool app. In that I can set font size

Instead, Beaker seems not to be affected by that

Maybe this also happens in Firefox. But in Firefox I can increase font size (with Ctrl +) and it even remembers the font size through reboots, so I did iut a long time ago and then forgot about it

I used to have a personal static blog on a small vps but now the vps is expired and I was mumbling to move my blog onto this DAT based thing

Thanks for your concern

**Comment by pfrazee** [comment]
Our UI code is too brittle to support changing the font-sizes right now, but you can enlarge the webpages using ctrl +. We'll put larger font sizes in the UI on our roadmap.

**Comment by humanitiesNerd** [comment]
Il giorno gio 13 set 2018 alle ore 17:43 Paul Frazee <
notifications@github.com> ha scritto:

> Our UI code is too brittle to support changing the font-sizes right now,
> but you can enlarge the webpages using ctrl +. We'll put larger font sizes
> in the UI on our roadmap.
>

Ctrl + doesn't enlarge the web ppage thoug. Nothing happens

Thanks anyway

**Comment by pfrazee** [comment]
Then that's actually a bug. You should be able to enlarge.

**Comment by humanitiesNerd** [comment]
Il giorno gio 13 set 2018 alle ore 18:19 Paul Frazee <
notifications@github.com> ha scritto:

> Then that's actually a bug. You should be able to enlarge.
>

so I was onto something :-)

Can you reproduce it ?

**Comment by pfrazee** [comment]
I can't -- I'm on OSX but I'm able to expand with `cmd +`. The way electron works, it should register for both cmd & ctrl, depending on the platform.

Do other shortcuts work, like `ctrl R` to reload the page?

**Comment by humanitiesNerd** [comment]
Il giorno gio 13 set 2018 alle ore 18:28 Paul Frazee <
notifications@github.com> ha scritto:

> I can't -- I'm on OSX but I'm able to expand with cmd +. The way electron
> works, it should register for both cmd & ctrl, depending on the platform.
>
> Do other shortcuts work, like ctrl R to reload the page?
>

Yes, Ctrl r does reload the page

Not only that !!

Ctrl - _does_ shrink the page !!

I pressed it 2 times and now I don't now how to mae it as large as before !

This seems to afffect one key combination only.
Strange !

**Comment by pfrazee** [comment]
Hah okay it turns out we have a bug in Windows. You have to press `ctrl shift +` right now. Silly. We'll get that fixed asap.

**Comment by pfrazee** [comment]
Just pushed a fix to master so that zoom shortcuts work as expected.

**Comment by humanitiesNerd** [comment]
Il giorno ven 14 set 2018 alle ore 18:35 Paul Frazee <
notifications@github.com> ha scritto:

> Hah okay it turns out we have a bug in Windows. You have to press ctrl
> shift + right now. Silly. We'll get that fixed asap.
>

Wonderful ! It works !!

Thanks !

**Comment by tomisme** [comment]
My eyes aren't the best and I'm running into the same issue, was the issue closed because it's possible to increase the browser UI font size?

**Comment by pfrazee** [comment]
@tomisme Are you seeing this on the 1.0 beta?

**Comment by pfrazee** [comment]
@tomisme it's possible to set a defualt zoom in the settings btw

**Comment by tomisme** [comment]
> @tomisme Are you seeing this on the 1.0 beta?

Yeah, sorry I wasn't clear, I meant the 'browser chrome' the UI around the webpage (address bar, tabs etc.)

I'm running via AppImage on Arch linux.
