### ISSUE TITLE
P2P version available - inconsistent appearance of the label

### ISSUE THREAD

**Issue by nettiopsu** [beakerbrowser/beaker#1146]
Operation System: MacOS
Beaker version: v0.8.0-prerelease.9

"P2P version available" label that appears in the address bar on the right is a really cool feature for promoting P2P internet! But it works a bit inconsistent, and moreover for just one case:
1. https connection
2. existing /.well-known/dat

I think it could be extended, as Beaker itself works fine with another cases like:
1. http connection (why would not Beaker make the same request to /.well-known/dat in this case)
2. TXT record for dat domain (Beaker supports by default domains created with dat TXT record, no need in /.well-known/dat)

**Comment by pfrazee** [comment]
Thanks for reporting! That's really a bug if it's not hitting those cases. I'll put aside some time to check on this.
