### ISSUE TITLE
Crashes on close with Win 7 x64 

### ISSUE THREAD

**Issue by parfish** [beakerbrowser/beaker#1147]
Operation System: Win 7 x64 Ultimate
Beaker version: v0.8.0-prerelease.9

This is the first version of Beaker that I've used that has crashed like this. Very simple: 
1) Beaker works fine while running (no crashes at all), BUT ...
2) Close Beaker 
3) "Beaker Browser has stopped working"

![beaker-crash-beaker v0 8 0-prerelease 9-win7-x64](https://user-images.githubusercontent.com/35550512/45394555-2c6c2780-b629-11e8-8ecf-d5786ccb364a.png)

I've tried a new fresh install and the same thing happens - so at least it's consistent and repeatable.
Let me know if you need more system info etc ..

P.

**Comment by pfrazee** [comment]
Thanks for reporting. I've seen this on MacOS too. I'll investigate.

**Comment by pfrazee** [comment]
[Filed an issue with Electron](https://github.com/electron/electron/issues/14616). Not sure yet what could be causing this.

**Comment by psych0fred** [comment]
Just wanted to add to this that I couldn't launch the browser a few days ago so I reinstalled it (.8) and while I had this same problem before it no longer happens. The only other thing of note is then when I updated windows this month (which was before the reinstall)  I updated .Net and all the patches that weren't previously installed.
