### ISSUE TITLE
Copy files cross archive

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1150]
Operation System: windows 7 
Beaker version: 0.8.0

The existing Copy method doesn't copy files from 1 archive to another archive.
Copy files from one archive to another archive on the will open new use cases which are not possible now and i need that urgently ,which is a big thing.
Can someone here develop such a method please?thanks! I love this project and follow.

**Comment by RangerMauve** [comment]
```javascript
async function copy(sourceArchive, sourcePath, destinationArchive, destinationPath) {
  const content = await sourceArchive.readFile(sourcePath);
  await destinationArchive.writeFile(destinationPath);
}
```

Try this out

**Comment by RangerMauve** [comment]
That's probably the best you'll be able to get in the near future. 😅

An alternative would be to use [DatArchive.fork](dat://beakerbrowser.com/docs/apis/dat.html#datarchive-fork) if you want to copy _everything_ in an archive into a new archive.

**Comment by arni077** [comment]
RangerMauve no i also thought about that but,fork method creates new folder at the main beaker directory and also endow new url to the new fork.

**Comment by pfrazee** [comment]
This probably wouldn't be too hard to support.
