### ISSUE TITLE
I have a specific use case,

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/beaker#1152]
Operation System: Linux Mint 18.1
Beaker version: Most Recent

I can't seem to quickly load the library to build web pages, even those hosted on my own computer.

I'm wanting to host something like enoki, for another bug I might ask about with that dev.

But is there a way to fix this issue? Otherwise my only option is Secure Scuttlebutt. Which isn't installing either.

**Comment by pfrazee** [comment]
@LWFlouisa can you explain a little bit more detail which pages aren't loading quickly? Which page is it (what url)? Does it take a long time and then load, or not load at all?

Also, feel free to use Secure Scuttlebutt, but please be respectful in the issues board. We are here to help. We're not particularly bothered if you choose to use something else.

**Comment by pfrazee** [comment]
Closing for now. Will reopen if we can get more info.
