### ISSUE TITLE
.download() sometimes times out

### ISSUE THREAD

**Issue by RangerMauve** [beakerbrowser/beaker#1153]
Operation System: Windows 10
Beaker version: Prerelease 9

I'm not sure if this is really a beaker issue or if it's related to hyperdrive in general.

Sometimes, when you invoke `.download()` on an archive even if you have downloaded it in the past, it will stall and timeout after 5 seconds instead of resolving right away.

I'm guessing the issue is somewhere in [hyperdrive.content.download()](https://github.com/mafintosh/hyperdrive/blob/master/index.js#L368), but I'm not sure how to reproduce it or why it would be happening. I'm guessing because the rest of the abstractions on top look straight-froward.

I think this issue is also popping up in [webrun](https://github.com/RangerMauve/webrun/issues/2#issuecomment-421053776), which is what's leading me to thing it's a hyperdrive issue and not beaker-specific.

**Comment by pfrazee** [comment]
Thanks for filing. The good news is, I have no trouble reproducing! I'm digging into it now.

**Comment by pfrazee** [comment]
I agree this does seem to be an issue with hypercore but I wasn't able to reproduce in hypercore tests. I was able to fix it by aborting early if already downloaded.

**Comment by RangerMauve** [comment]
Cool, that works, too. :D

**Comment by RangerMauve** [comment]
Could it be related to this TODO? https://github.com/mafintosh/hypercore/blob/master/index.js#L328
