### ISSUE TITLE
beta-info gets cut off at smaller resolutions

### ISSUE THREAD

**Issue by rickycodes** [beakerbrowser/beaker#1154]
Operation System: osx (high sierra)
Beaker version: 0.8.0 (master)

Seems the div and text get cut a bit odd on smaller screens (like mine):

![image](https://user-images.githubusercontent.com/675259/45512976-62b3bf00-b76f-11e8-85bb-701e48fff297.png)

**Comment by pfrazee** [comment]
Fixed! Thanks for reporting
