### ISSUE TITLE
Windows zoom shortcuts

### ISSUE THREAD

**Issue by fenwick67** [beakerbrowser/beaker#1155]
Operation System: Windows 10, 64-bit
Beaker version:0.8.0-prerelease7 

To zoom in takes three keypresses (`ctrl`,`shift`+`[the =+ key next to backspace]`). I think the `shift` key being required here is a bug.

Zooming out with `ctrl`+`[the -_ key]` works fine.

And finally, `ctrl`+`numpad -` and `ctrl`+`numpad +` don't do anything, where in Chrome and Firefox it zooms out and in.

Related issue: #1071

**Comment by pfrazee** [comment]
Whoops well that's dumb! Thanks for reporting. I'll get that fixed.

**Comment by pfrazee** [comment]
Fixed in master. Thanks again.
