### ISSUE TITLE
Converging DatArchive API with experimental FileSystem API?

### ISSUE THREAD

**Issue by tswast** [beakerbrowser/beaker#1157]
I noticed the inconsistent casing in readdir verus readFile, too (https://github.com/beakerbrowser/beaker/issues/571). I understand the choice to use the Node.js `fs` module as a model at the time, but now Mozilla and others have published a spec for [in-browser filesystem access](https://github.com/mozilla/libdweb/blob/master/Readme.md#filesystem-api) as part of the libdweb project.

https://github.com/mozilla/libdweb/blob/a78b0a0c9a1f1d3d1e3343995de7d4a9b0cb000c/src/FileSystem/FileSystem.js#L8-L39

[MDN article](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API)

At first glance it seems to be a more consistently designed API. Plus, it might make a natural fit for Dat to fit in if other browsers are already looking at adopting the FileSystem API.

**Comment by pfrazee** [comment]
Yeah this is a good thing to look into. We aren't afraid to deprecate APIs. We can do things like leave the old API for a time, and even put out new APIs by names like `DatArchive2`. We just want it to be well-warranted, and this is the kind of thing that might warrant it.

Let's see what adoption turns into with the new filesystem APIs.
