### ISSUE TITLE
Auto-reshare dat archives toggle in user preferences

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#116]
Beaker does not automatically upload dat archives; it requires the user to toggle "sharing" on. This is to preserve the user's bandwidth. (Or, more specifically, to keep people from worrying about their bandwidth being abused.)

Some users have requested the option to do auto-resharing. If enabled, archives would automatically upload on open.

**Comment by millette** [comment]
Is this still relevant?

Related to "Save to library", perhaps?

**Comment by pfrazee** [comment]
It's not, actually. Auto-resharing is now the default behavior. We're also doing some new work on the UX. I'm going to close for now.
