### ISSUE TITLE
Preview mode should respect .datignore

### ISSUE THREAD

**Issue by yihangho** [beakerbrowser/beaker#1164]
Operation System: macOS 10.13.6
Beaker version: v0.8.0-prerelease.9

As the title says, switching on preview mode unhides files ignored by `.datignore`. But this happens only in library (i.e., the `beaker://library/<dat url>` page). Not sure if this is intended, so reporting here to be safe.

## Steps to replicate

1. Create a new empty project. Notice that this will also create a `.datignore` that ignore, among other things, `node_modules`.
2. Set a local folder for the project. Mine is in `~/Sites/untitled`.
3. Create `node_modules` in the local folder (e.g., `mkdir ~/Sites/untitled/node_modules`).
4. Go back to the library page for that project (i.e. `beaker://library/<dat url>`). Notice that `node_modules` is not shown.
5. Go to Settings and switch on preview mode.
6. Go back to the Files tab and see that `node_modules` is shown.

**Comment by RangerMauve** [comment]
Oh snap! That's what was causing it? I thought datignore just wasn't working!

**Comment by pfrazee** [comment]
Hi @yihangho. Thanks for filing! You're correct, this is not the right behavior (though it is known/expected). Basically what's happening is that .datignore is correctly used during publish or sync, but it's not yet used to filter the content in the preview. To do that, I'll need to wrap the file calls (readdir, readfile, writefile, etc) and apply the filtering logic. On my todos!

In a way @RangerMauve, the .datignore *isn't* working 😅

**Comment by yihangho** [comment]
@pfrazee Alrighty, thanks for the explanation. Feel free to close this if it has already been tracked somewhere else.

**Comment by pfrazee** [comment]
Fixed in latest master
