### ISSUE TITLE
.appimage works but npm start doesn't

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1168]
Operation System: ubuntu 18.04
Beaker version: prerelease.9

I used node 8.12 LTS and 10.11 to build ... same problem

Beaker "window frame" starts, but initializing the menus seems to fail in main.js line 137: 

error: beaker.browser.getInfo().then  .. is not a function

```
    beaker.browser.getInfo().then(info => {
      this.browserInfo = info;
      this.updateActives();
    });
```

**Comment by pmario** [comment]
I did download the appimage file and installed it. .. The packaged version seems to work as intended.

**Comment by pfrazee** [comment]
Apologies, I messed up some dependency version pinning. I'll try to get this fixed today.

**Comment by hossameldeen** [comment]
To anyone who needs a _temporary_ quick fix urgently:

- In `app/package.json`, change `beaker-core` version from `^2.10.5` to `2.10.5`
- Run `npm run burnthemall`
- Run `npm start`

**Comment by pfrazee** [comment]
@hossameldeen Just pushed that fix. Thanks.
