### ISSUE TITLE
Settings page is blank

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1171]
Operation System: Ubuntu 16.04
Beaker version: 8da88a5d80943bb51f408e9cd257d51732dd8716 (Note: the problem may have come up before this commit).

`beaker://settings` renders a blank page with grey background. `beaker://bookmarks/` works as normal.

**Comment by pfrazee** [comment]
@hossameldeen Have you made sure your npm dependencies are updated? There have been some changes to upstream that could cause this; try running `npm run burnthemall`

**Comment by hossameldeen** [comment]
@pfrazee Thank you. I just did as you said and the problem still persists.

Note: Just FYI, for me not urgent at all; not using this page currently.

**Comment by pfrazee** [comment]
Does anything show up in the pages devtools, by chance?

**Comment by hossameldeen** [comment]
You're right, there's an error in the console tab:

```
main.js:740 Uncaught (in promise) Error: (datHandler || "").trim is not a function
    at setup (main.js:736)
    at <anonymous>
```

**Comment by pfrazee** [comment]
Just pushed another guard on that. LMK if it's not fixed for you.

**Comment by hossameldeen** [comment]
Fixed. Thanks!
