### ISSUE TITLE
Add spell checking

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1177]
See:

 - https://github.com/mixmaxhq/electron-spell-check-provider
 - https://github.com/electron-userland/electron-spellchecker

**Comment by rickycodes** [comment]
@pfrazee I could take a look at this if you want?

**Comment by pfrazee** [comment]
@rickycodes Sure, though I think @septimus may be working on it.

**Comment by Septimus** [comment]
Just about done.

https://i.gyazo.com/d422ccc5a0edf5c49ddc68e7c6130cb1.mp4

**Comment by pfrazee** [comment]
Done thanks to @Septimus! https://github.com/beakerbrowser/beaker/pull/1190
