### ISSUE TITLE
Beaker does not find my peer dat servers, though dat cli finds

### ISSUE THREAD

**Issue by nettiopsu** [beakerbrowser/beaker#1178]
Hello,

I started to have a weird problem, when Beaker does not see my own peers hosted in different VPS in different countries (though they are hosted by the same company). One is hosted with docker and dat sync, another with hypercored. I see in logs that it connects to discovery1.publicbits.org:5300 and discovery2.publicbits.org:5300 from time to time, but it does not get right IPs. It tries to connect though to old IPs that are not valid anymore

At the same time, dat cli is working e.g. with dat clone and dat sync

I tried: installing-reinstalling, macOS, Windows, wi-fi connected to ethernet and wi-fi connected to mobile phone, Beaker subversions 7 and 9

Second issue is that at some point Beaker stopped catching even local connection with dat sync running separately in Terminal (which, as I said, works fine). I managed to solve it by deleting all History, but not with reinstalling app, neither by removing the site from the cache in Library

Original issue:
https://github.com/beakerbrowser/beaker/issues/1087

Operation System: MacOS/Windows
Beaker version: 7-9

**Comment by nettiopsu** [comment]
This makes me even more confused: I just have copied locally the same dat content, shared it with new dat url and added it to above mentioned hypercored server. And this url works perfectly fine! So shortly: same hypercored is sharing 2 dats at the moment: old one and new one, but Beaker can not connect to the old one... I can not find any logical explanation to this situation :)

**Comment by pfrazee** [comment]
@nettiopsu Is there any chance that the dats couldve been corrupted, perhaps because you moved the data from one computer to another, or exported them from Beaker? (The potential for this corruption is something I'm actually working on today!)

If not that, this may just be some kind of failure in peer-discovery. We're replacing our stack with Hyperswarm soon, which should improve results overall.

**Comment by nettiopsu** [comment]
No, I have not moved anything anywhere. It started to work at some point by itself. I thought it could be some problem with the discovery servers

I thought at first that the problem might be with hypercored, but since then I changed it to dat sync, but nothing has changed in relation to Beaker

And, as initially I said, dat cli works fine and relatively fast

**Comment by nettiopsu** [comment]
@pfrazee I made a small experiment and found out one interesting fact. I made a copy of my dat archive that is very slow in Beaker - the same environment, same code and same files, but with new dat url (so .dat was not copied).
So this archive works like a charm now, very fast.

Question is - can it be somehow related with dat archive history (history of file changes)? This archive is updated every minute via API, so its history is pretty big. Here two versions that came to my mind - being confused with tracking this history, or - trying to download old versions of files?

It also can somehow explain why dat cli works fine - they clearly state that they do not download any history of changes

P.S. But it also might be that dat archive history is somehow corrupted in opinion of Beaker browser, taking this (#1129) into account. I guess beakerbrowser.com is not being updated every minute :)

**Comment by pfrazee** [comment]
Oh yes, the history in the current version of Dat incurs a notable performance penalty. This is one of the things being fixed in the new version of dat's internal structure, hyperdrive.

**Comment by nettiopsu** [comment]
@pfrazee but does Beaker try to read/download all dat archive history before loading a page? It might be the reason why dat cli works faster and immediately.
But if Beaker does it, then is it possible to switch this off? In any case browser should not load the history, it should just serve the latest file versions

**Comment by pfrazee** [comment]
@nettiopsu it does not download the history first, no

**Comment by nettiopsu** [comment]
It seems that Beaker 0.8.2 loads almost immediately my dat archives, though I have not made any changes to them. It is also strange because I have tested it with 0.8.1, removed all cache, reinstalled it etc. etc., but it just did not work. At the same time, it seems that changes from 0.8.1 to 0.8.2 are not that significant to influence the performance

I will test it more, if it keeps working, then we can close this ticket

**Comment by pfrazee** [comment]
The change to 0.8.2 was pretty big. I moved the dat code into a separate process.

**Comment by nettiopsu** [comment]
I have tested this issue multiple times and it seems that nowadays Beaker loads my dat archive immediately without any problems. Good work! Thanks!
