### ISSUE TITLE
Login redirect issue (Feedly)

### ISSUE THREAD

**Issue by jeanFrancoisHicter** [beakerbrowser/beaker#1179]
Operation System: Windows 7 SP1
Beaker version: Beaker v0.8.0-prerelease.9

Hi!
I start to log in Feedly with my Google account as I do in other browsers, but, it loops without login:
![image](https://user-images.githubusercontent.com/4332623/46266031-52039700-c52c-11e8-815d-2c09fefbb191.png)

**Comment by pfrazee** [comment]
Thanks for filing! I'll check into that. Is there a specific login flow you use?

**Comment by jeanFrancoisHicter** [comment]
Sorry, I don't understand your question... As I mentioned, I log to Feedly with my Google ID... There is no other login specification. There has never been a problem with other browsers. Cheers! :)

**Comment by pfrazee** [comment]
@jeanFrancoisHicter Right, like you clicked the "Login with Google" rather than, say, entering a username and password manually?

**Comment by jeanFrancoisHicter** [comment]
Yep: I click the _Login With Google_ button
