### ISSUE TITLE
Redirects not occurring

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/beaker#1180]
It would be useful if we would be navigated to a network's login page when it's required or be notified about this (like in Firefox or Chrome).

**Comment by pfrazee** [comment]
What do you mean by a network's login page? Is the problem that login redirects aren't happening consistently?

**Comment by kodedninja** [comment]
Maybe the problem's with the network here, but there are no redirects at all. In Firefox and Chrome I get a prompt that takes me to the login page. If I don't click on the button and I try to access a website I don't get redirected.

**Comment by pfrazee** [comment]
@kodedninja Sounds like it's related to a redirect issue that electron has had, but fixed in electron3 (which we're updating to now). When you say 'network', is this like a wifi network?

**Comment by kodedninja** [comment]
Yes, sorry. It's the wifi network of the university :)

**Comment by pfrazee** [comment]
Okay gotcha. If you're comfortable building from source, you might try the `electron3` branch. Otherwise we can test this again when the next release comes out.
