### ISSUE TITLE
Facebook chat fails to create new windows

### ISSUE THREAD

**Issue by jeanFrancoisHicter** [beakerbrowser/beaker#1181]
Operation System: Windows 7 SP1
Beaker version: Beaker v0.8.0-prerelease.9 is up-to-date

Blank null when try to chat

![image](https://user-images.githubusercontent.com/4332623/46371080-a53e2c80-c687-11e8-965a-91db85feeefd.png)

**Comment by pfrazee** [comment]
Thanks for reporting. I'll look into it.

**Comment by jeanFrancoisHicter** [comment]
Precision: it is in Messenger window: when you click for a _phone-call_ or a _cam-call,_ you have this blank window which is opening
