### ISSUE TITLE
feature request:  experimental.datPeers.getOwnId()

### ISSUE THREAD

**Issue by monteslu** [beakerbrowser/beaker#1182]
Operation System: OSX Sierra
Beaker version: v0.8.0-prerelease.9

Need a way to get your own peer Id.  Unless I'm just not seeing it in the docs:  Everyone else can see your peerId on a join or broadcast, but you can't see it yourself.

**Comment by pfrazee** [comment]
Yeah that makes sense. Added to my todos.

**Comment by pfrazee** [comment]
Okay that's merged, I'm going to test it a bit and then will include it in a new release soon (this week).

Sorry for the delay. Been very heads down on the next major release.
