### ISSUE TITLE
Move globalFetch out of experimental

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1184]
Beaker version: Beaker v0.8.0-prerelease.9

I think we should move the `globalFetch` API from experimental to permanant because it is too important to consider it in any way just as experimental only. Millions of users will need this in the future,no point in keeping this experimental as it make it seem not credible enough for developers to rely on for serious dapps. Anyone who has used XMLHttpRequest,knows why `globalFetch` API provides a more powerful and flexible feature set with HTTP.

**Comment by pfrazee** [comment]
I don't plan to deprecate `globalFetch` without a good replacement. The question in my mind is whether the existing `fetch` API might be someday expanded to support the `globalFetch` behaviors (requesting to escape CORS). If we can be sure it won't, then I'm +1 to `globalFetch` moving to permanent support.
