### ISSUE TITLE
Dynamic web pages

### ISSUE THREAD

**Issue by githubhero** [beakerbrowser/beaker#1188]
Not an issue, maybe a feature request.

Would it be possible to serve dynamic (eg. PHP) pages instead of HTML?

**Comment by pfrazee** [comment]
@Robert-Halls I think what @githubhero is talking about is a way to dynamically generate the pages.

PHP is traditionally run on servers. Dat doesn't have servers. Instead it has "archives" of files (like a torrent or a zip file). You can change the files, but when you do, you're changing the files universally.

So, to dynamically render a page, you need to use clientside javascript. One way to do that is using the [fallback_page directive](https://beakerbrowser.com/docs/apis/manifest#fallback-page) and building an [SPA](https://en.wikipedia.org/wiki/Single-page_application).

**Comment by githubhero** [comment]
@pfrazee Ok, thank you   :-)
