### ISSUE TITLE
Black line at the bottom of the browser window

### ISSUE THREAD

**Issue by jeanFrancoisHicter** [beakerbrowser/beaker#1191]
Operation System: Windows 7 SP1
Beaker version: 0.8.0-prerelease.9

![image](https://user-images.githubusercontent.com/4332623/46548396-44a13080-c8cf-11e8-847f-e44eb8671406.png)

**Comment by pfrazee** [comment]
Thanks for reporting. I'll see if I can figure out why that's happening.
