### ISSUE TITLE
Creating site from existing directory breaks other site that uses same directory

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1192]
Operating system:
MacOS

This is:

- [x] a bug
- [x] general feedback

I'm not sure if there's going to be reasonable solution to this problem but even preventing from creating such conflict would be better.

**Comment by pfrazee** [comment]
What version of Beaker?

This is would be some kind of issue with the sync algorithm. There's no reason that having multiple dats on the same local dir should cause them to do anything other than converge on the same content.
