### ISSUE TITLE
Preview mode as a real dat url

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1193]
I would really like that preview mode enables iteration on the site without publishing every single change, but it comes with few downsides:

1. There is no (simple) way to share preview version. Use cases for this being:
   - It would be very useful to let comrade try version that is about to go live.
   - Beta / Alpha channels
2. Tools that depend on versioning don't work in preview mode.
    <details>
    I have a app hot-swap utility which reloads JS code on updates leaving DOM and App State intact. Which unfortunately does not work in preview mode.
    <br/></br>
    That is because ES modules get cached such that importing same URL would return same instance. And even though you'd be able to sidestep cache by adding query param to the main module it's imports will still end up loading from the cache. With dev server that is fairly easy to solve by using entry in the path instead of query param, which is also possible in non preview mode by using versioned URLs but that no longer works in preview mode.
    <br/></br>

    ![image](https://user-images.githubusercontent.com/21236/46549622-7e4e4900-c887-11e8-9575-aba16d8c54ba.png)
    </details>

**Comment by pfrazee** [comment]
We're not going to do this. Preview mode covers enough use-cases , and spending more time on it would be a mistake. I think we could cover most what you're describing with multiple dats and a way to diff between them.

**Comment by Gozala** [comment]
I've discussed this bit on IRC but probably this is better medium for more ellaborate conversation. I think system would be far more flexible if instead of using +preview versioned URL beaker would just have create separate archive and use that in place of +preview URL. This "in preview" archive can be created lazily meaning - first time preview gets activated.

Also worth noting that you could still server that "in preview" archive from `dat://${hash}+preview`  URL as you alreday do, but I'd argue that there is better ways to indicate that page is in preview mode (for example have something like version chooser (that you have in library) saying "preview" in the addressbar, that can be colorcoded).

That would make  preview URLs sharable so you can pass it on for test drive. It also opens up opportunity for more advanced features like beta / alpha channels.

**Comment by pfrazee** [comment]
We spent months and months on the current preview mode (from last winter to late summer). It stalled a lot of Beaker development, and we went through multiple prototypes which included ideas like you're describing. I'm not revisiting this!!
