### ISSUE TITLE
unable to open files from the command line

### ISSUE THREAD

**Issue by coetry** [beakerbrowser/beaker#1196]
Operation System: macOS High Sierra 10.13.6
Beaker version: 0.8.0-prerelease.9 Electron: 2.0.8 - Chromium: 61.0.3163.100 - Node: 8.9.3

I'm trying to open Beaker with a file argument from the command line, yet this does not work. Only the browser is opened, but it doesn't load the file passed in as an argument.

`open -a 'Beaker Browser' index.html`

**Comment by pfrazee** [comment]
Thanks for filing! I'll check into it.

**Comment by pfrazee** [comment]
Fixed in the `electron3` branch, should be included in the next release
