### ISSUE TITLE
Feature request: support forum

### ISSUE THREAD

**Issue by MPE2016** [beakerbrowser/beaker#1203]
Operation System: Linux Mint 19 Cinnamon
Beaker version: 0.8.0

Hi there,
Lately I have been realizing that one of the things beaker really misses is a support forum. In my mind, this can go two ways:
- a subsite for beakerbrowser.com
- a standalone support site, seeded by all of its users, only available over the dat protocol.

Just a thought:)

All the best,

MPE

**Comment by pfrazee** [comment]
We do have a [google group](https://groups.google.com/forum/#!forum/beaker-browser) that can be used for support. If somebody decides to build forum software over dat:// then I'd love to deploy it. [See this http/dat hybrid for reference](https://github.com/pfrazee/node-http-dat-forum).

**Comment by MPE2016** [comment]
Thanks for the suggestion Paul, I hadn't found the google group, so I'll definitely check that out. 

Unfortunately, building a support forum (over any protocol for that matter) is beyond my technical capabilities, but I still think it's a sweet idea:)

The beaker browser rocks by the way!

**Comment by pfrazee** [comment]
We're going to use github's new discussions feature, I think
