### ISSUE TITLE
Beaker is slow to start

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1205]
Operation System: windows 7
Beaker version:  Beaker v0.8.0-prerelease.9

When I try to open beaker ,the browser always takes long time(about more than 2 minutes) to open it on my PC, sometimes it just won't even open it, in order to open beaker  i have to click it several times more. i mean it does not respond when i click it once. i dont have any problems like those with my google chrome browser,it always responds very fast to everything.

**Comment by pfrazee** [comment]
Yikes, thanks for reporting. I know we've got some performance degradation cases but I haven't been successful in diagnosing them. (Part of the problem is that electron's internal tooling for capturing memory usage crashes Beaker.)

Does the performance problem subside after a while or is it persistent?

**Comment by arni077** [comment]
Persistent. Happens everytime.

**Comment by pfrazee** [comment]
@arni077 I mean, does it ever become usable again, or does it stay slow until you quit?

**Comment by arni077** [comment]
Beaker works great. It just when you first try to open the browser it responds very slow to the mouse 'click' on beaker icon..and sometimes it does not respond and wont even open the browser untill i click it several times again. But when it does open beaker everything works fast.

**Comment by pfrazee** [comment]
Okay, maybe what's happening is the setup process is slow, and Beaker isn't showing the window till it's ready.

**Comment by pfrazee** [comment]
Okay I deferred some of the loading until after the window is visible, which should improve this issue
