### ISSUE TITLE
Favicon: Basic drawing tool

### ISSUE THREAD

**Issue by raphaelbastide** [beakerbrowser/beaker#1206]
Additionally to a _Upload favicon_ option https://github.com/beakerbrowser/beaker/issues/875, I think that a favicon editor could be interesting and coherent with the use of Beaker: I am sometimes frustated not to be able to adapt my favicon to the page / site I publish with beaker. Sometimes, a basic red square or a yellow circle would fit perfectly.

![screenshot_2018-10-09_15-35-53](https://user-images.githubusercontent.com/193122/46672986-0cecfe00-cbd9-11e8-98fb-a09a660eafd5.png)

Such an editor could be found under a _Create your icon_ button, open a tooltip with the minimum tools required to make basic 16×16px art updated in real time in the current tab. The submission of the drawing create a favicon.ico at the root of the site folder.

Possible issue: the ico format embed more than just a 16×16px drawing. Filling all the formats can lead to an exercise with no fun.

**Comment by RangerMauve** [comment]
I think this'd be great as an application published on Dat!

The flow could be:
- Visite the dat website for the editor
- User draws the favicon they want
- It calls `DatArchive.selectArchive()` to prompt the user where they want to add the favicon
- It saves the favicon.ico in the archive
- ???
- Profit!

**Comment by pfrazee** [comment]
@RangerMauve is right that this can be a userland app, but I also like the idea of including this in Beaker itself. I'd accept a PR with that feature for sure.

**Comment by tswast** [comment]
There are a couple of open source web-based pixel art editors that could be a good starting point for this. A couple I've used include

* Piskel https://github.com/piskelapp/piskel
* Make 8-bit Art https://github.com/jennschiffer/make8bitart

**Comment by pfrazee** [comment]
This has been added!
