### ISSUE TITLE
Download prompt when pressing Ctrl/Cmd + S

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/beaker#1209]
The download prompt is awesome, but shouldn't it also appear when we press `Ctrl/Cmd + S` on a site. Currently nothing notifies you that a file have been downloaded to your machine.

**Comment by pfrazee** [comment]
Are you on master? We just merged that update

**Comment by kodedninja** [comment]
Ah no, I'm on the last release. Sorry, I should really stop reporting already done issues...

**Comment by pfrazee** [comment]
All good!
