### ISSUE TITLE
editable copy of the site does not preserve dat.json config

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1211]
It looks like "make editable copy" ignores `experimental` and `content_security_policy` fields from "dat.json" which in some instances creates a broken copy.

For example attempt to fork dat://library.hashbase.io/ creates an app that does not work because folowing is omitted:

```
"experimental": {
    "apis": ["library"]
 }
```

I think `experimental` field should probably be copied as is. As of `content_security_policy` it's interesting as some restrictions may still break a site (as it may contain domain it's hosted on) never the less I think it's that copying is a better default.

**Comment by pfrazee** [comment]
Thanks for the heads up. It's easy to fix this, a couple of config lines in beaker-core's lib/const. I'll include this in 0.8.0.

**Comment by pfrazee** [comment]
Fixed on master.
