### ISSUE TITLE
I cannot open dat links

### ISSUE THREAD

**Issue by MikePap** [beakerbrowser/beaker#1213]
Operation System: ubuntu 18.04
Beaker version:

I downloaded beaker on my ubuntu 18.04 laptop. If I try to open this "dat://beakerbrowser.com/" it does not open.
Later, I installed "dat" on the same laptop then I created a dat on a folder («dat create») and I shared that folder.
So if I try to open my folder' links, in beaker, all is working but  "dat://beakerbrowser.com/" does not work.

**Comment by pfrazee** [comment]
@MikePap Is this like, you're in Chrome or Firefox and click on a dat:// link and Beaker doesn't open?

**Comment by MikePap** [comment]
not really the same. It shows me a window that say: Timed out. It took too long to find this site on the peer-to-peer network.
Troubleshooting: Your firewall may be blocking peer-to-peer traffic. There may not be any peers hosting this site right now.
If you think this is a bug, copy the debug log and file an issue. ...

**Comment by MikePap** [comment]
home network. It's a adsl. I'm from Italy.

**Comment by jahed** [comment]
I'm having a similar issue, installed Beaker for the first time on Linux Mint 19. Home network, ADSL, UK. Can't connect to any peers. Every Dat website ends up on the "It doesn't seem like anybody is sharing this site right now." page.

It used to work before on older versions so I'm assuming it's the networking changes.

Is there anything I can do on my end to get it work? Other P2P protocols work fine (IPFS, Bittorrent). I've attached a debug.log below.

Thanks,

<details>
<summary>debug.log</summary>

```
Log started at Sun Oct 28 2018 22:22:37 GMT+0000 (GMT)
dat Throttling upload to 1 MB/s
dat Throttling download to 1 MB/s
dat event=traffic trafficType=out:query messageId=57913 message=TXT Additional (announcing self) peer=discovery1.publicbits.org:5300 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=out:multicastquery messageId=undefined message=TXT Question (requesting peers list) peer=undefined key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=swarming discoveryKey=100ca28624d67817dbeb9d68878f9b5d2dcc81cf57bc9f7ca7a25e4aa73c06c0 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=in:multicastquery messageId=0 message=TXT Question (requesting peers list) peer=192.168.1.100:5353 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=out:multicastresponse messageId=undefined message=TXT Answer (heres a peers list) peer=undefined key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=in:multicastresponse messageId=0 message=TXT Answer (heres a peers list) peer=192.168.1.100:5353 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=out:query messageId=57915 message=TXT Additional (announcing self) peer=discovery2.publicbits.org:5300 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=in:response messageId=57915 message=TXT Answer (no peers found) peer=188.166.107.197:5300 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
dat event=traffic trafficType=in:response messageId=57913 message=TXT Answer (no peers found) peer=45.55.78.106:5300 key=87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
datgc GC unsaving 0 expired archives
datgc GC cleaning out 0 unused archives
datgc []
datgc GC completed in 5 ms
dat-serve Timed out searching for 87ed2e3b160f261a032af03921a3bd09227d0a4cde73466c17114816cae43336
```

<details>

**Comment by jahed** [comment]
This seems to have something to do with the Dat build shipped with Beaker.

After encountering this issue, I decided to install Dat and use it without Beaker.

The native binaries failed to compile on Node 8, so I switched to Node 11 (latest stable), installed Dat (`yarn global add dat`), added it to the PATH. I had to `apt install automake autoconf` to compile the binaries. After playing around with Dat, I thought I'd try Beaker one last time, I launched it and lo and behold, it worked.

So my assumption from this is that the build of Dat that comes with Beaker is incompatible with at least some Linux distributions and the fix is to build and install Dat, add it to the PATH and Beaker will pick up the fixed build instead of using its own bundled build.

**Comment by jcalfee** [comment]
I'm having an issue like this, very slow.  Also, two machines running beaker on the same network can't share a library.  I'm running beaker 0.8.2 ..

In the swarm-debugger in 99% of the  peers the connect-failed count === the connecting count.
