### ISSUE TITLE
Crashing on boot with SyntaxError

### ISSUE THREAD

**Issue by RangerMauve** [beakerbrowser/beaker#1223]
Operation System: Windows 10
Beaker version: 0.8.0 (Got installed through the auto updater today)

After updating to 0.8.0, beaker started crashing every time I'd try to start it with the following error:

```
$ "./Beaker Browser.exe"

native array.js:627
for(var x=o;x<aE;x+=aJ){
^^^

SyntaxError: Unexpected token for
    at internal/modules/cjs/helpers.js:110:15
    at internal/modules/cjs/helpers.js:161:3
    at NativeModule.compile (internal/bootstrap/loaders.js:238:7)
    at NativeModule.require (internal/bootstrap/loaders.js:159:18)
    at internal/modules/cjs/loader.js:41:5
    at internal/modules/cjs/loader.js:823:3
    at NativeModule.compile (internal/bootstrap/loaders.js:238:7)
    at NativeModule.require (internal/bootstrap/loaders.js:159:18)
    at module.js:3:18
    at module.js:5:3
```

I assume it's got something to do with Electron.

**Comment by pfrazee** [comment]
Thanks for reporting, I'm debugging now

**Comment by pfrazee** [comment]
We discussed in IRC. Soon after, Ranger ran into a sudden uninstall (https://github.com/beakerbrowser/beaker/issues/1102). He ran the installer again and all was well. I'm trying to reproduce the issues in a windows VM.

**Comment by RangerMauve** [comment]
Running the installer (taken from the releases page) twice fixed the problem. 🤷‍♂️

It seems the first time I ran the installer, it uninstalled it, then the second time the install succeeded.

**Comment by pfrazee** [comment]
@RangerMauve any chance the installer does an uninstall if already installed, and you just didnt notice the UI saying that?

**Comment by pfrazee** [comment]
Well I just tested in my VM, which has Window Server 2016 (which I believe is a windows 10 variant) and unfortunately ... of *course* ... I can't reproduce.
