### ISSUE TITLE
Markdown sidenav and custom CSS is not working

### ISSUE THREAD

**Issue by cryptowyrm** [beakerbrowser/beaker#1224]
Operation System: elementary OS 5 Juno (Ubuntu 18.04)
Beaker version: 0.8.0

---

I've been making use of Beaker's Markdown website functionality (as explained here: https://beakerbrowser.com/docs/guides/create-a-markdown-site), where you just put a Markdown file, some CSS and a nav.md file into a folder and Beaker then automatically turns it into a website with a sidebar.

It worked fine in Beaker 0.8.0-prerelease.9, but it doesn't work anymore in Beaker 0.8.0 final, CSS and the sidebar aren't displayed anymore and there is an error in the console.

This is what it looks like and the error shown in the console:

![screenshot from 2018-10-22 20 40 07](https://user-images.githubusercontent.com/16908445/47313264-bf43ad00-d63e-11e8-9a12-0b9b2a4abbdd.png)

This is what it should look like (old screenshot):

![steem2beaker_articles](https://user-images.githubusercontent.com/16908445/47313282-d08cb980-d63e-11e8-806a-d41aa829733d.png)

Here is the link to my site shown in the screenshot if it helps: dat://b6201615277a04b958afd25b3531b90083f9dc4e2c38e3cbedb0a257def456fe/

And the error message in text form:

```
Uncaught (in promise) ReferenceError: DatArchive is not defined
    at renderNav (<anonymous>:102:16)
    at Object.1.remarkable (<anonymous>:99:3)
    at o (<anonymous>:1:265)
    at r (<anonymous>:1:431)
    at <anonymous>:1:460
```

**Comment by pfrazee** [comment]
Hmm, I cant get your dat site to load, what's your dat.json look like? Are you using the `content_security_policy` directive by chance?

**Comment by pfrazee** [comment]
Oh can you be more specific about what's broken? Is it just the nav?

**Comment by pfrazee** [comment]
Scratch that, I see. It's the nav and the CSS. I was able to reproduce.

Okay this isn't cool. I'm on it. Thanks for reporting.

**Comment by cryptowyrm** [comment]
@pfrazee Ah good that you can connect now, I'm seeding the site with hypercored (as explained here: https://docs.datproject.org/server) so it should always be available even when I have Beaker closed, but it's on my home internet connection so there might be some firewall/router issues going on.

The dat.json is the default created by Beaker, I don't think I've ever manually edited it (just used the Beaker UI to add a donation link) so it should be fine, there is no content_security_policy directive in there but you have probably seen that now that it works for you.

**Comment by pfrazee** [comment]
Okay should be fixed in master
