### ISSUE TITLE
Beaker 0.8.0 release not working on ubuntu 17.10

### ISSUE THREAD

**Issue by Guitlle** [beakerbrowser/beaker#1226]
Operation System:Ubuntu 17.10
Beaker version: 0.8.0

I have downloaded the AppImage release for linux for version 0.8.0 but it does not work. I was using the prerelease 0.8.0-prerelease.9 before and it works well. The debug.log does not show anything wrong. The issue is that no beaker browser window is shown at all. 

### The output
```
xxx@yyy:~/Downloads$ ./beaker-browser-0.8.0-x86_64.AppImage 
installed: X-AppImage-BuildId=a4f55de0-d594-11a8-2f9f-ab15474b2d06 image: X-AppImage-BuildId=a4f55de0-d594-11a8-2f9f-ab15474b2d06

(beaker-browser:14470): Gtk-WARNING **: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(beaker-browser:14470): Gtk-WARNING **: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(beaker-browser:14470): Gtk-WARNING **: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Logfile: /home/guillermo/.config/Beaker Browser/debug.log
Detected Linux. Using default en_US spell check dictionary.
```

###  debug.log

```
Log started at Mon Oct 22 2018 17:43:45 GMT-0600 (CST)
dat Throttling upload to 0 MB/s
dat Throttling download to 0 MB/s
datgc GC unsaving 0 expired archives
datgc GC cleaning out 0 unused archives
datgc []
datgc GC completed in 5 ms
/home/xxx/.config/Beaker\ Browser/debug.log (END)
```

**Comment by pfrazee** [comment]
Hm. I'm able to open the app image from the CLI but it segfaults if I open it from the files explorer. Looking into that.

**Comment by pfrazee** [comment]
@Guitlle can you try running it like this:

```
XDG_CONFIG_DIRS="" GTK2_RC_FILES="" ./beaker-browser-0.8.0-x86_64.AppImage
```

I want to confirm if it's this issue: https://github.com/electron/electron/issues/11234

**Comment by Guitlle** [comment]
No, sorry. No beaker window is shown. I am running only from the cli to see what messages are printed.

**Comment by pfrazee** [comment]
@Guitlle okay so the env vars didn't fix it. Are you able to build from source? If so, is Beaker able to start?

**Comment by Guitlle** [comment]
I'll try build later and see if i can identify the commits that introduce the bug.

**Comment by pfrazee** [comment]
Okay thanks. So sorry for the issue.

**Comment by Guitlle** [comment]
Hi @pfrazee. I am not sure if this should go in a new issue. I attempted to build from source with the git repo but I keep getting this blank beaker window: 

![image](https://user-images.githubusercontent.com/2118234/47958000-1c1c5d00-df87-11e8-9f0c-8481cdf7b5a5.png)

I have followed the simple directions in the readme.

```
npm install
npm run rebuild
npm run start
```

Found a youtube video describing the source but It didnt mention any different steps for building from source.

**Comment by Guitlle** [comment]
As mentioned at #1244, this has to do with an libuv bug that affects electron, somehow related to gpu acceleration. The AppImage can be run in ubuntu 17.10 by doing the following:

```
$ ./beaker-browser-0.8.0-x86_64.AppImage < /dev/null >/dev/null 2>/dev/null
```

Hopefully this will be fixed in the next versions of electron.
