### ISSUE TITLE
On small screens dialogs / panels are getting cut off 

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1229]
Operating system:  macOS 10.14  / Beaker v0.8.0 

This is:

- [x] a bug
- [ ] general feedback

<img width="969" alt="screen shot 2018-10-23 at 9 39 10 pm" src="https://user-images.githubusercontent.com/21236/47406673-59255b80-d70c-11e8-81e1-2e5214cfc248.png">
<img width="968" alt="screen shot 2018-10-23 at 9 39 22 pm" src="https://user-images.githubusercontent.com/21236/47406674-59255b80-d70c-11e8-8801-46fe03204929.png">

**Comment by pfrazee** [comment]
Oof thanks for reporting, I'll get on that.

**Comment by pfrazee** [comment]
This has been fixed for the browser menu dropdown, still a TODO for the modals and other menus
