### ISSUE TITLE
Loading markdown pages causes errors (in console)

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1231]
Operating system: macOS / Beaker v0.8.0

This is:

- [x] a bug
- [ ] general feedback

<img width="1284" alt="screen shot 2018-10-24 at 4 11 47 pm" src="https://user-images.githubusercontent.com/21236/47466825-0600e680-d7a8-11e8-9c1a-93aa26b8a45c.png">

I'm not sure where does that script is coming from, but it does not seem to have `DatArchive` API available. Document itself seem to have access to `DatArchive` API. If I had to guess it's likely a preload script that is loaded ahead of script that exposes `DatArchive` API.

**Comment by pfrazee** [comment]
Thanks for reporting, this got fixed in master. See https://github.com/beakerbrowser/beaker/issues/1224
