### ISSUE TITLE
Embedded images in markdown are treated as links

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1232]
Operating system: macOS / Beaker v0.8.0

This is:

- [ ] a bug
- [x] general feedback

Here is an example url dat://78fafa05de3ae7ece4c6a5b80c109179a747021747c19e353e300e0012ccd46a+20/Readme.md 

I would have expected to see following (please ignore color theme)

<img width="443" alt="screen shot 2018-10-24 at 4 25 24 pm" src="https://user-images.githubusercontent.com/21236/47467114-7825fb00-d7a9-11e8-8fe2-e5a36f701060.png">

instead of 

<img width="677" alt="screen shot 2018-10-24 at 4 24 42 pm" src="https://user-images.githubusercontent.com/21236/47467090-5dec1d00-d7a9-11e8-9fec-f7be77083a04.png">

**Comment by pfrazee** [comment]
Confirmed, thanks for reporting. Fixing now.

**Comment by pfrazee** [comment]
This is an issue in Remarkable, see https://github.com/jonschlinkert/remarkable/issues/145

**Comment by pfrazee** [comment]
Okay fixed in master by switching to a better-maintained markdown module
