### ISSUE TITLE
Question: Is there a roadmap for 0.9.x

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1234]
Now that beaker 0.8.x is out there. ... Congratulations! 

Is there a roadmap for 0.9.x?

**Comment by pfrazee** [comment]
Thanks! We're working on some documents but nothing's ready to share yet. Here's a rough outline of our plans:

 - @Septimus is working on improving the authoring tools which will include
   - A more powerful builtin editor built on Monaco (VS Code's editor)
   - A favicon drawing tool
   - More I'm sure (we've got ideas)
 - @mafintosh is working on the [Dat protocol improvements](https://docs.google.com/document/d/1ersQltSqPdXKNDMygq1M2dxtLkXMnAHLSBSl6y6nTcA/edit) which will include
   - More reliable peer discovery and hole-punching
   - A new version of the hyperdrive datastructure that will handle more files and boost read/write performance significantly
   - "Mounted" dats, a concept similar to symlinks but for dats
   - Multiwriter
 - I'm working on the application stack which will include
   - [Dat identities](https://github.com/beakerbrowser/dat-identities-spec)
   - [Record protocols](https://github.com/beakerbrowser/record-protocols-spec)
   - The [PeerSockets](https://github.com/beakerbrowser/beaker-core/pull/6) API
   - Cryptography tools to sign and encrypt files at rest ([current API proposal](https://gist.github.com/pfrazee/e4a9d1bdd095564991b5b75a5fe49bd7))
   - A few other things

We're also going to be prototyping some ideas around Web-of-Trust Certificates and Search which we're really excited about but not quite ready to discuss yet. We'll keep everyone updated.

**Comment by pmario** [comment]
Hi, 
Just saw on the beaker homepage, that there is a new update on the way. I could help building _and_ testing with Ubuntu 18.04 LTS and windows 10. Just let me know.

**Comment by pfrazee** [comment]
Thanks @pmario!

Whew this issue is old. My response is like... 50% what we ended up doing 😄. I'm going to close it - we'll give detailed updates once the beta is public.
