### ISSUE TITLE
Archive output UI suggestion

### ISSUE THREAD

**Issue by roscoevanderboom** [beakerbrowser/beaker#1236]
This is what it looks like now.

![screenshot 2](https://user-images.githubusercontent.com/39595310/47612095-af5a0d80-da30-11e8-9d52-b34d44039378.png)

Could it be styled to look like this by default?

![screenshot 3](https://user-images.githubusercontent.com/39595310/47612104-cac51880-da30-11e8-877f-78f4eabdffe0.png)

the breadcrumb is not really necessary as it already shows the file path in the browser. Just looks nice

**Comment by pfrazee** [comment]
I'm +1 to a visual improvement. Maybe not that exact style but it could definitely be better.

**Comment by roscoevanderboom** [comment]
haha...yea for sure. 

a container and some padding would go a long way
