### ISSUE TITLE
DatArchive.watch and DatArchive.history should have similar formats

### ISSUE THREAD

**Issue by RangerMauve** [beakerbrowser/beaker#1237]
As mentioned on IRC:

The `history()` API uses `{path, version, type}` for it's change information, where `type` is `"put"` or `"del"`. 
The watch() API, however, uses `{path, type}` where `type` is either `invalidated` or `changed` (the event name)

If you need to get the version and type when a change happens, you need to invoke the history API rather than getting that information right in the event.

Ideally these two APIs should have the same data in them to simplify code that indexes archives and listens for changes.

**Comment by pfrazee** [comment]
I do think we should unify this. I made it hard by reusing the `type` attribute. Perhaps we do this...

For `history()` we output:

 - `path` as before
 - `version` as before
 - `operation` to encode `'type'` and `'del'`
 - `type` as before, for legacy reasons with a plan to deprecate

And then we update `watch()` to emit:

 - `type` as before
 - `path` as before
 - `version` added
 - `operation` added

**Comment by RangerMauve** [comment]
I think that would be perfect!
