### ISSUE TITLE
Can't build beaker browser from source in Ubuntu 17.10

### ISSUE THREAD

**Issue by Guitlle** [beakerbrowser/beaker#1244]
I attempted to build from source with the git repo but I keep getting this blank beaker window:

![image](https://user-images.githubusercontent.com/2118234/47958000-1c1c5d00-df87-11e8-9f0c-8481cdf7b5a5.png)

I have followed the simple directions in the readme.

```
npm install
npm run rebuild
npm run start
```

Found a youtube video describing the source but It didnt mention any different steps for building from source.

I am using ubuntu 17.10. 

I attempted to build checking out the 0.8.0 release commit, and also the 2 previous prereleases with the same result.

**Comment by Guitlle** [comment]
Yes, I tried that too and got the same result.

**Comment by pfrazee** [comment]
When the browser loads, can you hit the `alt` key and get a menu to open? If so, try going

`View > Advanced Tools > Toggle Shell-window DevTools`

And see if any errors show up in there

**Comment by Guitlle** [comment]
Ok, I got this:

```
main.js:137 Uncaught TypeError: beaker.browser.getInfo(...).then is not a function
    at new BrowserMenuNavbarBtn (main.js:137)
    at setup$1 (main.js:1611)
    at setup$4 (main.js:6660)
    at Object.1.@beaker/core/lib/error-page (main.js:6694)
    at o (main.js:1)
    at r (main.js:1)
    at main.js:1
```

Where is beaker.browser.getInfo defined?

**Comment by Septimus** [comment]
I'd recommend, if you don't have any changes, fast-forwarding your fork to the latest commit on master. 

Then run `npm run burnthemall` again.

The `getIntendedUrl` is a relatively recent addition to the source I believe.

**Comment by pfrazee** [comment]
Yeah `beaker.browser.getInfo()` is likely the issue. This looks like beaker-core is out of sync with your source code. Follow @Septimus's advice and you should be okay.

**Comment by Guitlle** [comment]
Well, the problem with that is the related issue #1226 . Latest version does not open any window in this system when both: building from source or with the packaged release.

**Comment by Guitlle** [comment]
Ok, after touching the code in the latest commit at master for a while, I have found out that the issue is related to electron and hardware 3d acceleration : https://github.com/electron/electron/issues/13415

If I add ```app.disableHardwareAcceleration()``` at background-process.js, the windows is shown correcty. 

Maybe the old prereleases are based on an older electron version. 

@anszom fixed it a few days ago  https://github.com/electron/electron/pull/15555  and in the first issue I mention he recommends running the bad electron versions with ```" < /dev/null >/dev/null 2>/dev/null " ``` 

I tried this with the official beaker release 0.8.0 AppImage and it worked fine

```
$ ./beaker-browser-0.8.0-x86_64.AppImage < /dev/null >/dev/null 2>/dev/null
```

**Comment by pfrazee** [comment]
Oh nice find.
