### ISSUE TITLE
Enable UPnP port-forwarding

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1246]
Beaker is supposed to be for normal users that don’t fiddle with their router settings, right? Then it should pick a random TCP port number for Dat and setup port-forwarding using UPnP for that port by default.

This should help increase the number of reachable seeders. It should also give people a better experience when they experiment with peer-to-peer distribution in Beaker.

Note that Beaker shouldn’t use a hard-coded port number with UPnP in case there are more than one client on the same network. Assigning a random port number for every session is also the preferred solution anyway as some [crappy budget] routers have issues with renewing/reassigning the same port number and will return a failed state for existing port mappings even when they point to the same internal IP that is requesting reassignment.

Using a hard-coded port number with IPv6 and falling back to one on IPv4 when UPnP fail is in line with what other software does.

**Comment by RangerMauve** [comment]
Beaker is going to be using [hyperswarm](https://github.com/hyperswarm/network) for all it's networking, so it might be a good idea to check to see how this would work there.

**Comment by nettiopsu** [comment]
@RangerMauve @pfrazee btw, do you have some approximate timeline when is it gonna be released with hyperswarm?

**Comment by pfrazee** [comment]
Unfortunately no. Maf is workin hard on it.
