### ISSUE TITLE
Beaker tries to download whole dat archive before showing a site

### ISSUE THREAD

**Issue by nettiopsu** [beakerbrowser/beaker#1247]
Operation System: MacOS 
Beaker version: 0.8

I have a dat archive that contains a big PDF file (8mb), plain html and json file. The last two files are updated often, PDF - never and it is not linked to index.html. 
I just realized that Beaker tries to download this PDF at first, while I am just trying to download the plain index HTML. As a result I am just waiting like a minute at least, because Beaker deals with big PDF, but does not show any HTML during this time... Moreover, Beaker often times out, probably because does not get in time this PDF, which I do not need

I do not think this is right behavior to download anything apart from index.html before other files. Moreover, why Beaker downloads this PDF? Should not it load just HTML and then only related JS, CSS etc. files that index.html needs?

**Comment by pfrazee** [comment]
@nettiopsu what's your evidence that Beaker is downloading the PDF? It's designed to only download files as needed, so that would indicate a bug.

If the issue is just performance, then the cause might be different than the PDF getting downloaded.

**Comment by nettiopsu** [comment]
@pfrazee yeah, it seems you are right, because I clicked this "peer-to-peer" icon in top right corner in Beaker and it was showing me that it is downloading something N kB/s and I thought this is speed of download. But now I realised it shows size of this download :) sorry for that

I still having problems with performance, as it takes to long even to download 200kb. And there is a big difference comparing to dat cli in speed and connectivity . But I think I will close this ticket, as it is a false alarm for PDF download anyway

**Comment by nettiopsu** [comment]
@pfrazee no, it is actually hosted on 2 remote servers. Beaker also does not see one of them sometimes. But still speed sometimes seems to be too slow in Beaker, as dat cli can reach 1mB/s

Yeah hyperswarm seems to be cool feature but I struggle to show my partners Beaker in production and promote dat, because I can not load even the simple page :D

**Comment by pfrazee** [comment]
Yeah, the reliability and performance is a problem. Maf's full time job right now is on fixing that.
