### ISSUE TITLE
Can't add DNS issues to watchlist

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1249]
Operation System: Fedora Linux 29
Beaker version: 0.8.0

1. Open dat://example.com/

Expected: Error page with button that allows you to add the site to your watchlist.

Actual: You'll see a page saying "No DNS record found for dat://example.com".

**Comment by pfrazee** [comment]
Should we be watching, in that case? It's not really a "failed to find a peer" issue -- it's a "there isn't a dat setup here" issue.

**Comment by RangerMauve** [comment]
I think it kinda depends on what the error is. If the error occurred because you have no internet and can't do a DNS query, it should be added. If the DNS query worked, but a record wasn't found, it shouldn't be added.

**Comment by pfrazee** [comment]
@RangerMauve Good point

**Comment by da2x** [comment]
Or there was an issue on the server, such as with Hashbase earlier today ... .
