### ISSUE TITLE
Plugin development steps

### ISSUE THREAD

**Issue by dmp1ce** [beakerbrowser/beaker#125]
Operation System: Arch LInux
Beaker Version: I don't know

I followed the steps here https://github.com/beakerbrowser/beaker/blob/master/doc/authoring-plugins.md for building a plugin but I couldn't get it to work by doing `npm install` in the `beaker` directory. I had to do `npm install` in the `app` directory and then `npm run rebuild`. Then I could begin working on the plugin. Every change then required me to restart beaker with `npm start`.

Does that sound right?

**Comment by pfrazee** [comment]
That's correct

**Comment by dmp1ce** [comment]
This is what I had to do to get my beaker-plugin-example to work. #126
