### ISSUE TITLE
writing files is slow

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1250]
Operation System: windows 7
Beaker version: Beaker v0.8.0-prerelease.9 is up-to-date

for some unexpected reason i can't find any answer why beaker writes 1500 json files very slow compared to another app i created which writes much larger amounts of json  files in less than 4 minutes,whereas the following code takes to write those json files more than 2 hours
  i use the following code:
async function wobjects()
{

var archive = new DatArchive(window.location );
 await archive.mkdir('/objects'); 
   var initdata = {fname:"Bob"};
  var data = JSON.stringify(initdata);
 for(var i = 0;i < 1500; i++)
 {
 
  var path = "/objects" +"/" + i +".json";
  await archive.writeFile(path, data);

   }
var topFiles = await archive.readdir('/objects');
}

**Comment by pfrazee** [comment]
Huh. This actually is quite slow. I have an SSD and it took... well, about 2 minutes to hit 750 writes, and the entire browser slowed down for it, *and* the writes were slowing down as it went.

I'm going to profile but there's a chance this is just hyperdrive v1 being slow. Hyperdrive v2 should be faster. I'll see what I find though.

**Comment by pfrazee** [comment]
Yep, looking at a profile, the work is being done entirely inside of hyperdrive. I'm going to leave this open while we track the hyperdrive v2 update.

**Comment by arni077** [comment]
When v2?

**Comment by pfrazee** [comment]
Within the next 6 months
