### ISSUE TITLE
beaker won't apply new changes

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1251]
Operation System: windows 7
Beaker version: Beaker v0.8.0 is up-to-date

Today i updated beaker version to the latest and noticed the new version won't update new changes when i edit my code, i mean changes to my javascript code or even changes to HTML code (if i change < p > tag value from 0 to 1 beaker will continue to show on my website page 0 instead of 1) 
i also tried to change this with javascript, and that didnt work
document.getElementById("p").innerHTML = countf;

**Comment by arni077** [comment]
Sorry,i dont understand how to config.
I edit the code from my personal notpad and the files i edit located within C:Dat folder which i dont share

**Comment by arni077** [comment]
ok i got it, but i think it is too much complicated...why wont change it be automatic as it was before?

**Comment by Septimus** [comment]
@arni077 if you turn of preview mode, there is a toggle in the settings tab in library view, it will change it automatically as it did before :)
