### ISSUE TITLE
Couldn’t resolve the DNS address for...

### ISSUE THREAD

**Issue by glensimister** [beakerbrowser/beaker#1257]
Operation System: Windows 10
Beaker version:  - 

At a first glance, Beaker Browser looks great! I got it working with a site that I am developing although it has since stopped working and now says “Couldn’t resolve the DNS address for...”. I am able to load other sites though. I have looked at the settings, cleared the history/cache but to no avail. Any ideas? 

Anyway, while i'm here, there's a few questions I'd like to ask....

1) Has anyone used GunDB (gun.eco)?  GunDB is an “eventually consistent” P2P graph database engine, which resolves merge conflicts using string comparison. It is lightweight (just one js file) and has a relatively simple syntax (similar to Firebase). Would there be any benefits of using (or possibly integrating) GunDB with Beaker? 

2) I'm really interested in Tim Berners-lee's Solid project. Could something like this be done using Beaker? Has anyone looked into it? I read that some of the people using GunDB are already looking into this. Is it worth collaborating with them? I'm working on a social media application that is designed to give communities political independence. https://github.com/glensimister/givemecredit.  However, there's no point doing the social media stuff myself since other people have already done this, a thousand times before. I'd rather just aggregate data from multiple platforms using a REST API. What social media platforms have been developed on Beaker so far? I've seen Fritter. Anything else? What about Minds.com? It is open-source and has crypto built into it. It is currently hosted on Amazon Web Services (AWS) and is built using  MongoDB, NodeJS, Socket, OpenSSL, Ethereum, etc. Can we port Minds onto Beaker to make it truly decentralized?  

3) One thing that I am surprised about is the lack of ratings/comments features on web browsers. I have designed a basic extension (screenshot at the link above) which allows people to like, dislike, flag, tip and comment on anything, anywhere. To me, these things seem like important features which could also serve as the back-bone of a search engine. I haven't done any of the back-end code yet because I'm not a back-end coder. Not only that but I still haven't decided which technologies/platforms to use yet. One obvious problem is that in order for it to be of any use, it would require a large percentage of users to participate, which would generate large volumes data unless users were able to store only their likes/dislikes/comments etc. Anyway, does anyone have any plans to do something like this? 

I don't mean this as an insult, but there seems to be an overall lack of collaboration in the decentralised tech scene. Everybody is doing their own thing, which is great, and I appreciate their work, but would it not help to work together a bit more? One thing that I would suggest to start with is to get all of these projects on the same forum – each with their own category. Thanks!

**Comment by pfrazee** [comment]
I'd need more information to answer you question about the DNS issue. Any more you can share?

I don't have a lot of time to respond to your points, so I'll just give a quick rundown: we currently don't need any other tech and we collaborate whenever we think it'll benefit the Beaker community. Some things just take time.
