### ISSUE TITLE
Writing files skips on files

### ISSUE THREAD

**Issue by arni077** [beakerbrowser/beaker#1259]
Operation System:windows 7
Beaker version: Beaker v0.8.0-prerelease.9 is up-to-date

writing 1100 json files inside a 'for' loop misses writing 16 files constantly. I cant even understand why it happens?

**Comment by pfrazee** [comment]
Really? That's interesting, was it the same 16 every time?

**Comment by arni077** [comment]
it wasnt the same 16 files every time! sometimes it misses to write 18 files and so on... it seems like a random behavior to me.

**Comment by Butterfly** [comment]
Observation from the (nosebleed) bleacher seats.. I couldn't help noticing 16's divisible by a computational type 8 bits.. in case that somehow leads to insight into the issue.. :smile:

**Comment by pfrazee** [comment]
Not yet, sorry

**Comment by pfrazee** [comment]
Have you tried since the latest release, which put dat in its own thread?

**Comment by pfrazee** [comment]
I really don't have any theories yet. The write is failing silently, because otherwise the `await` would not return, or would throw an error. It's probably a sign of something wrong in Beaker or Dat's internals.

**Comment by hossameldeen** [comment]
@arni077 I'd like to try it. If the code is not private, could you show it to me, please?
