### ISSUE TITLE
Can hypercored by used for mirroring Beaker's dats?

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1260]
Can [hypercored](https://github.com/mafintosh/hypercored) be used for mirroring Beaker's dat archives?

Sorry, not familiar with hyperdrive vs hyperdb vs hypercore vs DatArchive.

I've tested it and it worked. I just want to make sure it'll work in all cases.

Thanks in advance!

**Comment by pfrazee** [comment]
Yep!
