### ISSUE TITLE
SVG-in-OT support missing for color emoji fonts

### ISSUE THREAD

**Issue by interfect** [beakerbrowser/beaker#1263]
Operation System: Windows 7
Beaker version: 0.8.0

Color fonts, like EmojiOne and Twemoji, are not being rendered in color in Beaker. I see monochrome versions of the characters instead. I suspect that this may be due to a lack of SVG-in-OT support in the Chromium renderer being used.

1. Go to https://color.typekit.com/ in Beaker
2. Disable the `color: transparent;` rule on the `.emoji` class with the inspector.

You will see white non-color emoji characters pop up over the polyfilled SVG backgrounds.

You should see rendered color emoji characters from the font, like you get in Firefox, where the polyfill is deactivated.

I *did* manage to find one color emoji font that Beaker will draw: [Google's own Noto Color Emoji](https://github.com/googlei18n/noto-emoji). However, Firefox can't draw that font, because it's in a format Firefox can't handle.

**Comment by pfrazee** [comment]
This is probably something we'll just have to wait for Chromium to implement.

**Comment by baerbock** [comment]
Nobody needs color emoji. Beaker is a real project, not something for playful children.

**Comment by interfect** [comment]
Nobody *needs* most of the features in a web browser. Also, color support
in fonts isn't *only* for emoji; you can also use it to colorize something
like Font Awesome.

Also, the Beaker project seems to value fun. Emoji are fun.

**Comment by lvivier** [comment]
For reference, OpenType-SVG support is [Chromium issue 306078](https://bugs.chromium.org/p/chromium/issues/detail?id=306078). The general colour font support is [issue 703332](https://bugs.chromium.org/p/chromium/issues/detail?id=703332), apparently with no plans to support OpenType-SVG 😐
