### ISSUE TITLE
Make an editable copy not copying contents

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1265]
Operation System: macOS 10.14.1
Beaker version: v0.8.1

Using either the UI "Make editable copy" or the DatArchive.fork api creates an editable copy with only the folder structure, and not any of the files other than `.datignore` and `dat.json`.

Steps to recreate, make an editable copy of a dat, e.g. beakerbrowser.com

Version history from an editable copy made from beakerbrowser.com, appears to only contains entries for the folder structure.
![screenshot 2018-11-19 at 19 34 36](https://user-images.githubusercontent.com/1552489/48730476-6281e500-ec32-11e8-963c-d1787c04375f.png)

**Comment by paul90** [comment]
Just rebuilt v0.8.0, and making an editable copy works correctly with that version.

**Comment by Vassili-g** [comment]
Same problem on my side with the UI on the latest downloaded version

**Comment by pfrazee** [comment]
Yep able to reproduce. Looking into it now, thanks for filing

**Comment by pfrazee** [comment]
Okay, fix pushed to master. Will release a new version with the fix soon.
