### ISSUE TITLE
Handle tab overflow

### ISSUE THREAD

**Issue by kekukui** [beakerbrowser/beaker#1272]
If too many tabs are open to fit in the current window, the excess tabs are not visible.  Chrome addresses this problem by reducing tab width.  Some Chrome-based browsers will also limit the maximum number of tabs in a window.  Firefox uses tab scrolling instead.  Regardless of what solution you choose, the problem of invisible tabs needs to be addressed.

**Comment by pfrazee** [comment]
Added to the todos

**Comment by pfrazee** [comment]
This behavior has been updated. Now, all tabs are visible, though they are a bit crowded. We do need a better solution: a dropdown or a scroll for overflow.
