### ISSUE TITLE
Unsupported Emojis on linux

### ISSUE THREAD

**Issue by raphaelbastide** [beakerbrowser/beaker#1273]
Operation System: Linux (Debian XFCE)
Beaker version: 0.8.0 Electron: 3.0.4 - Chromium: 66.0.3359.181 - Node: 10.2.0

Emojis appears correctly in any browser I use except in Beaker where I have for most of it, the empty rectangle glyph.
![screenshot_2018-11-26_15-42-02](https://user-images.githubusercontent.com/193122/49020950-e20f3700-f191-11e8-97e3-5cdcf5825c92.png)
Tested with the hole emoji "🕳" for exemple.

Edit: After some basic tests, I can see that Beaker takes my default font «Deja Vu» and stops there. It does not load my local emoji font “Symbola”, just like Chromium does.

**Comment by pfrazee** [comment]
Thanks for filing. We should check if this is a known issue with Electron.

**Comment by raphaelbastide** [comment]
Hello, I just got back to the issue and it now works for me too! I don’t really know how the issue solved itself on my system. Closing. Thank you !
