### ISSUE TITLE
Using a frontend router / pushState

### ISSUE THREAD

**Issue by oelmekki** [beakerbrowser/beaker#1274]
Operation System: linux
Beaker version: 0.8.1 (from git sources)

Hi guys,

I'm having a lot of fun playing with Beaker, thanks a lot for it!

I'm currently building an application using react and react-router. It's a pushState based frontend router, which changes url using pushState and parses the url on page load to detect which "page" to render (the frontend is entirely responsible for it).

When I do that on top of a classic http backend, I just make the backend render the base html/js/css files for any unknown url, and then the frontend decides what to do with it.

But with beaker, if I use pushState to change the url then reload the page, it obviously gives a "File not found" error.

Eg:

1. the path `/` lists some articles
2. clicking an article title change the url to `/articles/1` and displays its content (the file does not exist, the frontend app manages how to retrieve the article)
3. if I reload the page, I have an error "File Not Found, Beaker could not find the file /articles/1"

> I hope this is clear enough, let me know if you want me to publish a demo

This is all expected behavior of course, but I wonder if you know any workaround that allows to use a frontend router, like for example allowing a fallback content for file not found in a given archive?

**Comment by pfrazee** [comment]
Hi @oelmekki !

This should be easy to fix, just use https://beakerbrowser.com/docs/apis/manifest#fallback-page

**Comment by oelmekki** [comment]
Oh, awesome!

And sorry to have missed that. Hopefully, this will help people searching for things related to frontend routers or pushState :)

thanks for your help,
closing.
