### ISSUE TITLE
DatArchive.fork() Promise fulfilled before contents fully copied

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1275]
Operation System: macOS 10.14.1
Beaker version: v0.8.2

When calling DatArchive.fork(), on a fully downloaded archive, it is hit or miss that the files will have been copied before trying to read one of them in subsequent code - resulting in file not found errors even if when viewed in the library the file is present.

A simple test script, it writes to the console.log and is run by pressing the 'create fork' button which may need to be done a number of times given the hit or miss nature of the problem -  dat://90bc6f42d4bf0b76d194470d860ca563869dd46d751104a7776adde9fe119f8e

**Comment by pfrazee** [comment]
Okay thanks for filing. I'll hit this asap.
