### ISSUE TITLE
Changes not detected while preview mode is off

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/beaker#1276]
I've experienced this issue a few times since I've updated to 0.8.1 and now to 0.8.2. If preview mode is off the changes aren't visible on the site. They're sometimes visible in the `+preview` version, but other times not. 

I thought it happens only for me, but I've experienced the issue from other computers too (in a workshop in Brussels for example, that was a bit embarrasing haha).

Operation System: Linux
Beaker version: 0.8.2

**Comment by pfrazee** [comment]
@kodedninja are you saying that the automatic publish fails sometimes? Are you sure the path is set correctly?

**Comment by kodedninja** [comment]
Exactly! If I just turn preview mode off for an archive that worked with preview mode and change something, it's not published. After I re-enable preview mode the changes are detected and I can publish them.

I'm not sure about the "sometimes". Currently it never works for me...

**Comment by pfrazee** [comment]
Is there any chance you have a cyclical symlink in your folder? That might cause the sync to abort.

**Comment by kodedninja** [comment]
I don't think so. It happens for totally new sites too. 

My `Sites` directory is used by Beaker only. Oh, and Atom. Can that cause the problem?

**Comment by pfrazee** [comment]
> Oh, and Atom. Can that cause the problem?

It shouldn't. If you start Beaker from the CLI, do you see some output that might explain anything?

**Comment by kodedninja** [comment]
I'll try it when I get home! Is it perfectly working for you?

**Comment by kodedninja** [comment]
It works on Windows (at least when I tried it). This might be connected to the other bug I experience: live reload doesn't work (same sometimes).

**Comment by pfrazee** [comment]
Live reload gets triggered on change, so that would be connected

**Comment by kodedninja** [comment]
So, I've been observing the console for a while and found no unexpected output other than `Uncaught TypeError: this._store[key].timeout.unref is not a function`, but this happens only when preview mode is enabled and live reload is turned on. Other than that everything seems quite right. :/

**Comment by pfrazee** [comment]
Okay, I've got this on my todos to fix. Sorry for the trouble.

**Comment by kodedninja** [comment]
Great! No problem. Sorry that I can't give more information.
