### ISSUE TITLE
Session restore does not work on 0.8.1 and 0.8.2

### ISSUE THREAD

**Issue by rapha8l** [beakerbrowser/beaker#1280]
Operation System: Void linux and AppImage
Beaker version: 0.8.1 and 0.8.2

Even when set, session restoring does not work , I just get one blank tab
Thanks

**Comment by pfrazee** [comment]
Thanks for filing. Do you have any other data that fails to retain?

**Comment by rapha8l** [comment]
Thanks
Well I did not notice anything else for the moment

**Comment by alexandre1985** [comment]
I have this same issue on Manjaro Linux
