### ISSUE TITLE
Higher memory consuming webpages reload

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/beaker#1281]
Since the latest update websites with higher memory usage (Google Inbox, Google Docs), but sometimes even Are.na or just random sites, after the first load don't stop reloading for another few times and it makes a few sites unusable. I think it's related somehow to memory.

Operation System: Linux
Beaker version: 0.8.2

**Comment by pfrazee** [comment]
Thanks for filing. I'll see if I can figure anything out about this.
