### ISSUE TITLE
DatArchive.create({ prompt: false }) should allow selection.

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1286]
From my experience more often that not I want to deliver experience where user can work on the content without distraction, and  [`DatArchive.create({ prompt: false })`](https://beakerbrowser.com/docs/apis/dat.html#datarchive-create) delivers that to some degree, because user isn't required to take immediate action. On the other hand it fails at reusing already existing archive where that would be have made more sense e.g. same app can be loaded under different URLs (hash, preview url, domain name, next version).

I would suggest to combine `DatArchive.create` and `DatArchive.selectArchive` into one API call e.g. `DatArchive.mount` as I think reuse vs creation is odd to be a user choice. It also would provide an opportunity for beaker to provide selection when there's an archive(s) that matches criteria. Furthermore I think door-hanger prompt should give user a choice to select archive when:

- App attempts to create new archive.
- When app is trying to write into an archive first time.

My general sentiment is I as an app author rarely care where data is being written to, all I care is to preserve pointers to things that I've written for quick access. And when I write things it's either 1. to save for a future revision or private use or 2. to publish it to a group of people (which could mean everyone a.k.a public). In 1st case I think location / archive does not matter and 2nd user is in a better position to make that call.

P.S. I'm not sure how relevant all this given the profiles work but I thought I'd still write it down.

**Comment by pfrazee** [comment]
Yeah thanks for posting this. I've been thinking about it idly as I work on blue. I'm not sure what the final solution should be but I do think the flows for apps to create & work-on dats has been subpar. I think it'll improve as the experience overall gets more defined.
