### ISSUE TITLE
Preferences menu selection causes no visible UI change with no open windows

### ISSUE THREAD

**Issue by machawk1** [beakerbrowser/beaker#1287]
Operation System: macOS 10.14.2
Beaker version: 0.8.2

Many macOS application, inclusive of Beaker Browser, stay open when the last window is closed. In Beaker Browser's case, this may be useful for continually seedings sites (I would imagine, I'm new to it).

When I have closed the last Beaker Browser window, it remains in my macOS Dock and the Beaker Browser menus (Beaker Browser, File, Edit, etc.) remain accessible. Selecting the Beaker Browser menu then Preferences causes nothing to be visually shown in the user interface.

This only seems to be the case when there is no visible Beaker Browser window being displayed. If one is visible, a new tab is created to show the Preferences. However, if no window is shown, it seems that no new tab/window is created.

**Comment by machawk1** [comment]
On further inspection, this same behavior is exhibited for other menu items as well. For example, in the same scenario with no Beaker windows open, selecting View>Toggle Dev Tools does not cause anything to display on the screen.

**Comment by pfrazee** [comment]
Fixed! Huge thanks to @lvivier. I didn't even have time to triage this before it was fixed
