### ISSUE TITLE
Update peer count UI to not change width when the peer count changes

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1289]
![peer-count](https://user-images.githubusercontent.com/21236/50366530-0f4fca80-052f-11e9-9955-7a8b8c9fec90.gif)

I just had that happening non-stop distracting me from what I was trying to do. Allowing little more space for the peer count might be a good idea.

**Comment by pfrazee** [comment]
Fixed by @lvivier. Thanks!
