### ISSUE TITLE
Setting favicon updates archive even if preview mode is on

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1290]
Operation System: Ubuntu 16.04
Beaker version: Latest - compiled from source

- I have **preview mode on**.
- From **Settings**, I change the icon to another one.
- **Expected:** Icon is written to the draft/preview.
- **Actual:** Archive is updated instead of the preview.

**Comment by pfrazee** [comment]
Thanks for filing. Added to our todos.
