### ISSUE TITLE
Discussion: DatArchives sending "signals" to each other

### ISSUE THREAD

**Issue by mikister** [beakerbrowser/beaker#1295]
Could it be possible for DatArchives to send "signals" to one another.

## Implementation Suggestion:

An experimental API that behaves similar to creating a JS custom event, e.g.:

```javascript
// Target of the datSignal
var otherArchive = new DatArchive(otherArchiveLocation);

// Create a Custom datSignal
var updateSignal = experimental.datSignal("Update");

// Dispatch the datSignal
updateSignal.dispatchTo(otherArchive);
```

And on the front-end side this doesn't event need to be implemented, but the JS event system could be used instead.
Say, in that **`otherArchive`** the **`updateSignal`** is received by an EventListener **`updateEvent`** attached to document, and when the archive receives that signal it just fires off that **`updateEvent`**.

**Comment by pfrazee** [comment]
Is the idea that these signals would go over the network, and the signals would go to the dat owners?

**Comment by pfrazee** [comment]
Or is the idea that these are just custom events that you could fire on the objects within your app?

**Comment by mikister** [comment]
The former. The signal would be dispatched to the target archive which would receive it and fire it off as a JS event inside of its own html page.

Also I can see one problem in this and that is that archives aren't available all the time, so there might not be an archive to receive the signal. A solution might be to implement/reuse a watcher (just like the one used for the Beaker Watchlist) and dispatch the signal when the archive becomes available.

**Comment by pfrazee** [comment]
@mikister yeah that's a solid idea, basically using Dats as identities. We've got some tools for messaging in the works with https://github.com/beakerbrowser/beaker-core/pull/6 so we might be able to accomplish that kind of stuff.
