### ISSUE TITLE
Support communication with Dat Fox extension, without need to download their app

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1299]
https://github.com/sammacbeth/dat-fox

**Comment by DaniellMesquita** [comment]
So, without need to download an app, Beaker could work like [dat-fox-helper](https://github.com/sammacbeth/dat-fox-helper).
@sammacbeth would you help @pfrazee on that?

**Comment by pfrazee** [comment]
Is the reasoning for this that you want to be able to share datasets between Beaker and dat-fox?

**Comment by DaniellMesquita** [comment]
> Is the reasoning for this that you want to be able to share datasets between Beaker and dat-fox?

Yes, with Beaker running on background as a helper app of dat-fox

**Comment by pfrazee** [comment]
Okay we can consider that.
