### ISSUE TITLE
Use a new VCS for versioning the sites

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1300]
![image](https://user-images.githubusercontent.com/6765277/50747237-0a229900-121a-11e9-9ad8-2f76eda06b0c.png)

Sorry, but the current VCS is pretty weird, creating more than 200 versions: one version for every file added. Better if there could be an simple VCS, with option for add which files to version, and commit with a title.

I would recommend you Pando, that is a simpler and improved VCS: https://github.com/pandonetwork/pando/tree/master/packages/cli

Personally I'm starting to replace git to Pando on my projects, as it is usable on IPFS and Ethereum's contracts.

Also, a question: is Dat really lightweight compared to IPFS, by just appending the bytes changed instead of uploading a new file?

**Comment by pfrazee** [comment]
The VCS will get better over time. It's just not our focus right now. Some ways you can improve the situation:

 - Turn on preview mode. It lets you work on the site and then publish when you're ready to go.
 - Use .datignore to keep items out of the repo, if you want.

**Comment by DaniellMesquita** [comment]
@pfrazee

I didn't noticed about that, so I suggest you to show a message for when creating a site.

Isn't better to use an already existing VCS and contributing to it?

So when using Pando (that is focused on Ethereum/IPFS) and committing, users are automatically doing that for Dat/Beaker.

**Comment by DaniellMesquita** [comment]
@osarrouy 
Could you refactor Pando's VCS to be compatible with the VCS of Dat/Beaker? That would be a very good gap between Dat and IPFS.
So when committing with Pando, you're also committing to IPFS and Dat, and same when committing from them.

Hope to see DApps running on Dat network.
