### ISSUE TITLE
Using two icons

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1305]
![image](https://user-images.githubusercontent.com/6765277/50749263-eb75cf80-1224-11e9-9015-ba411b82700a.png)

**Comment by pfrazee** [comment]
Interesting, thanks. Must be an old asset somewhere.

**Comment by jeremyredhead** [comment]
somewhat relatedly, how do i get the old icon back? ;P
(i like it better, sorry)

**Comment by pfrazee** [comment]
> somewhat relatedly, how do i get the old icon back?

You'll have to solve that one yourself, sorry

**Comment by paul90** [comment]
I notice building the current master branch - a0a698d3522f07ee220357ece549873e5867ab1d  - on macOS shows the old icon on the homepage tab.

**Comment by paul90** [comment]
There are 4 old icon files in `app/assets/img/`

**Comment by pfrazee** [comment]
Finally got this handled
