### ISSUE TITLE
Supports for IPv6

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1306]
Maybe related to: https://github.com/beakerbrowser/beaker/issues/1246

**Comment by da2x** [comment]
You'd never use UPnP with iPv6. The last time I tested, it appeared to work fine. What support do you mean is missing?

**Comment by kravietz** [comment]
From my observations, IPv6 addresses seem to be ignored completely while discovering peers, which seems to be a huge downside as IPv4 is in many cases blocked by NAT while IPv6 aren't. Essentially, with IPv6 there's no need for UPnP whatsoever.

**Comment by RangerMauve** [comment]
This is where ipv6 support would need to be added. https://github.com/hyperswarm/dht/issues/1
