### ISSUE TITLE
Most important sites are built with the app and saved on user folder

### ISSUE THREAD

**Issue by danimesq** [beakerbrowser/beaker#1309]
Instead of downloading important sites like "Beaker home", "Documentation", "Dat project", "Explore the p2p web", they are built with the app and saved on user folder, for fast loading.

**Comment by DaniellMesquita** [comment]
> We're looking into a good way to have some dat sites preinstalled but haven't worked out the mechanics yet. Closing because it doesn't really need to be in the issue tracker.

Its not just a issue tracker. It is supposed to be just for bugs, but there is also the `enhancement` label.

About preinstalling dat sites, it is pretty simple: sites are shipped on Electron's app folder, and when starting for first time, copy these sites and add to user folder; as usual way new sites are created/downloaded.
