### ISSUE TITLE
Beaker Quantum

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1310]
Even with the fact that it can have a great refactor, I see that Beaker is very lightweight, reliable and faster than Brave and other browsers.

But it can have a great change on its design and receive new features on an new Beaker: Quantum.

![image](https://user-images.githubusercontent.com/6765277/50796782-e6af2b00-12b9-11e9-836e-abd935799b05.png)

The rebranding includes new icon and new typography:

![image](https://user-images.githubusercontent.com/6765277/50796845-165e3300-12ba-11e9-87d5-130388a63d54.png)

The brand new Beaker includes these new features:

![image](https://user-images.githubusercontent.com/6765277/50797440-e9ab1b00-12bb-11e9-8caf-42c8bf9c2b9a.png)

**Comment by pfrazee** [comment]
@DaniellMesquita Hey, I appreciate the suggestions! But we have limited time, team members, and resources, and we've already committed to a roadmap internally.
