### ISSUE TITLE
AppImage keeps starting forever on Ubuntu

### ISSUE THREAD

**Issue by fiatjaf** [beakerbrowser/beaker#1319]
Operation System: Ubuntu 17.10 artful
Beaker version: 0.8.2

```
fiatjaf@menger ~> ./Downloads/beaker-browser-0.8.2-x86_64.AppImage 
installed: X-AppImage-BuildId=e318d970-f3ef-11a8-14c1-8f8c7cf8238c image: X-AppImage-BuildId=e318d970-f3ef-11a8-14c1-8f8c7cf8238c
[ dat-daemon ] Starting...
```

It stays on that screen forever.

**Comment by brechtcs** [comment]
I've experienced the same issue myself. For me though this only occurred when starting Beaker from the Terminal. When running the AppImage from anywhere else, for example the File Explorer, it should work.

**Comment by fiatjaf** [comment]
As if I had a file browser.

**Comment by brechtcs** [comment]
Note to self: never bother trying to help @fiatjaf again.

**Comment by fiatjaf** [comment]
C'mon, @brechtcs, I didn't mean to hurt you. I don't know why I sounded bad, but if I did I'm sorry. I was frustrated.
