### ISSUE TITLE
support for dweb protocol for dat only

### ISSUE THREAD

**Issue by norzak** [beakerbrowser/beaker#1327]
I am not sure how feasible could this be but also adding dweb:// for only dat into beaker browser would make the standardization efforts of the web decentralization for the future easier. Just a thought.

Both dat://beakerbrowser.com/ and dweb://dat/beakerbrowser.com/ would just do the same thing.

**Comment by pfrazee** [comment]
Thanks for the suggestion, but that would just complicate things
