### ISSUE TITLE
Show alltime leech/seed totals in settings

### ISSUE THREAD

**Issue by cybermancy** [beakerbrowser/beaker#1331]
Operation System: macos
Beaker version: v0.8.2

When you visit Library > Currently Seeding > $website_name > network the totals/ratio aren't shown. I think the totals are shown if you actually visit a page and click the peer number but I'm not sure if those are totals or not. It would be nice to see totals in both places however.

Also show totals in the main settings > dat-network-activity overview

I take pride in getting a high ratio :)

**Comment by ahstro** [comment]
This would be really cool (and a bit of a carrot for those of us who need to attach a number to our altruism for it to count :wink:). Is the data available already and it's just a matter of writing a UI for it or is only the last hour's network activity saved?
