### ISSUE TITLE
No one can access my shared sites

### ISSUE THREAD

**Issue by cybermancy** [beakerbrowser/beaker#1332]
Operation System: macos, windows, ubuntu
Beaker version:0.8.2

I have tried sharing files from multiple computers on multiple networks. I don't know what's wrong but I simply cannot create a site and have others begin visiting it. I've tried on a home network and on a cellular network on all the operating systems listed.

**Comment by pfrazee** [comment]
Try updating to 0.8.3 and let me know if this continues. We released some fixes to the Dat stack.

**Comment by pfrazee** [comment]
(Connectivity still won't be perfect but there were a few known bugs that got fixed.)

**Comment by kodedninja** [comment]
I don't know if it's technically related to this, but the outcome is kind of the same.

Operating System: macOS
Beaker version: `^0.8.0` for sure

Peers are found, but all the connections end up with "Error: No proof available for this index". 

The peer count rapidly jumps between 0 and number of peers. My sites are not accessible outside of Beaker, not even with locally running the Dat CLI. The `.dat` directory is downloaded, but no other files. Tried with multiple sites, networks and Beaker versions.

It's interesting though, that I can access other sites and download them locally.

**Comment by pfrazee** [comment]
@kodedninja Yeah that's the issue that suddenly showed up in the Dat stack. Definitely make sure you're using latest everything.

**Comment by kodedninja** [comment]
@pfrazee Is it solved in `0.8.5`? There's still the freezing issue there :( But I'm patient 🙄

**Comment by pfrazee** [comment]
@kodedninja Yeah that's where the fixes got included ☹️ . Unfortunately I the Electron team hasn't picked up that issue yet. (I'm in the process of rewriting Beaker's UI to use BrowserViews right now with the hope that it'll solve the freezing, or at least reduce it's frequency. It's a big undertaking, unfortunately.)

**Comment by kodedninja** [comment]
@pfrazee Allright, thanks a lot! Wish you luck haha

**Comment by johnnagro** [comment]
I'm experiencing what seems to be the same issue - basically unable to view any sites (even dat://beakerbrowser.com/), peer count jumps around, all connections end with "Error: No proof available for this index".

Ubuntu 18.04.2 LTS
Beaker.Browser.0.8.8.AppImage

I will note that older versions work fine - beaker-browser-0.8.2-x86_64.AppImage works fine.

**Comment by kodedninja** [comment]
@johnnagro this should be fixed with the latest Beaker release, although the old archives are corrupt. I cloned my not working sites and they're working good now.

**Comment by johnnagro** [comment]
@kodedninja unfortunately 0.8.8 was not working, however i had a thought - i deleted `~/.config/Beaker Browser` (which was originally created long-ago by an older build) and retried 0.8.8 appImage and it seems to be working now.

**Comment by johnnagro** [comment]
@kodedninja actually i take that back. i was heading to https://beakerbrowser.com and it was transitioning to dat://beakerbrowser.com. If i try to head to dat://beakerbrowser.com/ direclty, no dice. The peers number seems to be stable at least. Nothing in the swarm-debugger, literally no data at all - no logs, no errors, nothing.
