### ISSUE TITLE
Kevin Marks’ P2P homepage doesn’t work

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1335]
Operation System: *
Beaker version: 0.8.3

Steps to reproduce:
1. Open http://www.kevinmarks.com/ in Beaker

Expected results:
Should find http://www.kevinmarks.com/.well-known/dat and redirect  to dat://b7930c5e0d55aee8aeb6fa996c8e782e2e9b99b62bf25cab0be7ae195f56a158/

Actual:
Beaker is stuck in old centralized ways.

**Comment by paul90** [comment]
Doesn't the /.well-known/dat file needs to be served by https:// - see https://beakerbrowser.com/docs/guides/use-a-domain-name-with-dat#well-knowndat

**Comment by da2x** [comment]
I can see a website over HTTP. Why would auto-discovering a Dat website over HTTP be any less secure?

**Comment by pfrazee** [comment]
We require https so that we can be confident that the DNS names of Dats are not MITMed ever. Sorry @da2x I know it's a bit of a pain.

**Comment by da2x** [comment]
Maybe this should produce an error in the developer console? So people know why their website won’t load over Dat.

**Comment by pfrazee** [comment]
I've been planning to add a "DNS diagnostic" tool for that reason
