### ISSUE TITLE
Browser UI constantly freezes since last update

### ISSUE THREAD

**Issue by CR0CKER** [beakerbrowser/beaker#1337]
Operation System: macOS
Beaker version: 0.8.3

UI freezes as soon as I open a couple tabs. Menu bar continues to work, but no element in the browser window works anymore until I force quit the app.

**Comment by CR0CKER** [comment]
I should add that the 0.8.3 version also didn't properly relaunch after installation. Menu bar showed up but main browser window didn't, until I killed it and restarted. The update apparently went through because the settings tab showed 0.8.3 after restarting the app.

**Comment by pfrazee** [comment]
Yes, I just solved this yesterday and will be putting together a patch release today. See: https://github.com/beakerbrowser/beaker/issues/1333

Sorry for the issue!
