### ISSUE TITLE
[security] Websites can spoof address field and replace Beaker UI

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1339]
Operation System: macOS 10.14.3
Beaker version: 0.8.4

1. Visit https://www.youtube.com/watch?v=U2B9mwRFE8U
2. Start the video and then click the full screen button

Expected: nothing to happen or to enter full screen mode.

Actual: Beaker browser becomes YouTube browser with YouTube’s UI functionally replacing Beaker.

This has security implications as the address field can be spoofed.

![screenshot](https://user-images.githubusercontent.com/1102886/52826579-c432dd80-30c1-11e9-86ca-2f22639818fb.png)

**Comment by pfrazee** [comment]
Oh bad bug. I wonder how that got introduced. I'll look into it.

Thanks for reporting.

**Comment by pfrazee** [comment]
Okay, looks like what happened is that Electron 4 broke the fullscreen APIs, and so Beaker's chrome styles are getting removed but the rest of the fullscreen behaviors aren't happening.

Reference issue: https://github.com/electron/electron/issues/16648

I'm going to have to disable the fullscreen API for now.

**Comment by pfrazee** [comment]
Okay, 0.8.5 has been released with fullscreen disabled for now.
