### ISSUE TITLE
Files read from dat archive are sometimes cut off on Linux

### ISSUE THREAD

**Issue by cryptowyrm** [beakerbrowser/beaker#1342]
Operation System: Arch Linux & Ubuntu 18.04
Beaker version: 0.8.5

When I try to open my site iftool.hashbase.io in Beaker via https:// it works fine, but when opened via dat:// I have to sometimes refresh the page a few times before it works. When it doesn't work, the page is blank and the following error is shown in the dev tools console:

**Uncaught SyntaxError: Invalid or unexpected token bundle.js:1**

Looking at bundle.js in the dev tools when this happens, it seems that Beaker sometimes doesn't load the whole bundle.js file from disk (the site is fully cached on disk), instead it cuts off after exactly 351602 bytes.

This is reproducible, it happens always exactly at that point, the last 6671 bytes get cut off.

The response headers in the network tab of the dev tools interestingly show the right Content-Length, 358273 bytes, and status 200 OK, even when only 351602 bytes have been loaded.

Here are the last few bytes of bundle.js before it gets cut off:

klucHV0cyBoYXZlIGlzc3Vl

And a few bytes directly following those:

cyIsclt0LmlkXT0iQWN0aW9

So there is nothing weird in the file at that point that would explain this and it works fine with https in Beaker (and in Firefox and Chrome), so this looks like an issue with the Dat integration and not Electron.

It seems to only happen on Linux, I tried it out on a friends' computer with Windows 10 and everything worked fine there, I tried reloading the page a few times and it always displayed correctly. On Ubuntu 18.04 and on a completely fresh install of Arch Linux, bundle.js is cut off until I reload the page a few times, and then it gets cut off again if I reload after the site displayed correctly.

It is however possible that it is not specific to Linux and happens only on slow computers, I'm on a 1.4 Ghz Chromebook, so it would be good if someone else with a faster computer can verify this happens on Linux for them too.

### Steps to reproduce

1) Open dat://iftool.hashbase.io in Beaker
2) Refresh the page a few times, it will sometimes display and sometimes be blank due to bundle.js getting cut off

### Response Headers in dev tools
(identical no matter if the file is loaded correctly or cut off)

Request URL: dat://iftool.hashbase.io/bundle.js
Request Method: GET
Status Code: 200 OK
Referrer Policy: no-referrer-when-downgrade
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 358273
Content-Security-Policy: 
Content-Type: application/javascript; charset=utf8

**Comment by pfrazee** [comment]
Thanks for filing. Electron historically has had some issues on this front (truncating custom protocol responses). If we can't find any obvious causes in the dat code we should try to reproduce in a clean electron app.
