### ISSUE TITLE
Extensible dat.json

### ISSUE THREAD

**Issue by ThisIsMissEm** [beakerbrowser/beaker#1343]
Beaker version: 0.8.5

### Context

Recently I've begun working on a few Dat Application ideas and one of the issues forefront to my mind was: if the process for running the application was to fork the original (or another instance) of the application such that you can have the application self-hosted within its own Dat Archive (i.e., user data and application live in the one Dat Archive), then how do you receive updates to the application?

After exploring how other Dat Applications have been built, I stumbled across the [Forkup module](https://github.com/kodedninja/forkup).

Forkup is really cool because it allows everyone to have separate copies of the application, but still receive updates from the original developer. However, there's something weird in it, which is it places the information about updates in the `package.json` in the Dat Archive.

To me, I think it'd make far more sense for information about updates to be part of the `dat.json` file, as it's quite literally stuff describing the state of the Dat Archive. i.e., to deploy a new version you just push out an updated Dat Archive, you don't do an `npm publish` or create a node package.

### The problem

Currently when using `datArchive.configure` you can pass in an anything as the `settings`, however, it'll silently ignore all but the ["allowed" fields](https://github.com/beakerbrowser/beaker-core/blob/master/lib/const.js#L29-L36). Likewise, your `dat.json` may include a whole heap more fields than just the standard ones, however, `datArchive.getInfo` will only return the standard ones.

### Proposal

I'd like to propose adding a field to `dat.json` called `extensions` which is just an object with arbitrary key/object pairs. This field would allow us to store additional data about our Dat Archives in a reasonable place, given that what we define could later be adopted as a standard field or a common practice. For now, I don't think it'd make sense to allow any key at the top level of the `dat.json` (as that's more tightly managed by Beaker).

It's not inconceivable that Beaker may wish to provide application developers with a standard manner for updating applications in the future. In which case we could pave that standard "extension" to `dat.json` as the "given way".

---

For instance, I'm thinking may `dat.json` look something like this:

```json
{
  "title": "Sample App",
  "description": "A simple application built with the Beaker Browser",
  "type": ["application", "social-network"],
  "links": {
    "license": [{
      "href": "http://creativecommons.org/licenses/by-nc/2.5/",
      "title": "CC BY-NC 2.5"
    }]
  },
  "fallback_page": "/public/index.html",
  "web_root": "/public",
  "content_security_policy": "default-src 'self'",
  "experimental": {
    "apis": ["datPeers", "globalFetch", "library"]
  },
  "extensions": {
    "updates": {
      "source": "dat://peerpals.com",
      "last_updated": "2019-02-20T19:32:45.425Z",
      "version": "0.1.0",
      "files": [ "/public/*" ]
    },
    "donations": {
      "url": "https://opencollective.com/some/project",
      "bitcoin": "14bTyJGTZKwBEomfBAHhTdf2RcaUKnqsXN"
    },
    "contribute": {
      "url": "https://github.com/thisismissem/dat-sample-app"
    }
  }
}
```

(Sure, you could argue that both `contribute` and `donations` may be better in `links`, but they're really just examples; Primarily thinking for things that are more complicated than just links, e.g., `updates`)

**Comment by ThisIsMissEm** [comment]
@kodedninja this issue may interest you, as I mention your module!

**Comment by kodedninja** [comment]
@ThisIsMissEm I implemented forkup to use the version in the `package.json` because it's a standard to keep track of your versions. As most sites include some kind of JavaScript it's also very common that `package.json` already exists.

Also, you don't need to `npm publish`, `forkup` directly opens `package.json` via the `DatArchive` API. 

But of course, we could generally come up with a proper solution to solve this issue (which I think is pretty important), maybe built into Beaker. I made `forkup` because I needed a drop-in solution for my apps.

What I prefer in the `forkup` way of updating is that the developer can specify which files need to be updated for a given update. Of course, this could also be done similarly via Beaker.

**Comment by ThisIsMissEm** [comment]
@kodedninja yeah, but in the context of Dat Applications, `package.json` is more development-time than runtime. Where as `dat.json` is more natural as part of the runtime of a Dat Application.

As for Forkup, I did read the source code :) I've actually been thinking about an alternative means which just looks at `fallback_path` and `web_root` and mirrors those directories, though that lacks mirroring the source code to the application, which makes me want a `scr_root` Or something

**Comment by pfrazee** [comment]
I think this makes a lot of sense! I like the pattern of using an extensions field to test out ideas that could become standard.

For anybody wondering, Beaker controls the dat.json tightly because some fields can have security implications. The `content_security_policy` field is an example of that, and there will probably be more in the future.

One question we need to answer is, when forking a site, should the `extensions` value be copied over as well? Sometimes you don't want that, as in the case of the "donations" link.

**Comment by kodedninja** [comment]
I hope you didn't get me wrong, I also think the `extensions` fields would be a proper solution.

> One question we need to answer is, when forking a site, should the `extensions` value be copied over as well?

Definitely! If you say that it would be possible to notify the owner of a site that there's an update and then be able to get that through the Beaker UI, then my dream would come true! We just need to make sure, that the user is aware of what's going to happen and developer must make sure that they handle versioning (for backward compatibility) correctly. After the update there's no easy way back.

**Comment by ThisIsMissEm** [comment]
> I think this makes a lot of sense! I like the pattern of using an extensions field to test out ideas that could become standard.

Glad to hear that you like the idea!

> One question we need to answer is, when forking a site, should the extensions value be copied over as well?

Yes, absolutely, as extensions could affect how the application works. Perhaps that right thing here is that we say something like "If your application does something specific that could be undesirable to users, then in your documentation or "settings" page in your application, you should give them the option to changes or opt out"

 I'm thinking for the "updater" that it'd just be an npm module that ships with some UI to show the user, and "best practices" around informing the user.

Also, as it's just reading another dat in order to check for updates, and updates can only be installed by the owner, we can control the messaging here.

Obviously if someone wanted to do something nefarious, they absolutely could, and I'd hope that through a process of natural selection only semi-decent apps continue to get shared and used.

I could totally see Beaker implementing something like a prompt or alert upon DatArchive.load and such that notifies the user of access outside of the current dat & that that other dat isn't owned by the user. Maybe even as a permission setting in dat.json "this site wishes to access data on from the following site(s):" or "this site wishes to access data from any other dat:// site"
