### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by CookieKenneth** [beakerbrowser/beaker#1345]
Operating system:
**Windows 10 x64**

This is:

- [ ] a bug
- [x] general feedback

Feedback:
Hello, I was wondering where I could find out the privacy statements exactly. I love the browser and using it but it is a very easy way to grab data and passwords. How do I know when I'm using the browser I'm secure?

**Comment by pfrazee** [comment]
@CookieKenneth Sorry for the delayed response. I'm very behind on my email queue right now!

I understand the concern. We do need a privacy policy. I'll try to get that added soon.

**Comment by da2x** [comment]
This is a duplicate of [beakerbrowser/beakerbrowser.com/issues/92](https://github.com/beakerbrowser/beakerbrowser.com/issues/92).

**Comment by pfrazee** [comment]
Indeed it is. Closing as a duplicate.
