### ISSUE TITLE
Unable to find sqlite3 when run

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1348]
Any folks building from source, feel free to give the new master a try and let me know how this refactor works for you. Hopefully there aren't too many new bugs or regressions.

_Originally posted by @pfrazee in https://github.com/beakerbrowser/beaker/pull/1346#issuecomment-469533632_

Running `npm start` fails with `Error: Cannot find module '/Users/Paul/Projects/dat/beaker/app/node_modules/@beaker/core/node_modules/sqlite3/lib/binding/electron-v4.0-darwin-x64/node_sqlite3.node'`

The directory `beaker/app/node_modules/@beaker/core/node_modules/sqlite3/lib/binding/electron-v4.0-darwin-x64` does not exist!

Looking at `npm install` output, `node_sqlite3.node` is getting installed in a different location `beaker/app/node_modules/@beaker/core/node_modules/sqlite3/lib/binding/node-v64-darwin-x64`

**Comment by paul90** [comment]
Just spotted, the location of the module aside, the name of the file `node-v64-darwin-x64` would suggest that the Electron 3 prebuilt version of sqlite3 is getting installed.

**Comment by pfrazee** [comment]
Did you try running `npm run rebuild` and/or `npm run burnthemall` ?

**Comment by paul90** [comment]
I have tried both, tried `npm run burnthemall` after using rebuild failed.

**Comment by pfrazee** [comment]
You're on macos, right? Which version?

Are there any errors when you run `rebuild` ?

**Comment by paul90** [comment]
Yes, macOS 10.14.3

While I don't see any sqlite3 errors in rebuild, in the install I see..
```
> sqlite3@4.0.6 install /Users/Paul/Projects/dat/beaker/app/node_modules/@beaker/core/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/Users/Paul/Projects/dat/beaker/app/node_modules/@beaker/core/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" is installed via remote
```

In `rebuild` I see sodium-native install fail with an error finding `libtool`, even though the xcode cli tools are install, but no other errors.

**Comment by pfrazee** [comment]
Weird that this is suddenly happening, but try running `brew install libtool autoconf automake`

**Comment by pfrazee** [comment]
(And then rebuild again)

**Comment by paul90** [comment]
Looks to have been a bit more complex than simply doing that brew install...  As I have xcode installed brew install libtool as glibtool, so in itself it didn't solve anything..

However, creating a link so that brew installed libtool highlighted what was probably the real problem, `libtoolize` was missing. *The brew install libtool failed as it was being passed invalid paramters.*

Rebuild now runs, and I am able to start beaker, though I notice `dat-serve Failed to load sodium-native. Performance may be degraded. Error: Cannot find module 'sodium-native'`

**Comment by pfrazee** [comment]
Was there any error during the rebuild of sodium-native?

**Comment by paul90** [comment]
No errors.

Not finding `sodium-native` looks to have been caused by my npm configuration, which contained `global-style = true`, so it was not in the expected place. Removing that setting resolves that issue.

Going to close this issue, as the build now completes and `npm start` starts beaker without any errors.

**Comment by pfrazee** [comment]
Good deal, sorry for the issues!
