### ISSUE TITLE
Issue using <input type="file" multiple>

### ISSUE THREAD

**Issue by PiusNyakoojo** [beakerbrowser/beaker#1350]
Operation System: macOS Mojave - Version 10.14.2 (18C54)
Beaker version: v0.8.4

**Code Reproduction**:
https://codepen.io/anon/pen/ZPKQQm

**Expected Behavior**:
To select multiple files using the input element (with type="file") and one or more of the following attributes: multiple, webkitdirectory, mozdirectory, multiple, or allowdirs.

**Actual Behavior**:
1.) Only 1 file is selected when selecting a directory with multiple sub-files.
2.) The 1 selected file is empty when attempting to read from it using the FileReader API.

The code reproduction link behaves consistently, and as expected, on Chrome, Firefox and Safari. Beaker Browser is where the code doesn't work as expected.

**Thank you** for your help.

**Comment by pfrazee** [comment]
Sorry for the delayed response! Thanks for filing, I'll try to get a fix out soon.

**Comment by figueredo** [comment]
This seems to be an Electron bug. If you run this pen with electron-quick-start the same happens. Also, this problem is reported here: https://github.com/electron/electron/issues/749
