### ISSUE TITLE
Build from souce failed "cannot find module"

### ISSUE THREAD

**Issue by mckkaleb** [beakerbrowser/beaker#1351]
Operation System: Windows 10
Beaker version: latest (0.8.5?)
Electron is failing to find a module named node_sqlite3.node. Any solutions?

![screenshot 2](https://user-images.githubusercontent.com/29008641/54026696-c17d5280-416c-11e9-9172-360723de3dcb.png)
I have run npm run restart

**Comment by pmario** [comment]
You should try: `npm run burnthemall` everything is rebuilt.

**Comment by pmario** [comment]
be sure you have the pre-requisites: https://github.com/beakerbrowser/beaker#building-from-source AND https://www.npmjs.com/package/windows-build-tools

**Comment by mckkaleb** [comment]
I've done both of those things and nothing has changed

**Comment by pfrazee** [comment]
Did you notice any errors during the `npm run rebuild` run?

**Comment by mckkaleb** [comment]
I've gotten all of this:
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kaleb\AppData\Roaming\npm-cache\_logs\2019-03-08T20_42_24_339Z-debug.log
`

**Comment by pfrazee** [comment]
Any indication about why that is failing?

**Comment by mckkaleb** [comment]
`C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(
67,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 bui
ld tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by select
ing the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Kaleb\beaker\app\no
de_modules\sqlite3\build\deps\action_before_build.vcxproj]`

**Comment by pfrazee** [comment]
Have you installed https://www.npmjs.com/package/windows-build-tools ?

**Comment by mckkaleb** [comment]
Yes
________________________________

**Comment by pfrazee** [comment]
I'm not primarily building on Windows, so at this stage I think you'll need to debug this yourself based on the error messages your getting. Sorry!

**Comment by pmario** [comment]
check your environment variables. path settings

**Comment by pmario** [comment]
@mckkaleb ... Which node.js version do you use?
