### ISSUE TITLE
Startup Error: Cannot find module '../dbs/domain-names'

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1352]
Operation System: win 10
Beaker version: branch blue: commit 056aafc99317c9f8dabad55f1918d984da44495a

After doing a `burnthemall` I still get this info: 

![beaker-startup-message](https://user-images.githubusercontent.com/374655/54124314-4d5bdc80-4402-11e9-9885-c48a99702cfc.gif)

**Comment by pfrazee** [comment]
@pmario yeah sorry, just pushed the updated branch. Try now

**Comment by pmario** [comment]
git pull says, I'm up to date?!

**Comment by pmario** [comment]
https://github.com/beakerbrowser/beaker/network says the same?

**Comment by pfrazee** [comment]
Do an `npm install` again. The `beaker-core` module is being pulled from git.

**Comment by pmario** [comment]
That did the job. thx
