### ISSUE TITLE
Routing Pleroma through Dat

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/beaker#1353]
Operation System: Mint 18.1
Beaker version: Latest

Is it currently possible to route Pleroma through Beaker browser? I can't seem to find any information on it online. Or is Beaker primarily for static (non-dynamic) websites?

When I tried it, it just kind of froze.

**Comment by pfrazee** [comment]
Sorry, what's Pleroma?

**Comment by RangerMauve** [comment]
The dat protocol is for static content, beaker should be able to load any HTTP based clients for pleroma, though.

If you're interested in getting ActivityPub working over dat, hit me up on twitter since I've been thinking about that a lot lately.

**Comment by LWFlouisa** [comment]
Thanks, will ask more when I'm not swamped with other things.
