### ISSUE TITLE
Most of the times does not work

### ISSUE THREAD

**Issue by tiotrom** [beakerbrowser/beaker#1354]
Operation System: Manjaro Linux
Beaker version: beaker-browser-bin  0.8.5-1

I am trying to make this work but I only can see it working rarely. So, say I shared these files dat://d3ff739c73952f8c7c8adcde836b1ff8231ca820258ea36ad8d7c0c678f731aa - one time I was able to open super quickly from another computer and seed them. But then any other try failed with "It doesn't seem like anybody is sharing this site right now." - even though I share them from my own computer.

How to debug this? I really want it to work :D - we have a project since 2011 and we have many videos, books, or audio files that we want to move from dropbox to a decentralized location and Beaker so far seems, in theory, an excellent solution.

**Comment by pfrazee** [comment]
@tiotrom yeah I'm not happy with our connectivity success rate right now. I'm going to be implementing some analytics soon so we can try to diagnose what's going on.

**Comment by CR0CKER** [comment]
Same here, on macOS. Can't get any peers most of the times. Used to work fairly well a few releases ago, but since the recent couple updates it's become completely unusable, unfortunately.

**Comment by tiotrom** [comment]
The weird thing is I am from Spain. I try connecting to a friend in Canada and never works. Try Romania, doesn't work. Try Germany and works wonderfully. Then because I connect to Germany the other friends from Romania and Canada can connect too. So I push a change to my files and they go through Germany to Canada and Romania.....I don't get it. When it works it is simply wonderful. But when it doesn't (most of the time) I have no idea why.

**Comment by Flingafu** [comment]
I am suffering from the connectivity issues as well on both manjaro and windows 10. Most links are never discoverable!

**Comment by tiotrom** [comment]
How is a VPN influencing the connection? I am using a VPN with port forwarding. I live in Spain and the VPN uses a canadian IP (connection) with port forwarding. I share a file from Beaker to a friend in Canada and he cannot connect at all. I share it with a friend on the same home network, and it connects instantly. These without exception. So I don't understand how this work. Me using a Canadian VPN connection shouldn't connect easier to someone from Canada?

**Comment by todrobbins** [comment]
@tiotrom for what it's worth, I was able to pull up the index of your site:

<img width="460" alt="Screen Shot 2019-04-01 at 10 42 30 PM" src="https://user-images.githubusercontent.com/158590/55376861-8baf5d80-54cf-11e9-8fe7-1a535bfdbd99.png">

Trying to seed right now but not seeing much activity yet:

<img width="841" alt="Screen Shot 2019-04-01 at 10 44 32 PM" src="https://user-images.githubusercontent.com/158590/55376894-be595600-54cf-11e9-8560-58fdac50d554.png">

**Comment by tiotrom** [comment]
We updated the link to this dat://7cc1c2db97f0320ea6d815a341ab0bb4a3c2fe17fc636d3a6f359266bd791b95 and we'll keep it to this. But where are you from? And can you try again please? Let's see if you can connect

**Comment by todrobbins** [comment]
This reminds me, @pfrazee: is there a way to export the logs from Swarm Debugger besides copy/paste of the tables? CSV export would be a great feature to add to that tool. 👍🏻

**Comment by todrobbins** [comment]
@tiotrom I'm in Utah, USA. I'm trying the new link now, but get the following from Beaker:

<img width="738" alt="Screen Shot 2019-04-01 at 10 48 14 PM" src="https://user-images.githubusercontent.com/158590/55376993-47708d00-54d0-11e9-90a0-8f62186625e1.png">

**Comment by tiotrom** [comment]
Thanks for trying. I am currently seeding it and I even have a 600Mb connection but unfortunately I cannot share with many people because it finds no peers.
![2019-04-02_06-49](https://user-images.githubusercontent.com/34804533/55377051-8aa01f80-5513-11e9-9862-f83f9ee2fff7.png)

**Comment by raphaelbastide** [comment]
I agree with @tiotrom, Beaker doesn’t work anymore, at least most of the time: 
I am at home with a normal network architecture, no firewall, and several computers running the last version of Beaker. I can’t acces my project 50% of the time with either other computer but also the computer that seed the project. I don’t understand because the dat archive is on my computer (+ on a pi running homebase) and I can’t access it. I think this issue is new but I am not 100% sure.

As you can see on the following screenshot, the original file is hosted by this computer and 1 peer is found, but the archive remains unavailable.

![Screenshot_2019-07-25_18-16-33](https://user-images.githubusercontent.com/193122/61891392-da16bb00-af09-11e9-9025-f79302c7348d.png)

I found that sometimes, restarting Beaker can load a page that was not found just before.

**Comment by pfrazee** [comment]
Yeah this is a frustrating issue. I have some suspicions about what's causing it but I haven't nailed it down yet.
