### ISSUE TITLE
Can’t click on address field drop-down suggestions

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1360]
Operation System: Linux, Fedora 29
Beaker version: 0.8.6 (flatpak runtime via [flathub](https://flathub.org/apps/details/com.beakerbrowser.Beaker))

1. Visit https://example.com so it’s in your history. Close the tab.
2. Open a new tab and focus the address field
3. Type example.com
4. Click on https://example.com/ in the address field drop-down selection list

Expected: should navigate to the pressed item.

Actual: drop-down is dismissed when you click on it and the address field resets to previous value (dismissing what you’ve just typed).

Work-around: use keyboard arrow keys and press enter instead of using the mouse.

**Comment by pfrazee** [comment]
Thanks for filing. I'll check into that. It doesn't seem to happen on MacOS.

**Comment by da2x** [comment]
Same issue on Windows 10.

**Comment by pfrazee** [comment]
Okay, I was able to reproduce on Windows and pushed a fix. LMK if that doesn't solve it for you.
