### ISSUE TITLE
Beaker won't re-open after closing

### ISSUE THREAD

**Issue by jeremyredhead** [beakerbrowser/beaker#1362]
Operation System: Windows 7 (64-bit)
Beaker version: 0.8.6

Steps to reproduce:
1. [log out and log back in (to windows)]
2. Start Beaker (from taskbar, if relevant?)
3. Wait for new tab page to load, visit a few sites maybe
4. Close Beaker
5. Wait a little while, trying opening it again, wait a little longer... forever, in fact
6. GOTO 1 (logout necessary to start Beaker again)

A very odd (and frustrating) bug.

**Comment by jeremyredhead** [comment]
Correction/Update: the problem is that it isn't exiting properly when closed; several Beaker Browser processes are lingering even after "closed".
Clicking the "Big X" and good ol' <kbd>Alt</kbd>+<kbd>F4</kbd> both exhibit this problem.
As soon as all the stray Beaker processes are closed, it becomes possible to open Beaker normally again.

Firefox actually suffers from a similar problem, but it opens a native dialog that says something like: 
"The old firefox process is still running and must be closed before opening another",
with a [Close Process] and [Cancel] button.
But I'm guessing doing something like that in electron would be difficult or impossible :/

**Comment by pfrazee** [comment]
Hi @jeremyredhead, I just addressed this problem in https://github.com/beakerbrowser/beaker/issues/1359. Hopefully that fix will work. Keep an eye out for the next patch release.

**Comment by pfrazee** [comment]
Thanks for filing. Closing as a duplicate.
