### ISSUE TITLE
Distributed DNS

### ISSUE THREAD

**Issue by Hedzer** [beakerbrowser/beaker#1363]
A completely distributed web would need a distributed DNS. Maybe using blockchains could work? something like eos://domain.com or eth://domain.com and those would lead a contract containing the records. Those records could point to an IPNS or DAT link for loading the actual page.

I created an issue in the EOS github page suggesting integration as well:
[EOS DNS](https://github.com/EOSIO/eos/issues/6994)

**Comment by pfrazee** [comment]
We're going to have a distributed search engine but I'm not currently sold on any blockchain tech.

**Comment by Hedzer** [comment]
I'm not sold on it either for most use cases, but a DNS is actually a decent use case for it.

**Comment by pfrazee** [comment]
Yeah I agree that DNS is one of the better use-cases.

**Comment by Hedzer** [comment]
Even if it's not on a blockchain, a distributed DNS makes sense. I only mention blockchains because they deal with bad actors pretty well.

 If you feel this is outside the scope of this project, I can go ahead and close the issue, I definitely don't want to be a thorn in the side of the team over this.

**Comment by pfrazee** [comment]
@Hedzer Appreciate that! I just don't have a good answer for making a distributed DNS replacement. You need some way to enforce a single consensus on the registry, and without a decentralized consensus algorithm like PoW, I don't know of any good options. This is why I'm instead working on distributed search, which does not require the same consensus.

**Comment by bitcoinbrisbane** [comment]
> Even if it's not on a blockchain, a distributed DNS makes sense. I only mention blockchains because they deal with bad actors pretty well.

Ive started a project for exactly this (from forking breaker).  Its an ETH browser. https://github.com/bitcoinbrisbane/fireWolf
