### ISSUE TITLE
Issue with markdown rendering

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1368]
Markdown rendering seems to be failing.

Example: http://diglifebeaker101.hashbase.io/Assignment1.md

**Comment by paul90** [comment]
Also markdown pages display a blank page in Beaker. There appears to be an injected stylesheet that is setting `display: node` on the `pre` that contains the rendered Markdown.

![Screenshot 2019-03-31 at 10 29 24](https://user-images.githubusercontent.com/1552489/55287387-1abd5800-53a0-11e9-9e85-e11a837aa966.png)

**Comment by pfrazee** [comment]
This appears to be caused by an issue in the bundling of Beaker. Markdown rendering is done by injecting javascript into the page, and that .js is not being loaded successfully.

Looking into a solution.

**Comment by pfrazee** [comment]
Okay, fixed. Will try to put out another patch release tomorrow.

**Comment by paul90** [comment]
Thanks
