### ISSUE TITLE
Options - Toggle GitHub flavored markdown

### ISSUE THREAD

**Issue by Pawper** [beakerbrowser/beaker#1370]
I'd love if markdown support had an option for GitHub flavored markdown, so emojis and other great features were supported. 😃 When I think of things folks would like for simple websites that are super easy to deploy with ```dat://```, emoji are at the top of the list.

I am aware there is <kbd>Win</kbd>+<kbd>.</kbd> to bring up the Windows emoji keyboard, but I think the quick tags are nice. e.g., ```:smiley:``` = :smiley:

There's also the checklist stuff.
```
- [ ] Unchecked
- [x] Checked
```
- [ ] Unchecked
- [x] Checked

I am not sure of Beaker's support for tables, ```<kbd>``` and code in markdown with the nifty syntax highlighting and stuff

**Comment by pfrazee** [comment]
I actually am 👍 with this kind of feature. It's a defacto standard, why not do it!

**Comment by pmario** [comment]
hmm, defacto standard, is imo depending on the users context. ... It's a one of the many [variants](https://tools.ietf.org/html/rfc7764) that are defined in [the spec](https://tools.ietf.org/html/rfc7763).
