### ISSUE TITLE
Explore page is not found

### ISSUE THREAD

**Issue by ShalokShalom** [beakerbrowser/beaker#1376]
Operation System: KaOS
Beaker version: 0.8.7

![Screenshot_20190404_125744](https://user-images.githubusercontent.com/6344099/55550785-6db54900-56d9-11e9-988f-d56aaadb6479.png)

**Comment by pfrazee** [comment]
This is caused by a bug that was introduced to the DNS resolver and has since been fixed. See https://github.com/datprotocol/dat-dns/pull/12. Next release of beaker will resolve this.

**Comment by pfrazee** [comment]
Thanks for filing

**Comment by ShalokShalom** [comment]
I have to ask: How could this happen?

Is there no testing about such fundamental things?

**Comment by pfrazee** [comment]
Actually, there is, but there was a bug in the test. Cache wasn't disabled.
