### ISSUE TITLE
Support for F5 and F6

### ISSUE THREAD

**Issue by ShalokShalom** [beakerbrowser/beaker#1378]
Operation System: KaOS
Beaker version: 0.8.7

Currently, F5 will not reload a page, F6 will not jump into the adressbar and mark it. 

Is the support for F keys implemented at all?

**Comment by ShalokShalom** [comment]
Can I simply adjust this right now in some settings file or is this not possible at all currently?

**Comment by pfrazee** [comment]
No the key bindings are hard-coded.

**Comment by ShalokShalom** [comment]
Can I change them? I mean for me personally. Where are they hard coded? F5 for refresh and F6 for jump into the adress bar and Mark all its content is pretty much the standard since couple of decades.

**Comment by pfrazee** [comment]
Okay got the keybindings added. Will be in the next release.

**Comment by ShalokShalom** [comment]
Superb ^.^
