### ISSUE TITLE
Split cached/seeded Dats from User's own Dats

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1379]
Seeded and cached/recent Dats should live in `~/.cache/Beaker Browser/`, / `~/Library/Caches/com.beakerbrowser.Beaker/`, and `%TEMP%\Beaker Browser\`. See [platform-folders](https://www.npmjs.com/package/platform-folders).

Dats created by the user should stay where they are today in local app data.

The separation simplifies backup as there is only one directory to backup to backup your own personal unique Dats. It also automatically excludes ephemeral Dats with many existing backup software including GNOME Backup, Apple Time Machine, and Windows Backup/File History, Arq, Backblaze, SpiderOak ONE, and others.

This should resolve issue #815 by integrating well with the existing backup tools people are already using.

**Comment by krisradio** [comment]
This seems like a good improvement to me.

**Comment by krisradio** [comment]
This seems like a good improvement to me.
