### ISSUE TITLE
Better file-level controls in beaker:archive

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#138]
Dat file viewer, needs to be able to:
- [ ] Rename files
- [ ] Delete files
- [ ] Move files
- [ ] Create folders
- [ ] Rename folders
- [ ] Delete folders

**Comment by joehand** [comment]
If an archive was created by an app, that'd be nice to see in the main archive list.

(may belong in another issue)

**Comment by pfrazee** [comment]
Yeah, created a new issue: https://github.com/beakerbrowser/beaker/issues/176
