### ISSUE TITLE
Pinned tabs overflow onto other tabs

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1381]
Operation System: Fedora 30
Beaker version: 0.8.8

1. Pin one tab
2. Open a dozen tabs or so

![pinned_tab](https://user-images.githubusercontent.com/1102886/55669812-274c1f80-587c-11e9-8113-0b1256a193bb.png)

Note that the pinned tab’s favicon moves even further to the right than its normal position.

Related to #1272.

**Comment by pfrazee** [comment]
Thanks for filing, will check into it

**Comment by pfrazee** [comment]
Fixed on master
