### ISSUE TITLE
`window.close()` freezes tab instead of closing

### ISSUE THREAD

**Issue by brechtcs** [beakerbrowser/beaker#1382]
Operation System: Windows 10
Beaker version: 0.8.8

I'm observing an issue with a couple of apps calling `window.close()`. Instead of closing the tab in question, it remains visible. It's still possible to manually close the affected tab, but you can no longer interact with its contents. The Beaker UI and all other tabs are unaffected.

I'm thinking this could be a side-effect of the fix for the freezing issue in previous versions, as that seemed to be [connected to `window.open`](https://github.com/beakerbrowser/beaker/issues/1333#issuecomment-477995371).

**Comment by pfrazee** [comment]
Thanks for filing. This may just be an unhandled event. I'll check into it.

**Comment by brechtcs** [comment]
@da2x I'm seeing the behaviour both in normal windows and in windows opened with JS. Either way I don't think it's expected behaviour though, because you'd expect normal windows to stay responsive after a `window.close()` call, rather than freezing as it does now.

I have some a project locally that reproduces it. It needs some cleaning up before pushing to Github though, will post again when that's done.

**Comment by pfrazee** [comment]
@brechtcs Yeah let me know when you've got that. I need to understand the flows that use `window.open` to get the behavior right.

@da2x Thanks for pointing out that specced behavior.

**Comment by brechtcs** [comment]
I've pushed the project where I'm experiencing this bug. 

The use case is a basic text editor to open and edit files from [dterm](https://github.com/dterm/dterm). As such, the `window.open` call is located in [this code](https://github.com/dterm/dcode/blob/5c2b4028760dc1ebe98288cdadee1f6bb0a4c90e/commands/vim.js#L6), meant to be run as a command in dterm. The `window.close` call happens from [the editor code](https://github.com/dterm/dcode/blob/5c2b4028760dc1ebe98288cdadee1f6bb0a4c90e/index.js#L57), and should close the tab to return to the terminal. 

Since I haven't documented its usage yet, here's how to reproduce it:

- Go to `dat://dterm.hashbase.io`
- Run `ls` and choose a dat from the list to navigate into
- Run `term install dat://dcode.hashbase.io/commands/vim.js`
- Run `vim <any-file-in-dat>`
- In the newly opened editor tab, type `<ESC>:q!`
- The editor tab should now still be visible, but frozen

**Comment by da2x** [comment]
The tab doesn't freeze but the webapp stops handling events and appears dead. It's fully functional still, however. The window.close() call is ignored and the webapp doesn't know what to do after that.

@pfrazee the newly opened tab is probably missing a scriptclosable attribute (or whatever the Eletron equivalent is). Here is a small test case:
dat://e71784fbaaac13e7a1b20ba39d8149b2ba893171204672575eab8b4fd0758ec3/testcase.html

**Comment by pfrazee** [comment]
Okay, just pushed a fix. Thanks for the excellent help on this. Let me know if there are any remaining issues.
