### ISSUE TITLE
Status bar stays open and detached from window

### ISSUE THREAD

**Issue by kaotisk-hund** [beakerbrowser/beaker#1385]
Operating system:
ArchLinux

This is:

- [X] a bug
- [ ] general feedback

Beaker's status bar, that one that when you hover a link it shows there the actual link you are going to follow, stays on after hovering and (!!!!) overlays other windows opened, for example I am in firefox writing about this issue and I see the Beaker's status bar with the latest hovered link in it.

**Comment by pfrazee** [comment]
Thanks for filing. That's a real pain! I'll see if I can reproduce in Ubuntu.

**Comment by da2x** [comment]
I can reproduce on Fedora with GNOME on X11 and Wayland. However, this problem also happens with other Electron apps so I don't think it's Beaker specific.

I can reproduce it by hovering over a link and then switching to another GNOME workspace with a keyboard shortcut. This suggest the tooltip window isn't dismissed when the main window looses focus without a mouseout. A window will have trouble tracking its own window focus under Wayland, and I'm not even sure how you'd go about working around that.

**Comment by dym-sh** [comment]
:white_check_mark: reproducible in Ubuntu 18.04 (i3)

the real problem is: it stays visible even if you move the mouse away from the link

**Comment by pfrazee** [comment]
Using Ubuntu 18.04, I'm able to reproduce the statusbar appearing over *other* windows during hover, but I'm not experiencing the issue where the statusbar stays visible after hovering.

I'm using Gnome; I wonder if this might be specific to Wayland.

**Comment by pfrazee** [comment]
Wayland doesn't seem to make a difference. I just pushed an update to master which hides the statusbar when the window is blurred. Let's see if that solves this.

**Comment by dym-sh** [comment]
tried the latest master, same thing (in i3):
![beaker-addressbar-in-i3--main](https://user-images.githubusercontent.com/39516339/56962065-e6cb8300-6b55-11e9-8515-75410ca404de.png)
![beaker-addressbar-in-i3--overrides](https://user-images.githubusercontent.com/39516339/56962068-e92ddd00-6b55-11e9-99e9-24369c233320.png)

is address bar set to be system-wide front-top window instead of regular float? never seen such effect in any other app...

**Comment by the-cloud** [comment]
I'm on Ubuntu 18.04, with i3wm. 
Switching apps and workspaces makes no difference, the white bar is always there in bottom left corner.
