### ISSUE TITLE
Contents doesn't fit in contribution pop-out window

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1386]
Operation System: Windows 10.1809
Beaker version: 0.8.8

1. Create or visit any Dat archive with a donation URL in its dat.json manifest
2. Click on the Heart icon in the address field to

The window doesn't fit the contents.

dat://e71784fbaaac13e7a1b20ba39d8149b2ba893171204672575eab8b4fd0758ec3/1386/image.png

**Comment by pfrazee** [comment]
I fixed this when I merged your PR, thanks!
