### ISSUE TITLE
Document viewport slightly larger than maximized window

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1388]
Operation System: Windows 10.1809
Beaker version: 0.8.8

The viewport is slightly larger than a maximized window. Only affect windows with no scrollbars (test case #1).

Same issue also causes the hover-over-link-address-tooltipto be displayed outside the visible window (test case #2).

Test case and screenshot:
dat://e71784fbaaac13e7a1b20ba39d8149b2ba893171204672575eab8b4fd0758ec3/1388/

**Comment by pfrazee** [comment]
Thanks for filing, checking into this. Probably the same issue as #1392.

**Comment by pfrazee** [comment]
Okay thanks for reporting. Looks like a quirk of windows that I was able to solve by using a different bounds-fetching function. Fixed in master!
