### ISSUE TITLE
Make Settings icons the corresponding favicons for Settings pages

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#1389]
![Screen Shot 2019-04-12 at 11 12 00 AM](https://user-images.githubusercontent.com/158590/56054398-ee94c600-5d13-11e9-8989-a8bccc79df4b.png)

I'd like to propose making the various Settings pages icons also appear as their favicons to provide clarity, especially when tabs are pinned.

![Screen Shot 2019-04-12 at 11 19 48 AM](https://user-images.githubusercontent.com/158590/56054770-e8531980-5d14-11e9-8497-cd3d39fd24ee.png)

Thoughts? I looked through the code a bit and noticed the icons are drawing from FontAwesome (`beaker://assets/font-awesome.css`), and that there is existing SVG with those [here](https://github.com/beakerbrowser/beaker/tree/master/app/assets/fonts).

**Comment by pfrazee** [comment]
Thanks for bringing this up! I've addressed this in the `blue` branch. Since this isn't critical, is it okay with you to wait for `blue` to land to solve it?

**Comment by todrobbins** [comment]
Totally cool! Just raising the usability issue, and glad to know you're already on top of it 👍🏻

**Comment by pfrazee** [comment]
Thanks!
