### ISSUE TITLE
Library performance (slow favicon loading?)

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1390]
Operation System: Linux
Beaker version: 0.8.8-flatpak

1. Seed tens of archives with favicons
2. Restart Beaker
3. Go to Library: Currently seeding

Most archives are shown with no favicon, some with the wrong favicon temporarily, and a few with the correct icon. My hard drives spins up like crazy while Beaker becomes really sluggish and unresponsive. I can see the right favicons slowly populate in the list of seeded archives. Seeding 30 archives makes Beaker almost lock up for two minutes (is the favicon loading happening on the main UI thread?)

Is the favicon loading really the only thing Beaker is loading up all of these Dats for when opening the archive? Or is there more things going on when opening this page? Should they perhaps be cached in a database or some more efficient format?

**Comment by pfrazee** [comment]
> Is the favicon loading really the only thing Beaker is loading up all of these Dats for when opening the archive? Or is there more things going on when opening this page? Should they perhaps be cached in a database or some more efficient format?

Yeah, that's what's going on. I'm working on a caching solution now.
