### ISSUE TITLE
Markdown rendering issue

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beaker#1391]
Operation System: macOS Mojave
Beaker version: v0.8.8

### in beaker

dat://taravancil.com/explore-the-p2p-web.md

<img width="994" alt="Screen Shot 2019-04-15 at 10 12 15 PM" src="https://user-images.githubusercontent.com/169280/56183563-dfd83880-5fcb-11e9-8f23-d01883696a83.png">

### in chrome

https://taravancil.com/explore-the-p2p-web.md

![image](https://user-images.githubusercontent.com/169280/56183557-da7aee00-5fcb-11e9-9e08-1ae20ff8a109.png)

**Comment by pfrazee** [comment]
Hey, sorry it took me so long to respond on this.

I noticed this and fixed it in the blue branch, but haven't had time to backport to current.

**Comment by pfrazee** [comment]
Fixed in master, thanks
