### ISSUE TITLE
Edges of sites off screen

### ISSUE THREAD

**Issue by ChildishGiant** [beakerbrowser/beaker#1392]
Operating system: Windows 10

This is:
- [x] a bug
- [ ] general feedback

The edges of a website are off the edge of the screen.
Here's the same site using Brave and Beaker
[Beaker](https://gfycat.com/FairFlickeringFrog)
![](https://thumbs.gfycat.com/FairFlickeringFrog-size_restricted.gif)
[Brave](https://gfycat.com/IllfatedBlondAcouchi)
![](https://thumbs.gfycat.com/IllfatedBlondAcouchi-size_restricted.gif)
[test-site.zip](https://github.com/beakerbrowser/beaker/files/3099018/test-site.zip)

**Comment by brechtcs** [comment]
I've noticed this too, on the 0.8.8 release (in Windows 10 as well).

**Comment by pfrazee** [comment]
Interesting, thanks. I'll check into it.

**Comment by pfrazee** [comment]
Confirmed to occur on Windows (not macOS) when fullscreen. Investigating causes...

**Comment by pfrazee** [comment]
Okay thanks for reporting. Looks like a quirk of windows that I was able to solve by using a different bounds-fetching function. Fixed in master!
