### ISSUE TITLE
Where are the keys on Linux?

### ISSUE THREAD

**Issue by zeitrechnen** [beakerbrowser/beaker#1393]
Operation System: Ubuntu 18.04
Beaker version: Version: 0.8.8 Electron: 4.1.3 - Chromium: 69.0.3497.128 - Node: 10.11.0

Hi, I published a website with Beaker. Now I want to backup the archive including the keys. Where can I find the archive and the keys? I searched inside the beaker path /home/christian/.var/app/com.beakerbrowser.Beaker/config/Beaker Browser but couldn't find them.

Thanks!

**Comment by pfrazee** [comment]
Hi @zeitrechnen! I'll refer you to this other issue: https://github.com/beakerbrowser/beaker/issues/815
