### ISSUE TITLE
Can't Type in the URL Bar

### ISSUE THREAD

**Issue by OnlyOnTuesday** [beakerbrowser/beaker#1394]
Operating system:
Fedora Linux 28 (Workstation Edition), x86_64

Window Manager:
Xmonad 0.13

This is:

- [x] a bug
- [ ] general feedback

When I start Beaker with `npm start` I can use the browser just fine, except for the top url-search bar.  I can click around and even use the web-search bar (the one that says `Search the Web, your Library, bookmarks, and more` by default).  

The problem with the url search bar is that it rewrites the current url whenever I'm trying to type in it.  If I hold down a key I can see the letter appearing there (i.e. the pixels can't change fast enough, so the letter flickers there), but it always disappears right after.

Here's my terminal output:
```javascript
[User1@Shadow:0 beaker-0.8.8]$ npm start

> beakerbrowser@ start /home/User1/beaker/beaker-0.8.8
> gulp start

[16:15:50] Using gulpfile ~/beaker/beaker-0.8.8/gulpfile.js
[16:15:50] Starting 'start'...
[16:15:50] Starting '<anonymous>'...
Spawning electron /home/User1/beaker/beaker-0.8.8/node_modules/electron/dist/electron
Starting external process dat-daemon
dat-daemon ready
Logfile: /home/User1/.config/Beaker Browser/debug.log
Detected Linux. Using default en_US spell check dictionary.
configureFolderToArchiveWatcher() false false
Error: timeout
    at Timeout._onTimeout (/home/User1/beaker/beaker-0.8.8/app/node_modules/nat-upnp/lib/nat-upnp/client.js:187:14)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```
This is while Beaker is still running, so there's no shutdown output or anything.

Also, I built from source. (Edit: tried the AppImage; I get the same result.)

I hope this helps, if you need more information just ask :)

**Comment by pfrazee** [comment]
Sorry for the issue! Might be distro/WM specific. I'll need to find some time to look into it.

**Comment by afterconnery** [comment]
Also present when I downloaded 0.8.7.

**Comment by pfrazee** [comment]
@afterconnery Any custom window manager?

**Comment by afterconnery** [comment]
No custom window manager. Pretty plain vanilla setup.

**Comment by OnlyOnTuesday** [comment]
@pfrazee This took me awhile to come back to, but for me it seems to be a problem with Xmonad.  I tried beaker on Xfce and first Xfce told me beaker had crashed.  It gave me the option of restarting or restoring the last session, so I chose to restart and it worked perfectly.  

I went back to Xmonad and tried again and it gave me no warning about crashing, started, and still refused to let me type in the url bar. I don't know why it wouldn't work with your's though, @afterconnery's, granted I'm obviously not an expert.

**Comment by Simon-Laux** [comment]
I have this issue too with the appimage version 0.8.8

**Comment by tpaixao** [comment]
I have the same issue on both Ubuntu MATE and Linux Mint MATE. if I copy the url I want to navigate to and "paste & go" the browser behaves normally, though. 

Just adding some info in the hopes it helps track the bug down...

**Comment by pfrazee** [comment]
@tpaixao Thanks. I'll dedicate some time to this next week when I have my linux box available again.

**Comment by ThornedRose** [comment]
I also have this issue on Arch Linux 5.1.4-arch1-1-ARCH (Deepin 15.10.1 DE)

**Comment by pfrazee** [comment]
I've found a solution to this which will be included in the upcoming 0.9 release.

The location bar dropdown is currently a subwindow. I found a way to implement it within the existing browser window, which should solve this issue.

**Comment by OnlyOnTuesday** [comment]
@pfrazee Thanks for helping so much, I'm excited to use it.

**Comment by pfrazee** [comment]
So glad I can fix this for yall!

**Comment by JGAntunes** [comment]
Hello @pfrazee :wave: sorry bother you, but was just wondering if this fix has already landed in master? I'm currently running Beaker from latest master, on elemantaryOS (Ubuntu based essentially) and I'm facing this particular problem. Was trying to figure out from the PR's if there's some particular branch I should be looking into but couldn't find anything.

Thanks in advance for putting your time into this :+1:

**Comment by pfrazee** [comment]
Hey @JGAntunes, no need to apologize at all! I'm really sorry to say it's not. The fix was a pretty extensive rewrite that's in the upcoming 0.9 branch. I'm going to try to start the prerelease beta next month, so hopefully you'll be able to pull down the fix then 😑 Sorry it couldnt be sooner!

**Comment by JGAntunes** [comment]
No worries @pfrazee :+1: I'll keep on the look out for the new release. Once again, thanks for all your work :raised_hands:

**Comment by nemanjan00** [comment]
This problem still persists for sway wm.
