### ISSUE TITLE
Can't display image.svgz files

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1399]
Operation System: any
Beaker version: 0.8.8

Beaker can display SVGZ files loaded from file:// and from properly configured web servers (or you know, the defaults on Apache HTTPD) but not over dat://.

SVGZ is just SVG in a gzip-style deflate container frame. It's a formal standard. Web servers special-case the extension and send a `Content-Encoding: gzip` header for `\.svgz$` to trigger the client to decompress it as it would any other resouce. Browsers (including Beaker) special-case decompression handling when loading `file:///.*.svgz$`. Beaker needs to adopt either methods for dat://.

Testcase: dat://e71784fbaaac13e7a1b20ba39d8149b2ba893171204672575eab8b4fd0758ec3/1399/testcase.html

**Comment by todrobbins** [comment]
@da2x I get the following error when trying to view the `.svgz` file via a dat-gateway in Chrome (73.0.3683.103):

![Screen Shot 2019-05-06 at 8 37 21 AM](https://user-images.githubusercontent.com/158590/57232654-486a7200-6fda-11e9-92f6-50768e95f58f.png)

Maybe it's an encoding error after all?

**Comment by da2x** [comment]
@todrobbins of course it’s an encoding problem. That is what I said above. Browsers and [some] servers special-case this extension and add a `Content-Encoding: gzip` response header so that the browser will decompress it using their normal decompression logic.

Save the image locally and then open it in your browser and it will render just fine. I already opened a bug for the dat-webext. Could you open one for the gateway?

**Comment by todrobbins** [comment]
No worries, I'm not especially versed in `.svgz`. 👍🏻
