### ISSUE TITLE
dat:// sites can't be reached 

### ISSUE THREAD

**Issue by Fxztam** [beakerbrowser/beaker#1400]
Operation System: Win 10
Beaker version: 09.05.2019  built from github
(don't know to find the version)

**_dat://beakerbrowser.com/docs/  .. => 'This site can’t be reached' ?_**

**_Unhandled Rejection at: Promise Promise {_**
  _<rejected> { Error [NotFoundError]: File not found
      at loadArchiveInner (C:\Works\Work-Electron\beaker-master\beaker-master\app\node_modules\@beaker\core\dat\library.js:300:34) name: 'NotFoundError', notFound: true } } reason: { Error [NotFoundError]: File not found_

**From Settings:**
![image](https://user-images.githubusercontent.com/5808032/57464807-b1254900-727d-11e9-8bbf-4e2aa8363897.png)
![image](https://user-images.githubusercontent.com/5808032/57464961-f34e8a80-727d-11e9-8a6f-d2a5a57db8d1.png)

**Comment by pfrazee** [comment]
Sorry for the slow response; busy couple of weeks.

Thanks for filing. That does seem like it could be a data corruption issue, since there's a file-not-found error emitting on load. Have you tried clearing your dat cache, restarting beaker, and visiting the site again?

**Comment by evdubs** [comment]
I am currently having this problem in beaker version 0.8.8. I can view the following dats on datbase:

https://datbase.org/view?query=dat://6a797780a33db5b65fe08e5ba5a8dcf0277ba9d508d064efda08458db1e1a3da
https://datbase.org/view?query=dat://8eed8dc41ab7ff1ac84ce4c4cf364bf04218b719b601c802ca6bcad46421b748

I cannot, however, view these dats in beaker. Perhaps it is worth noting that these dats just host CSVs in a folder and do not attempt to host any HTML/JS/CSS documents.

**Comment by pfrazee** [comment]
There has been some erratic dat failures that I haven't been able to diagnose. We're just about to launch a major dat-stack upgrade that rewrites the connection layer and upgrades the data structures. I've been waiting for that to land to see if it improves our connectivity issues.

**Comment by evdubs** [comment]
Do you anticipate that being available in the next couple weeks?

**Comment by pfrazee** [comment]
Realistically it’ll be 6-8 weeks

**Comment by evdubs** [comment]
@pfrazee do you happen to have an update for this?

**Comment by pfrazee** [comment]
I guess 6-8 weeks was optimistic. We're still working hard and making progress, but I'm not sure how much longer.

**Comment by evdubs** [comment]
Do you happen to have an update? I am finding it harder to keep up with what's happening in the dat ecosystem.

**Comment by pfrazee** [comment]
I post pretty regular updates (usually via retweets) on twitter.com/beakerbrowser
