### ISSUE TITLE
Client-initiated single-request switching origin protocol from Dat to HTTPS

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1402]
To be clear: this is about forcing a single request to go over HTTPS to the same origin that have used Dat DNS to map itself from HTTPS to Dat.

I’ve found a few situations where it would be useful to tag a link in a way that would force it to load over HTTPS instead of Dat. E.g. the `dat.json{fallback_page}` could benefit from being able to link to the web as there may be redirect or new information (301, 302, 403, 404, 410, etc.) about the fallback address on the web. It may also be useful to be able to send POST requests to an Dat origin over HTTPS to the “same” origin.

Here are some suggestions for discussion:

Suggestion 1: a reserved version name `https-only` (like `+preview`) that always routes the request over HTTPS:

    <a href="dat://example.com+https-only/this-request-goes-over-https">HTTPS link</a>

Suggestion 2: a new `https-only` URI scheme that always routes to HTTPS:

    <a href="https-only://example.com/this-request-goes-over-https">HTTPS link</a>

Design suggestion 3: using the `method` attribute (non HTML standard compliant use on the a element but reusing existing standard mechanism; limited to only be used on a, area, form, and portal elements):

    <a href="dat://example.com/this-request-goes-over-https" method="get">HTTPS link</a>

Suggestion 4: `https-only-path` array and `fallback_to_https` boolean in dat.json. Least flexible but serves most usecases I can think of:

    dat.json: {
        "fallback_to_https": true,
        "fallback_page": "/returned-if-above-https-request-returns-404-when-set-or-otherwise-follow-redirects-or-display-other-errors-from-https",
        "https-only-path": ['/this-request-goes-over-https', '/contactform', '/ping']
    }

#### Motivation

I’ve had a few different URI designs over the years and have thousands of inbound links pointing to locations that redirect to their new locations. My HTTPS server returns almost half a million redirects every month. Anyone using Beaker may follow an old link and will end up on the `fallback_page` which currently tells them to visit the same URL over HTTPS using a different web browser. Either automatically checking in with the HTTPS server, or being able to point people to HTTPS would provide a better user experience than asking them to copy a HTTPS address into another web browser to check if updated information about the address is available over HTTPS.

**Comment by pfrazee** [comment]
Is this needed because Beaker will redirect from https to dat automatically?

**Comment by da2x** [comment]
> Is this needed because Beaker will redirect from https to dat automatically?

Yes, as is the intended and in most situations the desired behavior.

Maybe only redirecting for 200 responses? But then every HTTPS link would need to go via the HTTPS server instead of being rewritten client side.

**Comment by webdesserts** [comment]
Curious third-party here:

@da2x What would be the difference between

```html
<a href="https-only://example.com/my-route">link</a>
```
and
```html
<a href="https://example.com/my-route">link</a>
```

That part's not entirely clear to me.

**Comment by pfrazee** [comment]
@webdesserts Right now, Beaker will redirect automatically from https to dat if it detects dat is available. This issue makes me wonder if that's really the best call or not.

**Comment by da2x** [comment]
> This issue makes me wonder if that's really the best call or not.

99% of the time, this is the right decison. For form submissions, pings, "redirect checks", and a few other situations you still want some way to be able to reach the origin over HTTPS.

Forms and pings are easy: if request is POST then submit it over HTTPS and display the response over HTTPS. Subsequent main frame requests can be loaded from the Dat. I’m not actually 100% sure on the current behavior there.

However, as I say in the original issue: sometimes it’s also useful to direct a normal GET request. **Maybe** it’s no more complicated than POST requests, though? If a resource isn’t found in the Dat archive, retry the request over HTTPS. That would handle HTTP redirects, HTTP Gone, outright missing resources in the Dat archive version, and a few other commonish situations. The redirected location can safely be redirected back to the Dat archive. In cases where there is a redirect chain, you’d need to jump back an forth a few times but that is okay. If the site returns 404 then return the Dat fallback_page or fallback to the HTTPS error page.

**Comment by pfrazee** [comment]
Okay, I'm going to think on this a little bit. I need to wrap my head around this use-case and routing in general before I even come up with a temporary solution.

**Comment by webdesserts** [comment]
@pfrazee I think it's maybe a bit of a departure from the way that links currently work on the web at least. My understanding of the way that links currently work is that...

```html
// I would normally expect this link to _explicitly_ use https
<a href="https://example.com/my-route">link</a>
// and this link to "use whatever protocol we're currently working with"
<a href="example.com/my-route">link</a>
```

Maybe the auto-redirect should only work when you enter the url in the address bar and not on every request?

**Comment by da2x** [comment]
The redirect is a good thing and it will ease the adoption and migration for website publishers. It really should stay  We can't expect people to redevelop entire websites to work with Dat.

Many static content generators that otherwise produce perfect candidates for Dat sites will output absolute URIs. The redirect deals with this just fine.

It's just that Dat doesn't have a replacement for POST submissions or things like redirects. Enabling these request to go to a central HTTPS server enables a lot of usecases (commenting, contact forms, pings, webmentions, etc.) and also ease people's transition to Dat.

@pfraze Your can simply dictate that a Dat-ified origin can't send requests to HTTPS and ask people to send their forms, pings, and redirect chain checks to another origin. That should be documented, however. The documentation should suggest POSTing to a different origin, and doing one-off HTTPS request through a origin alias (like www-forced.example.com that doesn't have the DNS record or WellKnown to redirect it.) This will require more complex setups for webdevs than "simply" tagging one specific request in their apps and sites as requiring HTTPS but will keep Dat implementations simpler to ease adoption on the client side.

We need sime formal standards for Dat in web browsers. Things like this needs to be defined so client implementations won't diverge too far and webdevs know what they've got to work with.
