### ISSUE TITLE
"Seed this site" should update Dat key for DNS Dat

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1403]
1. Open dat://beakerbrowser.com
2. Open the p2p menu and click "Seed this site's files"
3. Edit the DNS TXT record or WellKnown for dat://beakerbrowser.com to point to a new Dat archive

Expected results: Clients should periodically rediscover Dat DNS key's for seeded domains, stop seeding the old Dat archive, and start seeding the new archive (assuming they're roughly the same size on disk).

Actual: You'll keep seeding the old  archive despite indicating you're interested in contributing bandwidth towards a domain's distribution. You lose offline access to the site.

Internally, I believe that "seed this site" pins the domain's current Dat key instead of pinning the domain itself. The former is expected when accessing  a raw Dat archive but the latter is expected when accessing websites via their domains.

**Comment by brechtcs** [comment]
Not 100% sure, but I think this behaviour might change when https://github.com/beakerbrowser/beaker-core/pull/21 is released. (Assuming you've tested this on the 0.8.8 release, not on master.)

**Comment by pfrazee** [comment]
@brechtcs No that just resolves the dns prior to saving.
