### ISSUE TITLE
Download as ZIP option

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#1405]
Operation System: macOS 10.14.4
Beaker version: v0.8.8

I am unable to complete a download of a DAT archive using the ZIP option. Progress bar stops early on and there is an incomplete zip file that either cannot open or extracts to a .zip.cpgz in a loop. 

lmk if you want more info. Not sure if this is a known issue or has some limitations. I tried a handful of dats including pfrazee.hashbase.io

**Comment by pfrazee** [comment]
Thanks for filing. I'll check into this.
