### ISSUE TITLE
Trouble Creating Beaker Sites

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/beaker#1407]
Operation System: Linux Mint 19.2
Beaker version: Current

Does anyone else have a problem with creating new beaker sites? It seems to be limiting me to creating one per instance of beaker browser at the moment.

**Comment by pfrazee** [comment]
Can you describe what's happening? How is it limiting you?

**Comment by LWFlouisa** [comment]
Ah sorry I didn't specify. Basically whenever I try to click on new, and I click on a tab in menu, then it acts as if the link itself is not present. I tried doing it the normal way through the side bar, and that also only worked once.

So each time I want to create a new website, I have to redownload the browser.

**Comment by pfrazee** [comment]
@LWFlouisa Sorry to ask, but would you be able to record your screen to demonstrate this issue? I'm not sure what could be causing this.

**Comment by LWFlouisa** [comment]
Yea absolutely!

![Browser Issue](https://raw.githubusercontent.com/LWFlouisa/lwflouisa.github.io/master/artgallery/beaker.png)

Basically whenever I click on new and then one of the panels that drop down, clicking on it only highlights it. And building a site through the drop down menu is largely unresponsive.

**Comment by LWFlouisa** [comment]
So as an update, oddly enough it seemed to resolve, at least for this one website. I'll have to see for the rest of my website.
