### ISSUE TITLE
Editing title/desc of a dat removes all other data in dat.json

### ISSUE THREAD

**Issue by krisradio** [beakerbrowser/beaker#1409]
OS: Win 8.1
Beaker: v0.8.8

Editing the name/description of a dat in Beaker's library removes all other metadata from dat.json (e.g. `type`, `links`, or `content_security_policy`). 

Editing a dat.json file locally and publishing the changes through Beaker clears all metadata in Beaker's view - the name becomes untitled, the description blank. 

Solution: Read local changes into Beaker rather than zeroing metadata.

**Comment by todrobbins** [comment]
I've noticed this as well on the macOS client (v0.8.8).

**Comment by pfrazee** [comment]
No bueno! I'll check into this. Thanks for filing.
