### ISSUE TITLE
Public Beaker file viewer/editor as a Dat webiste

### ISSUE THREAD

**Issue by RangerMauve** [beakerbrowser/beaker#1410]
Dat is getting support in more environments like the Clizq browser and the mobile app they're working on. I'm also going to be working on adding Dat support to [Exokit](https://github.com/exokitxr/exokit) for the P2P WebXR stuff I'm working on.

It'd be cool to be able to reuse some of the tooling that comes bundled in Beaker across these platforms rather than having to reimplement the same features per platform.

**Comment by pfrazee** [comment]
There are still some blockers that stop the Editor from being a userland app. I believe that the next round of Web API updates (part of Blue) could lay the groundwork for that.
