### ISSUE TITLE
DNS cache doesn’t persist between sessions

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1412]
Operation System: Linux, macOS, and Windows
Beaker version: 0.8.8

1. Go to dat://beakerbrowser.com
2. Choose to seed the website
3. Give it some time to download the site. Check in the Library to confirm you’ve got the whole site.
4. Quit Beaker.
5. Disconnect from the internet.
6. Restart Beaker
5. Go to dat://beakerbrowser.com again.

Expected: page should load just fine as you have a local copy.

Actual: “It doesn't seem like anybody is sharing this page right now.”

beaker://dat-dns-cache/ confirm that the DNS cache fails and doesn’t persist between sessions.

**Comment by pfrazee** [comment]
I'm actually not 100% sure this is DNS cache that's failing. You'd get a message specific to DNS if it was.

My guess is there's some code that tries to check in with the network before loading the dat.

**Comment by da2x** [comment]
beaker://dat-dns-cache/ shows “false” so I figured that was the reason why the archive failed to load even though there is a local copy of it. As far as I can tell, there is no other mapping between dat://beakerbrowser.com and the raw dat archive key. beakerbrowser.com’s dat has a TTL of 1 hour so it should at the very least work for one hour. (Ideally the TTL should be configured to days and weeks and not just an hour – see the proposed changes in [/datprotocol/DEPs/pull/59](https://github.com/datprotocol/DEPs/pull/59/files).) Reusing an expired stale response is better than not showing the page especially when a copy of the site is cached locally.

**Comment by raphaelbastide** [comment]
It sounds to be linked to my repport here https://github.com/beakerbrowser/beaker/issues/1354#issuecomment-515114790
