### ISSUE TITLE
Websites with a local seed randomly fails to load

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1413]
Operation System: Linux, macOS, and Windows
Beaker version: 0.8.8

1. Go to dat://beakerbrowser.com
2. Choose to seed the website
3. Give it some time to download the site. Check in the Library to confirm you’ve got the whole site.
4. Restart Beaker
5. Go to dat://beakerbrowser.com again.
6. Reload a couple of times.

Expected: page should load just fine as you have a local copy.

Actual: “It doesn't seem like anybody is sharing this page right now.” error page.

**Comment by pfrazee** [comment]
Okay this is what I thought you were reporting in https://github.com/beakerbrowser/beaker/issues/1412. I agree this is an issue, I'm unsure about #1412.

**Comment by da2x** [comment]
#1412 is specifically a issue with DNS caching. This issue happens even when accessing raw Dat keys without Dat DNS being involved. Alternate steps for this issue: go to library, open an archive, click the raw Dat link, and then you seemingly at random get the “nobody is sharing” error despite having a local copy.
