### ISSUE TITLE
Peer count not pulling from live data

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#1416]
Operation System: macOS 10.14.5

Beaker version: 0.8.8

Peer count in the menubar does not match the peer count in the description:

<img width="324" alt="differing-peer-count" src="https://user-images.githubusercontent.com/158590/59120594-04d59180-8913-11e9-885c-ad6309a73b77.png">

**Comment by pfrazee** [comment]
Thanks for filing, I'll check into this
