### ISSUE TITLE
i3 window manager has problem with url display bar on lower left hand corner

### ISSUE THREAD

**Issue by plankatron** [beakerbrowser/beaker#1418]
So as the title implies, the url bar in the lower left hand corner shows up on all workspaces and infront of all windows.. not sure why but it has been doing this for a few months now. 

as a side note, the settings menu also can sometimes display in odd places and not where it should be. 

Operation System: Linux Mint 19

Beaker version: 
Version: 0.8.8 Electron: 5.0.0 - Chromium: 73.0.3683.119 - Node: 12.0.0

**Comment by pfrazee** [comment]
I've found a solution to this which will be included in the upcoming 0.9 release.

Basically the status bar (the URL display) is currently a subwindow. I found a way to implement it within the existing browser window, which should solve this issue.
