### ISSUE TITLE
Tiny issues with main website

### ISSUE THREAD

**Issue by anchpop** [beakerbrowser/beaker#1420]
I wasn't sure where to report this, but here's a couple things:

On [this](https://beakerbrowser.com/docs/how-beaker-works/peer-to-peer-websites#so-whats-a-peer-to-peer-website) documentation page, there's a link to dat://beakerbrowser.com. However, visiting this page in Beaker reports to me "It doesn't seem like anybody is sharing this page right now. [...] The p2p page was not found on the network.". dat://explore.beakerbrowser.com/ works fine however. Is the link incorrect or is the site down? I'm on Beaker v0.8.8.

The other issue was that the download for Beaker on the website appears to be out of date - downloading it and viewing the welcome screen actually gives a DNS error. I had to update Beaker through the update menu to view the welcome screen.

**Comment by pfrazee** [comment]
I saw somebody on HN comment that the beaker site wasnt available (maybe that was you!) so I just spent some time on it and got it up again.

> The other issue was that the download for Beaker on the website appears to be out of date

Could you tell me where the link was you're referring to? I can't find it.

**Comment by andrepopovitch** [comment]
Nope, wasn't me! Haha. I'm just talking about https://beakerbrowser.com/install/ - I installed it and when I opened it there was an icon in the dropdown menu saying there was an update available. dat://beakerbrowser.com works fine now though, cool.

**Comment by anchpop** [comment]
Nope, wasn't me! Haha. I'm just talking about https://beakerbrowser.com/install/ - I installed beaker and when I opened it there was an icon in the dropdown menu saying there was an update available. dat://beakerbrowser.com works fine now though, cool

**Comment by pfrazee** [comment]
Oh right. I'll check into that.

Thanks!~
