### ISSUE TITLE
[Feature] Add i2p Support

### ISSUE THREAD

**Issue by oijkhg** [beakerbrowser/beaker#1421]
**Feature**: Add i2p support to DAT and Beaker Browser
**Why?**: Mainly for privacy and security but also to support decentralized web communications.
**How?**: BitTorrent already has wide usage of i2p thank to i2p-snarks and [XD](https://xd-torrent.github.io/).
**Related Issues**: #1371 
____________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75580975-feature-add-i2p-support)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75580975)](https://www.bountysource.com/issues/75580975-feature-add-i2p-support)

**Comment by RangerMauve** [comment]
This is a duplicate of https://github.com/datproject/dat/issues/1120

**Comment by pfrazee** [comment]
Going to let the dat repo track this idea
