### ISSUE TITLE
Security report

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1422]
Hi, @pfrazee ! Thanks for unblocking me from /beakerbrowser org on GitHub.
I've never before described issues here, what made you wanting to block.
I forgive our disagreement, and I'm now here to do support and describe this issue.

The most sensible kind of Electron app is a browser, which is the case of Beaker.
I'm doing security audit on lots of Electron apps, and Beaker were special because of being a browser. And it showed vulnerabilities, and more than the other apps.

Attached to this issue is the HTML file of the report.
[beaker-security_report.html.zip](https://github.com/beakerbrowser/beaker/files/3294515/beaker-security_report.html.zip)

**Comment by pfrazee** [comment]
So, I talked with Tara about what happened. I know your intentions are good! but you do make a lot of issues and sometimes they're not super helpful.

I appreciate you running a security audit on the browser, but are any of these results important? I scanned through them and didn't see anything I don't already know about.

**Comment by DaniellMesquita** [comment]
> So, I talked with Tara about what happened. I know your intentions are good! but you do make a lot of issues and sometimes they're not super helpful.

Thanks.
Well, in lots of projects I post only the title, and they are correctly interpreted. But it depends, and I'll remember to describe in anything related to Dat and Beaker.

> I appreciate you running a security audit on the browser, but are any of these results important? I scanned through them and didn't see anything I don't already know about.

If Electronegativity, as a security auditor and not a JS-best-practices program, I think these results are important.
Well, you already knew about?
