### ISSUE TITLE
ImportDeclaration should appear when the mode is ES6 and in the module context

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1423]
That is required for security parsing.

Error parsing /1/Apps/beaker/tests/apps-test-disabled.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/archives-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/bookmarks-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/browser-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/dat-archive-synced-folder-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/dat-archive-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/experimental-capture-page-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/experimental-dat-peers-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/experimental-global-fetch-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/experimental-library-web-api-test.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/profiles-web-api-test-disabled.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/tests/timeline-web-api-test-disabled.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/json-renderer.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/location-bar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/markdown-renderer.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/perm-prompt.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/webview-preload.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/basic-auth.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/bg-process-rpc.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/buttons.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/common.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/create-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/fork-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/inputs.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/prompt.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/select-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/modals/spinner.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/bg-process-rpc.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/bookmark.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/browser.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/buttons.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/common.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/donate.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/inputs.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/local-path.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/page.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/peers.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-menus/site-info.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/perm-prompt/bg-process-rpc.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/perm-prompt/buttons.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/webview-preload/execute-javascript.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/webview-preload/exit-full-screen-hackfix.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/webview-preload/locationbar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/webview-preload/prompt.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/webview-preload/window-open-close-hackfix.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/electron.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/streams.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/time.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/bg/dat-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/bg/fs.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/fg/archive-progress-monitor.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/fg/event-handlers.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/fg/img.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/fg/markdown.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/fg/perms.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/lib/fg/rehost-slider.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/bg-process-rpc.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/navbar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/spinner.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/tabs.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/win32.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/navbar/button-reset.css.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/navbar/inpage-find.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/navbar/location.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/new-shell-window/navbar/site-info.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/avatar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/box.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/close.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/file-o.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/file-text-o.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/filesystem.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/folder-color.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/folder.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/gear-small.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/gear.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/globe.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/grid.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/heart.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/history.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/home-grayscale.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/home.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/list-expanded.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/list.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/network.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/news.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/padlock.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/pencil.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/photos.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/pin.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/replies.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/restore.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/rss.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/search.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/star-fill.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/star.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/three-dots.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/trash-grayscale.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/trash.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/icon/videos.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/bookmarks.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/downloads.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/history.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/install-modal.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/library-view.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/library.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/profile.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/settings.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/start.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/swarm-debugger.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/view-source.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/views/watchlist.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/add-watchlist-item-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/back-link.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/builtin-pages-nav.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/context-input.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/context-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/create-archive-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/crop-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/downloads-list.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/dropdown-menu-bar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/img-with-fallbacks.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/motd.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/notice-banner.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/onboarding-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/peer-history-graph.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/segmented-progress-bar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/share-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/tabs.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/toast.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/toggleable.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/toggleable2.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/archive/archive-comparison.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/archive/archive-history.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/archive/archive-select-btn.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/archive/diff.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/library/copydat-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/library/createfile-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/library/localsyncpath-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/library/view-compare.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/library/view-local-compare.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/settings/add-pinned-bookmark-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/settings/dat-network-activity.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/settings/edit-bookmark-popup.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/settings/favicon-maker.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/settings/favicon-picker.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/settings/settings-field.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/files-browser/file-editor.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/files-browser/file-preview.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/files-browser/files-browser.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/builtin-pages/com/files-browser/files-flat-view.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/adblocker.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/analytics.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/browser.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/child-processes.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/nat-port-forwarder.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/open-url.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/test-driver.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/protocols/beaker-favicon.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/protocols/beaker.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/context-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/downloads.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/keybindings.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/permissions.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/session-watcher.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/view-manager.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/window-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/windows.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/views/zoom.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/subwindows/location-bar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/subwindows/modals.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/subwindows/perm-prompt.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/subwindows/shell-menus.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/background-process/ui/subwindows/status-bar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/command-handlers.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/pages.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/swipe-handlers.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/pages/zoom.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modal.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/prompt.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/tabs.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/toast.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/win32-titlebar.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/icon/close.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/icon/nav-arrow.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/icon/padlock.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/icon/refresh.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modals/base.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modals/create-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modals/example.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modals/fork-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modals/index.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/modals/select-archive.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/apps-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/bookmark-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/browser-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/datsite-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/donate-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/page-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/site-info.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/syncfolder-menu.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/updates.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/navbar/watchlist-notification.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/shell-window/ui/prompts/permission.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-element.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lit-html.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/async-append.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/async-replace.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/cache.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/class-map.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/guard.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/if-defined.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/repeat.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/style-map.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/unsafe-html.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/directives/until.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/default-template-processor.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/modify-template.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/parts.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/render.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/shady-render.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/template-factory.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/template-instance.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/beaker/app/vendor/lit-element/lit-html/lib/template-result.js - ImportDeclaration should appear when the mode is ES6 and in the module context.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/beakerbrowser/beaker/issues/1422

**Comment by pfrazee** [comment]
I don't know what exactly your auditing tool is expecting, but I'm not likely to figure it out without running the auditing tool myself. Thanks but I'm not going to dig into this.

**Comment by DaniellMesquita** [comment]
https://github.com/doyensec/electronegativity

@phosphore
