### ISSUE TITLE
Open existing Dat on Beaker

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1424]
By reading the "url" field on dat.json

**Comment by pfrazee** [comment]
Open existing dat? Can you give more information?

**Comment by DaniellMesquita** [comment]
I create a Dat on Windows, then needs to open it in Mac. Beaker will ask to create a new dat based on this folder, instead of importing.

**Comment by evdubs** [comment]
To elaborate further, as I am having the same issue, if you first `dat share` some folder, it will create a dat.json file and prepare the contents to be shared. You can then use dat-desktop to share this already-created dat, or you can continue to use `dat share`. You cannot, as far as I can tell, share this existing dat in Beaker.

The options in Beaker are:
- Create New / From Folder. This will overwrite the existing `dat.json` file.
- Share Files. This doesn't seem to load the existing dat information and use that to share.

An option like "Share existing dat" that does the same thing as `dat share` or dat-desktop is useful here.

**Comment by evdubs** [comment]
In addition to general usefulness, I think this feature is useful because I (and I assume others) have been told that dat-desktop is deprecated and people should switch to beaker / dat share / dat-store. It is nice to have a GUI for managing dats, but if dat-desktop is deprecated and beaker can't share existing dats, I don't think there's an available recommended GUI to do this.

**Comment by pfrazee** [comment]
Okay that makes sense. We're about to unify the dat networking stack between the CLI and Beaker. Once that's done, we can look at making sure this specific flow works correctly.

**Comment by evdubs** [comment]
I am curious about an estimated timeframe. Do you anticipate the networking stack unification to be available in a week? a month?

**Comment by pfrazee** [comment]
I just started on the first PR today. All told, I'd estimate 1-2 months.

**Comment by evdubs** [comment]
@pfrazee do you happen to have an update?

**Comment by pfrazee** [comment]
Aiming to start the internal beta this month
