### ISSUE TITLE
About site APIs

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1425]
- How a site creates a Dat (I mean the script used) ?
- Also, how this site reads/writes to a Dat?
- How it parses/writes to its JSON?
- How it lists files?

Thanks in advance

**Comment by pfrazee** [comment]
Okay @DaniellMesquita, I really need you to take a pause on all the issues you're opening. Do you really need this question answered? It takes time for me to respond to these.
