### ISSUE TITLE
In site script, how to detect if it is open in Beaker?

### ISSUE THREAD

**Issue by DaniellMesquita** [beakerbrowser/beaker#1426]

**Comment by pfrazee** [comment]
You can check if the `DatArchive` API is available

**Comment by DaniellMesquita** [comment]
Not exact detecting if it is in Beaker. For example, if it is a NodeJS app, it will say DatArchive is available?

Althought, if it shows DatArchive API as available, but isn't in a app, considers it as Beaker.

**Comment by mkroehnert** [comment]
Hi Daniell,

You should always check for APIs/features and not for specific browsers.

Same as when developing a regular web page.
