### ISSUE TITLE
Build fails with Node versions 6, 7, 9, 12 

### ISSUE THREAD

**Issue by jasonszhao** [beakerbrowser/beaker#1430]
Operation System: **macOS 10.14.5**

Beaker version: 0.8.8 release (7206281)

README.md and CONTRIBUTING.md say that building from source "requires node 6 or higher." However, not all Node versions >= 6 actually built on my machine. 

## Steps to reproduce

I tried building with Node versions 6–12 with the following script:

```bash
for i in $(seq 6 12)
do 
nvm install $i
npm i -g gulp node-gyp
npm run burnthemall > "../beaker-logs/using-node-$i.txt" 2>&1
done
```

## Results:

I've attached the build logs for each version of Node. I've glanced at the logs—it appears that the problem comes from dependencies.

[using-node-6.txt](https://github.com/beakerbrowser/beaker/files/3324002/using-node-6.txt)
[using-node-7.txt](https://github.com/beakerbrowser/beaker/files/3324003/using-node-7.txt)
[using-node-8.txt](https://github.com/beakerbrowser/beaker/files/3324004/using-node-8.txt)
[using-node-9.txt](https://github.com/beakerbrowser/beaker/files/3324005/using-node-9.txt)
[using-node-10.txt](https://github.com/beakerbrowser/beaker/files/3324006/using-node-10.txt)
[using-node-11.txt](https://github.com/beakerbrowser/beaker/files/3324007/using-node-11.txt)
[using-node-12.txt](https://github.com/beakerbrowser/beaker/files/3324008/using-node-12.txt)

### Node 6, 7, 9:

node-gyp complains about XCode tools not being installed. nodejs/node-gyp#569 may be related.

In [this issue](https://github.com/beakerbrowser/beaker/issues/1277#issuecomment-445891070), a core contributor says that you should update to Node 10.x. 

### Node 8, 10, 11

Builds successfully! 🎉

### Node 12:

node-gyp build error. This electron-userland/electron-installer-dmg#39

Though the issue is on Windows, #1351 might be related.

## Conclusion

I'm not sure if this is specific to my operating system. The build instructions might have to be updated with compatible versions of Node. Let me know if I can do anything related to this issue.

**Comment by pmario** [comment]
It would be interesting, which node version @pfrazee uses to build the stuff.

**Comment by pmario** [comment]
with windows 10, node 10.16 on the "blue" branch I do get the same error message, as shown in using-node-9.txt

```
'URL' is imported from external module 'url' but never used
'default' is imported from external module 'mime' but never used
[23:31:47] 'bundleTask' errored after 3.58 s
[23:31:47] Error: Cannot find module '@beaker/core/webview' from '/Users/jason/Documents/Code/beaker/app'
    at /Users/jason/Documents/Code/beaker/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/jason/Documents/Code/beaker/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/jason/Documents/Code/beaker/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/jason/Documents/Code/beaker/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/jason/Documents/Code/beaker/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/jason/Documents/Code/beaker/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:170:21)
[23:31:47] 'bundle' errored after 3.58 s
[23:31:47] 'build' errored after 3.58 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beakerbrowser@ build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the beakerbrowser@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jason/.npm/_logs/2019-06-25T06_31_47_175Z-debug.log
[23:31:47] Finished '<anonymous>' after 6.23 s
[23:31:47] Finished 'rebuild' after 6.23 s
```

**Comment by pfrazee** [comment]
Interesting. I use v11.11.0. I'll keep an eye on the v12 situation. Thanks for the detailed research.

**Comment by pmario** [comment]
@pfrazee ... do you still use node v11.11.0 to build branch: **blue-hyperdrive10**?

**Comment by pfrazee** [comment]
I'm using 11.15 right now

**Comment by pmario** [comment]
Are you able to compile beaker with unix and windows? ... Which node version does work atm?
