### ISSUE TITLE
beaker/blue only shows empty tabs.

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#1431]
Windows 10 PRO,
node 10.16.0
beaker/blue commit 1275eecb201ac2a8fa482d7e6463a1ed6dfb4892

I can compile the stuff using `npm run burnthemall`

I can start the app, but every view only creates a white tab and the console shows this:

tested: `beaker://start/` and `beaker://library/`

```
VM12:1032 Uncaught Error: Unknown API: profiles
    at Navigator.importSystemAPI (<anonymous>:1032:11)
    at dat.js:10
```

**Comment by pfrazee** [comment]
Make sure you have the latest versions of everything in blue's apps, including the stdlib

**Comment by pmario** [comment]
`npm run burnthemall` should install the latest dependencies. right?

**Comment by pmario** [comment]
`D:\git\beaker\app\node_modules\@beaker\library-app\vendor\beaker-app-stdlib\js\com\library\sidebars`

seems to contain an outdated dat.js file.

**Comment by pmario** [comment]
same with: D:\git\beaker\app\node_modules\@beaker\start-app\vendor\beaker-app-stdlib\js\com\library\sidebars

**Comment by pmario** [comment]
As var as I can see, this should be, what's defined in the app/package.json
```
$ npm list --depth=0
beaker-browser@0.9.0-prerelease.4 D:\git\beaker\app
+-- @beaker/core@3.0.2 (github:beakerbrowser/beaker-core#cdfec1991396f31fe90e0d9986dd707ec685920b)
+-- @beaker/dat-archive-file-diff@1.0.0
+-- @beaker/library-app@3.0.1
+-- @beaker/search-app@2.1.0
+-- @beaker/start-app@3.0.0
```

**Comment by pmario** [comment]
@pfrazee I have no idea, how the `beaker-app-stdlib` is included into the `start-app` since `start-app` doesn't seem to have a dependency. ... 

So can you please tell me, how we need to modify the main readme, so that we can do a "build from source" that works for every OS.

**Comment by pfrazee** [comment]
@pmario I'm sorry, but blue is strictly internal so I'm not going to give support on it in the interest of time
