### ISSUE TITLE
On the new tab page, the link to dat://datproject.org should be dat://dat.foundation/

### ISSUE THREAD

**Issue by anchpop** [beakerbrowser/beaker#1434]
dat://datproject.org seems to not be their page anymore

**Comment by pfrazee** [comment]
Thanks for the reminder. I'll update the default bookmarks.

**Comment by dym-sh** [comment]
/related
beaker can't handle http-redirect if accessed directly to dat://datproject.org and display empty page

> λ curl --HEAD datproject.org
```
HTTP/1.1 301 Moved Permanently
Date: Wed, 04 Sep 2019 02:28:52 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Wed, 04 Sep 2019 03:28:52 GMT
Location: https://dat.foundation
Server: cloudflare
CF-RAY: 510c8856e98f2d57-TXL
```

**Comment by pfrazee** [comment]
We discussed handling redirects on dat-dns and decided not to support it for now. We're worried about the complexity and whether it could introduce some kind of attack vector or bugginess.
