### ISSUE TITLE
I want to make clone version of me . 

### ISSUE THREAD

**Issue by kurodenjiro** [beakerbrowser/beaker#1441]
i want to make a clone version and edit brand , can i copy edit without legal of copyright ?

**Comment by pmario** [comment]
see:https://github.com/beakerbrowser/beaker/blob/master/LICENSE

**Comment by pfrazee** [comment]
Currently: When you want to fork a site, look for a file called "LICENSE" in the repo, or check the README for a license section. If there's not a permissive open-source license given, you shouldn't fork the site.

In the future: We'll add tools to help people set the licenses on their work, and the browser will let you know if it's okay to fork a site.

**Comment by RangerMauve** [comment]
Yeah, it'd be useful to have a license selection screen be part of creating projects inside Beaker. 🤔

Maybe default to something from [creative commons](https://creativecommons.org/)

**Comment by pfrazee** [comment]
@RangerMauve Agree, the tooling around that should be really well integrated for both creation and usage.
