### ISSUE TITLE
[UI] New Tab -> Paste Doesn't Replace Start URL

### ISSUE THREAD

**Issue by Miserlou** [beakerbrowser/beaker#1443]
OSX, latest Beaker.

When I open a new tab and then press "APL+V" to paste, the base URL doesn't get replaced, so the resulting URL in is "beaker://start/dat://mywebsite.hashbase.io", which is obviously invalid.

Annoyingly, this doesn't happen every single time, but it does happen enough to be quite irritating. If I find a better way to reproduce it, I'll add that here.

**Comment by Miserlou** [comment]
Here's a repro:

Open a working or not working site. Select the URL. Open a new tab. Press paste. You will have a "beaker://start/dat://mywebsite.hashbase.io" URL.

**Comment by pfrazee** [comment]
Yeah this is a real pain! I've got this fixed in the upcoming release (just fixed it last week). Sorry to make you wait for 0.9 but it is solved.

**Comment by Miserlou** [comment]
Nice! Thanks!
