### ISSUE TITLE
ESM import automatically add /index.js to dat addresses

### ISSUE THREAD

**Issue by sgwilym** [beakerbrowser/beaker#1445]
Operation System: macOS 10.14.5

Beaker version: 0.8.8

---

I'll give you a moment to get the image of having mime problems out of your head. 

When trying to import ESM from another dat in a JS file, like so:

```
import { now } from "dat://ceb2e9271ed0f334d4f4e51794eedc8011bb003ce0d9cfcc8ea9c30b1944f496";
```

I get the following error: 

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

The only way I can make it work is if I do this:

```
import { now } from "dat://ceb2e9271ed0f334d4f4e51794eedc8011bb003ce0d9cfcc8ea9c30b1944f496/dist-web/index.js";
```

Even though I _should_ be able to do it the other way the same package works in other browsers when server from a non-dat source (and also works in Beaker when imported from a non-dat source).

Here's a dat reproducing the issue: dat://4b91d299129dbf8507aedb3fc6691abb635d282120d739c19c818690f5210994/

And here's a repo to go with it, just in case:
https://github.com/sgwilym/esm-beaker-repro

**Comment by RangerMauve** [comment]
Could you post the URL of the HTTP example?

**Comment by sgwilym** [comment]
Sorry for the delay. Here is an example of a dat successfully importing the same module via HTTP: dat://656aaf5c441f175627e381ff9a2129aaddf1e35b8727535f104f872e883d8aca/

**Comment by pfrazee** [comment]
I actually looked into this a while back and found that Electron wasn't giving me enough information to determine that a module was being requested (as opposed to a web page). The Accept header was set to `*/*` and nothing else was helping in the request information. I'll have to look again to see if I can solve it.
