### ISSUE TITLE
Cannot enter address in adressbar

### ISSUE THREAD

**Issue by djbacon** [beakerbrowser/beaker#1446]
Operating system: Ubuntu Mate 18.04 64bit

This is:

- [x] a bug
- [ ] general feedback

I open Beaker Browser and i click on address bar to enter address and as soon as i type first letter drop-down shows for a split second and address reverts back to what it was before i started typing. I tried it to day on 0.8.7 and then checked that there is 0.8.8, but unfortunately same issue is on 0.8.8 as well.

The only way to type new address is to copy it from somewhere else and right click in address bar and select Paste & Go.

**Comment by pfrazee** [comment]
Hey @djbacon, sorry about this issue. I *think* we have it solved in the upcoming release. Unfortunately that won't be out for another month or two, and backporting isn't really any option.

**Comment by djbacon** [comment]
Thanks.
That's alright. It's not my primary browser.

**Comment by thearthur** [comment]
does this work on older versionas as well and if running the old one a reasonable idea? (this is my first time looking at this project)

**Comment by thearthur** [comment]
I tried 0.8.7 and it also has this bug, and the previous version has scary security vulnerability messages on the release page, so I'll check this project out next time it comes up in life.

**Comment by kapitaali** [comment]
I'm using 0.8.8 AppImage on Linux Mint 19.2 and I have this issue. 

Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Version: 0.8.8 Electron: 4.1.3 - Chromium: 69.0.3497.128 - Node: 10.11.0

**Comment by thearthur** [comment]
@kapitaali it seems to happen in all distributions and install methods. 

I thought the browser was completely unusable because I had missed the last word on the workaround at the bottom of this bug report:
"The only way to type new address is to copy it from somewhere else and right click in address bar and select **Paste & Go.**"
if I just hit paste then it still doesn't work.
