### ISSUE TITLE
Redirect to dat:// redirects even when dat:// isn't available

### ISSUE THREAD

**Issue by Pawper** [beakerbrowser/beaker#1447]
![image](https://user-images.githubusercontent.com/22269691/62915447-4e928c00-bd49-11e9-91d1-809165616767.png)

The feature to redirect to dat:// is happening even though dat:// is not working as described. If I change dat://beakerbrowser.com/docs/guides/ to https://beakerbrowser.com/docs/guides/ it redirects back to the broken dat:// URL.

![image](https://user-images.githubusercontent.com/22269691/62915340-e9d73180-bd48-11e9-8b88-3c7b74e3035b.png)

I know the dat:// connectivity issue is due to the mysterious bugginess of the Dat networking stack (see #1400 ). But shouldn't this feature still work as described?

Perhaps it's possible to allow the user to override this feature if they manually change back to https:// ? Or have an option to use https:// for the current domain? Maybe Beaker can detect this happening and give us a heads-up to use https:// for the current domain? This would add a bit of resiliency against dat stack issues yeah?

**Comment by Pawper** [comment]
Geez it made that screenshot obnoxiously huge. My obnoxiousness is real but is never intended! :heart:

**Comment by pfrazee** [comment]
@Pawper yeah you're right, it's an incredibly annoying setting when it turns out the dat site isn't *actually* available.

> Perhaps it's possible to allow the user to override this feature if they manually change back to https:// ? Or have an option to use https:// for the current domain? Maybe Beaker can detect this happening and give us a heads-up to use https:// for the current domain? This would add a bit of resiliency against dat stack issues yeah?

These are good suggestions. Once dat2 lands, we should also try to get some sense of how frequently that happens. If it's still common, we might want to reconsider automatically redirecting
