### ISSUE TITLE
Project file conversion options

### ISSUE THREAD

**Issue by Pawper** [beakerbrowser/beaker#1448]
It would be cool if Beaker let us convert files in our projects to the format that is most accessible/comfortable for us. Perhaps an option in the right-click context menu?

HTML <> Markdown
JSON <> XML <> TSV <> CSV

I know there's some curveballs in this but it seems possible with some requirements at least.

**Comment by pfrazee** [comment]
That's a cool idea. I wonder if this should be builtin or a userland tool? Userland would mean waiting for some kind of tooling for executing userland scripts in the browsing context. The sidebar terminal would probably be the first place we'll get that tooling which wouldn't make it super convenient but at least you'd be able to do it. I'll mull this over.
