### ISSUE TITLE
Bug : 

### ISSUE THREAD

**Issue by mixmix** [beakerbrowser/beaker#1450]
with my current Beaker, I have this challenge where the current dat:// address is on top of all my windows on all desktops. 
It's enough for me to not run Beaker sometimes because it obscures important VIM interface.
Any ideas ? 

```
Version: 0.8.8 Electron: 4.1.3 - Chromium: 69.0.3497.128 - Node: 10.11.0
User data: /home/mixmix/.config/Beaker Browser
```

OS: linux (Kubuntu / debian)
window manager: i3 (tiling desktop manager)

**Comment by pfrazee** [comment]
Yeah this should be fixed in the upcoming release. Sorry for the PITA.

**Comment by pfrazee** [comment]
I'm going to close but please reopen if it's still happening after the upcoming release

**Comment by mixmix** [comment]
Thanks Paul!
