### ISSUE TITLE
i changed icon but rebuild it is not work

### ISSUE THREAD

**Issue by kurodenjiro** [beakerbrowser/beaker#1451]
Hello i changed my icon but it is not work . how can i do it ?

**Comment by pfrazee** [comment]
Hi @kurodenjiro, can you give more information on this? Do you mean the icon on your site?

**Comment by rajatpundir** [comment]
@pfrazee Just saw your beaker project. I think a major hurdle would be around its adoption, maybe you guys could get some corporates to host their internal sites using dat protocol. Once you have your browser on enough machines, maybe then other players could add support for dat as well. Concept like yours and ZeroNet seems like a much needed step in the right direction. Hopefully we will be able to decentralize the web from the control of some few players as it was originally envisioned by Tim Berners Lee.
