### ISSUE TITLE
Accessibility Tree does not display

### ISSUE THREAD

**Issue by Pawper** [beakerbrowser/beaker#1455]
Beaker:
![image](https://user-images.githubusercontent.com/22269691/64067319-a3545480-cbdb-11e9-8138-aa3867dd8143.png)

Chrome:
![image](https://user-images.githubusercontent.com/22269691/64067334-e7dff000-cbdb-11e9-895a-aa336cbab0e5.png)

Operation System: Windows 10

Beaker version: Latest

**Comment by pfrazee** [comment]
Thanks for filing. Probably an issue with Electron.
