### ISSUE TITLE
DatArchive.download('/') returns before the archive is completely available to Beaker

### ISSUE THREAD

**Issue by gohai** [beakerbrowser/beaker#1461]
> Paul: Thank you for Beaker. I've put together an experimental version of the Hotglue site-building tool to run on top of the `DatArchive` API ([hotglue-dat](https://github.com/gohai/hotglue/tree/dat)), and tried it out with other people at the our networks conference this weekend. Here some issues I encountered (in this and following bug) - hope you find those helpful.

```
let fork = await DatArchive.fork(url);
await fork.download('/');
window.location = fork.url;
```

It appears that `download` returns before the entirety of the site is available to Beaker, since the navigating to the URL is reproducibly showing a directory listing (with some files missing), rather than the content of `index.html`. This is at least on Beaker 0.8.8 (haven't tested other versions).

(Currently working around this by delaying redirect by two seconds, but I am not sure if this would reliably work with larger archives.)

**Comment by paul90** [comment]
Previously reported in https://github.com/beakerbrowser/beaker/issues/1275
