### ISSUE TITLE
Ability to view your own archives as if they were someone elses ("incognito mode"?)

### ISSUE THREAD

**Issue by gohai** [beakerbrowser/beaker#1465]
For developing applications that use the `DatArchive` API, I haven't quite found a way to view one's own archives in `Read-Only` mode (as if they were someone else's). Did I overlook a way to do so that exists already (0.8.8 on macOS), or would this perhaps be a generally useful feature?

**Comment by pfrazee** [comment]
I think you'd need to just do this in your application. You're ultimately going to be reacting to the `owner` flag
