### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by iBilley** [beakerbrowser/beaker#1471]
Operating system: manjaro linux

This is:

- [ ] a bug
- [ x] general feedback
i have low vision

i would love to see a dark theme option inside beaker. i currently use firefox and have it tweaked so its respecting my dark theme and together with a darkreader plugin this works 99% of the time.

beaker is electron app and defaults to a standard GTK or QT white theming?. because its sandboxed frm the os ? 

would be nice to see a GTK/QT theme chooser.

**Comment by pfrazee** [comment]
After the next major release (0.9) I plan to get this on the roadmap

**Comment by Ornataweaver** [comment]
Duplicate of https://github.com/beakerbrowser/beaker/issues/1035
