### ISSUE TITLE
Adding tens of thousands of files to the library from a folder causes the Library to become inaccessible

### ISSUE THREAD

**Issue by Bluebie** [beakerbrowser/beaker#1487]
Operation System: MacOS High Sierra

Beaker version:
v0.8.8

I added a website, the static site build of https://find.auslan.fyi/, as a folder, to my beaker library, hoping to publish it on Dat. After about 10 mins of intense CPU usage, it finished seemed to give up, and now I cannot access the library screen in Beaker. It's unclear how I could possibly remove or abort the operation.

I suggest, if the issue with large numbers of small files cannot be cleanly resolved and cannot provide some user interface with the ability to abort the operation, that Beaker should detect when trying to add a folder which has a lot of files in it, and warn the user that it could be slow or even effectively brick the beaker library view.

**Comment by pfrazee** [comment]
Yeah, thanks for reporting. Agree that shouldn't happen.

**Comment by Bluebie** [comment]
Beaker doesn’t seem to have any trouble streaming the site out of the Dat archive in general though. dat://find.auslan.fyi/ is working fine for me in Beaker on my High Sierra machine.
