### ISSUE TITLE
Tabs stuck in a blank screen

### ISSUE THREAD

**Issue by JerryGreen** [beakerbrowser/beaker#1492]
## Problem

Sometimes tabs don't show any info, and cannot be closed. It happens with various pages, including some of `dat:` pages, but the most easy reproducible way to achieve it what I've found is to open Settings, - it never opens.

## Preview

![Untitled](https://user-images.githubusercontent.com/13215662/71447149-1c5c5680-274d-11ea-90bd-0aff745f4e3a.gif)

## Versions

Operation System: macOS Catalina 10.15.2
Beaker version: 0.8.8

**Comment by ScottGrimmett** [comment]
Duplicate of #1417 ?

**Comment by JerryGreen** [comment]
Huh, it's indeed a duplicate. I'll close this issue, and will subscribe to that one :)
