### ISSUE TITLE
(Not an issue) Hows the project doing?

### ISSUE THREAD

**Issue by danrobi11** [beakerbrowser/beaker#1494]
Hello @pfrazee 
Hows the project doing? Im a bit scared here

Last commit here since june 2019: https://github.com/beakerbrowser/beaker/commits/master

Last commit there since sept 2019 : https://github.com/beakerbrowser/unwalled.garden/commits/develop

Is the project moved somewhere else? 

Thanks to You, the Team and Contributors for Beaker. Happy New Year!

**Comment by pfrazee** [comment]
Hey 👋 

We’re very active! The dev build is not easy to build without help but its the “blue-hyperdrive10” branch.

Check out my twitter (@pfrazee) for my dev log
