### ISSUE TITLE
Encrypted dat protocol

### ISSUE THREAD

**Issue by wuniversales** [beakerbrowser/beaker#1502]
I understand that the dat protocol is not encrypted, is there any way to encrypt it?

Theirs would be to add anonymity to the web, encrypt p2p connections (including metadata) so that the isp cannot decrypt the content.

That way they would not know what web you are browsing, or what files you are downloading.

Only users who download the web should access it.

**Comment by RangerMauve** [comment]
Dat does transport level encryption.

ISPs can't see what users are viewing, but they can see that people are making p2p connections and might be able to analyze traffic size.
