### ISSUE TITLE
beaker doesn't support XP

### ISSUE THREAD

**Issue by andika207** [beakerbrowser/beaker#1509]
it doens't support Windows XP
I won't support this project with my money $$

**Comment by pfrazee** [comment]
I haven't tried Beaker on XP but I won't say I'm surprised!

I am sorry we don't have XP support -- it's a great OS -- but it's a fairly old OS with a pretty small userbase, so I can't dedicate resources to it. If anybody can supply fixes for XP I'll be happy to merge.

**Comment by andika207** [comment]
@pfrazee Most of the time the excuse is that XP is from 2001 and it's too old when actually the latest version of the APIs and calls is from about 2008 so not so terribly old as people think.... W7 came out in 2009.

**Comment by andika207** [comment]
@pfrazee Most of the time the excuse is that XP is from 2001 and it's too old when actually the latest version of the APIs and calls is from about **2008** so not so terribly old as people might think.... 

W7 came out in **2009** and with regard to the small userbase it's because only a handful of web browsers do keep the support up for XP.

all this said XP has been getting official updates till April 2019, just 8 months before W7 EOL.

**Comment by sentialx** [comment]
Electron does not and won't support Windows XP
https://github.com/wexond/desktop/issues/393

**Comment by andika207** [comment]
@sentialx why are you posting this here ? 
you are even linking a message from @weolar who claimed Electron 5 was compatible with XP.

**Comment by andika207** [comment]
@sentialx why are you posting this here ?
you are even linking a message of @weolar who claimed Electron 5 was compatible with XP.

**Comment by sentialx** [comment]
Electron 5 while we have 10

**Comment by andika207** [comment]
@sentialx Nothing stop you from using old electron 5 to compile code for XP.  
You don't support XP because you don't want Not because it can't be done

**Comment by limeschool** [comment]
This matter is resolved. Electron has not supported Windows XP and will continue to not do so, thus making Beaker on Windows XP impossible. You can dualboot with a modern distribution of Linux, or update your version of Windows, to run Beaker on your PC.
