### ISSUE TITLE
Receiving error during load

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#151]
Operation System: OSX
Beaker Version:Latest Master 

Installing from source 
ran npm install and npm run rebuild

then npm start and received the following 

App threw an error during load
TypeError: electron.protocol.registerSecureSchemes is not a function

**Comment by pfrazee** [comment]
Yeah, this has to do with having the right Electron binary. We need to figure out why your master branch isn't getting the right binary.

**Comment by pfrazee** [comment]
See my comment here: https://github.com/beakerbrowser/beaker/issues/94#issuecomment-255450140

You'll need to delete your electron-binary cache to run beaker from master.
