### ISSUE TITLE
Error "A JavaScript error occurred in the main process" after upgrade and restart

### ISSUE THREAD

**Issue by johanbove** [beakerbrowser/beaker#1520]
Operation System: Windows 10
Beaker version: 0.8.8 -> 0.8.9

After a restart clicking the "restart" button from Beaker Browser v0.8.8, I now cannot start the browser and I see this "Uncaught Exception" error screen.

<img width="419" alt="Annotation 2020-03-13 073620" src="https://user-images.githubusercontent.com/922765/76596296-0f563480-64fe-11ea-86e3-297d1242e233.png">

**Comment by johanbove** [comment]
Reinstalled version 0.8.8 and the app is starting again. Will try the "Auto Updater" again.

**Comment by johanbove** [comment]
And the same error screen appears...

**Comment by graphixillusion** [comment]
I confirm: same error

**Comment by xDekpix** [comment]
Same error here too.

**Comment by pfrazee** [comment]
Investigating now, will try to replace the binary in <1 hour.

**Comment by pfrazee** [comment]
A new binary has been uploaded (https://github.com/beakerbrowser/beaker/releases/tag/0.8.9). I tested install from my Windows VM and the issue seems to be solved. Please let me know if it works for you!

**Comment by graphixillusion** [comment]
@pfrazee i confirm that with the new binary the program starts good.

**Comment by pfrazee** [comment]
Great, closing as fixed. Thanks for the quick report and sorry about the issue!

**Comment by johanbove** [comment]
Yes, confirming the issue is resolved thanks to the new binary. Thanks @pfrazee 👍
