### ISSUE TITLE
Welcome modal: "next" not working after activate the "Set Beaker as the default browser for dat:// URLs" switch

### ISSUE THREAD

**Issue by KBeDevel** [beakerbrowser/beaker#1522]
### Description
After activate the "Set Beaker as the default browser for dat:// URLs" switch, the "Next" button doesn't work. If the mentioned switch is off, the "Next" button works as intended. Off course, this a minor priority bug.

### Steps to reproduce:
1. Open the Beaker binary from a snap (stable channel) clean installation.
2. Activate the "Set Beaker as the default browser for dat:// URLs" switch.
3. Press the "Next" button

### Notes:
**Route**: beaker://start/

**Installation origin**: Snap package (Stable channel)

**GUI environment**: KWin TIling script

**Plasmashell & Kwin version**: 5.18.3

**Operating System**: Fedora Workstation 31 KDE Spin

**Beaker version**: 0.8.10 Electron: 8.1.1 - Chromium: 80.0.3987.141 - Node: 12.13.0

**Comment by pfrazee** [comment]
Thanks for filing and for the detail. We'll check into it!
