### ISSUE TITLE
Cant sync using the flatpak v0.8.10

### ISSUE THREAD

**Issue by danrobi11** [beakerbrowser/beaker#1525]
In order to be able to sync my website to hashbase I usually have to restart beaker for sync to work.
However, with the flatpak v.0.8.10 It doesnt work. Restarting beaker doesnt sync to hashbase. 
So theres no way to sync now with the flatpak v.0.8.10

**Comment by pfrazee** [comment]
One of the reasons we rebuilt the p2p stack with the new was because of connectivity issues like this. I may have to suggest waiting for the new release.
