### ISSUE TITLE
When updating Files from external storage, wipes the dat sites library

### ISSUE THREAD

**Issue by xDekpix** [beakerbrowser/beaker#1528]
howdy, encountered an odd problem id never seen before using beaker. It was kind of random so it beats me what exactly caused it. I'd been updating my site from a folder without problems since first using beaker and several days after the last update, but today while dragging from my folder to update things, it seemed to wipe the whole library of the site clean and I can no longer move files to it's library. I think it could also be relevant that I now store my files on a flash drive instead of my computer because of some storage issues and I wanted to backup the files, and have only been doing this the past couple of days. I have been updating it successfully for a few days since doing this, but it is something I've done different so it might be important. My whole site is currently wiped, and I am receiving an error that just says "uncaught error" when even trying to view the site history, as if every update in it's history had also been wiped.
![1](https://user-images.githubusercontent.com/36095003/77258954-65d91680-6c54-11ea-99fd-992ffa443246.png)
I'm not too hung up about it, I guess I'll just have to remake it from a different link if the current library wont let me make any changes anymore. but seemed kind of important to report anyway. thank you

Operation System: Win10

Beaker version:  v0.8.10

**Comment by xDekpix** [comment]
update: found another error when trying to edit the information of the site. not sure if this is helpful at all cuz im not very tech savvy
![1](https://user-images.githubusercontent.com/36095003/77259034-08919500-6c55-11ea-863e-da40f8385dc1.png)

**Comment by pfrazee** [comment]
Yeah yikes, thanks for reporting. That looks like some kind of data corrupting occurred for the dat. We might have to chalk that one up to gremlins because we're about to deploy a major rebuild of the protocol, so this bug may not apply anymore.

**Comment by xDekpix** [comment]
Okay! If it winds up happening again somehow after the new build, ill make sure to bring it up again, but hopefully this bugs already been squashed.

**Comment by pfrazee** [comment]
Thanks!
