### ISSUE TITLE
Error while reading the drive configuration

### ISSUE THREAD

**Issue by almereyda** [beakerbrowser/beaker#1532]
Operation System: Fedora 30
Beaker version: #1435 1677c5f9c58aee1aa1cab72ec3398f17d47c9371
Node: 10.15.3 (+ 12.16.1)
NPM: 6.9.0 (+ 6.14.3)

After successfully running `npm install` and `npm run rebuild`, `npm start` will throw the following error, next to #1531:

    Error while reading the drive configuration at /drives.json NotFoundError: File not found
    error:    Error while reading the drive configuration at /drives.json {"category":"filesystem","error":"NotFoundError: File not found"}

At this point it is not easy to guess how this can be avoided, or how `drives.json` can be put into place at `/`.

**Comment by pfrazee** [comment]
This is a little confusing, it's actually just debug info for me. Not an error. I'll remove it from the console output.

**Comment by pfrazee** [comment]
Removed from stderr
