### ISSUE TITLE
[blue-hyperdrive10] [a11y] Too low contrast in navigation bar status indicators

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1533]
Operation System:
Linux

Beaker version:
aa3bd12eb2e25e7c2c941ab7dc41385c1d63f0d2

There are a few different UI elements in the location bar that shows a light blue text against a blue background. The foreground–background contrast is [too low](https://webaim.org/resources/contrastchecker/).

**Comment by pfrazee** [comment]
Thanks for filing. I'll give it a contrast pass.

**Comment by pfrazee** [comment]
I've increased the contrasts. The blue on blue went from 2.73:1 to 3.85:1.
