### ISSUE TITLE
Is there any plan to support crx? 

### ISSUE THREAD

**Issue by 102286545** [beakerbrowser/beaker#1534]
If not, I suggest adding a translation function to the browser.

**Comment by pfrazee** [comment]
Sorry if I'm being thick, but what's CRX?

**Comment by frabrunelle** [comment]
I think he's referring to Chrome extensions.

**Comment by pfrazee** [comment]
Okay I'm going to close as a dup of https://github.com/beakerbrowser/beaker/issues/230

Extensions aren't off the table.
