### ISSUE TITLE
Address bar holds the focus when URL entered from address bar.

### ISSUE THREAD

**Issue by norzak** [beakerbrowser/beaker#1535]
Operation System:
MacOS 10.13.6
Beaker version:
0.8.10

When a page is opened directly typing to the address bar and pressing enter, focus remains on the address bar. The web page should get the focus instead.

**Comment by pfrazee** [comment]
Thanks for filing!

This is fixed in the upcoming release, so I'm going to close. Hope that's okay!

**Comment by norzak** [comment]
Thanks
