### ISSUE TITLE
[blue-hyperdrive10] Overflow issue in omnibar

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#1539]
Operation System: macOS 10.15.4
Beaker version: 0.9.0-prerelease.10

When a window is reduced to a small width (like a third of the screen) the text `My Hyperdrive` overflows underneath the browser chrome:

Wide:
<img width="361" alt="Screen Shot 2020-04-24 at 2 48 00 PM" src="https://user-images.githubusercontent.com/158590/80255926-1d3dc000-863b-11ea-9db0-125231453a64.png">

Narrow:
<img width="559" alt="Screen Shot 2020-04-24 at 2 47 54 PM" src="https://user-images.githubusercontent.com/158590/80255945-23cc3780-863b-11ea-8714-e3eccd14fa0b.png">

**Comment by pfrazee** [comment]
I actually just removed the "My Hyperdrive" badge because the site-info indicator shows the same info now, but I'm leaving open as a TODO to make sure overflow is right generally.

**Comment by pfrazee** [comment]
Okay fixed up
