### ISSUE TITLE
Hide System Drive Key in Network Stats

### ISSUE THREAD

**Issue by rzelnik** [beakerbrowser/beaker#1544]
I read somewhere in the documentation that System Drive doesn't have/show it's URL so that there is no reason to share it, because all users have the same URL: https://hyperdrive.network/system/. When I go to Settings > Network Stats, I see my System Drive as a first drive in the list, and it shows it's shortened URL. When I click to it, it opens the full URL of the System Drive (with hash). Is it safe for the user to have access to the full URL of his/her System Drive?

Operation System: Ubuntu Linux 20.04
Beaker version: compiled from source on Github

**Comment by pfrazee** [comment]
@rzelnik good catch. That should be masked there as well to prevent accidents.

It *is* possible to get the key via the file-explorer's tools, but users should definitely be conscious of what they're doing when they do it.

**Comment by pfrazee** [comment]
Okay done
