### ISSUE TITLE
Application Perms Controls

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#155]
- [x] Database for managing perms
- [ ] Browser-wide controls for permission defaults (settings page)
- [x] Per-site controls for controlling permissions (site-info navbar dropdown)
- [x] Per-site dat modification permissions (rules based)

---

Permissions that should be Browser-wide & Per-site:

 - [ ] Run Javascript (js)

Permissions that should be Per-site only:

 - [x] Use mic/camera (media)
 - [x] Desktop notifications (notifications)
 - [ ] Contact a specific host (network, parameterized)
 - [ ] Contact any host (network, *)

Permissions that should not persist, but be asked each time:
 
 - [x] Go fullscreen (fullscreen)
 - [x] Lock the pointer (pointerLock)
 - [x] Access midi devices (midiSysex)

The `geolocation` permission needs to be evaluated along with its entire API, because geolocation depends on Google Location Services.

---

To request network access, use the `navigator.permissions` API. This is for dat sites only. Network-access changes the site's CSP to enable the given hostname for `img-src`, `font-src`, `media-src`, and `connect-src`. It does not enable styles, scripts, or objects. The page must be refreshed for the policy-change to take effect.

```js
var res = await navigator.permissions.request({ name: 'network', hostname: 'github.com' })
res.status // => 'granted'

res = await navigator.permissions.query({ name: 'network', hostname: 'google.com' })
res.status // => 'blocked'

res = await navigator.permissions.revoke({ name: 'network', hostname: 'github.com' })
res.status => 'blocked'
```

Multiple hosts can be requested; subsequent requests add hosts, rather than replacing the current allowed hosts. A wildcard string ('*') can be used to request or revoke access to all hosts.

---

The Dat permissions will need to develop as we understand it better. For now, it will be rule-based: you can only modify a Dat that you have a 'save' claim for. At time of this writing, that's only possible for sites that create the dat, but it's planned to let other sites "open" a dat for writing, which will add a save claim.

**Comment by webdesserts** [comment]
It would be nice if there was a "permissions" section somewhere within the library view. I was about to create an issue requesting a "permissions page" in general, but then found this issue mentioning that you could already do this in the "network" icon dropdown. This is a bit unintuitive IMO as I would generally consider this a type of "setting", especially if we're drawing comparisons between the web and other platforms like iOS.

**Comment by webdesserts** [comment]
I think I've already mentioned this to you, but it would also be nice to eventually allow a user to disable "Network Access" (http) for a site and force that site to only work offline/p2p. Right now it seems like those line items are checked off, but I'm assuming this was prior to you rolling back the http restrictions for dat sites.

As a suggestion, perhaps it would be good to close this issue and break up the remaining items into smaller goals? This issue is aging a bit and is _mostly_ implemented from what I can tell.

**Comment by pfrazee** [comment]
I'm going to let this sit for a sec while we build the plan for applications, but I agree about wanting control over network access.

**Comment by lorenzos** [comment]
+1 for disabling HTTP(S) access. Not only for specific sites, it'd be great to also have a global option in the settings, so you can be sure the browser will not start any HTTP(S) request. 

This is useful for privacy, but also for checking that everything you are hosting is in fact on the P2P network. For example, I tried "porting" a simple static webpage into the Dat network, and I didn't see I was hosting the custom web font from Google Fonts via HTTPS...
