### ISSUE TITLE
Cannot access context menu in "Create New Hyperdrive" popup

### ISSUE THREAD

**Issue by metanomial** [beakerbrowser/beaker#1561]
**Description**
Right clicking on text in the "Create New Hyperdrive" popup does not open a context menu.

**To Reproduce**
1. Open menu.
2. Click "+ New Hyperdrive..."
3. Right click on text field.

**Expected behavior**
A context menu should drop down allowing copy/paste and spell check correction. Spell check does work in the popup, but the corrections are inaccessible.

 - OS: Windows 10
 - Version: 1.0.0-prerelease

**Comment by pfrazee** [comment]
Good call, we should fix this

**Comment by pfrazee** [comment]
Finally got this one fixed
