### ISSUE TITLE
Uncaught NotFoundError: File not found

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1562]
**Describe the bug**
Error while getting started having just install the beta, and 

**To Reproduce**
1. Start Beaker 1.0 Beta, for the first time,
2. Wait for initialization to complete, and then press 'Get Started'
3. Choose a picture, and enter display name. Then press 'Next'

**Expected behavior**

**Screenshots**
![Screenshot 2020-05-14 at 19 23 38](https://user-images.githubusercontent.com/1552489/81971357-daa74c00-9618-11ea-84b1-2e0e5c8640f9.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Beaker
 - Version 1.0 Beta

**Additional context**
I had the previous version of Beaker install, if that makes any difference...

**Comment by pfrazee** [comment]
Oof bummer. Discussing via IRC now.

**Comment by pfrazee** [comment]
Okay fixed this, turns out it was an issue created by @paul90 using an earlier build of the new release
