### ISSUE TITLE
User directory "Add to address book" button not present on MacOS

### ISSUE THREAD

**Issue by trevormeier** [beakerbrowser/beaker#1564]
When navigating to the User Directory in the macOS beta version of Beaker, users are listed but without the a "add to address book" button (which is mentioned in the User Guide).

**Comment by pfrazee** [comment]
Ah thanks for the issue, that's a bug in the docs. We'll update.

**Comment by pfrazee** [comment]
By the way, you can do this manually by going to the site and clicking the gray "site info" button on the left of the URL bar. There's an "add to address book" button there.

**Comment by pfrazee** [comment]
Fixed! Thanks again for reporting
