### ISSUE TITLE
fails to load images from a "big" hyperdrive

### ISSUE THREAD

**Issue by TBD** [beakerbrowser/beaker#1569]
**Describe the bug**
fails to load images from a hyperdrive (182MB in 381 files, mostly jpg)

**To Reproduce**
1. Go to hyperdrive page
2. press reload
3. images failed to load
4. general logs:

`Unhandled Rejection at: Promise [object Promise] reason: Error: Unexpected error: Error: Bandwidth exhausted`

**Expected behavior**
images should load quickly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser Beaker Browser
 - Version 1.0 beta

**Comment by pfrazee** [comment]
Thanks for filing. Something breaking in the gRPC connection to the daemon. We're looking into it.

**Comment by TBD** [comment]
👍 works OK with Beaker v1.0.0-prerelease.2 - no errors in the logs, images are loading.

**Comment by pfrazee** [comment]
That's great news! Reopen if you see this again!
