### ISSUE TITLE
Accessibility: webterm font in 1.0 beta  has weird shadowing making it hard to read.

### ISSUE THREAD

**Issue by matt1** [beakerbrowser/beaker#1570]
webterm font has weird shadowing making it hard to read - example seen on https://docs.beakerbrowser.com/advanced/webterm

I found this hard to read without having to squint and do weird things with my eyes and my vision is not even that extremely far away from 20-20 so others with worse eyesight might suffer more. From what I can tell, this was a deliberate thing to make it look like a CRT?

**Comment by pfrazee** [comment]
Yeah it's just a fun affect but if it's making things hard to read, I think we could give tools to disable it.

**Comment by cinnamon-bun** [comment]
The blue shadow makes my eyes think the text is out of focus, causing eyestrain.  The font is also quite small for me and can't be adjusted, so I pretty much can't use it except by copy-pasting the text into a text editor to read it.

Not to be too negative!  I'm excited to use it when I can adjust it to match the capabilities of my mortal meat body

**Comment by pfrazee** [comment]
Okay I’ll get some options in here

**Comment by pfrazee** [comment]
Decided to remove the shadow for now. Accessibility is more important than aesthetics in this case
