### ISSUE TITLE
Ability to set default zoom to be non-100% globally

### ISSUE THREAD

**Issue by nektro** [beakerbrowser/beaker#1572]
**Is your feature request related to a problem? Please describe.**
Running my computer at 4K, pages are extremely small at 100% zoom. However I do not set my computer's zoom at the changed size because I like taking advantage of the extra space for some programs. However for the browser it would be incredibly useful if I could set the zoom (as the default for app pages and origins) to be 150%, 200%, etc

**Describe the solution you'd like**
A zoom option in `beaker://settings/#general` that either is able to set the default zoom at a non-100% value, and/or have it be an independent modifier that would allow making 100% equivalent to 200% etc

**Describe alternatives you've considered**
Firefox has an `about:config` option to obtain a similar result named `layout.css.devPixelsPerPx`

**Comment by pfrazee** [comment]
I'll look into this. Shouldn't be too difficult.
