### ISSUE TITLE
Can’t host any more drives

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1575]
**To Reproduce**
1. Go to hyper://e36050c2651b2bd0bd265fc311c122122a5490bc11a17606201964246b69e4ef/
2. Click on the site badge
3. Click on Host this drive
4. Go to hyper://library/hosting

**Expected behavior**
To see the newly added drive in the hosting list.

**Actual behavior**
It’s not listed in the library.  I was able to add three drives but every drive since has failed silently.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Bro’: Beaker 1.0.0-pr1

**Additional context**
Restarting Beaker or indeed the device doesn’t restore the functionality.

**Comment by pfrazee** [comment]
Thanks for reporting. Was able to repro on that drive. Will look into it.

**Comment by pfrazee** [comment]
Turns out this particular issue was caused by the site not having a manifest file (index.json) and the codepath was choking on that
