### ISSUE TITLE
Can't load any hyperdrives

### ISSUE THREAD

**Issue by aadilayub** [beakerbrowser/beaker#1579]
**Describe the bug**
After installing Beaker and creating my profile, I can't load any hyperdrives. They just keep loading indefinitely. Initially, I thought the drives just didn't have any seeds, but I can't even access my own hyperdrives. 

**To Reproduce**
1. Install the new Beaker beta on Windows or Linux
2. Set up your profile
3. After some time (perhaps an hour), try to open your profile feed in Beaker.

**Screenshots**
Linux:
![image](https://user-images.githubusercontent.com/31581044/82041687-02062380-96c2-11ea-8108-772e1442b246.png)
Windows:
![image](https://user-images.githubusercontent.com/31581044/82042684-c0767800-96c3-11ea-8473-0142b807135b.png)

**Desktop (please complete the following information):**
 - OS: Windows, Ubuntu 20.04
 - Version: Beaker v1.0.0-prerelease.1

**Additional context**
This happened to me on both Linux and Windows. On Linux, I installed Beaker by building from source.

**Comment by aadilayub** [comment]
Possibly related: Webterm doesn't load 
![image](https://user-images.githubusercontent.com/31581044/82042989-4266a100-96c4-11ea-8a66-5935e05a1ab0.png)

**Comment by programmarchy** [comment]
@aadilayub I had something similar happen. When I went to beaker://settings/ it told me my daemon was disconnected (had a red error alert on the top of the page). Restarting Beaker resolved the issue for me, but guessing that's the state it's getting into -- communication with daemon is hung / crashed.

**Comment by aadilayub** [comment]
@programmarchy unfortunately restarting didn't seem to fix it for me. The Linux screenshot is just a few seconds after relaunch...

**Comment by pfrazee** [comment]
@aadilayub Do you get the "daemon not available" in your settings?

Is there any chance you ran an earlier version of beaker 1.0 in the past year, or are running a hyperdrive-daemon via the CLI?

**Comment by aadilayub** [comment]
> @aadilayub Do you get the "daemon not available" in your settings?

@pfrazee I did for a few seconds but that was yesterday and restarting the daemon fixed it (was able to access all my drives). When I took these screenshots there was no "daemon not available" error in the settings.

> Is there any chance you ran an earlier version of beaker 1.0 in the past year, or are running a hyperdrive-daemon via the CLI?

nope

**Comment by aadilayub** [comment]
okay i think @programmarchy was right. I restarted beaker on both linux and windows and that fixed things

**Comment by pfrazee** [comment]
Yeesh. Maybe some bugs with the daemon surfacing here.

**Comment by aadilayub** [comment]
Update: few minutes after restart, it's back to not loading drives. Strangely it isn't showing any daemon related errors in the terminal currently, but it did log a few when the browser was starting up:

```
aadil@x230:~/Applications/beaker/scripts$ npm start

> beakerbrowser@ start /home/aadil/Applications/beaker/scripts
> gulp start

[20:07:31] Using gulpfile ~/Applications/beaker/scripts/gulpfile.js
[20:07:31] Starting 'start'...
[20:07:31] Starting '<anonymous>'...
Spawning electron /home/aadil/Applications/beaker/scripts/node_modules/electron/dist/electron
info:     Logger started
info:     Initializing databases {"category":"browser","subcategory":"init"}
info:     Starting hyperdrive {"category":"browser","subcategory":"init"}
info:     Failed to connect to an external daemon. Launching the daemon... {"category":"hyper","subcategory":"daemon"}
info:     Starting daemon process, assuming process control {"category":"hyper","subcategory":"daemon"}
2020-05-15T20:07:58: PM2 log: Launching in no daemon mode
2020-05-15T20:07:58: PM2 error: (node:32604) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-05-15T20:07:58: PM2 error: (node:32604) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2020-05-15T20:07:58: PM2 log: App [hyperdrive:0] starting in -fork mode-
2020-05-15T20:07:58: PM2 log: App [hyperdrive:0] online
info:     Failed to connect to daemon, retrying {"category":"hyper","subcategory":"daemon"}
info:     Failed to connect to daemon, retrying {"category":"hyper","subcategory":"daemon"}
info:     Initialized dat daemon {"category":"hyper","subcategory":"drives"}
info:     Initializing hyperdrive filesystem {"category":"browser","subcategory":"init"}
info:     Loading root drive {"category":"hyper","subcategory":"filesystem","url":"hyper://6941fdd27bd31e00586875513ab8b3ec374de512a1d8bfc454646507417581e6/"}
info:     Initializing Web APIs {"category":"browser","subcategory":"init"}
info:     Initializing browser {"category":"browser","subcategory":"init"}
info:     Registering protocols {"category":"browser","subcategory":"init"}
info:     Running setup flow {"category":"browser","subcategory":"init"}
info:     Initializing window menu {"category":"browser","subcategory":"init"}
info:     Initializing context menus {"category":"browser","subcategory":"init"}
info:     Initializing tray icon {"category":"browser","subcategory":"init"}
info:     Initializing browser windows {"category":"browser","subcategory":"init"}
info:     Initializing downloads manager {"category":"browser","subcategory":"init"}
info:     Initializing permissions manager {"category":"browser","subcategory":"init"}
info:     Program setup complete {"category":"browser","subcategory":"init"}
info:     Hyperdrive daemon has been restored {"category":"hyper","subcategory":"daemon"}
info:     Destroyed browser window that attempted to navigate to https://beaker.dev/ {"category":"browser"}
2020-05-15T20:08:03: PM2 log: TypeError: Object has been destroyed
info:     Destroyed browser window that attempted to navigate to https://github.com/beakerbrowser/beaker/discussions {"category":"browser"}
2020-05-15T20:08:03: PM2 log: TypeError: Object has been destroyed
info:     Destroyed browser window that attempted to navigate to https://docs.beakerbrowser.com/ {"category":"browser"}
2020-05-15T20:08:03: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:05: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:05: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:05: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:27: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:27: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:48: PM2 log: TypeError: Object has been destroyed
2020-05-15T20:08:48: PM2 log: TypeError: Object has been destroyed
```

(The TypeErrors at the bottom are from #1585)

**Comment by pfrazee** [comment]
@aadilayub small thing but *might* be helpful, the `Destroyed browser window that attempted to navigate to` errors in the log were a bug that _should_ have been fixed before release, just want to check in that you're on latest master

**Comment by aadilayub** [comment]
Hmm it looks like I'm on the latest master
![image](https://user-images.githubusercontent.com/31581044/82069993-8fab3880-96ed-11ea-8600-30eb84b6ac07.png)

**Comment by pfrazee** [comment]
Okay must not have nailed that other bug yet.

**Comment by mafintosh** [comment]
This sounds a lot to me like the session mismatch bug that’ll be fixed in the next release

**Comment by aadilayub** [comment]
It’s likely that this is a duplicate of #1625, should I close?

**Comment by pfrazee** [comment]
@aadilayub are you able to load your _own_ drives now? That's what this issue is about, where as #1625 seems to be about loading other people's drives.

If you can load your own drives than this one can close as fixed.

**Comment by aadilayub** [comment]
Ah, yes. I can load my own drives.

**Comment by pfrazee** [comment]
Good deal
