### ISSUE TITLE
`[Object object]` in auto-updater section of settings

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1591]
Of course, of all things, the auto-updater is showing bugs. Need to see why `[Object object]` is showing in there.

**Comment by pfrazee** [comment]
Can't repro this anymore. Closing for now.

**Comment by todrobbins** [comment]
I'm seeing it this evening:

<img width="642" alt="Screen Shot 2020-05-18 at 10 11 34 PM" src="https://user-images.githubusercontent.com/158590/82283844-c33bcc00-9954-11ea-98bc-879166917293.png">

```

error | browser |   | Unhandled Rejection at: Promise [object Promise] reason: Error: net::ERR_FAILED | 2020-05-19T04:11:50.260Z
-- | -- | -- | -- | --
error | browser |   | [AUTO-UPDATE] error: Error: net::ERR_FAILED | 2020-05-19T04:11:50.260Z
info | browser |   | [AUTO-UPDATE] Checking for a new version. | 2020-05-19T04:11:50.259Z
```

**Comment by pfrazee** [comment]
That actually looks like correct behavior. Connection failed, maybe bad network or github downtime
