### ISSUE TITLE
Uncaught Error: The server does not implement this method

### ISSUE THREAD

**Issue by calm-rad** [beakerbrowser/beaker#1601]
**Describe the bug**
After creating my user drive, the editor says that I don't own this drive and doesn't bring up any files, and the files explorer gives a 'Uncaught Error: The server does not implement this method' message

**To Reproduce**
1. Downloaded the new beta release
2. Make profile
3. Click on profile in navigation bar
4. Click on "Editor"
5. Editor doesn't load and says I don't own the drive
6. Click on "Explore Files"
7. Displays the error message

**Expected behavior**
After creating a user drive, I can navigate to my profile drive, explore its files, and edit my site

**Screenshots**
<img width="806" alt="Screen Shot 2020-05-15 at 10 28 14 AM" src="https://user-images.githubusercontent.com/59620121/82121864-33ccc800-975e-11ea-941d-0ecf376deeec.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4
 - Beaker
 - 1.0.0 prerelease 1

**Additional context**
I suspect there's something left over in my system from either an old version of the daemon or from when I was building from Beaker's source before this version, since I can't seem to navigate to other hyperdrives either. I tried uninstalling the browser and deleting the beaker support files folder that's referenced in Beaker's settings, but that didn't seem to be enough

Are there any other steps or suggestions for how I can try installing the latest version with a clean slate?

PS. Congrats on launching! This is a huge deal and I'm very excited to use this!

**Comment by pfrazee** [comment]
@calm-rad is there any chance you're running an old `hyperdrive-daemon` outside of Beaker?

**Comment by calm-rad** [comment]
@pfrazee I haven’t installed the daemon outside of Beaker, but is there somewhere I could check in my system to see if there’s any old daemon-related stuff running or still installed?

**Comment by pfrazee** [comment]
@calm-rad hmm yeah try nuking Beaker's user data dir again, and then nuke ~/.hyperdrive

**Comment by calm-rad** [comment]
@pfrazee Nuking ~/.hyperdrive did the trick, thanks!
