### ISSUE TITLE
Screen resize of "edit window" unwanted sticky pointer

### ISSUE THREAD

**Issue by johanbove** [beakerbrowser/beaker#1602]
**Describe the bug**
While in "split screen" mode with editor / file browser left and the site right; when resizing the panels, the mouse gets stuck and does not release, so when the mouse is moved, the window resizing event is not released. The user has to click multiple on other parts of the UI to try to get the resizing to de-activate.

**To Reproduce**
1. Go to any site
2. Click on "Editor" or "Explore Files" or "Terminal"
3. Left-Click the panel separator and drag left or right.
4. Release the mouse left-click
5. Notice the mouse cursor is still stuck to the panel separator and move the mouse still resizes the panels.

**Expected behavior**
When I release the mouse from the panel separator, I expect no longer to be resizing the windows.

**Screenshots**
See screen-cast. (to be added)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Beaker Browser
 - Version: Beaker v1.0.0-prerelease.1

```
Electron: 9.0.0-beta.22
Chromium: 83.0.4103.34
Node: 12.14.1
Hyperdrive: 10.10.3
API: 0
Daemon: 1.13.6
Client: 1.14.5
Schema: 1.9.1
Fuse Native:
Fuse:
```

**Additional context**

**Comment by pfrazee** [comment]
Thanks for reporting, will look into it

**Comment by johanbove** [comment]
An update to the "sticky pointer" issue; the "stickyness" also happens when I resize the whole browser window and move to browser window around. Could this be an Electron issue?

**Comment by johanbove** [comment]
Since Release . 6 the way panels work has completely changed. In the new system it seems dragging to resize is not causing the pointer to stick. So this ticket can be closed.
