### ISSUE TITLE
Peers button show empty narrow dropdown when clicked, get stuck in pressed state

### ISSUE THREAD

**Issue by Foldover** [beakerbrowser/beaker#1605]
**Describe the bug**
Clicking on the `peers` button in the URL bar shows a narrow empty dropdown. Same happens for the button beside, a downward pointing arrow (not sure what the purpose of it is). This happens consistently. When they have been clicked they get stuck in a `pressed` state for the rest of Beaker's session. In the `General logs` an error is reported: `Unhandled Rejection at: Promise [object Promise] reason: TypeError: Error processing argument at index 0, conversion failure from`. The error is truncated I suppose.

**To Reproduce**
1. Go to 'Library -> My Drives'
2. Click on one of your drives
3. Click on the peers button, or the downward pointing arrow button at its right.
4. A narrow empty dropdown is shown and the button is then stuck in a `pressed` state for as long as Beaker is running (even in new tabs)

**Expected behavior**
A proper dropdown with options is shown, buttons do not get stuck in this `pressed` state

**Screenshots**
![image](https://user-images.githubusercontent.com/12360074/82124826-e96d3a80-97a1-11ea-8e8e-7ec114bb67e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Beaker
 - Version:  v1.0.0-prerelease.1

**Comment by pfrazee** [comment]
Thanks for filing, I'll check into this.

**Comment by pfrazee** [comment]
Okay I wasn't able to repro but I'm familiar with this error and I made some changes which should fix it. Please let me know if this happens again with 1.0.0-prerelease.2

**Comment by Foldover** [comment]
@pfrazee I can confirm the issue is fixed now!

**Comment by pfrazee** [comment]
Good deal! Thanks for confirming
