### ISSUE TITLE
Source of file not showing in editor

### ISSUE THREAD

**Issue by optimista** [beakerbrowser/beaker#1606]
**Describe the bug**
Even after multiple clicks on the file on the sidebar of editor and also using the 'Open' dialog, can't access the source of the file. It remains like [this](https://ibb.co/0fbzzT8). This happens only when editing files on my own or someone else's hyperdrive, e.g. accessing settings works nicely [here](https://ibb.co/Tw0Z3Vf).

**To Reproduce**
1. Go to your profile page
2. Click on editor
3. Select the file or open it via 'Open' dialog
4. See that the file is never opened to be edited

**Expected behavior**
To see the source of the file in editing panel.

**Screenshots**
[Not working in hyperdrive](https://ibb.co/0fbzzT8)
[Working on e.g. settings](https://ibb.co/Tw0Z3Vf).

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Beaker 
 - Version: 1.0.0-prerelease.1

**Additional context**
Intuition is telling me that it has to do with permissions, but that's just intuition.

**Comment by pfrazee** [comment]
Yeah were' having some issues with linux. If you're using the .AppImage, this is a dup of https://github.com/beakerbrowser/beaker/issues/1568.
