### ISSUE TITLE
Is there a way to have bookmarks open in new tab ?

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#162]
Operation System:MacOS
Beaker Version:Latest Master 

I'am trying to find a way to have bookmarks open in new tabs in test build
Would I add 'popup:true' to the below 

INSERT INTO bookmarks (title, url) VALUES ('Beaker Browser Homepage', 'https://beakerbrowser.com');

Thanks

**Comment by pfrazee** [comment]
Why do you want this? You can open in a new tab with a middle click, or cmd+click.
