### ISSUE TITLE
Can't open 1.0.0-prerelease.1 on Windows 10 Pro Insiders

### ISSUE THREAD

**Issue by bltavares** [beakerbrowser/beaker#1622]
**Describe the bug**
After installing the new release, opening Beaker Browser shows a loading indicator, then nothing.

It is crashing loading Electron, and I have not yet found the root cause.

**To Reproduce**
1. Install Beaker Browser
2. Try to open it

**Expected behavior**
The Browser should open.

**Screenshots**

**Desktop (please complete the following information):**
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19628 N/A Build 19628 (Insiders)
```

**Additional context**
I've tested this on 3 Windows systems, and 2 out of 3 showed the same behaviour.

Similarities between crashing systems:

- Both Windows 10 Pro
- Both on Windows Insiders Fast Track
- Both with NVidia video cards
- Both with WSL2/hyper-v/VS 2019 build tools installed

Differences to the one that is working by default:
- Windows Home
- Stable release, but up-to-date
- No extra videocard
- No developer tools installed

---

[Crash log](https://gist.github.com/bltavares/546b63aa3ca4f596842eb714a993c3c3) when running with [Dependency Walker](http://dependencywalker.com/) and [WinDBG](https://www.microsoft.com/pt-br/p/windbg-preview/9pgjgd53tn86).

---

It is not possible to start Electron when running `npm start` if building from source either.
Trying to open Electron.exe from `node_modules/electrong/dist/electron.exe` cause the same error.

---

Error message shows up when running the executable from `Git Bash Shell`:
![image](https://user-images.githubusercontent.com/109474/82223632-462f3900-98f9-11ea-9134-cd7b82d66c7f.png)

```sh
"./Beaker Browser.exe"
GetModuleHandleA: (126) The specified module could not be found.
```
---

Tested building from source with Electron `9.0.0-beta.22` and the current `9.0.0-beta.24`.

---

**Workaround found:**
- Go to `%LocalAppData%\Programs\beaker-browser` folder
- Right-click on `Beaker Browser.exe` -> Properties -> Compatibility
- Select `Windows 8 Compatibility mode`
- Beaker now opens

---

It would be nice if someone using Windows Pro and NVidia cards could test and see if it works, to validate if that is an Insiders error, and a Windows Pro without videocard to test if that is an NVidia error.

**Comment by pmario** [comment]
>It would be nice if someone using Windows Pro and NVidia cards could test and see if it works, to validate if that is an Insiders error, and a Windows Pro without videocard to test if that is an NVidia error.

I use Windows 10 PRO "stable track" and NVida card. No problems to instal and start the prerelease.1

**Comment by bltavares** [comment]
That is great then! I could close the issue as this could be something online on Insiders, like a bad kernel release. At least the workaround is documented if it happens again.

I hope a new update on Windows fixes the issue, and that it is not a preview of a future crash hehe
