### ISSUE TITLE
Can't access hyperdrives with seeds

### ISSUE THREAD

**Issue by aadilayub** [beakerbrowser/beaker#1625]
**Describe the bug**
I can't access any of the hyperdrives in the userlist, even the ones with many seeds.

Here is me attempting to navigate to [andrewosh's hyperdrive](hyper://560b8363ec54434397ffdc50d894d37786204b6154db772418440df38386eeea/) (it has 18 seeds according to the userlist)

![image](https://user-images.githubusercontent.com/31581044/82237342-e9f70400-994e-11ea-93e1-0a1e8561abfd.png)

**To Reproduce**
1. Install beaker on Linux or Windows
2. Go to the userlist
3. Try to visit any of the public profiles with seeds

**Expected behavior**
I navigate to the userlist. All public profiles with seeds are accessible and don't give the "Hyperdrive not found" error.

**Desktop:**
 - OS: Ubuntu 20.04
 - Version: 1.0.0-prerelease.1

**Additional context**
I installed beaker from source (up to date with the latest commit on master)

**Comment by pfrazee** [comment]
@aadilayub When this happens, have you tried refreshing a couple times over a period of ~30 seconds? I've been running into a situation where this occurs because it seems like the `hyper://` loader is giving up a little too quickly

**Comment by pfrazee** [comment]
cc @andrewosh

**Comment by todrobbins** [comment]
@aadilayub it looks like you might not be hole-punched since the amber dot appears on your `Network Status` icon.

Could you send a screen grab of your network status?

**Comment by aadilayub** [comment]
![image](https://user-images.githubusercontent.com/31581044/82286398-1181b700-99b7-11ea-817a-683798cf2b77.png)

@andrewosh yes it's not hole-punchable! It's like that on both devices I've installed beaker on.

**Comment by todrobbins** [comment]
Interesting! Not hole-punchable, but you have an IP address. When I'm on my work VPN I see something similar (non-hole-punchable, but no IP address).

**Comment by aadilayub** [comment]
@todrobbins yeah, I posted about this on ssb as well and a user recommended I check my router's firewall configuration. I don't think it's my router though since I get this while connected to my phone's wifi hotspot as well...

**Comment by aadilayub** [comment]
![image](https://user-images.githubusercontent.com/31581044/82681018-ff478900-9c01-11ea-9242-62f9790ee218.png)

So I hackintoshed my laptop today, and went to try out Beaker. Surprisingly, this bug is still there. I'm pretty perplexed at this point. This rules out, as a source of the bug:

- [x] My OS (This bug is present across Windows, Linux, and MacOs)
- [x] My hardware (I've experienced this bug on two laptops)
- [x] My router (This bug is there when I connect to my phone's hotspot as well as my home wifi)
- [x] Interference caused by previous versions of beaker (I've experienced this bug on fresh OS installs)
- [x] My laptop's wifi card (bug is there even when I use a usb wifi adapter)

At this point this leaves:

- [ ] my ISP?

**Comment by pfrazee** [comment]
Yeah at this point I figure it's either your ISP or issues that arise with both your router and hotspot. @mafintosh or @andrewosh, this may be a useful case for yall to dig into, since this looks like a novel connectivity situation

**Comment by mafintosh** [comment]
Are you using any kind of vpn?

If you are up for it, mb you want to join the discord, chat.hypercore-protocol.org and we can do some more realtime debugging

**Comment by aadilayub** [comment]
> Are you using any kind of vpn?
Not using a vpn of any kind.

> If you are up for it, mb you want to join the discord, chat.hypercore-protocol.org and we can do some more realtime debugging
That would be great! I just joined.

**Comment by aadilayub** [comment]
Tested this on Windows and macOS today, and the amber dot is gone. I'm able to load other people's hyperdrives!
 
![image](https://user-images.githubusercontent.com/31581044/82800223-c3782200-9e94-11ea-81d0-4cfeddf293f1.png)

I can't test this on Linux, since I wiped my Linux partition, but I'm assuming this is fixed across OSes.
