### ISSUE TITLE
Ability to cmd/ctrl+click or right click on Beaker menu bar items

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#1626]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
It would be great if I could cmd+click or right click and open in a new tab/copy URL for these:

<img width="261" alt="Screen Shot 2020-05-18 at 10 48 22 AM" src="https://user-images.githubusercontent.com/158590/82238842-2564e480-98f5-11ea-9b97-6b06b4b55aba.png">

<img width="269" alt="Screen Shot 2020-05-18 at 10 43 25 AM" src="https://user-images.githubusercontent.com/158590/82238790-11b97e00-98f5-11ea-8394-c269d3a351cf.png">

**Comment by todrobbins** [comment]
I'm going to take a stab at this. 👍🏻

**Comment by pfrazee** [comment]
Great!

**Comment by pfrazee** [comment]
Hey @todrobbins you still going to hit this?

**Comment by pfrazee** [comment]
(I can if not)

**Comment by todrobbins** [comment]
Go ahead. My weekend filled up 😆
