### ISSUE TITLE
Host This Drive resets every time I click it

### ISSUE THREAD

**Issue by mafintosh** [beakerbrowser/beaker#1627]
![ezgif-4-873e1d7a9be0](https://user-images.githubusercontent.com/376661/82242103-962fef00-993d-11ea-82a5-e3e00f80ee76.gif)

**Comment by pfrazee** [comment]
Dup of https://github.com/beakerbrowser/beaker/issues/1575

**Comment by mafintosh** [comment]
I should win coolest gif tho right?

**Comment by pfrazee** [comment]
haha sure
