### ISSUE TITLE
[Detail] Beaker icon on Mac OS Dark Menu Bar appears invisible

### ISSUE THREAD

**Issue by bltavares** [beakerbrowser/beaker#1629]
**Is your feature request related to a problem? Please describe.**
I've notice that the icon on the Menu Bar appears hidden, and I only noticed because there was a gap between icons.

<img width="74" alt="Screen Shot 2020-05-18 at 4 16 28 PM" src="https://user-images.githubusercontent.com/109474/82251081-f7969480-9922-11ea-96be-4a2eceef847d.png">
<img width="82" alt="Screen Shot 2020-05-18 at 4 16 33 PM" src="https://user-images.githubusercontent.com/109474/82251083-f82f2b00-9922-11ea-94b8-b131a45fdf68.png">

It's a minor detail, but easy to leave Beaker open on metered connections if there are no gap on icons, if beaker was opened last.

<img width="59" alt="Screen Shot 2020-05-18 at 4 12 28 PM" src="https://user-images.githubusercontent.com/109474/82251195-24e34280-9923-11ea-9b43-079da78b6f6d.png">
<img width="66" alt="Screen Shot 2020-05-18 at 4 12 32 PM" src="https://user-images.githubusercontent.com/109474/82251198-26146f80-9923-11ea-93bb-aba4d844ab0e.png">

**Describe the solution you'd like**
Make the icon white if the Menu Bar is on Dark Mode.

**Comment by pfrazee** [comment]
Thank for filing, I'll hit this soon

**Comment by da2x** [comment]
macOS expects a vector PDF icon for legacy reasons. The OS will handle theming and such on its own given a proper icon.
