### ISSUE TITLE
Editor does not work in Linux

### ISSUE THREAD

**Issue by thecherrybomb** [beakerbrowser/beaker#1632]
**Describe the bug**
Editor window does not show source code. The file loads in the main window (index.html, or index.json, for example).
I do see it flash "loading" at the top, but no source code loads.
On "beaker://desktop/" and "https://docs.beakerbrowser.com/", the source code loads in the editor, but it says the site is read only.
I have tried creating a new index.html in a new Hyperdrive, and met the same result.
Also, the index.json shows script in the main window, but not in the editor window

**To Reproduce**
1. Open Beaker browser.
2. Click on my profile
3. Open editor (or right click and select "edit source")

**Expected behavior**
Should see source code for my profile (or any html file I create) in the editor window, but it doesn't show up.

 - OS: Linux Mint 19.1
 - Browser: Beaker.Browser-1.0.0-prerelease.1.AppImage

**Comment by aadilayub** [comment]
probably related https://github.com/beakerbrowser/beaker/issues/1585

**Comment by pfrazee** [comment]
Yeah see https://github.com/beakerbrowser/beaker/issues/1568#issuecomment-630421690 for a fix
