### ISSUE TITLE
Cannot create or edit any files on my hyperdrive on Linux

### ISSUE THREAD

**Issue by despens** [beakerbrowser/beaker#1633]
**Describe the bug**
Cannot create or edit any files on my hyperdrive on Linux

**To Reproduce**
1. Create a new drive
2. Go to that drive
3. Click ![Editor](https://user-images.githubusercontent.com/571494/82291286-02940800-99a9-11ea-8333-b90ce94f6245.png)
4. Click ![Open...](https://user-images.githubusercontent.com/571494/82291335-163f6e80-99a9-11ea-8cc3-a18cc43652cf.png)
5. Pick `index.md` or `index.json`
6. Editor pane remains empty ![Empty editor pane](https://user-images.githubusercontent.com/571494/82291449-438c1c80-99a9-11ea-82bc-3cd318f6efa5.png)

**Expected behavior**
The editor should load, display, and edit files.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Beaker 
 - Version: 1.0.0-prerelease.1 (AppImage)

**Additional context**
Hyperdrive mount seems to be operational

**Comment by pfrazee** [comment]
Thank you for filing! Known issue, see https://github.com/beakerbrowser/beaker/issues/1568#issuecomment-630421690 for the temporary fix
