### ISSUE TITLE
Cannot play video files

### ISSUE THREAD

**Issue by freddi301** [beakerbrowser/beaker#1635]
**To Reproduce**
1. Create new drive and add a file
2. Share it (i tested on LAN)
3. Open the file on the other side
4. Video does not even load (0 bytes in network panel) (tested with 80mb .m4v)

**Expected behavior**
See the video

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Beaker
 - Version 1 beta

**Comment by pfrazee** [comment]
Thanks for filing but please check for existing issues first! This is a known issue: https://github.com/beakerbrowser/beaker/issues/1560
