### ISSUE TITLE
Beaker becomes unresponsive when editing text files while files list is open

### ISSUE THREAD

**Issue by cryptowyrm** [beakerbrowser/beaker#1636]
**Describe the bug**
After making and saving a few changes to a text file using Beaker's built-in editor while the files list sidebar is open, the whole Beaker Browser becomes unusably slow, CPU usage goes up, sometimes the GPU usage spikes. Most of the time closing the editor makes the issue go away again. Sometimes Beaker becomes so unresponsive that only a restart helps.

**To Reproduce**
1. Open Beaker's built-in file editor on a hyperdrive
2. Open the file listing sidebar of the editor using the three dots button
2. Make edits to a text file and save those edits a few times

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Beaker Browser 1.0.0-prerelease.1

**Additional context**
I'm able to reliably reproduce this on two laptops with Windows 10, even with a fresh Beaker install. Happens every time when I save with the files list open in the editor, every save seems to take a little longer than the last and makes Beaker exponentially slower (typing, scrolling, etc.) until after about 5 or more saves the UI becomes barely responsive, even moving the window turns into a slideshow. I have not seen it happen when the files list is closed. Detaching the editor to show it in its own window does not seem to make a difference. Couldn't find anything interesting in the logs or PowerShell when starting Beaker from the command line.

**Comment by pfrazee** [comment]
That sounds very much like a folder-watcher is getting turned on every save without deconstructing the previous one. I'll check into it.

**Comment by pfrazee** [comment]
I _think_ this should be fixed in prerelease.2. LMK with that release if you still see this.

**Comment by cryptowyrm** [comment]
@pfrazee It' seems to be fixed in prerelease.2, tried editing for half an hour and never saw the issue again. Thanks for the quick fix!
