### ISSUE TITLE
In HTML files: no javascript syntax highlighting for module scripts

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1637]
**Describe the bug**
In HTML files, syntax highlighting for javascript is gone when adding `type="module"` to the script tag.

**To Reproduce**
1. Create a new html file in any hyperdrive.
2. Add `<script>if (true) {console.log('hi')}('hi')</script>` somewhere in the file.
3. You'll see there's syntax highlighting for the javascript.
4. Add `type="module"`. I.e., edit the code to be `<script type="module">if (true) {console.log('hi')}</script>`.
5. Syntax highlighting for the javascript is gone.

**Expected behavior**
For the javascript syntax highlighting to work for `module` scripts.

**Screenshots**
Javascript syntax highlighting working in non-`module` scripts: (no problem here)
![image](https://user-images.githubusercontent.com/6719916/82394336-0c6d4800-9a49-11ea-85f1-7628c3555a8b.png)

Javascript syntax highlighting not working in `module` scripts:
![image](https://user-images.githubusercontent.com/6719916/82394387-2c9d0700-9a49-11ea-942e-7945473c5ed3.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Beaker Browser
 - Version: v1.0.0-prerelease.1

**Additional context**
None.

**Comment by pfrazee** [comment]
May be fixable by updating our version of Monaco. I'll check into it.

**Comment by pfrazee** [comment]
It took some fancy maneuvering (aka literally anything with Monaco) but I got this one!
