### ISSUE TITLE
Zoom using scroll + mouse/scroll wheel

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1638]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
To be able to zoom in and out using ctrl + mouse/scroll wheel.

**Describe alternatives you've considered**
I can already zoom in and out with ctrl + +/-.

**Additional context**
OS: Windows 10.

**Comment by pfrazee** [comment]
Added to roadmap

**Comment by pfrazee** [comment]
The simplest way to do this is via the new Electron API which only works on windows atm (https://github.com/electron/electron/pull/17747). Still needs testing but should work.
