### ISSUE TITLE
Hyperdrive with mounted frontend has stopped working.

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1639]
**Describe the bug**

Was trying out using a mounted frontend - using hypercore-daemon to import both the client code using in the frontend, and the drive it is mounted into. Got this to a state it was working.

Sometime later, trying to access the Hyperdrive with the mounted frontend nothing appears to happen. The only error I see in beaker's log is:
`{"category":"browser","message":"Unhandled Rejection at: Promise [object Promise] reason: NotFoundError: File not found","level":"error","timestamp":"2020-05-20T13:09:02.149Z"}`

**To Reproduce**
Really not sure how to reproduce...

**Expected behavior**
I expect the hyperdrive to load, and the mounted frontend to display.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Beaker 
 - Version: v1.0.0-prerelease.1

 - Hyperdrive Daemon @ 1.13.9

**Additional context**
Both the hyperdrive used as the mounted frontend, and the hyperdrive it is being mounted in are unseeded.

**Comment by pfrazee** [comment]
Okay a couple questions

 1. Wy frontend are you saying it was mounted to `/.ui` ?
 2. What happens when you access the mounted hyperdrive separately?
 3. Anything in the devtools for the page indicate what file is failing to load, or does the entire site fail to load?

**Comment by paul90** [comment]
1. Yes, mounted to `/.ui`
2. It loads, and runs as expected - displaying the wiki that it contains alongside the client.
3. As far as I can see the entire site fails to load, the devtools page remains empty unless I tab out of Beaker and back in. Then I am getting these three errors.
![Screenshot 2020-05-20 at 16 24 13](https://user-images.githubusercontent.com/1552489/82464755-5a6c6500-9ab6-11ea-80a6-f05ff82c3f45.png)
The three no-error lines there are also present when tabbing back to Beaker when the homepage is showing - so are probably not related.

**Comment by pfrazee** [comment]
@paul90 Okay interesting, those devtools errors are in the "start page" UI

Is there any chance any of your drives dont have an index.json? If so, does adding one solve this?

**Comment by paul90** [comment]
As far as I can see all my drives by an `index.json`. But, it is possible that I might has removed a drive from Beaker that didn't have one, but no idea where I'd find those...

**Comment by paul90** [comment]
Scrub that, just found a drive without an `index.json` - thought I created one. But, I was going to find another way of doing what I wanted as there is currently no ignore, and it contains a collections of plugins that in there own git repos, and all have node_modules.

Probably a silly question, and really should be asked elsewhere, but how do I delete a drive created with `hyperdrive import`?

**Comment by pfrazee** [comment]
> Probably a silly question, and really should be asked elsewhere, but how do I delete a drive created with hyperdrive import?

Beaker currently tracks your "library" of drives - those are the ones that show up in the start page "drives" tab and in the "hosting" tab of the library. Eventually we'll put in a system for GCing drives in the daemon's storage which aren't in that listing, but we haven't gotten to that yet, so they're not clearable yet.

**Comment by pfrazee** [comment]
@paul90 we're about to release prerelease.2. See if this issue persists there and lmk

**Comment by paul90** [comment]
Will do, thanks Paul.

**Comment by paul90** [comment]
> Beaker currently tracks your "library" of drives - those are the ones that show up in the start page "drives" tab and in the "hosting" tab of the library.

Interesting... the drives I've created using the `hyperdrive` command line don't appear in either of those places (3 created with `hyperdrive import`, and 1 with `hyperdrive create`).

**Comment by pfrazee** [comment]
Yeah it wouldnt. The daemon doesnt interact with beaker's library

**Comment by paul90** [comment]
Umm, sadly prerelease.2 doesn't fix - I am now also getting a 404 with `beaker://debug-log/`, and `beaker://hyper-dns-cache/` - with the javascript behind the 'Try Again' button getting blocked by CSP.

Trying to access the failing drive, I am getting a more detailed error in `beaker.log`
```
{"category":"hyper","subcategory":"daemon","message":"Opening drive-session bace..17","level":"debug","timestamp":"2020-05-21T06:57:34.056Z"}
{"category":"browser","message":"Unhandled Rejection at: Promise [object Promise] reason: NotFoundError: File not found NotFoundError: File not found\n    at toBeakerError (/Applications/Beaker Browser.app/Contents/Resources/app/node_modules/pauls-dat-api2/lib/common.js:20:12)\n    at /Applications/Beaker Browser.app/Contents/Resources/app/node_modules/pauls-dat-api2/lib/read.js:23:25\n    at /Applications/Beaker Browser.app/Contents/Resources/app/node_modules/call-me-maybe/index.js:13:28\n    at processTicksAndRejections (internal/process/task_queues.js:76:11)","level":"error","timestamp":"2020-05-21T06:57:49.478Z"}
```

**Comment by paul90** [comment]
Thing I might have found the problem.

Using the hyperdrive daemon I can access the problem drive, and `cd .ui`, but `ls` is showing everything in the mounted drive as being a directory!

**Comment by paul90** [comment]
Have tried using the beaker.hyperdrive API to unmount `.ui` - but that is just giving me `Uncaught Error: Uncaught NotFoundError: File not found`.

At this stage I'm wondering if it wouldn't be best to completely remove hyperdrive-daemon and beaker - and start from scratch - as long as there is nothing useful that can be extracted to help prevent other from getting the same problems.

If that is going to be the best route forward, what is the correct process for completely remove hyperdrive-daemon and beaker? Everything I've been working on is safely saved away in Git, and archived, so the only thing I would loose is my Beaker profile drive.

**Comment by paul90** [comment]
I have decided, in the interest of making some progress, to start again - rather than delete, I have moved the hyperdrive daemon and beaker files to one side just in case...

**Comment by pfrazee** [comment]
@paul90 is there any chance you were running an older hyperdrive-daemon? I'm just not sure why Beaker and a separate daemon that you start would be struggling to interact correctly.

**Comment by paul90** [comment]
@pfrazee I doubt that is it - I installed hyperdrive-daemon at the same time as installing the Beaker pre-release 1, I also updated the daemon to 1.13.12 at the same time as getting pre-release 2.

I had managed to recreate this problem earlier today - just using the browser and two drives. One with a `ui.html` and mounting it as `/.ui` in the other drive - with the hyperdrive daemon going to 98%CPU. I didn't see any error messages in either Beaker's or the daemon's logs when this happened. But, looking at those drive again just now, and they are behaving themselves...

All very confusing...

**Comment by pfrazee** [comment]
Very strange...

When you visit the hyperdrive that's acting up, there's a "site info" button on the left of the URL. It's gray for drives you don't own (and which arent in your addressbook) and blue for sites that you do own. Are either of the drives you created showing up gray?

**Comment by pfrazee** [comment]
Also, with the mounts, is there any chance you might have accidentally mounted the drives to themselves or created a recursive mount (where each mounts the other)?

**Comment by paul90** [comment]
The "site info" is blue.

They are not mounted to themselves, or a recursive mount.

Just had the CPU spike again getting this screenshot, but quitting Beaker and restarting it is behaving...

![Screenshot 2020-05-23 at 20 00 31](https://user-images.githubusercontent.com/1552489/82738529-1ab0b200-9d30-11ea-8037-a51a962a1903.png)

**Comment by pfrazee** [comment]
Okay I think that's all the information I could possibly ask for. I'm going to run a few tests next week to see if I can repro any of this.

**Comment by paul90** [comment]
Thank you Paul.

**Comment by paul90** [comment]
@pfrazee - Did your testing uncover anything? I've just tried again and all appears to be working as expected. So, I'm going to close this issue.

**Comment by pfrazee** [comment]
@paul90 not that I can think of. Weird one. Let me know if it shows again
