### ISSUE TITLE
"My Drives" and "Hosting" will not load

### ISSUE THREAD

**Issue by metanomial** [beakerbrowser/beaker#1644]
**Describe the bug**
At seemingly random times, the "My Drives" and "Hosting" tabs in "My Library" will fail to load, throwing the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'localeCompare' of null
    at drives.js:61
    at Array.sort (<anonymous>)
    at HTMLElement.load (drives.js:61)
```

**To Reproduce**
Unknown

**Environment**
 - OS: Windows 10
 - Version 1.0 Beta 2

**Comment by metanomial** [comment]
Okay, I think I've tracked down what's going on.

I opened a hyperdrive that was unavailable. Perhaps relevant, there was another peer that also did not have any files. I toggled "Host This Drive" hoping that the contents would become available while I was AFK.

When listed using `beaker.drives.list`, the unavailable hyperdrive in question has several bad values in it's `.info` object, including a `title: null` which causes the above error when the `.localeCompare` method gets called on what _should_ always be a string.

**Comment by metanomial** [comment]
Ah ha! I found a live hyperdrive that causes the bug, and might be reproducible on other clients. When hosting `hyper://e219fb97612d4a2b6bee1f5374becbd66de0217c8b831ddbd2cfa66621a9868f/`, `info.title` is null. I thought it might be related to the fact that there is no `index.json` file, but on investigation I am hosting other drives without an `index.json` file.

This bug persists through a full restart of Beaker.

**Comment by pfrazee** [comment]
Yep I can repro. Thanks for filing, I'll check into it.

**Comment by da2x** [comment]
It stopped working for me after I added the drive from issue #1575 (the one without a manifest).
