### ISSUE TITLE
Using the beforeunload event causes an error

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#1645]
**Describe the bug**
I have a page with a 'beforeunload' event handler on the body, which should nag the user before leaving the page. Reloading the page should be allowed after clicking 'leave' on the dialog. After clicking 'leave', the page does not reload.

An entry in beaker://settings/?view=general-logs appears:
Uncaught exception: ReferenceError: response is not defined	

**To Reproduce**
1. Add the following HTML file:
```
<!doctype html>
<html>
<body>
  Reload me!
  <script>
    function handleBeforeUnload(evt) {
      var message = "You have made changes to this page, if you leave these changes will not be saved.";
      evt = evt || window.event;
      // For IE and Firefox prior to version 4
      if (evt) {
        evt.returnValue = message;
      }
      // For Safari
      return message;
    }

    document.body.onbeforeunload = handleBeforeUnload;
  </script>
<script>
document.write(new Date().getTime());
</script>
</body>
</html>
```
2. Browse to the file, click on 'reload'
3. Click on the 'leave' button in the popup
4. page does not reload.

**Expected behavior**
Expected the page to reload after clicking 'leave'.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Beaker 
 - Version 1.0 beta-2

**Comment by pfrazee** [comment]
Wow you are finding bugs left and right. Thank you again, on my todo list.

**Comment by da2x** [comment]
Aside: You shouldn’t use `unload` or `beforeunload`.  They causes a few different issues and don’t work reliably in all browsers. [Use `pagehide` instead](https://www.ctrl.blog/entry/safari-beacon-issues.html).

**Comment by ylebre** [comment]
Thanks for the tip, I was not aware of that event so I learned something today!

I did a quick experiment, but as far as I can see the pagehide event does not allow me to interact with the user ("save changes before leaving?") the same way beforeunload does, allowing the user to cancel the navigation away to prevent them from losing unsaved work.

It has been a while since I've thoroughly checked browser support, but as far as I remember all of the browsers I care about will at least pop up a dialog to ask the user if they are ready to leave, which I haven't been able to achieve with pagehide. If I'm missing something there please let me know :)

**Comment by pfrazee** [comment]
@ylebre Your usecase of asking before leaving should still be supported. This was working previously so I must have just broken it at some point recently.

**Comment by da2x** [comment]
> allowing the user to cancel the navigation away to prevent them from losing unsaved work.

No, it doesn’t. But it enables you to automatically save the draft of unsubmitted work to localStorage. That way the user can come back later and continue their work later.
