### ISSUE TITLE
shift-reload with cache disabled in the network tab gives an error

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#1646]
**Describe the bug**
shift-reload with cache disabled in the network tab gives an error

**To Reproduce**
1. inspect element, go to the network tab
2. enable the 'disable cache' checkbox
3. shift-reload the page

Gives an entry in beaker://settings/?view=general-logs
Uncaught exception: TypeError: hyper.dns.flushCache is not a function

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Beaker
 - Version 1.0 beta 2

**Comment by pfrazee** [comment]
Thank you for filing! I'll get on this.
