### ISSUE TITLE
Editor pane is droppable

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#1647]
**Describe the bug**
Dropping a link on the editor pane will load that page.

**To Reproduce**
1. Open the file editor
2. drag-drop a link to that pane
3. See that it loads the link, giving a split-screen browser which is cool but unexpected

**Expected behavior**
I expected the file to be added to the hyperdrive, or not do anything at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/10849937/82543392-c2bd5400-9b53-11ea-832a-a4d9baca2b72.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Beaker
 - Version 1.0 beta 2

**Comment by pfrazee** [comment]
Oooh yikes, thank you very much for reporting. We'll fix this.
