### ISSUE TITLE
Start / shutdown issue

### ISSUE THREAD

**Issue by danrobi11** [beakerbrowser/beaker#1650]
- I started beaker instance (a), closed instance (a) from the terminal(ctrl+c) (Instance (a) still run in background, me I do not know that)
- I started another beaker instance (b), edited my website and tried to save modification. beaker wouldnt render the site, pressing reload was just hanging.
- Thats how I figured there was a problem. I killed both beaker instance (a,b)
- Now, launching beaker gives me this:

```
This may take a moment
Logger started [info]
Welcome to Beaker [info]
Initializing databases [info]
Starting hyperdrive [info]
Second instance opened [info]
Attempted to create a shell window prior to setup [error]

error:    Attempted to create a shell window prior to setup {"category":"browser","stack":"Error\n    at createShellWindow (/tmp/.mount_BeakertSV9Ls/resources/app/main.build.js:8801:82)\n    at ensureOneWindowExists (/tmp/.mount_BeakertSV9Ls/resources/app/main.build.js:9009:5)\n    at App.<anonymous> (/tmp/.mount_BeakertSV9Ls/resources/app/main.build.js:16537:5)\n    at App.emit (events.js:223:5)\n    at App.EventEmitter.emit (domain.js:475:20)\n    at App.topLevelDomainCallback (domain.js:130:23)"}
info:     Second instance opened {"category":"browser","subcategory":"init","argv":["/tmp/.mount_BeakertSV9Ls/beaker-browser","/tmp/.mount_BeakertSV9Ls/resources/app/node_modules/pm2/lib/Daemon.js"]}
```
Shuttingdown beaker gives me trouble. Seems like beaker is trying to re-start it self
Got demo video:
https://ipfs.io/ipfs/bafybeibyoijr2zze446fapbc7gjfn5ryjffufw5jymyynfz4lirduif2hu

**Comment by pfrazee** [comment]
That's interesting, it looks like a couple of issues are interplaying.

The issue where closing from the terminal causes an incomplete shutdown might be a sign that one of my "teardown" handlers is not being properly run when closed that way, which would leave the Hyperdrive daemon running. Not 100% positive that's what's happening, but it's possible.

The "Second instance opened" thing suggests to me that Beaker is trying to start the daemon by running electron in "nodejs mode" but for some reason that nodejs mode is not correctly being applied, causing the daemon spawn to effectively spawn a second Beaker instance. I ran into this previously but it was solved, so I'm surprised it's happening again. Not entirely sure what could be causing it.

Do you happen to see any instances in task manager named "node" or "hyperdrive" that shouldnt be there? I'm wondering if there are more zombie processes than you were aware of

**Comment by danrobi11** [comment]
@pfrazee Theres no 'node' nor 'hyperdrive' instance running here

**Comment by pfrazee** [comment]
Are you running this using the AppImage (prerelease 2) from the CLI?

**Comment by danrobi11** [comment]
@pfrazee ./Beaker.Browser-1.0.0-prerelease.2.AppImage
Thats all I do

**Comment by pfrazee** [comment]
Okay I'll test that, usually I double-click the appimage to start it. I'll see if starting from CLI makes any difference.

**Comment by danrobi11** [comment]
@pfrazee  Yes I see the 'hyperdrive' still running

**Comment by danrobi11** [comment]
I deleted .config/Beaker Browser and .hyperdrive 
Beaker now start as intended

**Comment by pfrazee** [comment]
@danrobi11 I'm pretty sure what you're running into is an issue where the hyperdrive-daemon isn't getting shutdown. If it happens again, just check to see if there's any zombie processes named 'beaker' or 'hyperdrive' and kill them. I'm going to see if I can repro this and stop it from happening.

**Comment by pfrazee** [comment]
I wasn't able to repro so I'm going to _optimistically_ close, but I think we have ongoing issues with the daemon management
