### ISSUE TITLE
The mv command fails when target file contains spaces 

### ISSUE THREAD

**Issue by johanbove** [beakerbrowser/beaker#1651]
**Describe the bug**
When using the command `mv` or `cp` with a target file name containing spaces, the process fails with the error message:

```
Error: Uncaught InvalidPathError: Path contains invalid characters
```

**To Reproduce**
1. Find a file in a hyperdrive
2. Drag and drop or execute the `mv` or `cp` with a target path containing spaces; use quotes to encapsulate the file name
3. The process will fail with the above mentioned error message

**Expected behavior**
The `mv` and `cp` commands should accept target paths with - escaped - spaces within the file name / folder

**Screenshots**
<img width="548" alt="Annotation 2020-05-22 183249" src="https://user-images.githubusercontent.com/922765/82689418-bb34a280-9c5a-11ea-8c75-bd75be5f050b.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Beaker: Version: 1.0.0-prerelease.2 
```
Electron: 9.0.0
Chromium: 83.0.4103.64
Node: 12.14.1
Hyperdrive: 10.11.0
API: 0
Daemon: 1.13.12
Client: 1.15.1
Schema: 1.10.0
Fuse Native:
Fuse:
```

**Additional context**
Not tested on other platforms.

**Comment by pfrazee** [comment]
Thanks for filing! I'll check into it.
