### ISSUE TITLE
Consider Ungoogled Chromium for the core engine

### ISSUE THREAD

**Issue by dustmoo** [beakerbrowser/beaker#1656]
https://github.com/Eloston/ungoogled-chromium

Chromium phone's home to Google by default. Please consider ungoogled-chromium patches and or other privacy mitigation.

Bromium for android is a good example of a more private chromium based stack.

**Comment by jamesgecko** [comment]
Beaker Browser is based on [Electron](https://www.electronjs.org/). I don't believe that Electron has the behavior you're concerned about.

**Comment by dustmoo** [comment]
Thanks @jamesgecko funny that the issues are named similarly. I'll have to look at the Chrome source, but if the "phone home" behavior is only related to the //chrome folder then it should be good. Thanks
