### ISSUE TITLE
Saving from file editor updates both ctime and mtime

### ISSUE THREAD

**Issue by kickscondor** [beakerbrowser/beaker#1659]
**Describe the bug**
Discovered this while editing posts in my microblog. I would visit the Markdown file directly and edit the text with the built-in editor. This shifted my posts around. However, the pfrazee-microblog script sorts by ctime. I used `stat` to compare the ctime and mtime - both had been updated to the same time when I saved.

**To Reproduce**
1. Go to your profile.
2. Click 'Editor' to edit the index.html.
3. Save changes.
4. Open the dev console and run: `beaker.hyperdrive.stat('/index.html').then(console.log)`.
5. Compare ctime and mtime.

**Expected behavior**
I expected ctime to be preserved when saving from the built-in editor.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.0.0-prerelease.2

**Comment by pfrazee** [comment]
Yeah I've seen this a couple times too. Thanks for reporting, I'll check into it.

**Comment by kickscondor** [comment]
I figured. No big deal at all. Just reporting it in case. Thanks!

**Comment by pfrazee** [comment]
Fixed!
