### ISSUE TITLE
Dat Web API v2.5 new methods

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#166]
- [ ] openArchive. Open a picker dialog. Pick an archive from the user's local saved archives.
 - [ ] listArchives. List the archives this site has write-access to

**Comment by joehand** [comment]
Get the list of archives created by app (didn't see that anywhere else).

**Comment by pfrazee** [comment]
Agree, a good short-term solution is to track it in local storage

**Comment by pfrazee** [comment]
Consolidating this issue into https://github.com/beakerbrowser/beaker/issues/311, closing
