### ISSUE TITLE
Session restore doesn’t work with the background daemon enabled

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1666]
**To Reproduce**
1. Enable session restore (restore tabs from last time)
2. Enable the background daemon
3. Open example.com in a tab
4. Press Command–q/Alt–F4 to Quit Beaker.
5. Start Beaker again.

**Expected behavior**
The window should be restored and reopen example.com in a tab.

**Actual behavior**
You get a new empty session.

**Desktop (please complete the following information):**
 - OS: Linux, macOS, Windows
 - Browser: Beaker
 - Version: 1.0-pr2

**Comment by pfrazee** [comment]
Fixed, will be in tomorrow's release
