### ISSUE TITLE
Peers menu rendering problems

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1670]
**Describe the bug**
This is three bugs reported as one. I’m assuming they’re related, though.

1) The peer, bookmark, and info pop-out dialogs don’t paint fully, or are very slow to paint. Only shows the top border of the window. (First screenshot below).

2) Buttons that open pop-out dialogs get stuck in pressed state even though the dialog is closed. (Second screenshot.) I believe this has to do with switching tabs while a pop-out attached to another tab is open.

3) The pop-out dialogs sometimes blink in and out repeatedly. Have to restart Beaker to fix it. Video (you’ll need to download and play it locally): hyper://0c3fdb310329ffad53aa70549d04f7b9c5b09e3f6d92d01f61943579e62bac2a/screenrecording.mp4

**To Reproduce**
Unknown. Happens frequently but can’t pinpoint the steps.

**Screenshots**
<img width="244" alt="half-a-dialog" src="https://user-images.githubusercontent.com/1102886/82755619-0d013800-9dd5-11ea-85ff-dc0c9896fbda.png">
<img width="118" alt="pressed-but-not-open" src="https://user-images.githubusercontent.com/1102886/82755642-286c4300-9dd5-11ea-810c-6710276bb7c3.png">

**Desktop (please complete the following information):**
- OS: macOS
- Browser: Beaker
- Version: 1.0-pr2

**Comment by pfrazee** [comment]
Thanks for filing, I'll check into it

**Comment by pfrazee** [comment]
I just pushed an update which I *think* should solve this. If you still see this after tomorrow's release, please let me know.
