### ISSUE TITLE
Command–L should select address bar contents

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1671]
**To Reproduce**
1. Navigate to any page.
2. Press Command–L

**Expected behavior**
Should focus the address field and select its contents (like in all other browsers).

**Actual behavior**
The cursor is placed at the end of the string.

**Desktop (please complete the following information):**
- OS: Linux, macOS, Windows
- Browser: Beaker
- Version: 1.0-pr2

**Comment by pfrazee** [comment]
:+1: I'll change this
