### ISSUE TITLE
Add legacy dat:// rendering/browsing

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1674]
Currently `dat://` URLs just render the converter interface. We should bring in readonly page-rendering and move the converter to another part of the UI.

**Comment by todrobbins** [comment]
🙏 👍🏻

**Comment by pfrazee** [comment]
Okay we've got browsing and viewing, now I need to hit the converter and we'll be good to go

**Comment by pfrazee** [comment]
![ezgif-4-5287274a272e](https://user-images.githubusercontent.com/1270099/83580687-4c7d0200-a502-11ea-9c42-26dc67de7c09.gif)

We're in business!
