### ISSUE TITLE
Export error in editor: "Error: Uncaught InvalidURLError: Hostname is not a valid hash"

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1676]
**Describe the bug**
When exporting a file from the editor, I get an error: "Error: Uncaught InvalidURLError: Hostname is not a valid hash".

However, when I export a file the file explorer ("Explore files"), it works.

**To Reproduce**
1. Open any hyperdrive url.
2. Click on "Editor".
3. Click on "Actions -> Export".
4. Select the folder to export to.
5. See error.

**Expected behavior**
File is exported without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/6719916/82865823-f61f2a80-9f27-11ea-9d2e-883187499459.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser: Beaker.
 - Version: v1.0.0-prerelease.2

**Additional context**
Exporting a file the file explorer ("Explore files") works, though.

**Comment by pfrazee** [comment]
Thanks, I'll check into it
