### ISSUE TITLE
object Object in auto updater

### ISSUE THREAD

**Issue by mafintosh** [beakerbrowser/beaker#1677]
<img width="439" alt="Screenshot 2020-05-26 at 12 51 12" src="https://user-images.githubusercontent.com/376661/82892486-d3a10780-9f4f-11ea-9397-86dd51445b14.png">

**Comment by Butterfly** [comment]
Hi.. "Just" a casual user here. Just saw this a few hours ago while cleaning out Beaker Github emails. It sounds possibly like #1591 where [Paul says](https://github.com/beakerbrowser/beaker/issues/1591#issuecomment-630879160):

> That actually looks like correct behavior. Connection failed, maybe bad network or github downtime

:four_leaf_clover:

**Comment by pfrazee** [comment]
@mafintosh if you see that again, can you check devtools to see if anything got logged? I hit that once and then couldnt repro

**Comment by da2x** [comment]
Just got this error. This was printed in the console.

```
{
  "browserInfo": {
    "version": "1.0.0-prerelease.2",
    "electronVersion": "9.0.0",
    "chromiumVersion": "83.0.4103.64",
    "nodeVersion": "12.14.1",
    "platform": "darwin",
    "updater": {
      "isBrowserUpdatesSupported": true,
      "error": {
        "message": "Error: net::ERR_FAILED"
      },
      "state": "idle"
    },
    "paths": {
      "userData": "/Users/Daniel/Library/Application Support/Beaker Browser"
    },
    "isDaemonActive": true
  },
  "settings": {
    "auto_update_enabled": 1,
    "auto_redirect_to_dat": 1,
    "custom_start_page": "previous",
    "new_tab": "beaker://desktop/",
    "run_background": 0,
    "default_zoom": 0,
    "start_page_background_image": "",
    "workspace_default_path": "/Users/da/Sites",
    "default_dat_ignore": ".git\n.dat\nnode_modules\n*.log\n**/.DS_Store\nThumbs.db\n",
    "analytics_enabled": 1,
    "dat_bandwidth_limit_up": 0,
    "dat_bandwidth_limit_down": 0,
    "no_welcome_tab": false
  },
  "defaultProtocolSettings": {
    "http": false,
    "hyper": true,
    "dat": true
  }
}
```

**Comment by da2x** [comment]
Manually clicking Check for updates changes `[object Object]` to `Error: net::ERR_FAILED` in the UI.

**Comment by pfrazee** [comment]
Okay I have some ideas about what could be happening, thanks yall.

**Comment by fwip** [comment]
Got the same Object: Object error when looking to upgrade to beaker v5. However, this time clicking Check for Updates successfully downloaded the new version.
https://imgur.com/a/1HptWGr.png
