### ISSUE TITLE
/diff/ path missing from address field for beaker://diff/?urls

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1678]
**Describe the bug**
The /diff/ path is missing from the address field when accessing beaker://diffs/.

**To Reproduce**
1. Go to beaker://diff/?base=hyper%3A%2F%2F1f7ad27de0f974dcecc390811908af4fb1ae7daab0af64e94249b2a631a880ef%2F&target=hyper%3A%2F%2Fddf4320397df61c4f260d2a51eaa20fa5e847d0be19f035942d434bd2557f28b%2F

**Expected behavior**
Should display the URL path in the address field.

**Screenshots**
<img width="148" alt="screenshot" src="https://user-images.githubusercontent.com/1102886/82917332-95b5da80-9f73-11ea-9caf-da1f66250a20.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Browser: Beaker
 - Version: 1.0-pr2

**Comment by pfrazee** [comment]
Hmm, yeah I think we can solve this by changing how Beaker's builtin interfaces are rendered in the site-info button. Saying just "Beaker" is too low-information.

**Comment by pfrazee** [comment]
Fixed!
