### ISSUE TITLE
Relative imports do not work in custom webterm commands

### ISSUE THREAD

**Issue by matthewauld** [beakerbrowser/beaker#1680]
**Describe the bug**
This is not an important bug, just thought I would include, especially for anyone else who is trying to figure it out!

Relative imports from the index.js file of a custom webterm command do not function and return a `TypeError: Cannot read property 'yourCustomCommand' of undefined` when installed. Absolute imports work file with the full 'hyper://xxx.." work fine. 

**To Reproduce**
1. Create a webterm command in a 'index.js' file
2. Create a 'test.js' that exports a single constant
3. Import said constant in index.js `import {x} from "./test.js"`
4. Attempt to install command
5. See error
5. Note that if you change import to "hyper://xxx/test.js" it works fine.

**Expected behavior**
Either have relative imports succeed as expected, or fail with a more descriptive error message, telling user to use absolute paths. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Beaker 
 - Version: beta 2

**Additional context**
Nope! Again, not a major issue at all!

**Comment by pfrazee** [comment]
Thanks for reporting, I'll check into it

**Comment by pfrazee** [comment]
Okay fixed
