### ISSUE TITLE
Extend `beaker.hyperdrive.forkDrive` API

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#1694]
**Is your feature request related to a problem? Please describe.**
In the old `DatArchive` API the fork method took a set of options that controlled the fork process. This allowed an application to collect the information from the user for both the creation of the new drive, and details that the application will use to populate the new drive in a single application prompt, and a prompt from beaker for permission to create the new drive.

**Describe the solution you'd like**
The `beaker.hyperdrive.forkDrive` method be extended to include a set of options:
* opts.title String. The title of the archive.
* opts.description String. The description of the archive.
* opts.prompt Boolean. Whether or not to show Beaker’s fork modal. (If false, a simple permission prompt will be shown instead.)

A new `beaker.hyperdrive.copyDrive` method, with the same options as `forkDrive`, but that will make a copy of a drive.

The modal that is displayed, if opts.prompt is true, defaulting to true if not supplied, will only display `fork` or `copy` depending on which method is used.

An alternative might be have just the single method, with an option to indicate if the existing drive should be forked or copied.

**Describe alternatives you've considered**
The only viable alternative would be to use the API to create a new drive, and then copy the contents of the template drive to the new drive.

**Additional context**
The original use of `DatArchive.fork()` is from code for the creation of a new Federated Wiki site, see [fedwiki plugin](https://github.com/paul90/wiki-plugin-wikigenesis/blob/master/client/wikigenesis.coffee#L84-L114), that uses some user supplied in the duplication an existing empty wiki and saves a name into the new wiki.

**Comment by pfrazee** [comment]
Okay I'm +1, thanks for the detailed specs

**Comment by pfrazee** [comment]
Okay so here are the updated params:

```
beaker.hyperdrive.forkDrive(url, {
  detached: Boolean, if true it will be a copy, if false it will be a fork
  title: String, the title of the drive (only applies if detached == true)
  description: String, the description of the drive (only applies if detached == true)
  prompt: Boolean, if false will only ask permission
})
```

**Comment by paul90** [comment]
Thank you Paul.

**Comment by pfrazee** [comment]
You bet!
