### ISSUE TITLE
dat site conversion results in blank drives

### ISSUE THREAD

**Issue by dasanchez** [beakerbrowser/beaker#1698]
Clicking the "Convert" button results in an empty hyperdrive with an index.json file.

**To Reproduce**
1. Go to the Home page and scroll down to the "You have xxx legacy Drives which can be converted to Hyperdrive" section.
2. Click on a dat side "Convert" button.
3. Click "Convert" on the next page.
4. The resulting page only displays an `index.json` file.

**Expected behavior**
A page that displays all the files with the dat repository, or the option to save existing files before  converting them.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Version 1.0.0 prerelease 3

**Comment by pfrazee** [comment]
Sorry for (yet another) dat converter bug. I updated the stack and did some extensive testing, during which I ran into this and resolved it.
