### ISSUE TITLE
More detail to query() output

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1699]
The `query()` function currently gives 3 pieces of information (among others):

 - `path` The path to the file relative to the queried drive
 - `drive` The drive containing the result (which may be a mounted drive within the queried drive)
 - `url` The URL of the file (which may be for a mounted drive within the queried drive)

The `drive` and `url` values are what you might call "canonical" -- they give you the drive containing the file and its URL on that drive. The `path` value is relative to the drive from which you queried.

When I first implemented `query()`, you could only pass one `drive` into it, so these values were sufficient. However now that you can pass multiple drives in, you may need to know which queried-drive the file matched.

It might be wise to update the results to the following:

 - `path` The path to the file relative to the queried drive
 - `drive` The queried drive
 - `url` The URL of the file relative to the queried drive
 - `origin` object
   - `path` The path to the file relative to the originating drive
   - `drive` The originating drive
   - `url` The URL of the file relative to the originating drive

This would be a breaking change which might screw with some people but hopefully wouldn't be terribly painful.

**Comment by AramZS** [comment]
It is also worth noting that there is a mount property on the files returned from a query that doesn't seem to fill to a value when the files are returning from a mount? I'm not sure what is intended there.

**Comment by pfrazee** [comment]
Okay updated. @AramZS The `mount` value is only set if the result is a mount. It tells you the mount's URL.
