### ISSUE TITLE
Closing a prompt modal does not return focus to window

### ISSUE THREAD

**Issue by metanomial** [beakerbrowser/beaker#1709]
**The Problem**
Closing a prompt modal does not return focus to the window.

**To Reproduce**
Prompt modal close behavior can be tested in various browsers with the follow code snippet:
```
window.addEventListener("focus", console.log);
window.prompt("Input does not matter");
```

**Expected behavior**
The prompt modal should return focus to window immediately after close, and an `Event { type: "focus" }` should be emitted.

**Environment**
 - OS: Windows 10
 - Version: v1.0.0-prerelease.3

**Comment by pfrazee** [comment]
Thanks for filing, I'll hit it this week

**Comment by pfrazee** [comment]
Fixed!
