### ISSUE TITLE
Indicate that shutdown is ongoing

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1712]
(Mainly adding this so I don't forget it in the next release.)

Latest hyperdrive-daemon isn't shutting down properly when I close beaker. Should be deamon is kill, but deamon is not kill.

EDIT: it turns out this is correct behavior. The daemon shutdown needs to take time to properly leave the DHT. Beaker just needs to indicate what's going on.

**Comment by todrobbins** [comment]
Might be related, but on macOS Beaker does not quit completely when I `cmd+q` or `Beaker Browser` > `Quit Beaker` but _does_ quit completely when I quite from the menubar app. 🤷

**Comment by pfrazee** [comment]
@todrobbins That's intended behavior if you have "Let beaker run in the background" enabled
