### ISSUE TITLE
Beaker API namespace is an empty object when accessed from a local file

### ISSUE THREAD

**Issue by metanomial** [beakerbrowser/beaker#1713]
**Describe the Bug**
The `beaker` namespace is an empty object when it is accessed from a local HTML or JavaScript file.

**To Reproduce**
1. Drag-drop a local HTML file into Beaker
2. Open the Developer Console
3. Evaluate `beaker`. An emty object will be returned.

**Expected Behavior**
The Beaker APIs should be accessible from local files. This is crucial for app development using an external workflow.

**Environment**
 - OS: Windows 10
 - Beaker Version: 1.0.0-prerelease.3

**Comment by pfrazee** [comment]
@metanomial we need to decide whether `file:///` should be able to do this. It's difficult to assign perms to `file:///` because it's a global namespace, and I'd rather use the folder-sync solution we're developing for local dev.

**Comment by metanomial** [comment]
@pfrazee if you decide against, please do not leave the empty `beaker` namespace exposed to local files. Evaluating `beaker != null` is a common check to determine if the Beaker API is available for use in cross-protocol sites.

**Comment by pfrazee** [comment]
Sure

**Comment by pfrazee** [comment]
Done
