### ISSUE TITLE
Writing to file using api erases metadata.

### ISSUE THREAD

**Issue by matthewauld** [beakerbrowser/beaker#1714]
**Describe the Bug**

When using the beaker api (`beaker.hyperdrive.writeFile()), any existing metadata from the file is lost on write.

**To Reproduce**
1. Create a file with some metadata
2. In the browser console, run `await beaker.hyperdrive.writeFile({path},"hello world")
3. View the metadata on the file to see it is gone

**Expected Behavior**

Unsure - Assume that either the metadata should persist, or there should be some option to retain the metadata. 

**Screenshots**

**Environment**
 - OS: Ubuntu
 - Beaker Version:  e.g. 1.0.0-prerelease.3 

**Additional Context**

**Comment by pfrazee** [comment]
Thanks, I'll get into this.

**Comment by pfrazee** [comment]
Fixed!
