### ISSUE TITLE
Hide tab-close button on background tabs (when there are many tabs)

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1720]
**Describe the Bug**
Overcrowded tab bars have been a source of frustration ever since tabs were introduced into browsers. It’s easy to accidentally close background tabs when you try switching to them.

**To Reproduce**
1. Open many tabs.
2. Hover the mouse cursor over a background tab.

**Expected Behavior**
The close button shouldn't appear for background tabs when there are many tab; only show it on the current active tab. Both Firefox and Chrome has this behaviour for a reason.

**Comment by pfrazee** [comment]
I'm +1 this.

**Comment by pfrazee** [comment]
The easiest thing to do was to just always hide the non-active tab's close button so that's what I did here
