### ISSUE TITLE
Change the default search engine

### ISSUE THREAD

**Issue by tiotrom** [beakerbrowser/beaker#1722]
Is it possible to change the default search engine? DuckDuckGo is full of ads and in Beaker you can't install any extenssions to block those ads. I recommend any SearX instance instead of Duck - https://searx.space/

**Comment by pfrazee** [comment]
Not currently, if anybody wants to implement this, it needs a setting (in the db and the settings page) and then the location-bar will need to be updated to pull from that choice.

**Comment by matthewauld** [comment]
Yeah, these are all things you would implement on top of beaker browser rather than built into it. A search engine for beaker would be a great project!

**Comment by pfrazee** [comment]
Distributed search is something we're pretty interested in once Hypercore APIs land

**Comment by rafapaezbas** [comment]
Hello I am looking for some contribution I could work on and this one seems pretty good for me. Anyway I have observed that default search engine can already be changed. Is this a feature you are still interested on? Any suggestions for a useful PR on this topic? Thanks in advance!
