### ISSUE TITLE
Folder sync keeps on "loading" and I am unable to "auto sync"

### ISSUE THREAD

**Issue by tiotrom** [beakerbrowser/beaker#1725]
![image](https://user-images.githubusercontent.com/34804533/83872562-87657c80-a732-11ea-984b-b97dc4f98b97.png)

The latest 4 beta of Beaker seems to not work 100% well with folder sync. I simply added a folder to sync but it keeps on "loading" despite all files being properly loaded from the folder. I also can't autosync, maybe because of that. I can tick the option but if I refresh that synced folder in Beaker the autosync is not ticked anymore.

**Comment by pfrazee** [comment]
Sorry for the issue! I never tested with files that large -- I'd bet that's a factor here. I'll teest that first.

**Comment by pfrazee** [comment]
Folder sync now assumes != if a file is too large to compare, which causes it to fallback on the mtime comparison.
