### ISSUE TITLE
Spelling corrections on right click.

### ISSUE THREAD

**Issue by matthewauld** [beakerbrowser/beaker#1745]
**Is Your Feature Request Related to a Problem? Please Describe**

I am a terrible speller. Just awful. It's great that beaker highlights misspelled words, however, the right click context menu doesn't provide corrections. 

**Solution You'd Like**

Right click shows top spelling corrections for a misspelled word. This could be always on, or toggleable in the context menu in firefox. 

**Alternatives You've Considered**

- Cut and paste the word into search. This makes me more aware that I cannot spell and therefore sad.
- Learn to spell properly - while possible, highly unlikely this will ever happen. 

**Additional Context**

It seems [electron has a nice api for this](https://www.electronjs.org/docs/tutorial/spellchecker). I would be happy to implement if everyone is happy with the addition. Seems simple enough

**Comment by pfrazee** [comment]
+1
