### ISSUE TITLE
Use system-ui in font stack

### ISSUE THREAD

**Issue by despens** [beakerbrowser/beaker#1752]
**Describe the Bug**

Linux AppImage version does not use system font in Beaker's user interface.

**To Reproduce**
1. Change system font to something funny
2. Start beaker
3. Funny system font not used.

**Expected Behavior**
System font should be used.

**Screenshots**
![image](https://user-images.githubusercontent.com/571494/85382801-9b391d00-b53f-11ea-87b8-93458827922e.png)
Menu bar is drawn in actual system font (set to IBM Plex Sans). Tabs and other beaker elements are drawn using Segoe UI, the Windows system font, which happens to be installed on my system too. 

**Environment**
 - Ubuntu / Gnome
 - Beaker Version: 1.0.0-prerelease.5

**Additional Context**
Using `system-ui` as main font should be enough on all platforms, since Beaker is not supposed to run with another engine than Blink.

**Comment by pfrazee** [comment]
Thanks! I wasn't aware of that font value. Great idea
