### ISSUE TITLE
SharedWorker not working with hyper:// 

### ISSUE THREAD

**Issue by elmasse** [beakerbrowser/beaker#1761]
**Describe the Bug**
SharedWorkers are failing silently.

**To Reproduce**

1. Use the simple-shared-worker [repo](https://github.com/mdn/simple-shared-worker). I cloned and then created a new hyperdrive that points to that folder
2. load index.html using the hyper:// protocol.
3. Fill the first and second text inputs.
4. Result doesn't change. It should be updated from SharedWorker.

See it live from [https://mdn.github.io/simple-shared-worker/](https://mdn.github.io/simple-shared-worker/)

**Expected Behavior**
To work exactly as from https:// protocol 
See it live from [https://mdn.github.io/simple-shared-worker/](https://mdn.github.io/simple-shared-worker/)

**Environment**
 - OS: MacOS Catalina 10.15.5
 - Beaker Version: 1.0.0-prerelease.5

**Comment by pfrazee** [comment]
This was an [electron issue which has recently been fixed](https://github.com/electron/electron/pull/20625). This should work in the next Beaker release (I tested and the demo worked for me!)
