### ISSUE TITLE
Outdated instruction in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JonathanLindroth** [beakerbrowser/beaker#1766]
**Running the tests** section is referencing folder "tests" which existed in the root directory in v0.8.10 but seems to have moved in v1.0.0-prerelease1.

https://github.com/beakerbrowser/beaker/blob/master/CONTRIBUTING.md#running-the-tests

**Comment by pfrazee** [comment]
Ah thanks for the heads up, we gotta couple outdated documents there. I'll update soon.
