### ISSUE TITLE
Allow Webterm to stay open when navigating a drive

### ISSUE THREAD

**Issue by johanbove** [beakerbrowser/beaker#1768]
**Is Your Feature Request Related to a Problem? Please Describe**

Since Release.6 clicking a file or folder in Webterm opens up that content within the same panel, while before it would open that file or folder in a "main" browser tab. I used the Webterm to quickly move around drives. Due to this, I cannot keep the Webterm open as an alternative view on a drive.

**Solution You'd Like**

When clicking a folder or file in Webterm, offer a "ctrl-click" dialog which would present the user a way to open the content in either the "other open panel", or in a new panel without "replacing" the Webterm view.

I would like to "attach" a Webterm to another panel. Moving through a drive using Webterm would then work as in the previous release. Navigating a drive using Webterm ls, open commands would be shown in the linked panel, and the active Webterm would stay open in Webterm view.

**Alternatives You've Considered**

The "open" command in Webterm could also given a new option argument to open the content in a specific panel.

```bash
open   Open the target in the browser package: std-cmds

Usage: open [-bn] {path}
    --bookmark, -b        Use {path} as the name of a bookmark to lookup and follow
    --new-tab, -n         Open in a new tab (default: false)
```

**Additional Context**

This might affect only "power users", but Webterm was one of my favorite features of Beaker. The panels implementation feels like a step back in regards to Webterm.

**Comment by johanbove** [comment]
Additionally for "Explorer" I feel that opening a folder with Explorer view works as expected when it shows the contents of the current hyperdrive. But then, when opening a file within the "Explorer" view, it opens those files in a new Tab. I would have expected that file to open in the main panel.

**Comment by pfrazee** [comment]
Yeah thanks for filing, I'll spend some time on this

**Comment by pfrazee** [comment]
Fixed in master
