### ISSUE TITLE
Custom Webterm commands no longer work

### ISSUE THREAD

**Issue by johanbove** [beakerbrowser/beaker#1770]
**Describe the Bug**

After upgrading to Release 6 my own custom Webterm command ["Blogpost"](hyper://cda2650ac7fa9940c021aa5daa8cd692a4cc72de6f890d13722d0f8745c8effb/) no longer works at all.

The Webterm returns the error message: "TypeError: Cannot read property '0' of null".
I'm pretty sure this output is not coming from my own code.

**To Reproduce**

Install the custom blogpost command.

```
86fcde..67> help blogpost
blogpost   Creates a new post in /MicroBlog package: hyper://cda265..fb

Usage: blogpost [-f] [{filename}] [-p] [-g] [-v] [{content}]
    --filename, -f        The blog post file name (default: "")
    --reply, -r           Add the hyperdrive url of the post you would like to reply to (default: "")
    --profile, -p         Asks for the profile of user to post for (default: false)
    --goto, -g            This option will open the new file in the editor (default: false)
    --verbose, -v         Prints out more debug information (default: false)
86fcde..67> blogpost -v "test"
TypeError: Cannot read property '0' of null
86fcde..67>

```

**Expected Behavior**

**Screenshots**

**Environment**
 1.0.0-prerelease.6 

Electron: 10.0.0-beta.2
Chromium: 84.0.4129.0
Node: 12.16.3
Hyperdrive: 10.13.0
API: 0
Daemon: 1.14.3
Client: 1.16.0
Schema: 1.11.0
Fuse Native:
Fuse:

**Additional Context**

<img width="539" alt="Annotation 2020-07-12 162318" src="https://user-images.githubusercontent.com/922765/87248957-8b389d00-c45c-11ea-8180-0c85c82079ab.png">

I will try reinstalling the custom command.

**Comment by pfrazee** [comment]
@johanbove can you share the code for the webterm command?

**Comment by johanbove** [comment]
Yes of course. The code is here: hyper://cda2650ac7fa9940c021aa5daa8cd692a4cc72de6f890d13722d0f8745c8effb/

**Comment by johanbove** [comment]
Found the issue in this code: ```drive = this.env.get('@').match(hyperRegExp)[0]``

**Comment by pfrazee** [comment]
Yeah, a victim of the loss of an "attached pane" concept. I'm going to fix those regressions by introducing controls and APIs to attach panes to each other, which webterm will then use to bring back the lost mechanisms like the `@` env var.

**Comment by pfrazee** [comment]
Fixed in master
