### ISSUE TITLE
Editor and terminal not toggling

### ISSUE THREAD

**Issue by JonathanLindroth** [beakerbrowser/beaker#1774]
**Describe the Bug**

"Toggle editor" and "Toggle terminal" does not toggle but adds new edit/terminal panes. I'm not sure if this is a logic bug or semantic error but since the mentioned actions are behaving differently from "Toggle devtools", which toggles, I at least did not expect this behavior as a user.

**To Reproduce**

Click the developer menu and use the tools mentioned above.

**Expected Behavior**

Mentioned panes switching between closed and open when toggling

**Environment**
 - OS:  Ubuntu 20.04 LTS 
 - Beaker Version:  

Version: 1.0.0-prerelease.6 

Electron: 10.0.0-beta.2
Chromium: 84.0.4129.0
Node: 12.16.3
Hyperdrive: 10.13.0
  API: 0
  Daemon: 1.14.3
  Client: 1.16.0
  Schema: 1.11.0
  Fuse Native:
  Fuse:

**Comment by pfrazee** [comment]
Ah, that is, at minimum, a semantic error from the recent updates. I'll think about whether I can make it back into a toggle within the panes system, but I might just need to change the label.

**Comment by pfrazee** [comment]
Okay I was able to bring back the toggling behavior. This will be fixed in the next release. Thanks for bringing this to my attention.
