### ISSUE TITLE
Support "Editor" & "Explore Files" on dat:// sites

### ISSUE THREAD

**Issue by jeremyredhead** [beakerbrowser/beaker#1775]
**Problem**
I cannot use the "Editor"... sidebar(?), nor "Explore Files" on (so-called) legacy dat sites.

**Solution I'd Like**
Supporting the "Editor" on dat sites should be easy enough, since it would be the same as for http(s) sites (read-only), except through a different protocol. (Actually, view-source: doesn't work on dat sites either...)
Being able to Explore Files shouldn't be too hard either, after all Beaker Browser used to only support dat protocol (how hard could it be too re-add support? ;)

**Alternatives I've Considered**
Opening the archives in Firefox w/ [Dat Fox addon](https://github.com/sammacbeth/dat-fox) and muck about with DatArchive API in console to list folders/files... yea, i'd rather use a GUI :p

**Additional Context**
I am sorry for being a little annoying in my phrasing of this issue, I was using Beaker Browser as (essentially) a visual version control for a few websites, so needless to say when I accidentally (for real) upgraded to beta version and found dat archives are considered legacy... well, I should've known better, ah well.
I know you all are doing your best, and the efforts are all experimental. Thanks.

**Comment by pfrazee** [comment]
Yeah, I'm sorry about the pain of the conversion process. I really don't think we can hit this -- we're already slammed getting hyper-based features delivered.

I'm hopeful that we'll soon have all the features that dat:// had (DNS, http mirrors) and converting to hyper:// will be painless.
