### ISSUE TITLE
UI Editor: Search Widget on Windows shows rectangles instead of icons

### ISSUE THREAD

**Issue by johanbove** [beakerbrowser/beaker#1776]
**Describe the Bug**

Within the built-in "Editor", when doing a search within the file, a search widget appears in the top right - I know it from Visual Studio Code. Since a couple of releases this snippet seems to have lost the correct path to the icons used in the buttons.

**To Reproduce**

1. Open a file in the Editor
2. Start a search by doing ctrl-f
3. Notice the Search Widget appear in the top right
4. Notice how the Search Widget works, but none of the icons are shown. Only rectangles are displayed.

**Expected Behavior**

I would see the Search Widget with all icons.

**Screenshots**

How the Search Widget currently looks:
<img width="448" alt="Annotation 2020-07-14 215436" src="https://user-images.githubusercontent.com/922765/87471013-f2ea1600-c61d-11ea-950b-4256f38c3a11.png">

How it should look:
<img width="349" alt="Annotation 2020-07-14 220504" src="https://user-images.githubusercontent.com/922765/87471118-1ca33d00-c61e-11ea-8181-e5c20dd2e741.png">

**Environment**
Version: 1.0.0-prerelease.6 

Electron: 10.0.0-beta.2
Chromium: 84.0.4129.0
Node: 12.16.3
Hyperdrive: 10.13.0
API: 0
Daemon: 1.14.3
Client: 1.16.0
Schema: 1.11.0
Fuse Native:
Fuse:

**Additional Context**

**Comment by pfrazee** [comment]
Whoops, accidentally closed

**Comment by pfrazee** [comment]
Fixed in the next release!
