### ISSUE TITLE
Can't see number of seeds/hosts in URL bar

### ISSUE THREAD

**Issue by aadilayub** [beakerbrowser/beaker#1780]
**Describe the Bug**
For all hyperdrives, the number of seeds/hosts shows as zero. When I click on the share/host icon, it doesn't render and just shows a loading icon.

**To Reproduce**

1. Navigate to any hyperdrive that you know is being hosted by 1+ people
2. Click on the sideways V icon that shows the number of hosts

**Expected Behavior**
The number of hosts for each hyperdrive show up accurately, and the option to host the hyperdrive shows up when the share icon is clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/31581044/87871047-c25ffe80-c9c6-11ea-9896-1cfeb281c4d4.png)

**Environment**
 - OS: macOS Mojave
 - Beaker Version: 1.0.0-prerelease.7

**Comment by pfrazee** [comment]
Thanks, yes this is an annoying bug that I will hopefully get to soon.

**Comment by pfrazee** [comment]
Fixed in the upcoming release (finally)
