### ISSUE TITLE
Unable to start local build: Did you forget to signal async completion?

### ISSUE THREAD

**Issue by digli** [beakerbrowser/beaker#1788]
**Describe the Bug**
I'm getting the following error when attempting to run `npm start` inside `/scripts`:
```
npm start

> beakerbrowser@ start /Users/digli/code/other/beaker/scripts
> gulp start

[13:45:28] Using gulpfile ~/code/other/beaker/scripts/gulpfile.js
[13:45:28] Starting 'start'...
[13:45:28] Starting '<anonymous>'...
Spawning electron /Users/digli/code/other/beaker/scripts/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
[13:45:29] The following tasks did not complete: start, <anonymous>
[13:45:29] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beakerbrowser@ start: `gulp start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the beakerbrowser@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/digli/.npm/_logs/2020-07-27T11_45_29_900Z-debug.log
```

**To Reproduce**
Follow the setup steps as described in the readme:
```
git clone https://github.com/beakerbrowser/beaker.git
cd beaker/scripts
npm install
npm run rebuild
npm start
```

**Environment**
 - OS: macOS 10.14.4 
 - nodejs: v12.16.1
 - npm: 6.13.4
 - Beaker Version: Current master (4b820491818f19f3b06a77fadfa3ed562eba7857) 

**Additional Context**
I've tried running `npm burnthemall` => `npm start` but to no avail; the same error occurred.

The error message `Did you forget to signal async completion?` seems to be related to gulp

**Comment by pfrazee** [comment]
Sounds like there might have been a build error. Could you try using node 14 and running `npm run burnthemall` and then `npm start` ?

**Comment by digli** [comment]
Tried it just now with node v14.6.0, getting the same error message.
Additional environment info:
libtool 2.4.6_2
autoconf 2.69
automake 1.16.2

**Comment by pfrazee** [comment]
Hmm. Odd... why aren't we getting any logs?

A couple things to try

 - `ELECTRON_ENABLE_LOGGING=true npm start`. See if you get anything there.
 - Check `/Users/{your_username}/Library/Application Support/Beaker Browser/beaker.log` for anything useful

**Comment by digli** [comment]
I figured out the issue! I had the beta build running in the background. 🤦 Once I closed the beta build I was possible to start my local normally through `npm start`.

**Comment by voxpelli** [comment]
I guess the README could be updated in some way to help others who experiences the same?

That or a code fix that communicates that fact rather than just crashing?

Thoughts @digli @pfrazee?
