### ISSUE TITLE
Editor: undo, redo, paste and select all option 

### ISSUE THREAD

**Issue by danrobi11** [beakerbrowser/beaker#1803]
Hello
I havent found undo, redo and select all option in the editor.
I know about ctrl+z/y and ctrl+a However, not everybody that used a text editor knows that. These seems to be the only missing options
New edit: Added 'paste'

**Comment by pfrazee** [comment]
Are you looking for, like, a menubar with these editor options in it?

**Comment by danrobi11** [comment]
@pfrazee Im guessing the most obvious for 'Select All' would probably be in the right click menu with cpoy and cut where the usually are. I forgot to mention 'paste' would fit in there too. As for undo/redo, in the 'Actions' drop down menu maybe? or again, right click, i guess. I think that would feel pretty much as a regular GUI editor. 
Very nice job btw with the editor, rich in features and run extra smooth :+1:

**Comment by pfrazee** [comment]
@danrobi11 Cheers! Got this done, it will be in the next releasae
