### ISSUE TITLE
Peers hosting indicator and menu aren't working

### ISSUE THREAD

**Issue by CerebralDatabank** [beakerbrowser/beaker#1811]
**Describe the Bug**
The peers hosting menu in the location bar does the same thing for every `hyper://` URL:
- Displays a number (usually 3 or around 3)
- After about one second, displays 0
- When clicking on it, displays a popup with a loading screen which stays like that.

**To Reproduce**
1. Go to the User Directory from the bookmarks bar
2. Choose a user and take note of how many peers are hosting their page (e.g. 36)
3. Visit the page
4. Notice that the peer connection indicator displays a number (usually 3 or around 3), and about a second later displays 0
5. Click the indicator
6. Notice that the menu opens but stays loading

**Expected Behavior**
The peers hosting indicator and the menu show the correct number of peers or show an error if one occurred.

**Screenshots**
![beaker-peers-not-working](https://user-images.githubusercontent.com/24465111/92678696-385c5400-f2ec-11ea-8397-f0ad004e9b46.png)

**Environment**
 - OS: Windows 10, version 2004 (x64)
 - Beaker Version: 1.0.0-prerelease.3

**Additional Context**
Beaker reports my network as not hole-punchable.

**Comment by da2x** [comment]
Same issue if you upgrade to 1.0.0-prerelease.7?

I’ve noticed the same issues on Linux and macOS too. However, for me Beaker works fine for maybe the first week or two, then this issue appears after some use. I don’t know the exact steps to reproduce it.

**Comment by CerebralDatabank** [comment]
Yes, the issue is present in version `1.0.0-prerelease.7`.

**Comment by pfrazee** [comment]
Yeah very sorry about this. We have a fix in the upcoming release.

**Comment by CerebralDatabank** [comment]
About the version string in my original post being 1.0.0-prerelease.3, I may have just un-commented-out whatever was in the template assuming it was the latest version; sorry about that 😛

**Comment by despens** [comment]
Same happens on Linux version with hole-punchable network

**Comment by pfrazee** [comment]
Going to close for the upcoming 1.0 release, where it's fixed
