### ISSUE TITLE
The Hyperdrive Daemon is Not Active

### ISSUE THREAD

**Issue by rzelnik** [beakerbrowser/beaker#1813]
I often see this error message in my Beaker Browser:

The Hyperdrive Daemon is Not Active
The "daemon" runs Beaker's Hyperdrive networking.
Restart the Daemon

It works well for a while after start, then the daemon crashes and shows this error message. After clicking to "Restart the Daemon" button, the daemon is unable to restart, I just see the endless spinner icon.

**Environment**
 - OS: Ubuntu 20.04.1 LTS
 - Beaker Version: 1.0.0-prerelease.7

**Comment by pfrazee** [comment]
We had some finnicky behavior with the hyperdrive-daemon and we're replacing it with the new hyperspace daemon in the next release, hopefully that will help
