### ISSUE TITLE
Guide for markdown websites appears outdated

### ISSUE THREAD

**Issue by Bios-Marcel** [beakerbrowser/beaker#1815]
https://beakerbrowser.com/docs/guides/create-a-markdown-site

Adding a `nav.md` seems to make no difference. Not a single page renders the menu. I was also unable to find any other page that uses this.

My structure is the following:

```
about.md
index.md
nav.md
```

About and index are just simple headings with a `TODO` beneath and `nav.md` is  this:

```md
[Home](index.md)
[About me](about.md)
```

I basically did exactly what was described in the guide.

**Comment by pfrazee** [comment]
Yeah, apologies, if you're in 1.0 or later then the accurate docs are at https://docs.beakerbrowser.com
