### ISSUE TITLE
Move away from Chromium to stop the Google's monopoly on web standerds.

### ISSUE THREAD

**Issue by MainTomato** [beakerbrowser/beaker#1820]
**Solution You'd Like**
I would like Beaker Browser to move away from Google's technology which Is trying to centralize the web.

**Alternatives You've Considered**
Mozilla's Gecko engine Is the way to go I think, other projects like Tor Browser have had success with Gecko.

**Comment by pfrazee** [comment]
I appreciate the motive but we lack the resources for a move like this, or to even build on gecko. Beaker depends on electron to be feasible given our resources.

**Comment by Krinkle** [comment]
There are numerous other options that might be worth checking out, these avoid Electron and its bundled Chrome:
<https://github.com/sudhakar3697/electron-alternatives#js>
