### ISSUE TITLE
Parts of Beaker Browser aren't styled correctly in dark theme

### ISSUE THREAD

**Issue by CerebralDatabank** [beakerbrowser/beaker#1822]
**Describe the Bug**
Certain parts of Beaker Browser still have light theme styling while in dark theme. In some cases, this causes the contrast between the text color and the background color to be insufficient for normal legibility.

**To Reproduce**
1. Make sure Beaker is set to use the dark theme
2. Go to any `hyper://` URL
3. Right-click anywhere on the page
4. Click either "Edit Source" or "Explore Files"
5. Notice that some parts of the UI are not in dark theme (the ones that I've noticed are listed below, but there may be more)
    - "Folder" options dropdown and "Settings" menu in the Beaker Files Explorer
    - "File Metadata" dropdown and "New File" dialog in the Beaker Editor
    - "Create Shortcut" and "New Drive" dialogs on the new tab page
    - Basic HTTP Authentication login window

**Expected Behavior**
All parts of Beaker Browser should be consistent in dark theme.

**Screenshots**
![beaker-dark-theme-bug](https://user-images.githubusercontent.com/24465111/94373707-c302c880-00cc-11eb-9d85-83a101b99a18.png)
*The open "Settings" menu in the Beaker Files Explorer*

**Environment**
 - OS: Windows 10, version 2004 (x64)
 - Beaker Version: 1.0.0-prerelease.7

**Additional Context**
(None)

**Comment by pfrazee** [comment]
This should be fixed in the 1.0.0 release
