### ISSUE TITLE
Rectangle glyphs in Find/Replace dialog in the Beaker Editor

### ISSUE THREAD

**Issue by CerebralDatabank** [beakerbrowser/beaker#1824]
**Describe the Bug**

**To Reproduce**
1. Open any `hyper://` URL
2. Right-click anywhere on the page
3. Click "Edit Source"
4. Press either <kbd>Ctrl</kbd> + <kbd>F</kbd> (find) or <kbd>Ctrl</kbd> + <kbd>H</kbd> (find and replace).
5. Notice that the icons are all rectangle glyphs.

**Expected Behavior**
The icons in the Find/Replace menu should all display properly.
Also, the Find/Replace menu in Microsoft Visual Studio Code contains light gray text when dark theme is used; perhaps that should be the case here as well.

**Screenshots**
![beaker-find-replace-bug](https://user-images.githubusercontent.com/24465111/94376602-1bdc5c00-00e1-11eb-9a1d-8656d5e2a649.png)
*Find/Replace menu in the Beaker Editor*
![beaker-find-replace-in-vscode](https://user-images.githubusercontent.com/24465111/94376772-5397d380-00e2-11eb-8965-6b41541c266c.png)
*Find/Replace menu in Visual Studio Code*

**Environment**
 - OS: Windows 10
 - Beaker Version: 1.0.0-prerelease.7

**Additional Context**
(None)

**Comment by pfrazee** [comment]
Thanks for filing. Got this fixed in the upcoming 1.0
