### ISSUE TITLE
Hamburger → Help: No DNS record found

### ISSUE THREAD

**Issue by jtagcat** [beakerbrowser/beaker#1830]
![hamburger menu](https://design.firefox.com/icons/icons/desktop/menu-16.svg) → ![help icon](https://design.firefox.com/icons/icons/desktop/help-16.svg) Help → opens a new tab with [dat://beakerbrowser.com/docs](dat://beakerbrowser.com/docs).

**Environment**
 - OS: Flatpak
 - Beaker Version: `0.8.10 Electron: 8.1.1 - Chromium: 80.0.3987.141 - Node: 12.13.0`

**Comment by pfrazee** [comment]
Thanks for reporting - this is fixed in the 1.0 release coming soon
