### ISSUE TITLE
Explicit what green/orange/red status are when syncing with local folder

### ISSUE THREAD

**Issue by yhancik** [beakerbrowser/beaker#1839]
**Is Your Feature Request Related to a Problem? Please Describe**
When syncing with a local folder, there's a coloured dot next to each file, which can be green, orange or red. 
It's never explained to the user (or found in the documentation?) what these colours mean.

**Solution You'd Like**
Display the status in a tooltip when hovering the file (or just the dot?), and update the documentation.

**Comment by pfrazee** [comment]
Good suggestion, I'll hit that now
