### ISSUE TITLE
This "pane" feature is kinda silly

### ISSUE THREAD

**Issue by despens** [beakerbrowser/beaker#1844]
Dear Beaker developers,

These "panes" are kind of repeating all the 1990's issues of HTML framesets, and adding some more on top:

- The connection in between URL and content displayed in the window is broken by panes. 
  - Panes show which pane is focused via an element that is below the displayed content, breaking how the rest of the window's location and hierarchy would be interpreted from top to bottom.
  - When I click the "back" button, which pane will be affected?
  - When I share the URL, is the person on the other end going to see my current pane setup?
  - When I click "Editor", which pane's contents will I be editing? (The editor is even stretching across the whole window height, regardless if it is split into several horizontal panes.)
- Even if I don't use panes, a Windows 95-y status-bar thing is always visible at the bottom of the window, repeating the drive's or site's title, which is already displayed in the tab and the groovy address bar.
- Beaker already features tabs as most browsers do.
- Typical operating systems today feature reasonable window management, with known interface patterns, keyboard shortcuts etc. There are extensions available that provide the "tiling windows" feature Beaker has implemented with panes, if users would be into that, even for Mac OS and Windows.

My suggestion would be to remove this feature.

**Comment by pfrazee** [comment]
Well we wanted to try something a little adventurous and other than the status bar at the bottom, it's pretty easy to avoid. Sorry it's not 100% your jam but I don't think we're going to remove it. Thanks for the feedback though.
