### ISSUE TITLE
Windows build error from source

### ISSUE THREAD

**Issue by shikhars371** [beakerbrowser/beaker#1845]
hello sir,

I been trying to build 1.0.0-prerelease-7 on windows from source but it always throws me error ,

on windows 64 bit i have, nodejs -12.0.0 , microsoft visual studio 2015, i have used windows-build-tools , i ahve follwed all the prerequisite - :
In Windows, you'll need to install Python 2.7, Visual Studio 2015 or 2017, and Git. (You might try windows-build-tools.) Then run:

npm config set python c:/python27
npm config set msvs_version 2015
npm install -g node-gyp
npm install -g gulp

I am getting error while doing 
npm run burnthemall

C:\beaker-1.0.0-prerelease.7\app\node_modules\fuse-shared-library\lib.js:17
    throw new Error(`fuse-shared-library is not currently supported on: ${platform}`)
    ^

Error: fuse-shared-library is not currently supported on: win32
    at Object.<anonymous> (C:\beaker-1.0.0-prerelease.7\app\node_modules\fuse-shared-library\lib.js:17:11)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:313:38)
gyp: Call to 'node -e "require('fuse-shared-library/lib')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\beaker-1.0.0-prerelease.7\app\node_modules\fuse-native
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

node-pre-gyp WARN Using request for node-pre-gyp https download
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  unpack_sqlite_dep
  'python2.7' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3\
build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\beaker-1.0.0-prerelease.7\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v10.0-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\beaker-1.0.0-prerelease.7\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v10.0-win32-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v10.0"
gyp ERR! cwd C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3\lib\binding\electron-v10.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3\lib\binding\electron-v10.0-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v10.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\beaker-1.0.0-prerelease.7\app\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\beaker-1.0.0-prerelease.7\\app\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3
node-pre-gyp ERR! node -v v12.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3\lib\binding\electron-v10.0-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\beaker-1.0.0-prerelease.7\app\node_modules\sqlite3\lib\binding\electron-v10.0-win32-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v10.0' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XLR8\AppData\Roaming\npm-cache\_logs\2020-11-09T05_00_17_970Z-debug.log
npm run build

Please help me

**Comment by shikhars371** [comment]
hello i resolved the error and ignored fused_library error as i guess its not supported on WINDOWS
but can anyone help me with
this error
"the following tasks did not complete: start, <anonymous>
"Did you forget to signal async completion? "
this im getting when i do npm run start

**Comment by pfrazee** [comment]
Yeah the FUSE error shouldnt break the build. Looking more closely at your log, it seems to be having trouble finding python. Are you sure Python 2.7 is installed?

**Comment by shikhars371** [comment]
sorry my bad its installed everything resolved, programe was not able to find python path, this windows is wierd. thanks

**Comment by pfrazee** [comment]
Good deal!
