### ISSUE TITLE
There is no user setup

### ISSUE THREAD

**Issue by ry-ga** [beakerbrowser/beaker#1847]
"During Beaker's setup, you filled out a name, picture, and bio for your profile. You can visit your profile drive by clicking your picture at the top right of the browser."

I installed the browser and there was no setup. How can I create a profile like the docs show? There is no explanation for this. It's not mentioned in the getting started, the FAQs, etc. It's like everything assumes a profile is created upon installation.

**Comment by pfrazee** [comment]
Those docs were for a feature in the 1.0 beta that we ultimately removed. I'll be removing that from the docs. Sorry for the confusion!

**Comment by xnghu** [comment]
if the user profile is no longer a part of beaker, how can i find the directory page where on a previous install i was able to find other people's sites & or how can i find existing hyper:// pages to visit and learn from?
