### ISSUE TITLE
File cut off

### ISSUE THREAD

**Issue by KyGost** [beakerbrowser/beaker#1848]
**Describe the Bug**

When loading large files via `hyper://`, they are inconsistently poorly loaded (cut off).
This occurs far more often with larger files and seems to occur more with minified (single line) files.

**To Reproduce**
- I don't have a reliable way to reproduce this.
- I have found it occurs often when loading large minified files. If wanted I can setup a demo hyperdrive, else just get a large project's minified version and see if it occurs.
- Occurs seemingly at random, refreshing often with a file that is vulnerable will at times fail due to cut off, at time load properly. The proportion of these occurances seems to be tied to the file based on it's vulnerability.

**Expected Behavior**

Files should not be getting cut off. Need be perhaps javascript files should attempt to reload once or twice if they are cut off. This would be a bad solution though.

**Screenshots**

Not included, let me know if you want some.

**Environment**
 - OS: Windows 10 
 - Beaker Version: 0.8.10 

**Additional Context**

This does not occur in Agregore.
If more information is desired I can try investing a bit more time into this.

**Comment by pfrazee** [comment]
I _believe_ this was an issue that was due to an Electron bug that we fixed and will be correct in the 1.0 release

**Comment by KyGost** [comment]
Awesome, I'll test once that is released.
