### ISSUE TITLE
cannot host Hyperdrives

### ISSUE THREAD

**Issue by xissshawww** [beakerbrowser/beaker#1855]
**Describe the Bug**

I cannot click on and open the peer count on the right side of the address bar. So I cannot  turn on hosting. 

**To Reproduce**

**Screenshots**

<img width="216" alt="image" src="https://user-images.githubusercontent.com/49092559/100406452-d3b9c580-30a0-11eb-9bea-260ba02664bc.png">

**Environment**
 - OS: Catalina 10.15.7
 - Beaker Version: Beaker v1.0.0-prerelease.7

**Additional Context**

I don't if it is because I have never share the url with my friends

**Comment by da2x** [comment]
This is an upstream issue that should be fixed in 1.0.

**Comment by pfrazee** [comment]
Should be fixed in 1.0.0, let me know if it persists for you
