### ISSUE TITLE
Can't click Allow button

### ISSUE THREAD

**Issue by slavnycoder** [beakerbrowser/beaker#1857]
Win10
Cant click allow button.
![image](https://user-images.githubusercontent.com/13649915/100545463-f698d500-326c-11eb-9f2b-2e603fdd8068.png)

**Comment by CerebralDatabank** [comment]
Cannot reproduce on:

Beaker version: 1.0.0-prerelease.7
OS: Windows 10, version 20H2 (x64)

The "Allow" button is clickable and works as intended (camera feed is visible on the page). Also, the elements of the browser and website are in the correct order, unlike your screenshot. I tested it by creating a new hyperdrive from the [Video Chat Template](https://beaker.dev/docs/templates/video-chat/) on the Beaker website.
