### ISSUE TITLE
Can’t scroll in the welcome/license view

### ISSUE THREAD

**Issue by da2x** [beakerbrowser/beaker#1862]
**To Reproduce**
1. Start Beaker with a clean profile
2. Click Next
3. Try to scroll downwards in the license iframe with the scrollwheel or by dragging the scrollbar

**Expected Behavior**
License should scroll.

**Expected Behavior**
Nada.

**Environment**
 - OS: Fedora 33.kde.x86_64
 - Beaker Version: 1.0.0.AppImage

**Comment by Vort** [comment]
Same bug with Windows 7 SP1 x64.

Also please fix "opt opt" typo.

**Comment by pfrazee** [comment]
Fixed both issues for next release, thanks for reporting!
