### ISSUE TITLE
Assign tags to drives from API?

### ISSUE THREAD

**Issue by omgitsraven** [beakerbrowser/beaker#1864]
From what I can tell:
- `beaker.shell.listDrives` and `beaker.shell.selectDriveDialog` can filter for only drives with a particular tag
- `beaker.shell.saveDriveDialog` can assign tags to a drive that it's saving

but
- `beaker.hyperdrive.createDrive` cannot assign tags to the drive that it's creating
- no other `beaker.hyperdrive` API can assign tags to an existing drive either (only to files *within* that drive)

How can a page create an empty drive for a user to write to, and then assign a tag to that drive so that the same page can check for the existence of that drive on the user's next visit?

**Comment by pfrazee** [comment]
Okay I think we need two updates:

 - `beaker.hyperdrive.createDrive` needs a `tags` option
 - `beaker.shell.requestAddTags()` needs to be added to prompt the user to add tags to an existing drive

Sound good?

**Comment by omgitsraven** [comment]
Sounds good to me, thanks!
