### ISSUE TITLE
'disallowCreate' included in saveFileDialog example but not spec

### ISSUE THREAD

**Issue by omgitsraven** [beakerbrowser/beaker#1865]
In this page in the docs: https://docs.beakerbrowser.com/apis/beaker.shell
the example for `beaker.shell.saveFileDialog` shows `disallowCreate` being used as one of the options, but the actual list of options directly above that doesn't mention it. (Though, an option with the same name DOES appear in the list of options for `beaker.shell.selectFileDialog`...)

**Comment by pfrazee** [comment]
Ah that was a docs bug, thanks. Will push fixed docs in a bit.
