### ISSUE TITLE
allow user to create drives and folders in `saveFileDialog` GUI

### ISSUE THREAD

**Issue by omgitsraven** [beakerbrowser/beaker#1866]
If my app calls `beaker.shell.saveFileDialog` to prompt the user to save a new file, and they decide that they'd like to store that file in a new drive, or even a new subfolder of an existing drive, there's no way for them to do so, except to open up My Library in a new tab, create things there, then switch back to the tab where the `saveFileDialog` window is still sitting open. This works, but it's awkward compared to a native file picker. (And in fact, it DOESN'T even work for drives, though I'll create a separate issue for that...)

**Comment by pfrazee** [comment]
Will be in the next release!
