### ISSUE TITLE
Can't refresh list of available drives in already-open saveFileDialog window

### ISSUE THREAD

**Issue by omgitsraven** [beakerbrowser/beaker#1867]
Currently, if the user has interacted with a page to produce a `beaker.shell.saveFileDialog` prompt, and then they decide that they'd rather put the file in question in a new drive, they can open "My Library" and create one... but then, if they change tabs back to the still-open `saveFileDialog` prompt, the new drive will NOT appear inside "My Drives", not even if the user does something like clicking "My Device" and then back into "My Drives" a second time. The only way to get it to appear is to close the `saveFileDialog` prompt entirely, and open a new one.

**Comment by pfrazee** [comment]
Fixed in next release
