### ISSUE TITLE
Window becomes un-snapped when changing tabs with ctrl-tab

### ISSUE THREAD

**Issue by omgitsraven** [beakerbrowser/beaker#1868]
**Describe the Bug**
If the user has snapped a window to one side of the screen in Windows 10, pressing ctrl-tab will jump it back into not being snapped.

**To Reproduce**
1. Launch Beaker
2. Drag the window to the left or right of your monitor (or press WinKey+LeftArrow).
3. The Beaker window should now be taking up half of your monitor.
4. Press ctrl-tab.
5. The Beaker window will now be floating in the middle of your monitor.

**Expected Behavior**
Using a keyboard shortcut to change tabs should not cause the Beaker window to change position as well.

**Environment**
 - OS: Windows 10
 - Beaker Version: 1.0.0.0

**Comment by pfrazee** [comment]
Fixed in the next release
