### ISSUE TITLE
Need to click editor twice to begin typing

### ISSUE THREAD

**Issue by omgitsraven** [beakerbrowser/beaker#1869]
**Describe the Bug**
When changing focus to another program and then returning to Beaker, the editor isn't editable until a subsequent click has been performed.

**To Reproduce**
1. Launch Beaker
2. Open the editor
3. Begin typing in the editor
4. Launch any other program (i.e. Notepad)
5. Position the other program's window so that you can still *see* the Beaker editor (but leave this other window focused for now)
6. With the other window still focused, click the Beaker editor where you would like to begin typing
7. Start typing: nothing happens
9. Click the same place in the editor again
10. Start typing: now text comes out

**Expected Behavior**
Clicking the editor while Beaker isn't focused should both bring Beaker to the front (works correctly) *and* make the editor ready to accept keystrokes (does not work).

**Environment**
 - OS: Windows 10
 - Beaker Version: 1.0.0.0

**Comment by pfrazee** [comment]
Fixed in the next release
