### ISSUE TITLE
Music on YouTube do not stop playing if you close tab with Alt+F4

### ISSUE THREAD

**Issue by Vort** [beakerbrowser/beaker#1871]
**Describe the Bug**
Browser should free tab's resources when its window is closed.

**To Reproduce**
1. Start playing any video on YouTube.
2. Press Alt+F4.

**Expected Behavior**
Tab is closed completely.

**Environment**
 - OS: Windows 7 SP1 x64
 - Beaker Version: 1.0.0.0

**Comment by pfrazee** [comment]
Can't believe this one fell through the cracks! Fixed in next release.
