### ISSUE TITLE
Browser window opens without address bar and shows random sites

### ISSUE THREAD

**Issue by Vort** [beakerbrowser/beaker#1872]
**Describe the Bug**
Before all previews are created, open new tab feature creates broken tabs.

**To Reproduce**
1. Start with clean profile.
2. Close browser window.
3. With tray icon, "Open new tab".

**Expected Behavior**
Full-featured tab should be opened.

**Screenshots**
![baker](https://user-images.githubusercontent.com/1242858/101272863-e1560600-3798-11eb-92d1-9b654087eb2a.png)

**Environment**
 - OS: Windows 7 SP1 x64
 - Beaker Version: 1.0.0.0

**Comment by pfrazee** [comment]
That's bizarre and shouldn't ever be possible! (Obviously)

Had you visited reddit recently? What is your setting for "When beaker starts?"

![image](https://user-images.githubusercontent.com/1270099/101273388-88677d00-375a-11eb-8e4c-f903e82883ce.png)

Any other possibly relevant information about what happened prior to this?

**Comment by Vort** [comment]
> Had you visited reddit recently?

No. This happens with clean profile.
Not only Reddit shows, but also Patreon.
It is probably related to default bookmarks and preview creation.

> What is your setting for "When beaker starts?"

Default:
![image](https://user-images.githubusercontent.com/1242858/101273460-4102e000-379e-11eb-9892-4c9527645cf2.png)

**Comment by pfrazee** [comment]
Okay thanks, I'll look into this. Might be a win7 specific bug, I only have
10 to test against.

**Comment by pfrazee** [comment]
Okay should be fixed in next release, thanks for the issue!
