### ISSUE TITLE
Bookmarks fail to save

### ISSUE THREAD

**Issue by basham** [beakerbrowser/beaker#1876]
I'm running Beaker v1.0.0 on macOS v10.15.7. I'm trying to save a bookmark, but it silently fails.

When attempting to save a bookmark in the URL toolbar with the star button, nothing happens after clicking the Done button. The popup doesn't even close.

When attempting to save a bookmark from the Bookmarks page (`beaker://library/bookmarks`), I notice some console logs, with one of them being an error.

![Error in edit-bookmark.js, line 168](https://user-images.githubusercontent.com/347558/101409624-228b0a80-38ac-11eb-9325-e00811020138.png)

When inspecting the General Logs, I notice that there's a failure in creating the bookmarks directory.

![Logs indicate an error in creating bookmarks directory](https://user-images.githubusercontent.com/347558/101410162-ed32ec80-38ac-11eb-995c-a400bf81fea3.png)

Maybe the issue is due to my odd hardware configuration. As I informed @pfrazee during the beta (via Twitter DM), my user folder is on its own hard drive, separate from the system drive. That seemed to cause problems with sqlite and making Beaker beta unable to start up. But since the v1.0.0, Beaker replaced sqlite with Hyperbee, making it able to start up fine.

As comparison, I have another Mac running macOS 11.0.1 with Beaker v1.0.0, and it does not encounter any problems with saving bookmarks.

**Comment by basham** [comment]
Well, I just as a quick test, I deleted Beaker and the two hidden directories `~/Library/Application Support/Beaker Browser` and `~/.hyperdrive`. Then reinstalled Beaker v1.0.0. And now bookmarks are working fine. Also, I now notice a new `~/.hyperspace` directory and no new `~/.hyperdrive` directory.

Closing this bug as a non-issue. 🤷

**Comment by pfrazee** [comment]
Okay sorry you had weirdness but glad it resolved
