### ISSUE TITLE
Broken images and links on beakerbrowser.com/docs

### ISSUE THREAD

**Issue by JerryGreen** [beakerbrowser/beaker#1888]
Broken images: https://beakerbrowser.com/docs/using-beaker/
Broken links (from the page above; returns 404): https://beakerbrowser.com/docs/tutorials/host-outside-of-beaker.html

## Preview

![image](https://user-images.githubusercontent.com/13215662/102825801-5f551680-4401-11eb-8b89-05bf9f8d9194.png)

**Comment by Vort** [comment]
I found this problem too, because Google showed me those pages.
But if you will start navigation from main page, then you will get to https://docs.beakerbrowser.com/ .
Which have no problems with images.

**Comment by JerryGreen** [comment]
@Vort yeah, though I don't see `host-outside-of-beaker` page there, which was quite interesting content

**Comment by pfrazee** [comment]
I'm going to replace all those pages with redirects to avoid confusion. @JerryGreen if you think any of the docs should carry over, we can make a separate issue
