### ISSUE TITLE
broken: docs.beakerbrowser.com

### ISSUE THREAD

**Issue by paulwratt** [beakerbrowser/beaker#1939]
**Describe the Bug**
I followed a [Wikipedia "References" link](https://beakerbrowser.com/docs/guides/use-a-domain-name-with-dat#well-knowndat) to:
https://beakerbrowser.com/docs/guides/use-a-domain-name-with-dat#well-knowndat
the page comes up, but the content has a redirection to:
https://docs.beakerbrowser.com/
but all I get is:
```
This site can’t be reached
docs.beakerbrowser.com took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT
```
**_AND_**
```
This site can’t be reached
docs.beakerbrowser.com refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

**To Reproduce**
see above. and another example:
https://docs.beakerbrowser.com/apis/beaker.shell#beakershelltagdriveurl-tags

**Expected Behavior**
proper redirection? (but the actual domain/url is not accessible anyway).

**Environment**
any web browser

**Additional Context**
In cases like this where a site redesign has only change the url, any links in the content should point to the new domain/url, and the content should be displayed anyway. At least this way the actual link would still be useful, even when the redirction is broken or the new domian is not accessible.

**Comment by pfrazee** [comment]
Looking into this now, sorry about that!

**Comment by pfrazee** [comment]
Okay this should now be fixed. DNS may take a second to propagate. Please let me know if it doesn't show up for you in the next 6 hours.
