### ISSUE TITLE
Cannot find module multihashes (or cids, or lodash)

### ISSUE THREAD

**Issue by siddharthist** [beakerbrowser/beaker#207]
After running the instructions in the readme (`git clone`,  `npm install`, `npm run rebuild`, etc.), I encountered the following error:
```
Uncaught Exception:
Error: Cannot find module 'multihashes'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/siddharthist/beaker/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/siddharthist/beaker/app/node_modules/ipfs-api/src/api/block.js:6:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```
It was not fixed by running `burnthemall`. It was fixed by running `npm install multihashes`, although I then encountered the same error with `cids` and then `lodash`. After manually installing all of these, Beaker started successfully. 

Operation System: Fedora 24
Beaker Version: HEAD (fd670e9d3c2b04ddcda328112eb0768f3f09ee6a)

**Comment by poga** [comment]
what's the version of your npm?

it seems like `ipfs-api` requires npm 3

**Comment by siddharthist** [comment]
```
[nix-shell:~/Dropbox/tex/math201]$ npm --version
2.15.9
```

**Comment by pfrazee** [comment]
Yeah I saw that same error yesterday, and it was somebody with npm 2.x.

@siddharthist could you follow this procedure for me?

 1. Go to `./app` in Beaker
 2. Do `npm install multihashes`
 3. Do `(cd ..; npm run build)`. If that succeeded, do `(cd ..; npm start)`.
 4. You should get *another* failed install. There's 2 or 3 modules, when I saw it, that had this problem. Repeat steps 2 & 3 on each missing module.

When it successfully runs, tell me which modules you had to install manually. I'll add them to the package.json, and we should be done with this error.

(Sorry to ask you to do this!)

**Comment by pfrazee** [comment]
@siddharthist I just noticed in the issue title, you listed 2 others, so maybe you already went through this. Is that all of them?

**Comment by pfrazee** [comment]
Aaaaand now I bothered to read your issue report. Yes, you did.

Forget what I asked. I'll add those modules to the package.json.

**Comment by pfrazee** [comment]
Thanks for reporting.

**Comment by siddharthist** [comment]
@pfrazee Thanks for the quick fix!
