### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by langston-barrett** [beakerbrowser/beaker#209]
Any reason in particular that this project doesn't already use some form of Continuous Integration testing?

**Comment by pfrazee** [comment]
No particular reason, I just haven't prioritized it yet.

**Comment by siddharthist** [comment]
Just a quick plug: if it were set up to test with multiple versions of `npm`, I would never have encountered #207. Something to consider!

**Comment by pfrazee** [comment]
Good point! Do you have any experience setting up travis with an electron app? I havent researched it yet

**Comment by siddharthist** [comment]
I don't, unfortunately :(

**Comment by pfrazee** [comment]
No worries

**Comment by ShadowRZ** [comment]
Maybe this can help.
https://electron.atom.io/docs/tutorial/testing-on-headless-ci/
