### ISSUE TITLE
IPFS Urls with trailing slashes search DDG

### ISSUE THREAD

**Issue by Miserlou** [beakerbrowser/beaker#212]
Operation System: OSX
Beaker Version: 0.5.0

Works: `QmVktW6uo1mcqSiufH7fmExsmyC7dFx2GCYiEDmJLSatnD`
Doesn't: `QmVktW6uo1mcqSiufH7fmExsmyC7dFx2GCYiEDmJLSatnD/`

:(

**Comment by pfrazee** [comment]
Will include a fix in 5.0.1. Sorry for the trouble, and thanks for reporting!
