### ISSUE TITLE
Add r/hashsites to Favorites list

### ISSUE THREAD

**Issue by Miserlou** [beakerbrowser/beaker#213]
So far, I've had a bit of trouble finding IPFS sites to play with. :(

I used to have this problem with Tor, so I started [reddit.com/r/onions](https://reddit.com/r/onions), and now it's grown to a community of over 50,000 users!

So, I've started [r/hashsites](https://reddit.com/r/hashsites) to solve this problem for IPFS. It'd be awesome if Beaker could include this as one of the default bookmarks so new users would have some stuff to explore.

If you're redditors, I'd be happy to add you as mods to the sub as well. I've also added Beaker to sidebar.

**Comment by pfrazee** [comment]
Oh cool, yeah this is a great idea. We should also expect dat:// sites.

**Comment by pfrazee** [comment]
I'm raging-rageaholic, if you want to mod me

**Comment by Miserlou** [comment]
Bam, added. Feel free to add any content you can find too.

**Comment by pfrazee** [comment]
Awesome
