### ISSUE TITLE
Do a release for Linux Distros

### ISSUE THREAD

**Issue by nicopace** [beakerbrowser/beaker#224]
That!
I'm available to test it.

**Comment by pfrazee** [comment]
Have you tried building from source? Also, what arch?

**Comment by nicopace** [comment]
Will do... but would be awesome to have a public release for GNU/Linux, as there are a big bunch of people related to the P2P movement that would love to test it.

**Comment by pfrazee** [comment]
For sure, I'm just balancing the resources on hand is all. Hopefully soon.

**Comment by kaosat-dev** [comment]
As discussed a bit on Twitter, I am starting to look into creating packages for Linux distros: realistically speaking (time constraints) however I will only be able to test on Debian :)

**Comment by pfrazee** [comment]
The work has been done for this. I think we'll have it in our next release, as an appimage.
