### ISSUE TITLE
Support <meta> tag to discover dats

### ISSUE THREAD

**Issue by mafintosh** [beakerbrowser/beaker#228]
Would be super cool if I could add a meta tag to my index.html telling beaker that my website is available as a dat (or the data inside the website). 

That way it would be easier to bootstrap new users to download dats.
My suggestion would be be

``` html
<meta name="dat" content="deafbeef..." description="Optional description detailing what the dat is">
```

If beaker sees a tag like that it would show an option to add the dat.

**Comment by pfrazee** [comment]
Yeah, I'll need to toy with the UX for suggesting the URL, and also think through if there are any security concerns. (Eg would it be possible for user content to have that meta tag and make it appear official.) I should look into how atom/rss has done it in the past.

I'd also suggest we use `<link rel=alternate>`. 

```
<link rel="alternate" href="dat://.../">
```

Might also consider [rel=canonical](https://tools.ietf.org/html/rfc6596)

**Comment by pfrazee** [comment]
This has been solved with https://github.com/beakerbrowser/beaker/pull/275
