### ISSUE TITLE
Endless redirect bug, only in beaker (not chrome)

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#232]
Operation System: *
Beaker Version: 0.5.1

The link in question: https://t.co/3xEjsV2EiE

Link gets stuck in an infinite redirect loop, but only in Beaker (not eg chrome).

**Comment by millette** [comment]
It works for me with Beaker 0.7.2 (and a bit of master thrown in) on Debian.

**Comment by cdaringe** [comment]
works for me too, 0.7.5

**Comment by pfrazee** [comment]
Yeah I'm unable to reproduce anymore. Closing.
