### ISSUE TITLE
Tab Positioning

### ISSUE THREAD

**Issue by wesleytodd** [beakerbrowser/beaker#233]
Operation System: All
Beaker Version: 0.5.1

Would be a handy feature for parity with how other browsers work.  So if you close tab at index 2 then `cmd-shift-t`/"re-open tab", instead of opening it at end, re-open at index 2.

Also, would be nice if `cmd-click`/"open in new tab" opened tab in the index next to the current tab.  Again, similar to the behavior in other browsers.

**Comment by wesleytodd** [comment]
Would you like another issue for opening new tabs next to their opener? or just this comment here?

**Comment by pfrazee** [comment]
Just edit this one to include both

**Comment by pfrazee** [comment]
This got done
