### ISSUE TITLE
Dat site events

### ISSUE THREAD

**Issue by marcelklehr** [beakerbrowser/beaker#235]
It would be nice to be able to subscribe to changes to a dat site in an app.

**Comment by pfrazee** [comment]
Yeah, in the API? Like `dat.on(URL, 'update', (e) => ...)` ?

**Comment by marcelklehr** [comment]
yup, something like that would be cool.

**Comment by pfrazee** [comment]
Yeah, that's a must-have. I'll try to bump it up in priorities.

**Comment by pfrazee** [comment]
Consolidating this issue into https://github.com/beakerbrowser/beaker/issues/311, closing
