### ISSUE TITLE
dat API: writeFile encoding option is not optional

### ISSUE THREAD

**Issue by marcelklehr** [beakerbrowser/beaker#237]
Operation System: Ubuntu 16.04
Beaker Version: https://github.com/beakerbrowser/beaker/commit/8c32d5cbc35a3f6e6f3700e68e9a9c5329801a0e

I tried to dat.writeFile without specifying an encoding and got an exception. I assumed utf8 (or anything else, really) would be the default encoding due to the `?` in the method signature in the docs. I might have been assuming wrong, though :)

**Comment by pfrazee** [comment]
You're assumption is right, it should be optional. What exception did you get?

**Comment by marcelklehr** [comment]
A WriteFileError, I think. The error message was an empty string.

**Comment by pfrazee** [comment]
Can you confirm that was the error? A WriteFileError is an unexpected internal issue. If you run Beaker from the CLI, you should see a more descriptive error in the console if that occurs.

**Comment by pfrazee** [comment]
Also what was your usage of the method?

**Comment by marcelklehr** [comment]
Ah, the I log was helpful. I had a trailing slash in the filename... My bad, sorry for the noise :)

**Comment by pfrazee** [comment]
No worries!
