### ISSUE TITLE
Enhancements to improve UX that encourage a "critical mass of hosts required for site reliability and availability"

### ISSUE THREAD

**Issue by rjsteinert** [beakerbrowser/beaker#244]
I just experienced for the first time spinning up a hello world index.html using dat and then accessing it in the Beaker Browser. From nothing to published on the distributed web in three commands. Very slick! However I'm left wondering how I'm going to persist my little hello world. When I shut down my computer, the hello world goes away. I need to get more people to host it for me! If I share my dat URL with my friends, I can instruct them to click a 2 levels deep and then click the Host button... But how about promoting that host button to the forefront? There seems to be a social dynamic to site reliability/availability here, with a critical mass of people hosting, the website will stick around and always be available. If there were a metric also on that host button of how many other people are hosting it, if I like that page and I see it has not reached critical mass, then I have an incentive to host because I want that page to stick around so I would be more likely to click the host button.

**Comment by rjsteinert** [comment]
We could call this an enhancement to improve UX that encourages a "critical mass of hosts required for site reliability and availability".

**Comment by pfrazee** [comment]
Maybe we should put a Host button next to the Bookmark button, in the navigation toolbar?

Our plan to solidify site uptime is to use Public Peer services. The current public peer project is called [hypercloud](https://github.com/joehand/hypercloud); it's what I'm working on when I'm not working on beaker.

**Comment by rjsteinert** [comment]
> Maybe we should put a Host button next to the Bookmark button, in the navigation toolbar?

My guess is that would be a good start to encouraging people to host. I'm also wondering about what kind of incentives are tied to hosting. For example, I share a link on Facebook often because it's something that should be promoted. In that same user story, I think my incentives are also aligned to host that piece of content/site. Just getting creative here and throwing out ideas, but maybe something like a social share button that automatically also starts hosting what you shared?

**Comment by rjsteinert** [comment]
hypercould looks rad, I read the spec on profiles. Are you thinking about incorporating those profiles into Beaker? That seems like the start of a decentralized social network to me where by being friends with someone you also host their content. Everyone has a social network and practices "I scratch your back if you scratch mine" but in this context it becomes "I'll host yours if you host mine".

**Comment by pfrazee** [comment]
You could very easily build a social community with that premise, but my plan is to use public peers to ensure availability. Hosting doesn't cost that much; better just to use a service than task your friends.

**Comment by rjsteinert** [comment]
I was thinking today how content on the Distributed Web has a chicken and egg problem: A piece of content can't be seen without a critical mass of hosts and a piece of content can't get critical mass of hosts without people who see the it.

It's tough for a new piece of content out there right now. When I published the other day I wondered, "Will someone try to visit this when my computer is off?" If I had a contract with a group of folks to host each others content, it wouldn't be a problem. It sounds like what you'll be setting up is that first friend who will host everyone's content thus providing a guarantee that it can be seen at least until it reaches a critical mass of hosts. In regards to disk space, this seems doable, Internet Archive is doing essentially that and without a monetization strategy as far I can tell. But I imagine they might not pay as much in bandwidth as this project potentially might have to if folks are lazy / take for granted that content will be hosted by a public peer. Take a look for example at the dynamic of the Bitcoin network, major centralization of processing power and that's even with getting paid as a miner. 

However! If folks are good citizens and click "Host" on their favorite things like foxnews, msnbc, etc. then the bill for high traffic sites will be widely distributed. Perhaps `more hosts == faster network speeds` which for someone who believes in something like foxnews or msnbc, this would be a personal goal to make sure that information spreads as far and as wide as possible. Afterall, the Bitcoin example is not one of `more hosts == faster network speeds`, it has a hard-coded speed limit.

**Comment by pfrazee** [comment]
The public peer we run will be a free-tier/paid-tier service. Probably something along the lines of 10gb storage free (100gb outbound traffic cap) and then $10/mo for 1tb storage. That's how we'll handle our hosting economics.

**Comment by rjsteinert** [comment]
That makes sense. 1tb storage, that's like a Super Duper Friend!

**Comment by pfrazee** [comment]
Hah yep. Still have to work out the economics so that price/storage amt may change.
