### ISSUE TITLE
Question: Mapping domain to dat link?

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#246]
Does Beaker support a DNS record for mapping a domain to a dat link? Say I wanted `domain.com` to point to `dat://...`, can I do this?

Apologies, as I know this is probably more of a Dat question than a Beaker question.

**Comment by aaronshaf** [comment]
Looks like my question was answered at:

https://youtu.be/pi-kreA52oI?t=17m28s

**Comment by pfrazee** [comment]
Im actively considering using TLS (https://github.com/beakerbrowser/beaker/issues/227). If you have thoughts on that, please share!
