### ISSUE TITLE
dat.stat on directories doesn't reflect changes of children

### ISSUE THREAD

**Issue by marcelklehr** [beakerbrowser/beaker#249]
Operation System: Ubuntu 16.04
Beaker Version: 338d856

Steps to reproduce:

1. Create a new directory
2. create a file inside the new directory a few seconds later

Run `dat.stat` on the directory.

**Expected result:**
mtime equals mtime of the new file.

**Actual result:**
mtime is the creation time of the directory.

**Comment by pfrazee** [comment]
Ah, I hadn't considered this case. This may need to wait until some upstream changes to the dat stack.
