### ISSUE TITLE
beaker logo isn't shown in the start-bar: ubuntu 16.10

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#250]
Operation System: ubuntu 16.10
Beaker Version: 0.5.2  master branch

I just compiled the latest version from source. -> worked. 

I did experience the same problem described here: https://github.com/electron-userland/electron-packager/issues/90#issuecomment-117807617

And the solution is described here: http://electron.atom.io/docs/api/browser-window/

I do have a patch, so PR is incoming. ... 

Do you have any special rules, that need to be followed? eg: signing off the PR, CLA or such?

**Comment by pfrazee** [comment]
Thanks for reporting, and for the PR.

No CLA, I just review and merge.
