### ISSUE TITLE
Page rendered at 100% zoom, even if page settings show 150%

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#253]
Operation System: ubuntu 16.10
Beaker Version: 0.5.2

To reproduce: 

- Open any page eg: https://groups.google.com/forum/#!forum/beaker-browser
- set zoom level to eg: 150% -> OK
- open a new group eg: https://groups.google.com/forum/#!forum/tiddlywikidev
- -> problem
  - The zoom level in the URL bar still shows 150%
  - The page is rendered with 100%
  - [ctrl] [+] sets zoom level to 175% and renders the page accordingly. 
- [F5] page reload produces the same -> problem

Is anyone else experiencing this behaviour?

It's extremely irritating for me, since I basically have to fix the zoom level after every page reload using a hiDPI display.

**Comment by pfrazee** [comment]
I'll look into it

**Comment by pmario** [comment]
Seems to be fixed, by ongoing development. I'll close it for now. Can't be reproduced anymore. :)

**Comment by pfrazee** [comment]
Woot!
