### ISSUE TITLE
Help menu is missing for ubuntu / win

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#256]
Operation System: ubuntu 16.04
Beaker Version: 0.5.2

The Help menu is completely missing. IMO It should be: 

File:   Edit:   View:  History: Window: BeakerDev: Help: 

Help: 
 - Help ... links to: https://beakerbrowser.com/docs/
 - Report Bug ... https://github.com/beakerbrowser/beaker/issues
 - Mailing List ... https://groups.google.com/forum/#!forum/beaker-browser
 - -- Seperator-- 
 - About .. same as Darwin About page

**Comment by pmario** [comment]
should I create a PR?

**Comment by pfrazee** [comment]
If you like. If not, I can hit it.

(Thanks for all these reports!)

**Comment by pmario** [comment]
It's a very interesting project. ... and may help the TiddlyWiki community quite a lot :)

**Comment by pfrazee** [comment]
I sure hope so!
