### ISSUE TITLE
<input> element focus() has different behaviour as with chrome browser

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#261]
Operation System: ubuntu 16.10
Beaker Version: master - commit 77e9f72

To reproduce: 

Try this MTC with chrome and then with beaker
 - https://jsfiddle.net/7t04wszc/15/   with autofocus attribute
 - https://jsfiddle.net/7t04wszc/16/   without autofocus.

related to: https://groups.google.com/d/msg/beaker-browser/9m8pQXshSeo/bEAs3OH2AwAJ but my MTC is a bit different, since the TW UI is much more complex.

may be related to: #253

**Comment by pmario** [comment]
MTC also tested with chrome and win10 pro. -> works there as expected.

**Comment by pfrazee** [comment]
I'll check this out, thanks for reporting
