### ISSUE TITLE
Beaker failing

### ISSUE THREAD

**Issue by mariokamenjak** [beakerbrowser/beaker#266]
Operation System: Linux, Debian testing
Beaker Version: 0.6.0

Beaker fails to launch with the following errors:
> @ start /home/zmaj/Preuzimanja/beaker-master
> gulp start

/usr/bin/env: „node”: Nema takve datoteke ili direktorija

npm ERR! @ start: `gulp start`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.8.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/zmaj/Preuzimanja/beaker-master
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/zmaj/Preuzimanja/beaker-master/npm-debug.log
npm ERR! not ok code 0

I hope you make an appimage.

**Comment by pfrazee** [comment]
Hi @mariokamenjak! Sorry for the trouble.

This looks like it might be a problem with the way Ubuntu installs nodejs. Could you try the steps in this stackoverflow and let me know if it solves your problem? https://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

**Comment by mariokamenjak** [comment]
It's Debian, not Ubuntu... Well let me try...

**Comment by pfrazee** [comment]
Oh, hmm. Yeah it looks like `node` is not installed, at least under the
name "node"

**Comment by mariokamenjak** [comment]
The first solution worked. Thank you. This will aid my paper about IPFS.

**Comment by pfrazee** [comment]
Good deal. Make sure you have the ipfs daemon running to use it.

Cheers

**Comment by mariokamenjak** [comment]
I know. I also need to make sure that my university doesn't block the default IPFS ports. Something that I learned after several hours of troubleshooting :)
