### ISSUE TITLE
AppImage packaging for Linux

### ISSUE THREAD

**Issue by mariokamenjak** [beakerbrowser/beaker#267]
Operation System: Debian Linux
Beaker Version: 0.6.0

Could you please investigate about making an AppImage package for Linux? If you do it will pretty much run on most distros. Well, maybe IPFS itself would be the only outside dependency, as I see packaging a separate IPFS in an appimage as a challenge.

**Comment by pfrazee** [comment]
Thanks for filing! We'll see what we can do

**Comment by probonopd** [comment]
electron-builde supports generating AppImage natively:
https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions-target

**Comment by SammDu** [comment]
Yeah @pfrazee plz maintain binaries for more platforms other than OSX, this project is really interesting to me and I hope I could try it out someday ;-)

**Comment by pfrazee** [comment]
Definitely, it's on the roadmap

**Comment by probonopd** [comment]
Since the AppImage for Linux is now available from https://beakerbrowser.com/docs/install/ I think this can now be closed. Thank you for providing the AppImage!

**Comment by pfrazee** [comment]
Ah thanks @probonopd !
