### ISSUE TITLE
Dat: ability to view html file without extension

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#272]
Is there a way to tell Beaker to treat `foo` as `foo.html`? Thanks!

**Comment by aaronshaf** [comment]
same issue with `/` and `/index.html`

**Comment by pmario** [comment]
But what if `foo` is a valid resource name?

**Comment by aaronshaf** [comment]
Perhaps resolve `foo` if it exists, and then `foo.html` or `foo/index.html`if not?

**Comment by pfrazee** [comment]
A couple questions:
 
 - Is this for dat?
 - Is the issue that you have a /foo.html, and you want /foo to load /foo.html ?
 - What happens now? Does it 404, or does it show foo with the wrong content type?

**Comment by aaronshaf** [comment]
Yes, dat. 

Two separate proposals:

1. `/foo/` loads `/foo/index.html` if `foo` file doesn't exist.
2. `/foo` loads `foo.html` if `foo` file doesn't exist.

Either would return a `text/html` content type with a `200 OK`.

#1 seems most standard browser behavior and has the benefit of parity with local "normal" behavior.  #2 not so much.

The big idea is that people are used to hosting web sites without showing the extension. Aesthetics, but still important. This is how GitHub routes automatically as well for Jekyll-generated sites.

**Comment by pfrazee** [comment]
Yeah I think I'm on board with both proposals. Let me think about it for a little bit, to make sure I'm not forgetting anything, but I'll give a soft 'yes' on both.

**Comment by tekknolagi** [comment]
I vote for proposal #1.

**Comment by pfrazee** [comment]
Turns out proposal 2 was already implemented. Proposal 1 will be in the next release.

Did you have trouble making proposal 2 work? It should be working (it is for me)
