### ISSUE TITLE
TypeError: ["patch","minor","major"].includes is not a function

### ISSUE THREAD

**Issue by crislar** [beakerbrowser/beaker#274]
Operation System: MacOS 10.12.2
Beaker Version: 0.6.0

going through the beaker tutorial creating and running a website
https://beakerbrowser.com/docs/howto/publish-a-site.html

Publish changes
Let’s add an index.html:
~/my-site echo "<h1>Hello, world</h1>" > index.html
~/my-site bkr publish 1.0.0

I get error 

TypeError: ["patch","minor","major"].includes is not a function

Everything up to that point including accessing the raw directory json file works as anticipated.

**Comment by pfrazee** [comment]
That's pretty odd! What version of node are you using, and how did you get Beaker... build from source, or downloaded binary?

**Comment by crislar** [comment]
sorry for the delay. this was running on MacOS 10.12.2. I think I downloaded the binary.

**Comment by pfrazee** [comment]
Ok, I think this might have been a problem with the node version you're running, but the new version of bkr (not yet released) removed the offending code, so hopefully fixed in bkr 2.0.0
