### ISSUE TITLE
thoughts about new start page

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#278]
Operation System: ubuntu 16.10
Beaker Version: 0.6.0 latest master commit: f3a95e4

I do have several thoughts about the new start page. I did mark the numbers with stars, so they are more visible.

![beaker-issue-1](https://cloud.githubusercontent.com/assets/374655/22642018/4a5636e6-ec59-11e6-884a-d570783c5554.gif)

1: The P2P icon is OK since users know the "share" icon. ... But it is still new and imo not established. So imo it needs some explanation (link). Eg: is the protocol secure ??

2: If I open info popup with the P2P button, it shows info about the URL, which is OK. But it should also contain information about the `dat:` protocol. Similar to FireFox `https://` info. ... The new Chrome Info imo is way overloaded. .. but still has some info about the protocol. Most important: **is it secure?**

3: IMO this "footer" looks completely "lost". It spans 2 columns. So it's not clear, where it belongs to? ... Should it be a "call to action"?. If so, it needs to link to more possibilities and needs different styling. .. The whole page should use "Verdana", which is "sans serif". -> OK 

But on my system, it uses "Liberation serif" as a fallback, which looks ugly. So imo the CSS needs a better definition: `Verdana; sans-serif`, which would fall back to "Liberation sans", which looks better. ... **It should probably use the same setting as the "New tab"**

4: Where is the sidebar? ... As I saw this page the first time, I was shocked. I thought. the "sidebar" is gone. ... As a new user, I'd "try to " open all the links and then get lost. ... What now?

5: IMO those icons are not visible enough, to get a newbie going. See 4: ... IMO we have a UX regression here. 

6: all `dat:/` links seem to be broken

7: icons?  IMO those icons don't fit the topics. ... but if these are placeholders only. .. it's just a reminder. 

8: icons? github? IMO there should be the platform icons used.

As noted! ... just some thoughts.

**Comment by pmario** [comment]
>6: all dat:/ links seem to be broken

IMO this is the worst thing, that can happen. As a newbie I'd think: "OK .. The whole thing is broken" .. I'm gone. ... 

So those links should only be there, if they work. ...

Even as a dev, I'm not sure, if the resources are not ready yet, or if there is an issue with the code. .. So in any way, there is a problem.

**Comment by pfrazee** [comment]
Appreciate the feedback! You make some really good points. Let me go down the list.

1. It is secure. Maybe the label should be "Secure P2P"

2. We can definitely give more info, especially since this is the foremost indicator of the novel tech in Beaker. We'll make an issue for this for 0.6.2.

3 & 7 & 8. Agree, and thanks for the heads up on the fonts. There's lots more design to be done here.

4 & 5. This is something we went back-and-forth on. This site (dat://hostless.website) gets loaded on first open. The interface that you're familiar with is now loaded when you create a new tab.

The main reason for hostless.website is to give users (especially new users) content to interact with immediately. Specifically, websites hosted on dat, and help docs.

Knowing our motivation, what are your thoughts on this change?

6. That's a bug that surprises me. What happens? That probably needs to be a separate issue.

**Comment by pfrazee** [comment]
@pmario also, sorry this was a disappointing change. This is a WIP change that probably shouldn't be in master -- though I'm glad to get this feedback, so who knows.

Stick with us here, we'll get this right.

**Comment by pmario** [comment]
>@pmario also, sorry this was a disappointing change.

... It's great to see progress :)

I try try to write things down, when they are fresh. .. Because after a day or two I get used to it. ... I think, we only have a very short period, to see things through "newbie" eyes. ... 

>Stick with us here, we'll get this right.

It already is a great browser, and a very interesting project!

**Comment by pfrazee** [comment]
Decided to revert back to beaker:start per your feedback, and rethink that idea.

@pmario Can you tell more about issue 6, and the failed dat loads? What did you see?

**Comment by pmario** [comment]
> Can you tell more about issue 6, and the failed dat loads? What did you see?

I just found out, that both "beaker teamblog" links point to the same `href` ... Is there a link, to the page source?

@pfrazee  - I get a 408 timed out
dat://www.datprotocol.com  ... same thing. 408

I'll have a look, if I can create a local test page. ... didn't check this for a while.

**Comment by pfrazee** [comment]
Huh, that's strange. I've got the site hosted from a VPS, so there
shouldn't be any connectivity issues. And you've definitely had some
success syncing sites, because you downloaded hostless.website (which this
issue is about).

**Comment by pmario** [comment]
@pfrazee You may have missed this info: Both beaker team block links point to: `dat://paulfranzee.com` if you click the links.

**Comment by pmario** [comment]
`dat://paulfrazee.com` .. works now. .. strange. 

What I did: 

 - I wanted to save `dat://hostless.website`
 - Then clone it -> problem 2 files where missing: `text.txt` and `steak_meat.png`
    - beaker was unable to load them. ... It showed the spinning wheel for about 10 min, then I closed the page
    - CPU load went up to about 40% for every core. normal is: 30% 1 core, 3-5% 3 cores
 - I did save `dat://hostless.website`
    - I did manually open the 2 missing files. 
    - They where loaded. -> Still a problem with the hidden files `dat.json and .DS_Store`
    - I did manually open them -> which worked. 
    - Now it was possible to Fork `dat://hostless.website`
  - After all those steps -> I can open `dat://paulfranzee.com` now. 
    - `dat://www.datprotocoll.com` -> shows 408
  - `dat://taravancil.com` manually typed into URL bar-> opens: `dat://db3a51..17/#timeout` and shows: "Searching the network for this site. Please wait..."  .. for ever 
     - cpu load up to ~40% for all 4 cpus :/

**Comment by pmario** [comment]
My question now is: "Is there a fast way to spin up a dat:// server in the cloud, to play with" .. including DNS name resolution? like `dat://paulfrazee.com`.. 

Can it handle IPv6?

**Comment by pfrazee** [comment]
> My question now is: "Is there a fast way to spin up a dat:// server in the cloud, to play with" .. including DNS name resolution? like dat://paulfrazee.com..

Yes. I'm using [dathttpd](https://github.com/beakerbrowser/dathttpd) on a VPS to host all of these sites, which, among other things, is a way to run `dat`. I'll announce this tool soon.

 > Can it handle IPv6?

I haven't tried, so I'm not sure.

About your other reports, I think there are three issues at work here. Here's what I see happening:

 1. The original issue was a data-loss problem with `dat`. That has since been resolved, which is why some pages started to load.
 2. A new problem seems to be that there are network connection errors. I'm seeing some signs of that in other tests, so I'll need to start debugging.
 3. The high CPU usage. I have some guesses about why that might be happening, but it won't be easy to solve.

I'll let you know when I make progress on the second item

**Comment by pmario** [comment]
just some more feedback

>4 & 5: This is something we went back-and-forth on. This site (dat://hostless.website) gets loaded on first open. The interface that you're familiar with is now loaded when you create a new tab.

I think at the moment, a live "Welcome" page is risky. ... It seems you only have the possibility to develop / test with macOS. ... Problems that I encounter (using ubuntu) may have several reasons. 

  - real issue ... as we found out :)
  - OS specific quirks
  - dat: resource (temporary) unavailable or different issue

So it's very hard to decide, where to search. ... I didn't even try to compile the stuff on windows 10. (because of #55 and #103) ... which will open a new universe of possible issues :)

**So I'd suggest:** Give `dat://hostless.website` a new title eg: 

Welcome to Beaker - Find and share you dat sites !

and PIN it as the first favourite. So we can be pretty sure, that it is clicked by every user.
PIN ... would be a new functionality, that removes the "x" - delete button, and moves the pinned-fav to the top of the list ;)

----

>The main reason for hostless.website is to give users (especially new users) content to interact with immediately. Specifically, websites hosted on dat, and help docs.

I like this.. but as I wrote, If the first _and_ the second click doesn't work, it looks broken. And the average user has no chance to see, what's the real problem. ... 

-----

>Knowing our motivation, what are your thoughts on this change?

I like the structure of the page from the OP. 

 - 3 columns: "social"   |  "how to"  |  "geeky stuff" 
 - Just the "Welcome to Beaker"  ... as it is now is missing
 - The new footer is better, but imo may be changed in the future. 

__but__ ...  

At the moment for me it feels to risky. I like the "pinned - fav - page" idea :)

I don't know, the system well enough, to trust it. I don't know the community and there are too many new and unknown elements involved.

 - the beaker browser ... in heavy development .. a very fast moving target, which is good for beta software. .. But problems need to be expected. 
 - the dat-protocol ... has version number 12 atm. It seems to introduce breaking changes every month. At least it looks like this, if you are used to [semver](http://semver.org) versioning. And the [update from](https://github.com/datproject/dat#upgrading-from-version-11) instructions indicate: "problems ahead" (for me)
 - The whole ecosystem around dat:// is in flux. ... 

just some thoughts.

**Comment by pfrazee** [comment]
Hey, I forgot to respond to your last comment but I found it insightful. Thank you for sharing.

I'm going to close this issue to keep the board clean. Please open similar issues in the future. We're rolling out another shot at the start page (which you can try on master) that I hope you'll like -- but, if not, let us know!

**Comment by pmario** [comment]
> that I hope you'll like

-1

> -- but, if not, let us know!

hmmm ... I'll sleep over it and post tomorrow. ..
