### ISSUE TITLE
Tab rendering issues in Linux

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#280]
I noticed in the screenshot from #278 that the tabs are fubar:

![https://cloud.githubusercontent.com/assets/374655/22642018/4a5636e6-ec59-11e6-884a-d570783c5554.gif](https://cloud.githubusercontent.com/assets/374655/22642018/4a5636e6-ec59-11e6-884a-d570783c5554.gif)

The edges are misaligned, and the colors are mismatched.

**Comment by taravancil** [comment]
The jagged corners *should* be fixed by [302](https://github.com/beakerbrowser/beaker/pull/302), but I'm not sure what's up with the mismatched colors. As far as I can tell, both the tab background and the SVG background that comprises the corners are `#ddd`.

**Comment by pfrazee** [comment]
Isn't that weird? I've seen that on the Panasonic in the living room too

**Comment by pfrazee** [comment]
These issues are fixed in the v0.7 branch
