### ISSUE TITLE
Can’t dat.writeFile from one bkr dev archive to another

### ISSUE THREAD

**Issue by fasiha** [beakerbrowser/beaker#284]
Operation System: macOS
Beaker Version: 0.6.0

In tab 1:
```
$ mkdir testing1 && cd testing1 && echo "hi there" > foo && bkr dev
  Building '/Users/ahmed.fasih/Documents/Personal/bkr-stuff/testing'...
  Ready. Sharing at:

  dat://6fd40d077132bc0d23ba36bbcf55737a8ed87ea187abddb6461bc216351ea6e8
```

In tab 2:
```
$ mkdir testing2 && cd testing2 && cp ~/index.html .
$ cat index.html
<script>
dat.writeFile('dat://6fd40d077132bc0d23ba36bbcf55737a8ed87ea187abddb6461bc216351ea6e8/fromJavaScript.txt',
    'hi from JS!', 'utf8').then(x=>console.log('written!', x))
</script>

<h1>Hi!</h1>
$ bkr dev
  Building '/Users/ahmed.fasih/Documents/Personal/bkr-stuff/testing2'...
  Ready. Sharing at:

  dat://26c297dad618b1bd4234a5901bba3a84e2ff007b1da096f6006c301f7650d78e
```

The second tab that opened up has the expected “Hi!” `h1` tag. Open DevTools (View->Toggle DevTools) in the second tab that opens up. I see `ArchiveNotWritableError {name: "ArchiveNotWritableError", message: ""}`:

<img width="912" alt="screen shot 2017-02-07 at 1 03 33 pm" src="https://cloud.githubusercontent.com/assets/37649/22704487/da79f2a8-ed35-11e6-8d2d-efbcd1bc51fb.png">

Beaker didn’t ask any permissions, on either tab. The first `testing1` directory contains no new files.

**Comment by pfrazee** [comment]
Thanks, very well-written report. I'll work on this tonight.

**Comment by pfrazee** [comment]
Ah, I've figured out the issue. The `bkr dev` command actually uses the `dat` tool internally, and it stores the keys in memory. That causes the issue seen here, where the dat created by bkr is not writable by beaker, because the keys are not stored in beaker.

Try creating the target dat by the dat web api, or with `bkr init` / `bkr publish`.

**Comment by fasiha** [comment]
Fantastic! Thank you 🙇!
