### ISSUE TITLE
Fork with Ignore option 

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#287]
I think it might be useful for users to fork a site and optionally filter which files get imported into the forked site. (related to [hyperImport](https://github.com/juliangruber/hyperdrive-import-files)). The Ignore option could be used to provide an "Include Only" option in Beaker's Fork feature (would need to ignore all files except those of filetype user chooses). This would allow for some potential efficiencies if a site is a simple front-end to assets and a user wants to grab all video files or .dwg CAD files etc. This might go beyond the intended use of Beaker to use DAT for "sites" but still could expand upon how users interact with archives through Beaker Browser.

**Comment by taravancil** [comment]
I dig this. I can imagine plenty of situations where it would be useful to only grab certain types of files, or specific files/directories.

**Comment by pfrazee** [comment]
Yeah I'm on board for this. There's two places we can do it: in the browser UI, and in the bkr fork command. Right now I'm working on improvements to `bkr`, so it's a good time to roll in some switches like `--ignore`.

@taravancil is taking the lead on UI/UX improvements inside of Beaker. The fork UI is a few weeks away but when it's up, we can add more power-user controls there.
