### ISSUE TITLE
Possible incorrect handling of Unicode in file/directory names?

### ISSUE THREAD

**Issue by fasiha** [beakerbrowser/beaker#288]
Operation System: macOS
Beaker Version: 0.6.0

I *hate* to be “that guy” but I went and created a file containing a Japanese character. 

```
$ mkdir unicode-test && cd unicode-test && echo "hito" > '人.txt' && bkr dev
```
Beaker tells me the archive contains one file: `äºº.txt`:

<img width="137" alt="screen shot 2017-02-11 at 02 47 56" src="https://cloud.githubusercontent.com/assets/37649/22852183/91a5db6a-f004-11e6-82c2-27759796204d.png">

When I click on it, it takes me to `dat://065d192147d7cd452e048b4ee9330b02d97fb3defa77ac7a5cb07e80ff43bc27/%C3%A4%C2%BA%C2%BA.txt` which 404s.

That encoded filename, `%C3%A4%C2%BA%C2%BA`, seems really long, but then I noticed, `decodeURIComponent('%C3%A4%C2%BA%C2%BA')` -> "äºº". Then inevitably, `unescape(encodeURIComponent('人'))` -> "äºº" 😭.

However! `encodeURIComponent('人')` -> "%E4%BA%BA" and luckily, I can open that! `dat://065d192147d7cd452e048b4ee9330b02d97fb3defa77ac7a5cb07e80ff43bc27/%E4%BA%BA.txt` shows the right file, contents “hito”.

So Beaker can find the right file, but it might have an `unescape` instead of `decodeURIComponent`… or something? (`bkr co` can a proper copy, filenames intact, so the archive seems fine, it’s just a Beaker thing).

Same problem with directory names containing Unicode characters (I almost wrote “fancy characters” but realized Japanese people probably don’t think of them as fancy).

**Comment by pfrazee** [comment]
Haha Thanks for being that guy! We should solve this. Labeling as a bug and putting into our project board.

**Comment by pfrazee** [comment]
Should be fixed. Reopen if you have anymore issues!
