### ISSUE TITLE
Spaces in directory names prevent directory contents from being accessible

### ISSUE THREAD

**Issue by sdockray** [beakerbrowser/beaker#290]
Operation System: OSX 10.11.6
Beaker Version: 0.6.0

> echo "hello" >oneword.txt
> echo "hello" >two\ words.txt
> mkdir oneword
> mkdir two\ words
> echo "hello" >oneword/oneword.txt
> echo "hello" >two\ words/oneword.txt

So the directory looks like:

> ├── oneword
> │   └── oneword.txt
> ├── oneword.txt
> ├── two words
> │   └── oneword.txt
> └── two words.txt
> 
> 2 directories, 4 files

After dat sharing the directory: browsing the dat in beaker browser, 3 of the 4 files are accessible, but the **two words** directory appears empty

<img width="409" alt="screenshot 2017-02-12 22 59 47" src="https://cloud.githubusercontent.com/assets/2905230/22861855/1523f6a2-f177-11e6-843f-1228fffa3ae6.png">

**Comment by pfrazee** [comment]
Thanks for reporting, I'll get right on it.
