### ISSUE TITLE
tests fail - ubuntu and win10

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#292]
@pfrazee 

Can you confirm, that all tests pass with latest master on macOS? ... So I do have a reference point :)

**Comment by pmario** [comment]
@pfrazee ... Any info on the macOS tests. Do they pass? .. I think, I did find some problems with windows already, but I need to be sure, that tests are ok with macOS. Otherwise it doesn't make sense to dig deeper.

**Comment by pfrazee** [comment]
No something's gone wrong, I just get infinite windows opening. I'm going to burnthemall and retry just to be sure

**Comment by pfrazee** [comment]
Yeah something's gone wrong in mine. I'll have to debug when I get home today.

**Comment by pfrazee** [comment]
Yeah this is all issues with the update to Electron 1.5. I needed to bump the Spectron version, and now it looks like Buffers are not transferring like they used to

**Comment by pfrazee** [comment]
Oooook, that was a PITA but we're updated. The `bkr fork` test fails for me, but it has for a while and I've got a TODO to figure out why. Everything else is passing in OSX on master.

**Comment by pmario** [comment]
cool. thx. I'll have a look and report back.
