### ISSUE TITLE
dat.json is hardcoded, but ther is a const: DAT_MANIFEST_FILENAME

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#299]
Beaker Version: 0.6.0

[There are some dat-settings](https://github.com/beakerbrowser/beaker/blob/master/app/lib/const.js#L13)

```
// dat settings
export const DAT_MANIFEST_FILENAME = 'dat.json'
```

but `dat.json`  is hardcoded all over the places. .. Shouldn't it use the global setting?

**Comment by pfrazee** [comment]
Ideally, if you want to make a PR to change that feel free, but I don't rate this very high on the list of concerns
