### ISSUE TITLE
latest master: hostless.website times out 408

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#309]
Operation System: ubuntu  16.10
Beaker Version: latest master 0b2e3d02773327e564d64e484b5406436b02302a

`dat://hostless.website` ... I always get 408 Timed out

How can I provide data to reproduce? Dev tools don't show anything.

**Comment by pmario** [comment]
just to be sure: 40 tests pass - 1 fails: bkr-test: bkr fork

**Comment by pfrazee** [comment]
Yeah I took it down just now. I'll put it back up in a sec.

Those test results are right. I have an open issue to fix the bkr fork test.

**Comment by pfrazee** [comment]
Thanks for reporting though!
