### ISSUE TITLE
html pages with src external image

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#314]
Operation System: OSX
Beaker Version: Latest

I created an html page and added an image via external site like this

src="http://www.007.com/wp-content/uploads/2014/01/4.jpg" style="width: 500px; height: 254px; border-width: 1px; border-style: solid;">

When I addd the html file into my Beaker Library and then go to the dat link the page shows up but not the image

Test against chrome and with chrome the image and the page show up

Thanks

**Comment by pfrazee** [comment]
Yeah, sites served over dat:// are not allowed to access the network without requesting permission. See https://beakerbrowser.com/docs/apis/permissions.html#network-access

**Comment by fredhampton** [comment]
Is there a way to include images in html files and serve them over dat:// 


Thanks

**Comment by pfrazee** [comment]
Sure, you can either encode the image into a DATA url, or add the image to the dat archive as its own file and load it from there
