### ISSUE TITLE
  beaker:library tab - left sidebar doesn't update on "save / delete" action

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#324]
Operation System: ubuntu 16.10
Beaker Version: 0.6.1 master: 9d3f1037f075cac0ac54b3d5ce44da0098288ba3

To reproduce: 

 - make sure that `dat://hostless.website/` isn't saved already
 - start beaker
 - open Bookmarks
 - open: `dat://hostless.website/`
 - open  dat://0e4ce8..e9/#files  with "View Site Files" button
 - click save button  -> left sidebar doesn't update 
 - ctrl-r  reload page -> left sidebar OK
 - click - delete - save - delete  -> update OK. 

BUT new issue comes up: beaker seems to crash. But this is a new issue.
see: #325

**Comment by pfrazee** [comment]
This is solved in the v0.7 branch
