### ISSUE TITLE
beaker:library clicking save / delete about 30 times with 500ms in between it crashes ... kind of. 

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#325]
Operation System: ubuntu 16.10
Beaker Version: 0.6.1 master: 9d3f103

coming from:  #324

To reproduce: 

 - open beaker:library 
 - select a saved library
 - click the save / delete button about 20-30 times in a row, with about 500ms in between
 - beaker will get confused until you restart it. 
    - the UI gets unresponsive for about 10-20 seconds
    - cpu load for 1 cpu up to 100% for about 10-20 seconds
 - if you click save / delete again you'll need to kill the thread.

**Comment by pmario** [comment]
For me it seems the action is async and the "save / delete" button update is sync. So you can reactivate the action, which isn't ready yet. So the app gets confused.

**Comment by pfrazee** [comment]
Closing now that we've updated to a new version of dat, please reopen if still an issue

**Comment by pmario** [comment]
UI has changed. so new test will be needed anyway.
