### ISSUE TITLE
Pretty-ifying Suggestions

### ISSUE THREAD

**Issue by ThatOneGamer999** [beakerbrowser/beaker#328]
Maybe to make the non-OSX builds shinier and more ✨ by setting the `background-color` to transparent on the start page, and adding a `backdrop-filter: blur(5px);` to make the browser absolutely 😻. Also think about maybe letting people change the search engine?

**Comment by pfrazee** [comment]
> Maybe to make the non-OSX builds shinier and more ✨ by setting the background-color to transparent on the start page, and adding a backdrop-filter: blur(5px); to make the browser absolutely 😻.

That's a good thought (if it's supported!). If any non-OSX devs want to make a PR with that, feel free. (We don't have a windows or nix machine to test against.)

> Also think about maybe letting people change the search engine?

If you want to open an issue for that, we can add it to the backlog of feature requests

**Comment by pfrazee** [comment]
We'll fix up the aesthetic for non-OSX in a bit. Closing this issue
