### ISSUE TITLE
Uncaught Error: Cannot find module 'C:\Users\guest1\electron\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64\node_sqlite3.node'

### ISSUE THREAD

**Issue by umapathi20** [beakerbrowser/beaker#343]
Operation System:windows
Beaker Version:
Dear All,

When i launch app it shows error message in console

Uncaught Error: Cannot find module 'C:\Users\guest1\electron\node_modules\sqlite3\lib\binding\electron-v1.4-win32-x64\node_sqlite3.node'

I have tried hundreds of times to solved this issue but no luck.
Please help me out

**Comment by pfrazee** [comment]
Windows isn't a supported platform so I'm not totally sure how that's going to go. Check the other issues about Windows builds (some people have had some success). You might try running `npm run burnthemall` but no promises.

**Comment by pfrazee** [comment]
If you don't mind, I'm going to close this for now, but I'd suggest you search the issues for other attempts to build windows and see what they found
