### ISSUE TITLE
horizontal scroll bar: problem with text overflow settings. caused by dropdown menue. 

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#345]
Operation System: ubuntu
Beaker Version: v0.7: 9ae93ea45c69856bf4ad09debf3ccacc9aaa3dac

Horizontal scrollbar is visible in full length: 
![bildschirmfoto vom 2017-03-10 14-12-16](https://cloud.githubusercontent.com/assets/374655/23796641/5267c050-059c-11e7-9fcc-989f161835f8.png)

Horizontal  scrollbar is hidden behind left sidebar: 
![bildschirmfoto vom 2017-03-10 14-16-24](https://cloud.githubusercontent.com/assets/374655/23796656/60c4cf12-059c-11e7-94fc-463867a8bf9c.png)

Dropdown icon in search box. (top left)
![bildschirmfoto vom 2017-03-10 14-16-40](https://cloud.githubusercontent.com/assets/374655/23796672/7369cf32-059c-11e7-9d51-4287f761227f.png)

Lost & Found a dropdown menue which causes the trouble ;)
![bildschirmfoto vom 2017-03-10 14-16-50](https://cloud.githubusercontent.com/assets/374655/23796682/85f0c840-059c-11e7-8807-2fbd07a9f5a4.png)

**Comment by pmario** [comment]
windows will have the same problems.

**Comment by pfrazee** [comment]
Woah weird, thanks for the heads up

**Comment by pmario** [comment]
Seems to be fixed with latest merges. I'll close and create a new one, if it comes back
