### ISSUE TITLE
open in editor and open - icons and text too similar -> causes confusion

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#346]
Operation System: ubuntu
Beaker Version: v0.7: 9ae93ea

open in editor and open - icons and text too similar -> causes confusion

![icons-too-similar](https://cloud.githubusercontent.com/assets/374655/23796820/3c477e7c-059d-11e7-8181-93d469221ecd.png)

------------------

Proposal: 

Edit Details should be: .... Site Settings or Site Details + Cog icon
Fork .. OK
Edit in Editor should be: ... Edit Site
Remove from Library .. OK

just some thoughts. ... 

I think, there are other inconsistencies. I'll open a new issue for them.

**Comment by pfrazee** [comment]
Yeah we agree. We realized yesterday there's a lot of redundancy in the site library and the editor, so we're going to merge them into one interface. That will solve this problem (wont be a need for both buttons in the menu).

Thanks! Closing since we have existing roadmap items that'll solve this.
