### ISSUE TITLE
editor creates 2 vertical scroll bars

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#347]
Operation System: ubuntu
Beaker Version: v0.7: 9ae93ea

editor creates 2 vertical scroll bars, which imo isn't necessary.

![too many scroll bars](https://cloud.githubusercontent.com/assets/374655/23797478/591b3856-05a0-11e7-87f2-944f36cb8245.png)

**Comment by pfrazee** [comment]
Thanks for the heads up!

**Comment by pmario** [comment]
I think, that's gone with the latest merge. ... So I'll close it now. If it comes up again, I'll create a new issue.

**Comment by pfrazee** [comment]
Cool, thanks!
