### ISSUE TITLE
Add "electron" to build documentation or scripts

### ISSUE THREAD

**Issue by avh-on1** [beakerbrowser/beaker#348]
I just spent an hour trying and failing to build beaker before realizing that it's an electron app, and I didn't have it installed. It would be nice if either:

- the readme said that electron was needed, or
- the install scripts installed/updated electron

**Comment by pfrazee** [comment]
How did you try to install Beaker? If you're building from source, the instructions here will install it https://github.com/beakerbrowser/beaker#building-from-source. You did run those commands from the toplevel of the repo, didnt you?
