### ISSUE TITLE
Message: "this site would like to open this URL in another program"

### ISSUE THREAD

**Issue by kumavis** [beakerbrowser/beaker#365]
Operation System: macOS 10.12.3 (16D32)
Beaker Version: Version 0.6.1 (0.6.1)
fresh install. 

this url was suggested/autocompleted for me, but when i press enter, it shows this message.
pressing "allow" seems to do nothing, just hides the message. I do not have an ipfs daemon running.

![image](https://cloud.githubusercontent.com/assets/1474978/24530711/a863ad58-1568-11e7-939b-49d9366db528.png)

**Comment by pfrazee** [comment]
Yeah we don't really support IPFS right now; I'm slowly stripping out that code. We're going with Dat.

**Comment by kumavis** [comment]
bummer

oh well, keep up the good work!
