### ISSUE TITLE
Ctrl-w closes browser instead of tab in Linux

### ISSUE THREAD

**Issue by morganrallen** [beakerbrowser/beaker#380]
Operation System: Linux
Beaker Version: master

Expected behavior is to close tab

**Comment by pfrazee** [comment]
Thanks for reporting! We'll check into it.

**Comment by pmario** [comment]
IMO that's only valid if the last tab is closed. 

Try:

 - Open several tabs
 - type Ctrl-W

tested with latest v0.7 branch from 2.May.2017

**Comment by chartgerink** [comment]
Echoing @pmario comment for Beaker 0.8 (54f8323301781839ad01f9c0549325ed9e494c99) on Fedora. Isn't it default behavior across browsers to close the window with CTRL+W if it's the last tab (except Opera in my experience)?

**Comment by pfrazee** [comment]
Yes, @morganrallen did you have other tabs open? If not, then the browser is supposed to close if you closed the last tab

**Comment by theorangepotato** [comment]
I am running Linux (Debian Stretch) with the latest stable Beaker (7.7), and pressing CTRL+W will close the entire window regardless of the number of tabs. Typically, pressing CTRL+W will only close the active tab in most browsers.

**Comment by pfrazee** [comment]
Ok weird stuff. I'll double check my build on ubuntu, because it does what you'd expect for ctrl+w.

**Comment by jrc03c** [comment]
I'm also having the same problem on Xubuntu 16.04 and Beaker 0.7.7!

**Comment by morganrallen** [comment]
@pfrazee as others reported, I had multiple tabs open.

**Comment by pfrazee** [comment]
We had an extraneous window-menu item that was bound to Ctrl+W. Some kind of precedence rules caused it to trigger in Linux but not OSX. Fixed now.

Thanks everybody! Sorry for doubting you :smile:

**Comment by taniki** [comment]
Do I need to add something to config?

I have done a `git pull`, and `npm rebuild` but the 0.7.9 still close the whole window instead of current tab.

**Comment by pfrazee** [comment]
Try running `npm run burnthemall` then `npm start`. If that doesnt solve it, LMK what distro you're using.

**Comment by taniki** [comment]
solved (:
