### ISSUE TITLE
History keyboard shortcut opening new tab in dvorak layouts

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#390]
Operation System: Mac

Cmd+y is opening beaker://start for some reason

**Comment by taravancil** [comment]
Update: Cmd+y accelerator works with qwerty but not dvorak

**Comment by pfrazee** [comment]
Can I close this as wontfix?

**Comment by taravancil** [comment]
Yes 😭

**Comment by pfrazee** [comment]
Haha <3

**Comment by pfrazee** [comment]
I actually ended up fixing this one
