### ISSUE TITLE
User-assignable background image on the start page

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#401]
Operation System:OSX
Beaker Version:Current Master

Is there a way to have a transparent background image for the start page ?

Thanks !!

**Comment by pfrazee** [comment]
Like where the entire window is transparent?

**Comment by fredhampton** [comment]
A bit like this https://www.bing.com/
Image as background instead of blank background

**Comment by pfrazee** [comment]
Oh I see! Yeah, I bet we could do that. Wdyt @taravancil, you think you could add a button to a bottom corner to set the BG image?

**Comment by fredhampton** [comment]
That would be awesome !!!

**Comment by taravancil** [comment]
Yeah, definitely! I'll put this on my TODO list.

**Comment by pfrazee** [comment]
Closed
