### ISSUE TITLE
Can't close tab in some situations

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#402]
I tried visiting dat://paulfrazee.com, and it wouldn't load. While the tab was still in a loading state, I was not able to close the tab.

**Comment by pfrazee** [comment]
Any errors in the console?

**Comment by taravancil** [comment]
Can't reproduce it now :\ Visiting your site now gives me the "No DNS record found" error instead of endlessly trying to load and preventing me from closing the tab.

**Comment by pfrazee** [comment]
Yeah. Not sure what that could be, but next time, definitely check the
console.

**Comment by taravancil** [comment]
:+1:

**Comment by pfrazee** [comment]
Seems to be happening if a page is loading

**Comment by pfrazee** [comment]
Fixed in an incoming PR

**Comment by taravancil** [comment]
😃
