### ISSUE TITLE
https://beakerbrowser.com/ .. invalid CERT

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#417]
Operation System: ubuntu 17.04
Beaker Version: latest v0.7 https://github.com/beakerbrowser/beaker/commit/cb1a84b8f613d02c32fa7dbb6d4250a2676577ec

https://beakerbrowser.com/ cert seems to have expired. 

beaker error info: 

```
Your connection is not secure
Beaker cannot establish a secure connection to the server for beakerbrowser.com.

ERR_INSECURE_RESPONSE
```

which is not right. It should be: `Error code: SEC_ERROR_EXPIRED_CERTIFICATE`

**Comment by pmario** [comment]
imo related to: #416

**Comment by pfrazee** [comment]
Going to continue conversation in 416

**Comment by pfrazee** [comment]
Thanks for the heads up on beakerbrowser.com. The cert was getting
autorenewed but I didnt have nginx doing an autoreload. Fixed now
