### ISSUE TITLE
Beaker vs Erlenmeyer

### ISSUE THREAD

**Issue by hsribei** [beakerbrowser/beaker#418]
A little nitpick, but the logo seems to represent an erlenmeyer, not a beaker. It probably doesn't matter though :grimacing:

**Comment by pfrazee** [comment]
Hah yeah we know. We just figured the Erlenmeyer looked better

**Comment by joehand** [comment]
+1 to a beaker logo:

![wired- 2011 -muppets_beaker](https://cloud.githubusercontent.com/assets/684965/25624699/153143ea-2f0f-11e7-889d-2fa0a12784b1.jpg)

**Comment by pfrazee** [comment]
Haha nice

**Comment by hsribei** [comment]
A little cognitive dissonance helps remember :D

**Comment by pfrazee** [comment]
Closed! Congrats to @taravancil for nailing it
