### ISSUE TITLE
Mysteriously crashed and stopped working

### ISSUE THREAD

**Issue by sergeny** [beakerbrowser/beaker#422]
Operation System: OS X El Capitan 10.11.6
Beaker Version: ? (installed Jan 2016)

I had a Beaker electron version on my mac. At some point it crashed (the window with the code disappeared) and refused to run any more. On subsequent restarts, Beaker would start, but it would only have "Quit" in the menu. I've tried reinstalling various versions of Beaker and/or Beaker electron, to no luck. The regular Beaker would technically start, but would not open anything in the browser, and attempting to manually open the url in the browser wouldn't work either. Sometimes it would not even start, particularly the electron one, complaining that the downloaded file was corrupted (when it does "Verifying...")

Something told me to reinstall Google Chrome. After reinstalling Google Chrome, Beaker 1.7.1 started working, though not the electron one. I've made Beaker Electron 1.7.1 to work by installing it outside of /Applications. Note that I have cleared /Applications/Beaker.app many times, but I imagine, there might be some other leftovers from a previous installation.

The whole issue started after I deleted `from numpy import *` from the python startup and tried to restart the interpreter, and then the Beaker itself. The reason I did it is that `numpy.any` shadowed the regular `any` function, which has a different semantics. Note that I am running a local Spark 1.6.1 in the notebook with `import findspark; findspark.init(); from pyspark import SparkContext; sc = SparkContext("local[2]")`.

**Comment by pfrazee** [comment]
> The whole issue started after I deleted from numpy import * from the python startup

We don't use any python. Is there any chance you're confusing us with http://beakernotebook.com/ ?

**Comment by sergeny** [comment]
Yes, that's what it is.

**Comment by pfrazee** [comment]
Ok cool. Closing.

Good luck!
