### ISSUE TITLE
A bad WiFi connection seems to freeze up the entire application

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#45]
I was at a coffeeshop with bad wifi, and started to get application-wide freezes. Are there blocking actions that depend on the network?

**Comment by pfrazee** [comment]
Issues included:
 - Cached dats failing to load (should just be a disk access)
 - The browser shell-window load stalling for 30s. (My guess is, the RPC timeout needed to trigger.)

**Comment by pfrazee** [comment]
This nonsense is still happening. Easiest way to reproduce: go to a coffee shop.

**Comment by pfrazee** [comment]
Weirdly, if I instrument the beaker: protocol with console.log()s to say when requests/responses happen, this bug disappears. 😡

**Comment by maxogden** [comment]
I think I ran into this today, downloaded latest build from beaker website, opened it, was on crap wifi, and whole app beachballed for 5 minutes till I force quit

**Comment by pfrazee** [comment]
Bleh yeah.

**Comment by mrspeaker** [comment]
By the way, a good tool for testing bad networks (if you're on Mac) is the [Network Link Conditioner](https://developer.apple.com/download/more/) (it's part of the `Hardware IO tools`). 

It lets you set imitate different network environments and packet drop rate etc.

**Comment by fuzzyTew** [comment]
I just downloaded beaker and am running into this issue in my home wifi.  The application is unusable; after a few refreshes I can get a dat site to load, but as soon as I interact with it it stops working, peercount drops to 0, times out, takes a number of reloads to see it again.

**Comment by pfrazee** [comment]
Does Beaker work correctly if you turn off wifi?

**Comment by fuzzyTew** [comment]
How would I test this?  Do you mean to connect via ethernet only?  Or to load a cached resource while offline?

**Comment by pfrazee** [comment]
Oh if you just turn off your network entirely, you should be able to load (for instance) the settings or library pages and tell the difference.

**Comment by fuzzyTew** [comment]
Those pages seem to work fine eother way.  I’m trying to load neauoire’s rotonde page, and it loads, but when I click a tab on it the peercount drops to 0, and after that not even the settings page will load.

**Comment by pfrazee** [comment]
Yeah. So what *seems* to be happening with this bug is, if the network stops responding quickly, the entire app slows down. There really shouldn't be any cause for it, because the actions that are going slowly should not involve any network transactions. Somehow, there's something network-related that's blocking the main thread.

Max's problem is probably different. Long beach balls, I've come to find, are usually the garbage collector running. I've made some updates on master that reduce overall memory usage, but the solution to that will probably be moving the Dat stack into its own process or thread.
