### ISSUE TITLE
Does it still use IPFS

### ISSUE THREAD

**Issue by mariokamenjak** [beakerbrowser/beaker#455]
Hello, I am inquiring out of curiosity, does Beaker Browser still use IPFS?

**Comment by pfrazee** [comment]
No, we ended up dropping IPFS and to use Dat solely. You can read the [dat whitepaper here](https://github.com/datproject/docs/tree/master/papers). We made this choice because we prefer Dat's URL spec and its builtin version logs.

**Comment by specious** [comment]
Code removed in #407.
