### ISSUE TITLE
Video files crash Beaker, possibly related to size

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#474]
Operation System: Linux
Beaker Version: 0.7.1

Tim reported a crash bug in linux where an FLV of around 983mb crashed Beaker. This only happened when reading the file from staging. It's possible there's some code that's trying to allocate a buffer of that size, when it ought to be streaming.

**Comment by pfrazee** [comment]
I spent some time debugging this and found I was able to produce crashes in both OSX and Linux. Both of them are segfaults, which suggests to me there's a bad pointer reference in the underlying C++.

I'm going to see if I can produce a test-case and file an issue with electron.

**Comment by pfrazee** [comment]
Filed https://github.com/electron/electron/issues/9635

**Comment by soyuka** [comment]
Interestingly, I'm able to reproduce this issue with `<audio src="dat://foo.mp3">` but not with `<video src="dat://foo.mp4">`.  Will keep updated on my findings if any.

Versions at the time of test:
![screen shot 2017-09-11 at 23 12 21](https://user-images.githubusercontent.com/1321971/30298491-dc7e178a-974b-11e7-9a8b-ef1ff6edc710.png)

**Comment by louiscenter** [comment]
Like @soyuka, I've been able to reproduce this crash using an `<audio>` element. Playing an `.mp3` file from the local `dat://` archive will bork the browser anywhere after 30 seconds to 1 minute.

I think this was answered on IRC, but I wanted to make sure it's documented in a GH issue for others to see: does this PR (https://github.com/electron/electron/pull/10918) fix the `<audio>`/`<video>` bug?

**Comment by pfrazee** [comment]
@louiscenter yes. We'll hopefully have a new version of beaker with the fix soon.

**Comment by pfrazee** [comment]
Fixed now that we have electron 1.8.2-beta.2. Will release soon!
