### ISSUE TITLE
Binary download on IPFS/IPNS?

### ISSUE THREAD

**Issue by aroemers** [beakerbrowser/beaker#48]
Would it be nice to be able to fetch the beaker binary from fetch it from IPFS (or DAT, but I'm unfamiliar with it), next to the S3 option, utilising the automatic integrity checks?

**Comment by pfrazee** [comment]
Yes, that'd be a good idea.

**Comment by buckle2000** [comment]
S3 is too slow in some regions, so this is a good idea.

**Comment by davux** [comment]
```
$ ipfs add beaker-browser-setup-0.7.11.exe
added Qme2ZBwZwBS4y3ENrMby4BusJy1JgDx8GHwpqhrSa9MXH7 beaker-browser-setup-0.7.11.exe
```

Just in case, do wait for someone trusted to confirm. :)
