### ISSUE TITLE
Show some indication that files are still being imported

### ISSUE THREAD

**Issue by mrbiber** [beakerbrowser/beaker#482]
Operation System: Ubtuntu 17.04
Beaker Version: 0.7.1

I created a new site with loads of large files. On opening the library, it seemed as if only some of them had been imported; others were shown in the staging view. When I pressed the "publish" button to also import them, I got a "time out" error message. Later on I discovered, that apparently the import process was still running and that the files eventually ended up being published. I found this confusing. Perhaps it would be better to show some indication if the import is still running and to disable the "publish" button until it has completed.

**Comment by pfrazee** [comment]
@mrbiber We just landed those exact fixes in https://github.com/beakerbrowser/beaker/pull/478! Thanks for reporting. We'll have it out in a new version in < a week.
