### ISSUE TITLE
Discussion: Self-mutating Dat sites

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#483]
There's an interesting usecase for Dat sites which store state by writing files to themselves. If the Dat site is not owned by the local user, it can self-fork.

However, writing to self opens a potential security concern: is it possible that self-mutations could lead to code injections or modifications? How can we allow self-mutating sites, and still protect the application code?

**Comment by pfrazee** [comment]
This basic risk exists for one Dat site attempting to inject into another. There is a permission prompt asking the user for the write permission, but, after that, there's no protection regarding what the mutator writes. So we might want to consider the risk for more than just self-mutation.

---

**Proposal: Blessed Script Files**

A "blessed" script would be whitelisted in the manifest file (`dat.json`). Any blessed script would not be writable from the Web APIs. A sha CSP would be used to only allow the blessed scripts to be executed.

Pros:

 - Strong control over execution rights. The manifest is already protected, and this would be a way to extend that protection to the scripts.

Cons:

 - Requires manual setup by the developer (inconvenient)
 - When opening a site, the manifest, then all blessed files, must first be downloaded and SHAed in order to compute the proper CSP header. This will hurt the time-to-first-byte.

**Comment by pfrazee** [comment]
CSP Level 3 will [allow specific subdirectories](https://www.w3.org/TR/CSP/#example-basic) which will make it possible to create "Blessed Folders" such as `/scripts`, and I have to imagine that's the ideal solution for this: unwritable directories which have the "execute" bit enabled.

**Comment by pmario** [comment]
So that's the reason, why creating / write to an archive is allowed, but attaching to existing archive and / write causes an error?

**Comment by pfrazee** [comment]
> attaching to existing archive and / write causes an error?

You should be given a permissions prompt. Can you elaborate in a separate issue?

**Comment by pmario** [comment]
>You should be given a permissions prompt. Can you elaborate in a separate issue?

need to test again.

**Comment by pfrazee** [comment]
I did find a bug (https://github.com/beakerbrowser/beaker/issues/487)

**Comment by pfrazee** [comment]
Closing, we'll go with the "blessed folders" plan

**Comment by Jermolene** [comment]
Hi @pfrazee apologies for coming into the discussion late.

> However, writing to self opens a potential security concern: is it possible that self-mutations could lead to code injections or modifications? How can we allow self-mutating sites, and still protect the application code?

Why does the application code need to be protected from mutating itself? If we trust the app, wouldn't we also trust any modifications it makes?

Am I correct in thinking that under the "blessed folders" proposal, it is possible to have an executable file that is not in a blessed folder, and is therefore able to write to itself?

Paul knows this, but as context for others, one of the use cases I'm interested in is more than a self-mutating site, it's a self-mutating HTML/CSS/JS file stored within a site (there might be multiple such files within a site).

**Comment by pfrazee** [comment]
The security decisions will co-evolve with the APIs and our understanding of the threats. We may be able to relax some decisions, and tighten others, as we go.

> Why does the application code need to be protected from mutating itself? If we trust the app, wouldn't we also trust any modifications it makes?

The goal is to avoid injections of unwanted code into a trusted domain, as that would enable privilege escalation. There are three vectors for accomplishing that.

 1. Page injections due to `eval()` or inline JS.
 2. Scripts included via `<script>` which originate from another domain.
 3. File injections via the DatArchive write APIs.

We can block 1 and 2 by default using [customizable CSP](https://github.com/beakerbrowser/beaker/issues/497).

For point 3, if you can trick an application or user into writing a malicious payload, then trick the application into loading the payload with a `<script>` command, then you'll have compromised it. I'm not yet sure how easy or hard that will be.

> Am I correct in thinking that under the "blessed folders" proposal, it is possible to have an executable file that is not in a blessed folder, and is therefore able to write to itself?

Blessed folders have to be strictly enforced to offer a full defense. By making *only* protected folders executable, we defend against file-injection attacks (point 3). If we allow unprotected folders to run code, then they can still be injection opportunities.

I think sites that don't have a full defense with blessed folders might need to be [considered 'unsafe'](https://github.com/beakerbrowser/beaker/issues/498) and constrained to their own sandbox. That would mean they can read and write to self, but not others.

Again, that's based on my crystal ball of risks. It's hard to say for sure if I'm right.

> Paul knows this, but as context for others, one of the use cases I'm interested in is more than a self-mutating site, it's a self-mutating HTML/CSS/JS file stored within a site (there might be multiple such files within a site).

By the way, we merged a new policy to master to [support self-mutating sites](https://github.com/beakerbrowser/beaker/issues/491), so we can begin playing with them now. The defense measures I'm discussing will be added over time.

**Comment by Jermolene** [comment]
Hi @pfrazee thanks, that's helpful.

> The goal is to avoid injections of unwanted code into a trusted domain, as that would enable privilege escalation. 

OK, so presumably injections of malicious code into the executable files of a site *from another site* can be avoided by the existing mechanism of requiring user approval for attempts to write to that site? So the concern must be that the modifications that the app itself makes might be tainted?

Wouldn't that only happen if the app itself were compromised, either by an XSS-type bug, or the user being phished into introducing rogue code?

If the intent is to guard against bugs or other vulnerabilities in self-mutating apps, I'm not sure that the platform should be taking that responsibility at this point in its evolution.

The security model of Beaker right now relies on the user appropriately responding to yes/no confirmations. Given the problems we saw when that approach was used with ActiveX controls 20 years ago, you must already be thinking about more elaborate approaches. In the meantime, given that self-modifying sites may have more risks, would it be sufficient to just turn up the volume on the confirmation dialogue that requests write access in the first place?

> Blessed folders have to be strictly enforced to offer a full defense. By making only protected folders executable, we defend against file-injection attacks (point 3). If we allow unprotected folders to run code, then they can still be injection opportunities.

That makes sense for conventional apps, but even for them might be cognitively burdensome for users. It means that granting write access to a site isn't a binary thing; a user would need to understand the concept of protected folders, and be able to see them, in order to understand whether any particular file in a site is writable. Perhaps the alternative is to use two "sites": one containing the app (no write access), and one containing the user data/profile for using the app (with write access). I'm sure you'll have thought more than me about this stuff.

> I think sites that don't have a full defense with blessed folders might need to be considered 'unsafe' and constrained to their own sandbox. That would mean they can read and write to self, but not others.

That would be a shame!
 
> Again, that's based on my crystal ball of risks. It's hard to say for sure if I'm right.

I guess the quandary is that these security concerns might end up constraining Beaker to only support the types of app that you can anticipate in advance, which of course would reduce its potential as a platform for innovation (which is my hope for Beaker, now that Firefox is becoming as narrow minded in the name of security as Chrome).

**Comment by pfrazee** [comment]
> OK, so presumably injections of malicious code into the executable files of a site from another site can be avoided by the existing mechanism of requiring user approval for attempts to write to that site?

Write-permissions help, but they're not a very extensive defense. Blessed folders are meant to do filter pass against executable code.

> So the concern must be that the modifications that the app itself makes might be tainted?
 Wouldn't that only happen if the app itself were compromised, either by an XSS-type bug, or the user being phished into introducing rogue code?

That's what I'm generally thinking. Another scenario is, for instance, an app that's designed to download and archive files *inside its own Dat*. Like a wget. The user downloads something, then clicks through to see what they just downloaded and -- oh no! it was html, and the page's code executed.

> If the intent is to guard against bugs or other vulnerabilities in self-mutating apps, I'm not sure that the platform should be taking that responsibility at this point in its evolution.

Fair point; it's a balancing act. On the flip side, I don't want to make a bad call early on that makes people afraid to use the browser.

> The security model of Beaker right now relies on the user appropriately responding to yes/no confirmations. Given the problems we saw when that approach was used with ActiveX controls 20 years ago, you must already be thinking about more elaborate approaches. In the meantime, given that self-modifying sites may have more risks, would it be sufficient to just turn up the volume on the confirmation dialogue that requests write access in the first place?

Perhaps! I wouldn't take that option off the table.

> That makes sense for conventional apps, but even for them might be cognitively burdensome for users. It means that granting write access to a site isn't a binary thing; a user would need to understand the concept of protected folders, and be able to see them, in order to understand whether any particular file in a site is writable. Perhaps the alternative is to use two "sites": one containing the app (no write access), and one containing the user data/profile for using the app (with write access). I'm sure you'll have thought more than me about this stuff.

Yeah, you're crystalizing a lot of my own thoughts here. You might be right that the concept of "protected folders" is too tedious, and that "protected dats" are the right level of generality.

> I guess the quandary is that these security concerns might end up constraining Beaker to only support the types of app that you can anticipate in advance, which of course would reduce its potential as a platform for innovation (which is my hope for Beaker, now that Firefox is becoming as narrow minded in the name of security as Chrome).

I agree and I'll take things incrementally, for this reason. Your feedback helps. We'll improve on the specs. I definitely don't think the answer is to cripple our applications; the whole point is to make more powerful server-free apps.

For now we've got self-mutating sites enabled, so we can start to experiment. I'll play with TiddlyWiki on Beaker a bit and see what I can come up with.

**Comment by Jermolene** [comment]
Thanks @pfrazee -- at the moment I'm using the binary releases of Beaker, I guess I've have to investigate building it to get the new self-mutating bits?

**Comment by pfrazee** [comment]
Yes, but we'll release the next update early next week

**Comment by pmario** [comment]
> .. I guess I've have to investigate building it to get the new self-mutating bits?

I'm building it for ubuntu. Works flawlessly. The only thing to remember is, that from time to time you have to rebuild everything from scratch, with "npm run burnthemall", if major components change. eg: dat or electron
