### ISSUE TITLE
Dat API: Dat-picker modal

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#486]
In order for an application to edit a Dat, it needs to be given the URL of that Dat. Currently, the user has to manually copy and paste the URL into the UI.

Instead, the application should be able to instantiate a "Dat-picker" modal dialog, which lets the user select from their library of Dats.

Like this, but for Dats:

![screen shot 2017-06-01 at 11 57 34 am](https://cloud.githubusercontent.com/assets/1270099/26691098/8b8d4448-46c1-11e7-8cd4-5d875dc2306a.png)

**Comment by todrobbins** [comment]
Is this feature now live in 0.7.2?

**Comment by pfrazee** [comment]
Yep!
