### ISSUE TITLE
Dat API: Add a {commit: true} flag to mutation methods

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#488]
In situations where you don't need the user to review changes before committing, it'd be helpful to have a `{commit: true}` flag to do the commit automatically.

```js
var a = new DatArchive('...')
await a.writeFile('/foo.txt', 'bar', {commit: true})
```

This would be added to:

 - writeFile
 - mkdir
 - unlink
 - rmdir

Tasks:

 - [ ] Add flags to API
 - [ ] Update documentation

**Comment by pfrazee** [comment]
There's more complexity to this feature than I realized.

Should `{commit: true}` commit only the target file, or should it commit all unstaged changes? The former is a natural choice, except that the commit may depend on staged changes.

For instance, consider this snippet:

```js
var a = new DatArchive('...')
await a.mkdir('/foo')
await a.writeFile('/foo/bar.txt', {commit: true})
```

In this snippet, if `{commit: true}` only committed the change made by `writeFile`, the commit would fail because the `/foo` directory has not yet been committed from staging.

There may be a simple enough algorithm for finding dependent changes. However, I wonder if this feature is worth that.

cc @joehand

**Comment by joehand** [comment]
To start with (I think this is the more simple one) you can either commit everything or the target file.

I wouldn't expect that code as written to work. You can either:

```js
var a = new DatArchive('...')
await a.mkdir('/foo', {commit: true})
await a.writeFile('/foo/bar.txt', {commit: true})
``` 

Or 

```js
var a = new DatArchive('...')
await a.mkdir('/foo')
await a.writeFile('/foo/bar.txt')
a.commit()
```

**Comment by pfrazee** [comment]
Would it throw an exception if there are dependent changes that haven't been committed?

**Comment by joehand** [comment]
Yea, I'd expect it to error the same as if you tried to commit without making the folder now:

```js
var a = new DatArchive('...')
await a.writeFile('/foo/bar.txt')
a.commit()
```

**Comment by pfrazee** [comment]
We've removed the old staging API in the `beaker-0.8` branch with plans to replace it.
