### ISSUE TITLE
Dat API: "Review and commit changes" dialog

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#489]
In applications which want the user to review changes prior to committing, it would be convenient to have a modal UI which the application could call, which shows the user the changes and lets them commit or revert. This would be a similar interface to the one provided by the library.

**Comment by pmario** [comment]
I'm not sure, if this needs to be part of beaker. ... If the app wants such a dialog, it should create one.  .. How should the "built in modal" deal with app theming. ... dark, light, .... IMO way too much hassle. 

I personally want to have more fine grained control, anyway. 
eg: I want to revert and commit changes on a file basis.

**Comment by pfrazee** [comment]
We removed the staging area from the `beaker-0.8` branch
