### ISSUE TITLE
Dat API: Protected files and folders

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#492]
Coming off the conversation in https://github.com/beakerbrowser/beaker/issues/483#issuecomment-305319967, add a `dat.json` manifest field for creating "protected" files and folders, which are not writable from Web APIs.

 - [ ] Add a manifest field for protected paths, and disallow Web API mutations of those paths
 - [ ] Add a manifest field for setting the script CSP to specific paths (requires either hashes or [CSP level 3](https://www.w3.org/TR/CSP/#example-basic))

**Comment by webdesserts** [comment]
@pfrazee would it make sense to make this a whitelist instead? For example, In a blog, I might only ever want to mutate the `/posts/` folder and something along the lines of a `profile.json`. If I had to blacklist every file that I add to the website as it came in, that might get annoying.

**Comment by pfrazee** [comment]
@webdesserts That would make sense. Perhaps we even support both.
