### ISSUE TITLE
Use utf8 for rendered markdown pages

### ISSUE THREAD

**Issue by millette** [beakerbrowser/beaker#499]
Nice to see markdown automatically converted to html, thanks!

I noted ```<meta charset="utf-8">``` is missing from the html head.

**Comment by pfrazee** [comment]
Added to 0.7.3 milestone

**Comment by pfrazee** [comment]
I spent some time on this, and I'm finding indications of an upstream electron bug that will slow this down. (Charset isn't getting respected on custom protocols.)
