### ISSUE TITLE
ZeroNet integration

### ISSUE THREAD

**Issue by OliverCole** [beakerbrowser/beaker#50]
> ZeroNet - Decentralized websites using Bitcoin crypto and BitTorrent network
> http://zeronet.io

I particularly like it because it has a clever JavaScript layer to allow you to build sites with data storage that give the impression of centralised hosting, but in fact store all the backend data in the same P2P manner as the site HTML.

I've opened a ticket over there too: https://github.com/HelloZeroNet/ZeroNet/issues/530

**Comment by pfrazee** [comment]
ZeroNet gave a great demonstration at the DW Summit. I'd be happy to help this happen.

**Comment by numidark** [comment]
Where is the project for Zeronet integration ?

**Comment by pfrazee** [comment]
It's not on my roadmap at the moment.

**Comment by millette** [comment]
Related: Namecoin Support #260
