### ISSUE TITLE
"Download full Dat" control

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#508]
Currently there's no way to request that Dat files are downloaded, except by clicking on them. It would be really great to have a tool that lets you trigger downloads of some/all of the archive.

**Comment by todrobbins** [comment]
I like the simplicity of Dropbox's UI on macOS:

![screen shot 2017-06-08 at 8 46 27 am](https://user-images.githubusercontent.com/158590/26934832-b07a8f0c-4c27-11e7-80c1-dc9b71c8dc01.png)

Right click and select via a contextual menu seems straight forward enough. Thoughts?

**Comment by pfrazee** [comment]
Oh hey, excellent suggestion. We'll keep that in mind.

**Comment by pfrazee** [comment]
Done with the recent sidebar changes
