### ISSUE TITLE
PDF view in beaker://view-source is broken

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#515]
Operation System: macOS 10.12.5
Beaker Version: 0.7.2

I just noticed when you are in the `beaker://view-source/` view clicking on a PDF renders it like so:

![screen shot 2017-06-08 at 8 57 31 am](https://user-images.githubusercontent.com/158590/26935267-bc0f8c40-4c28-11e7-978c-62c7dc606675.png)

Should this load the `chrome://pdf-viewer/` in this context?

**Comment by todrobbins** [comment]
I also noticed that the UI doesn't reflect which file is currently selected. Although, that's definitely a secondary issue.

**Comment by pfrazee** [comment]
Thanks for filing!

**Comment by pfrazee** [comment]
Fixed this just by having the PDF give a link you can click to open the pdf in another page
