### ISSUE TITLE
consistent devtools keyboard shortcut

### ISSUE THREAD

**Issue by dominictarr** [beakerbrowser/beaker#516]
Operation System: archlinux
Beaker Version: 0.7.2

was checking out the extended browser apis and found that beaker a different dev-tools shortcut. In beaker the devtools keyboard shortcut is `ctrl-alt-i` but on firefox and chrome it's `ctrl-shift-i`.

**Comment by pfrazee** [comment]
Sure thing, added to my todo list

**Comment by pfrazee** [comment]
Done
