### ISSUE TITLE
Add controls to specify which version of a site is forked (staging, latest, prev version)

### ISSUE THREAD

**Issue by millette** [beakerbrowser/beaker#519]
Operation System: Debian Jessie
Beaker Version: 0.7.2

Action: As the site owner, fork a site in development (with unpublished files/versions).

Expectation: Forks the published version and not the one currently in staging.

What happens: Staging version is forked.

**Comment by pfrazee** [comment]
We've been debating what the right behavior is for this. I'm wondering if
we should let the user choose from staging, last published, and historic
versions?

**Comment by millette** [comment]
It only applies to the dat owner (other uses get the last published version).

I think by default, it should fork the last published version, but if there are other versions, a selector would be handy. It's not something I would set as a general preference, though.

**Comment by pfrazee** [comment]
Thanks. We'll give this a look
