### ISSUE TITLE
Custom public directory

### ISSUE THREAD

**Issue by jondashkyle** [beakerbrowser/beaker#535]
A convention you’ll often see with build processes for modern Single Page Applications and static site generators is to build the output of a `/src` directory into a `/dist` directory. That is to say, placing the output of the application source into a public directory which is served to the client.

One of my favorite things about Beaker is the evolution of **view source**. Being able to define a custom public directory within `dat.json` would be helpful for those who would like to share the source of their projects while following common practice in regards to directory structure.

An example of how this option could be configured:

```javascript
{
  "url": "dat://4483a2..66/",
  "title": "Application Title",
  "description": "A short description of the app",
  "publicDirectory": "./dist"
}
```

**Comment by pfrazee** [comment]
This is an interesting idea. Tara and I have run into this use-case ourselves. For instance, with the beaker site, we use jekyll, which outputs the build to `./_site`.

This is one of those features that's going to impact the Dat protocol's Web specification in a pretty big way, so I want to make sure everybody's on board.

**Put your thumbs up and thumbs down on the original issue to signal your support. Feel free to explain why.**

**Comment by pfrazee** [comment]
Question: What should `readdir('/')` provide, if using the `DatArchive` API? cc @jondashkyle @mafintosh

**Comment by mafintosh** [comment]
It would provide the root of the archive. The dat.json root dir is considered a hint

**Comment by pfrazee** [comment]
That does make sense, I'm just wondering if that will surprise people frequently

**Comment by millette** [comment]
Should the publicDirectory field be absolute? In other words, ```"/dist"``` instead of ```"./dist"```?

**Comment by jondashkyle** [comment]
I think that is the clearest option, in parity with what you would expect elsewhere when working with the filesystem.

**Comment by millette** [comment]
If I see ./dist, I might assume ../../dist (or whatever) should work. The actual context is dat, so ```/dist``` or even ```dist``` might be less confusing.

For the key name, ```root``` is a bit too generic for my taste. The root of the dat remains /, only the web/html changes. So maybe call it ```webRoot```?

**Comment by pfrazee** [comment]
We're going to be trying to mix in with the [app manifest.json](https://developer.mozilla.org/en-US/docs/Web/Manifest) and [web extension manifest.json](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json) so it'll have to be snake-case.

`web_root` seems pretty solid to me

**Comment by jondashkyle** [comment]
@millette If `dist` works, then I don’t see a reason for why `./dist` shouldn’t. I do agree that `dist` is less confusing, though. I suppose my thought is coming from when accessing a directory when using the filesystem within node, but these are different problems.

@pfrazee `web_root` 👍

**Comment by pfrazee** [comment]
Ok, I'm sold. Added to the 0.7.4 milestone.

**Comment by frabrunelle** [comment]
It might be a late for this comment, but I wonder if there might a better name than `"web_root"`? How about `"public_html"`? It's the folder name used in cPanel, so I'm thinking it might be a more familiar name 🙂
