### ISSUE TITLE
Fix the delete UX

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#543]
This is what happens when you bulk delete archives in the Library.

![screen shot 2017-06-16 at 9 27 08 am](https://user-images.githubusercontent.com/7584833/27230774-04828d08-5276-11e7-8f46-0d185e40fd90.png)

Also there's a small typo in that prompt: "If you want to still want to..."

**Comment by pfrazee** [comment]
Yikes. (I just updated the text in that copy.)

What do you think *should* happen?

**Comment by pfrazee** [comment]
We could do a checkmark: "Yes to all (5 others)"

**Comment by taravancil** [comment]
I'm questioning whether we need to ask for confirmation at all

It's definitely not a big of a deal if the user accidentally deletes *one* archive from the library view, because they'll see the prompt to restore it immediately.

I mean, a user can restore from trash after bulk deleting, but unlike the case where they just delete *one*, it might not be obvious how to do that.

**Comment by taravancil** [comment]
Yeah that works for me.

**Comment by pfrazee** [comment]
We found these confirmation boxes confusing overall, so here's the plan:

 1. Change the confirmation to ask, simply, "Are you sure you want to delete the archive?"
 2. Add the checkbox, but have it say, "Delete the files at ${dir}"
 3. If multiple sites are being deleted, add a third button, "Yes to all"
