### ISSUE TITLE
rethink createdBy in dat.json

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#544]
Beaker adds a `createdBy` property to `dat.json` which indicates from where the archive was created. If it's another archive, its value is the key to that archive.

This prohibits an application from creating a new archive in order to share only some of its files secretly.

**Comment by pmario** [comment]
Is this a security concern, or a privacy concern?

**Comment by pfrazee** [comment]
Privacy. An example is, you have a site with lots of private files, and you add a script to create new archives to share a subset of the files. Whoops, just gave away the private site.

**Comment by pmario** [comment]
>Privacy. 

OK

I can see the reasoning. I was just confused by the label: "security feature" ... I'm not sure if it's worth a new label. eg: "privacy feature"
