### ISSUE TITLE
Auto-commit mode

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#547]
There are times that it'd be super handy if all changes just automatically commit to the archive. One example would be, if you're working on a site for somebody, and you want them to be able to live-reload updates as you make them.

**Comment by pfrazee** [comment]
We've removed the old staging API in the `beaker-0.8` branch with plans to replace it.

**Comment by akoenig** [comment]
@pfrazee Which means that there won't be an additional `publish` step in `0.8`?

**Comment by pfrazee** [comment]
Correct. I'm still working out how I want to replace the staging area. Making it a core part of the dat API was too complex, but the staging area concept is really nice for application dev. Will keep slugging at it.
