### ISSUE TITLE
fork button is gone

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#551]
Operation System: ubuntu 17.04
Beaker Version: master latest

I'm not sure, if I messed something up with my build. ... But the "fork - button" is gone form the menu. ... "burn the mall" doesn't fix it. ... I probably missed something else. 

to reproduce: 

 - go to: dat://example-self-mutator-pfrazee.hashbase.io/#
 - open menu

![fork-missing](https://user-images.githubusercontent.com/374655/27339947-81a7116c-55d9-11e7-8967-7610cdaed7bc.png)

**Comment by pfrazee** [comment]
Hey Mario!

We're actively building a new UI, but haven't perfected or documented it yet. (Master is the bleeding edge!)

You have two options to fork now. 1, you can use the context menu:

![screen shot 2017-06-20 at 10 06 49 am](https://user-images.githubusercontent.com/1270099/27340480-36866e46-55a0-11e7-8fc6-1be81a073b3a.png)

2, you can open the sidebar by clicking the panel button next to the hamburger menu. The fork button is there:

![screen shot 2017-06-20 at 10 07 22 am](https://user-images.githubusercontent.com/1270099/27340521-4dea96e8-55a0-11e7-8c1b-2b68000a645e.png)

**Comment by pmario** [comment]
Sorry for the noise. ... Just found it :) ... thx

funny. .. I'm using "Inspect element" .. but didn't recognize the "fork button" ... So I probably don't see, what I don't expect :)

**Comment by pfrazee** [comment]
No worries, we keep changing the UI on you :)
