### ISSUE TITLE
Expose DatArchive API to HTTPS pages?

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#553]
Right now, the `DatArchive` API is only available to Dat pages. All for/against exposing it to HTTPS sites?

## Reasons not to expose to HTTPS

We have less control over HTTPS sites. A dat:// site is hostless and uniformly-distributed, and users can peg the version they use to ensure there are no attacks injected. However, HTTPS sites are subject to the whims of the host. Is HTTPS safe enough for these APIs?

## Reasons to expose to HTTPS

The security benefits are nice but not mandatory. Allowing HTTPS access would make new projects simpler to develop, because people already know how to make HTTPS services. We could start making hybrids of P2P and Services this way!

## Vote

Vote 👍  to expose DatArchive to HTTPS, vote 👎  to keep it restricted, and vote ❤️  to say you love cats.

cc @taravancil @mafintosh @joehand @pmario @frabrunelle @jondashkyle

**Comment by taravancil** [comment]
Initially, I gave this a thumbs up, but I'm second guessing my vote now. We're exposing access to the user's filesystem, which risky as best, catastrophic at worst. Without the ability to peg versions, do users really have sufficient tools to manage which hosts can access their filesystem?

**Comment by pfrazee** [comment]
Keep in mind, the DatArchive API scopes all writes to a sandboxed folder, and it limits how much data can be written, so it **should not be dangerous**. If it's dangerous, then it shouldn't be exposed to Dat sites either.

There's always risk that a site will escape the sandbox, but that risk is not increased by exposing access to HTTPS

**Comment by pmario** [comment]
I voted -1 since I think additional permissions are not expected for `https`. ... All other browser vendors make file access harder with every version, and users get used to that. ... unfortunately. 

dat:// is a completely new protocol. So everyone who sees it knows, that something special is going on. IMO this works nicely with the "least surprise" principle.

I wouldn't enable it at the moment. Only if it is heavily requested in the future.

**Comment by pfrazee** [comment]
@pmario we decided to go ahead and expose DatArchive to HTTPS. Hope you don't mind. We don't see enough harm in the change, but there's plenty of benefit.

**Comment by pmario** [comment]
>Hope you don't mind. We don't see enough harm in the change, but there's plenty of benefit.

That's ok for me. ,,, I did just express a more conservative approach.
