### ISSUE TITLE
Improve wording of "...can not find the local copy..." dialog in the library

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#565]
Beaker Version: 0.7.2

I like the possibilities of "...can not find the local copy..." dialog. But I'd re-arrange the "action-buttons". eg: 

**Beaker cannot find the local copy of this site.** This is probably because the folder was moved or deleted.

 - [Update the location], if it was moved and things will resume as before.
 - [Choose a new location], if it was deleted accidentally, so beaker can restore the files from the last published state.
 - [Delete it from your library], if it was deleted on purpose, and you don’t want to keep the archive anymore.

I did remove the "(or you don't know, what happened)" in the second possibility ... because it doesn't make any difference to the status quo, nor the fix. ... IMO, it would be even possible to remove "if it was deleted accidentally"

just some thoughts

**Comment by pmario** [comment]
The second thing is: "red on red" - The contrast between text and background could be higher. It's hard to read. ... please don't use green.

![beaker-staging-area-removed](https://user-images.githubusercontent.com/374655/27479028-4dad648e-5812-11e7-9699-470cf834a27d.png)

**Comment by pfrazee** [comment]
Good suggestion! I'm on board. @taravancil ?

**Comment by taravancil** [comment]
I like the idea of putting all the action items at the front of the bullet point. We'll probably need to massage the copy a bit, but I'm on board.

Re: the red background -- thanks for pointing that out. I'm experimenting with some different alert styles that don't use colored backgrounds, so once those land, the contrast will be much higher.

**Comment by pmario** [comment]
@taravancil I did just delete a staging area, because I wanted to get a published version back. but it seems v0.7.3 doesn't show the 3 possibilities anymore. ... Why? It has been a great feature?

**Comment by taravancil** [comment]
@pmario Our goal here was to drastically simplify that flow. In the old prompt, 2/3 options did the same thing -- prompt the user to choose a new folder, and the third prompted the user to delete the archive. We decided to get rid of the delete prompt and to only show the "Choose new folder" one.

Just to clarify, you were trying to revert changes in the staging area so you could get back to a previously published state? If I'm understanding you correctly, using the "Revert" button in the staging area is better suited for that.

![staging](https://user-images.githubusercontent.com/7584833/27649754-595e69a6-5bf8-11e7-9130-6bc78da75aad.gif)

**Comment by pmario** [comment]
I tried to confuse the program:  **I want to restore the staging area from a "writeable" archive** because I killed the directory!

 - create a new site: abc
 - create test.txt in Site directory
 - Publish
 - open file browser and delete the "abc" folder
 - There seems to be no info anymore. 

--> IMO user is lost! It seems the browser doesn't recognize it anymore. At least for me it's completely broken now.

**Comment by pfrazee** [comment]
@pmario we do agree that we took a step back on that. We're fixing it now

**Comment by pfrazee** [comment]
@pmario I think we've got this fixed. You have to reload the page, but you'll get this:

![screen shot 2017-07-20 at 5 08 38 pm](https://user-images.githubusercontent.com/1270099/28440993-3692059a-6d6e-11e7-89ec-f8ae5e3ddbb6.png)

Clicking that returns the folder and restores all published files. Reopen if you feel like there's still an issue!

**Comment by pmario** [comment]
.. Would be OK for me, it the dialog would be the same, if the browser is restarted. 

to reproduce

 - crate a new dat
 - rename the staging area
 - open the dat -> shows the info above
 - close beaker
 - open beaker 
 - open library and dat
 - it shows. "NotFoundError: File not found"

which imo is still an issue.

**Comment by pfrazee** [comment]
I'll check into that

**Comment by pfrazee** [comment]
Ok good catch, just pushed a fix. Muchos gracias
