### ISSUE TITLE
Should we rename "fork archive" to "clone archive"?

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#566]
We've had a little confusion with the term "Fork", and so we're wondering if we should call it "Clone" ?

This would also mean changing the js, from

```js
var archive = await DatArchive.fork(url, {...})
```

To

```js
var archive = await DatArchive.clone(url, {...})
```

Open vote: 👍  to change to Clone, 👎  to stick with Fork

**Comment by joehand** [comment]
Makes sense that fork is confusing, but clone means something different to me and is no less confusing to non programmers.

Other options:

* Duplicate
* Make a copy

**Comment by millette** [comment]
> I think for advanced programmers, fork() makes a lot of sense. But for nonprogrammers, they hear that term and are like "what's a fork?"

That suggests leaving the code as is, but changing the UI only.

**Comment by pfrazee** [comment]
@millette that is an option, or we can rename it to something like `DatArchive.copy()`, or `DatArchive.copyArchive()`

**Comment by millette** [comment]
It's a copy, a duplicate, when it's shared and replicated over P2P as-is. When you change it's key, it *really* feels more like a fork.

**Comment by joehand** [comment]
I'd agree too but seems like usability should be prioritized over semantics.

**Comment by pfrazee** [comment]
Somewhat mixed into this debate is this:

[We're now thinking about giving the browser a FS](http://pfrazee.github.io/blog/reimagining-the-browser-as-a-network-os), where a private archive acts as the "User Root."

In that model, users would be able to link/mount archives into other archives, and then they'd behave conceptually like folders.

So here's a question to ask ourselves: lets say I mounted `dat://beakerbrowser.com` to `~/sites/beaker`, which means I could `ls ~/sites/beaker` and see a listing of the site's files.

```bash
> mount ~/sites/beaker dat://beakerbrowser.com
> ls ~/sites/beaker
```

What would be the command to "fork" an archive in the CLI?

```bash
> fork ~/sites/beaker ~/sites/beaker-fork # this?
> cp --fork ~/sites/beaker ~/sites/beaker-fork # this?
> mkarchive ~/sites/beaker-fork ; cp -R ~/sites/beaker ~/sites/beaker-fork # this?
> mkarchive ~/sites/beaker-fork --from ~/sites/beaker # this?
```

**Comment by pmario** [comment]
For me 
 - cloning a dat is working with the exact same content. 
 - forking a dat, is modifying the above mentioned clone. 

`dat clone` ... gives me a read only copy
`dat fork` .. creates a R/W copy 

both are copies at the very beginning.

**Comment by pfrazee** [comment]
We're going to stick with fork
