### ISSUE TITLE
Hyperdrive replication streams aren't always getting cleaned up

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#570]
For some reason, archives aren't always removing their replication streams, causing unbounded growth. Not a huge problem but it sucks up some memory

**Comment by DTV96Calibre** [comment]
I left Beaker open while connected to dat://taravancil.com/explore-the-p2p-web.md overnight and when I came back to my computer Beaker was using 2-3 gigs of RAM. I had 1096 peers for that page. 
![image](https://user-images.githubusercontent.com/10363350/37536168-3201bf98-2920-11e8-8b9e-8268c6cb96a5.png) And the browser is mostly unresponsive. Is this related to this bug?

**Comment by DTV96Calibre** [comment]
RAM usage has dropped but slowly increases back up.

**Comment by pfrazee** [comment]
Yeah this is on our todos to solve, there are definitely resources not getting released

**Comment by pfrazee** [comment]
I think we've figured this out, will have some updates committed soon.

**Comment by pfrazee** [comment]
Marking fixed, I think we got this handled
