### ISSUE TITLE
Inconsistant DatArchive method casing

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#571]
Operation System: Mac OS Sierra 10.12.5
Beaker Version: 0.7.2 (0.7.2)

---

It's a little bit odd that `archive.readFile()` is camel cased while `archive.readdir()` is all lower case. This caused some initial confusion for me when going back and forth between the two APIs. It also seems like a few of the other APIs like `archive.rmdir()` & `archive.mkdir()` match the casing of their command line cousins. I would argue that those APIs should not only be camel cased, but should probably be renamed to the longer `removeDirectory()` and `createDirectory()` to align with the other method names like `createFileActivityStream()`.

**Comment by taravancil** [comment]
Yeah, I get what you're saying. We're following the convention of Node's [`fs`](https://nodejs.org/api/fs.html) here, and will probably keep things the way they are for the sake of consistency.

**Comment by webdesserts** [comment]
Ahhh, that explains it. To be honest I never really noticed how inconsistent the method naming in `fs` was until now. A bit unfortunate that Beaker is inheriting that baggage, but I understand the decision.
