### ISSUE TITLE
URL "not secure" warning is misleading for self contained apps

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#572]
Operation System: ubuntu
Beaker Version: 0.7.2

The insecure protocol warning is confusing and way to aggressive. .. For users it indicates that the site which is shown is not secure. ... but the info is only about the protocol used: eg http://

tiddlywiki is a self contained app, that doesn't send anything back to any server.  So the warning is completely misleading here. 

![inappropriate-not-secure-warning](https://user-images.githubusercontent.com/374655/27529052-5cf5c916-5a53-11e7-9675-2cf8e431e9d3.png)

## Chrome and FireFox show the info like this:

![ff-http-protocol](https://user-images.githubusercontent.com/374655/27529341-5d1e4098-5a54-11e7-8ff8-cb9ac108f91a.png)

**Comment by taravancil** [comment]
We're definitely more aggressive than other browser vendors right now, but that's the direction other BVs are heading as well. For example, starting in October of this year, Chrome will mark any HTTP site with `<input>`s or `<textarea>`s as explicitly "Not secure", so TiddlyWiki would be included in that. We can consider more closely matching the schedule other vendors are on.

**Comment by pfrazee** [comment]
The logic is pretty straight-forward as well:

It's not that we don't trust TiddlyWiki -- we distrust the *transport*. Over HTTP has a high risk of injection-attacks by an intermediary. We can't guarantee that TiddlyWiki isn't compromised when you open it, so it's not a secure site.
