### ISSUE TITLE
hard crash when trying TiddlyWiki

### ISSUE THREAD

**Issue by TBD** [beakerbrowser/beaker#576]
Operation System: OSX 10.12.5
Beaker Version: 0.7.3

Steps:
1. create new site (hamburger menu - new site)
2. `wget http://tiddlywiki.com/prerelease/empty.html` in site dir (~/Sites/tiddlytest)
3. review and publish changes
4. add a journal entry
5. reload page -> hard crash

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000

**Comment by pfrazee** [comment]
I'm having trouble reproducing this. I'm on the same OSX version.

**Comment by TBD** [comment]
forgot about step 3.1 change the title of the TiddlyWiki

![Output sample](https://media.giphy.com/media/3o7bu34icLwQBeipsA/giphy.gif)

after saving the journal entry I press reload (CMD+R) (not shown in GIF) and crash

**Comment by pfrazee** [comment]
@TBD I just got it. Here's the dump:

<details>
Thread 13 Crashed:: Chrome_IOThread
0   com.github.electron.framework 	0x00000001060d741b 0x10458e000 + 28611611
1   com.github.electron.framework 	0x000000010465b6a6 atom::URLRequestFetchJob::OnURLFetchComplete(net::URLFetcher const*) + 70
2   com.github.electron.framework 	0x000000010465b710 non-virtual thunk to atom::URLRequestFetchJob::OnURLFetchComplete(net::URLFetcher const*) + 16
3   com.github.electron.framework 	0x0000000104811d50 0x10458e000 + 2637136
4   com.github.electron.framework 	0x00000001047db44b 0x10458e000 + 2413643
5   com.github.electron.framework 	0x00000001047db79c 0x10458e000 + 2414492
6   com.github.electron.framework 	0x00000001047dbb63 0x10458e000 + 2415459
7   com.github.electron.framework 	0x00000001047de385 0x10458e000 + 2425733
8   com.github.electron.framework 	0x00000001047db11e 0x10458e000 + 2412830
9   com.github.electron.framework 	0x00000001047f4173 0x10458e000 + 2515315
10  com.github.electron.framework 	0x0000000104a64388 0x10458e000 + 5071752
11  com.github.electron.framework 	0x0000000104a64516 0x10458e000 + 5072150
12  com.github.electron.framework 	0x00000001048148d9 0x10458e000 + 2648281
13  com.github.electron.framework 	0x00000001047e92b7 0x10458e000 + 2470583
14  libsystem_pthread.dylib       	0x00007fff8f9de93b _pthread_body + 180
15  libsystem_pthread.dylib       	0x00007fff8f9de887 _pthread_start + 286
16  libsystem_pthread.dylib       	0x00007fff8f9de08d thread_start + 13
</details>

This is the same issue as https://github.com/beakerbrowser/beaker/issues/474. It's being looked at by the electron team: https://github.com/electron/electron/issues/9342.

Thanks for filing! Sorry you got hit with it.
