### ISSUE TITLE
Add 'beakerbrowser' executable with npm link?

### ISSUE THREAD

**Issue by garbados** [beakerbrowser/beaker#581]
The current package.json runs the browser through npm start using gulp. Using a "bin" entry in package.json, npm link could be used to add a beakerbrowser executable to the user's PATH.

I began trying to work this out but gulp makes this pattern very difficult.

**Comment by pfrazee** [comment]
Oh yeah, that'd be nice. Let me spend a few minutes and see if I can get that working.

**Comment by pfrazee** [comment]
Done! Pull master and try it out

**Comment by garbados** [comment]
It works! Yay! Thank you :D
