### ISSUE TITLE
event listener fires for temporary files, if created according to the docs.

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#583]
Operation System: ubuntu 17.04
Beaker Version: 0.7.3

I did create the following code, according to the docs

	var archive = new DatArchive(document.origin);
	var evts = archive.createFileActivityStream("/dirName/**") // or...

	evts.addEventListener('changed', async ({path}) => {
		console.log(path, ": has been updated!")
	})

the problem is, that it also fires for temporary files eg: /dirName/.goutputstream-KA1M2Y like created by "gedit". In this case it fires 4 times ... 

So IMO the code to the activity stream should be 

	var evts = archive.createFileActivityStream("/dirName/[^.]**") // or...

Which works.   ... IMO the docs should be updated to mention this possibility. ... I don't know, it this is an issue with macOS too.

**Comment by pmario** [comment]
For me the best fitting docs for patterns to use seems to be: https://github.com/micromatch/micromatch
Since for me "excluding" matches are more important the the including ones. 

eg: including: `/dir/**` ... matches every change 
but excluding `!/dir/Draft_of**` ... excluding drafts and hidden files is more important

So IMO the docs should contain some links, where we can find the patterns, that are actually supported

**Comment by pfrazee** [comment]
Yeah the actual library we use is https://www.npmjs.com/package/anymatch, which uses micromatch on the inside. I'll update the docs.

**Comment by pmario** [comment]
Good. .... anymatch npm page says: 

>NOTE: As of v1.2.0, anymatch uses micromatch for glob pattern matching. ...

And there I found the best info about the possible patterns. Especially "exclude-match" patterns.

**Comment by pmario** [comment]
The mentioned API functions are deprecated with 0.8.0-pre.. So I'll close this issue and open a new one, if the new API has similar problems. ...
