### ISSUE TITLE
Apps that watch the fileActivityStream are affected by the live-reload mechanism

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#584]
Operation System: all
Beaker Version: 0.7.3

For apps, that watch for the "fileActivityStream" themselfs, the "live-reload" button is contra productive, because it auto-reloads the site which may not need to be reloaded. The app will handle it. 

There should be a possibility for an app, to disable the live reload button, or beaker may detect the API calls and disable or hide it.

**Comment by pfrazee** [comment]
I'm not sure the browser needs to force the button to disable. The user can just not use live-reloading in that case, right?

**Comment by pmario** [comment]
Is it possible, that the app can see, if the live-reload mechanism is enabled? So we can react to to the setting in a sensible way. eg: tell the user, what to do?

**Comment by sull** [comment]
I have found this to be an annoyance too. Maybe worth considering an app permission to signal to beaker in order to prevent a live reload for that specific change detection. In my case, if the app is in a certain state, the reload effectively causes the state to be lost, whereas in other cases the live reload works as intended to give user updated info. But I suppose app designers can work-around this if it should not be the concern of the browser. Still an interesting thought to let an app talk to Beaker in this way.

**Comment by webdesserts** [comment]
In my mind the live-reloading bit is mostly a developer feature. Which in that case, if the dev is aware that live-reloading is annoying for that app, why don't they turn it off? If an app needs "live-reloading"-like features, they can just use a File Activity Stream. Maybe live-reloading is something that should only appear in the upcoming "Workspaces" section of beaker? I think if you add any sort of API for this it should just be a `isLiveReloadEnabled` flag and nothing more. From that an app developer can display a warning or modify their logic. The former seems reasonable, the later seems overkill compared to the alternative solution of just turning off live reloading.

**Comment by pmario** [comment]
>In my mind the live-reloading bit is mostly a developer feature. 

Not necessarily. If I read a "cloned", "read only" version of a page, I want to be notified, if the original has been changed. ... And that's pure "consumer" related desire. 

>Which in that case, if the dev is aware that live-reloading is annoying for that app, why don't they turn it off?

Because new users, that experiment with their new toy, may not even know, that they activated the feature. ... They don't expect it to cause problems. ... So the developer needs to have a possibility to take action, if s/he knows better. 

....

I think "auto refresh" has been removed in 0.8.x So I'll close the issue and reopen if necessary.

**Comment by pfrazee** [comment]
No it's still in 0.8, we've just moved the menu item.

**Comment by pmario** [comment]
OK. ... Will there be some API to switch it on/off from an app?

**Comment by webdesserts** [comment]
> Because new users, that experiment with their new toy, may not even know, that they activated the feature. ... They don't expect it to cause problems. ... So the developer needs to have a possibility to take action, if s/he knows better.

Specifically

> if s/he knows better

I'm still confused on this. If the developer doesn't know enough to switch off live-reloading manually, how would they know enough to switch it off with a programmatic API?
