### ISSUE TITLE
How can I create a "read only" copy of a dat archive, that I own

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#585]
Operation System:
Beaker Version: 0.7.3

I seem to be unable to create a "read only" copy of a dat archive. ... How can I accomplish that?

**Comment by pfrazee** [comment]
Do you mean, you want to create an archive that nobody can edit, including yourself?

**Comment by pmario** [comment]
Nope, It is meant for testing: I want to switch write permission on and off. 

So I can see, how an app behaves if it has no write permission. eg: user visits the page. 

Because I do have write permission, it's hard to see, where eg: write access errors pop up, for users. .. I need to handle them in a proper way. ...

**Comment by pfrazee** [comment]
Oh I see. Let me think about that a bit.

**Comment by millette** [comment]
You could do from the command line:

```
dat clone YOUR_HASH NEW_DIR
cd NEW_DIR
dat share
```

That would make it read-only from Beaker's point of view, available at a new hash.

**Comment by pfrazee** [comment]
@millette's suggestion is the most straight-forward for the moment. I've got this in my TODOs.

**Comment by pmario** [comment]
I did find an other work around. I'm renaming the `secret_key` file and restart the browser. ... It's inconvenient and error prone, because you need to reload the browser ... but it works for the moment.

**Comment by pfrazee** [comment]
For now, I suggest using the dat cli to do this. Closing.
