### ISSUE TITLE
Option to populate forkOf in dat.json

### ISSUE THREAD

**Issue by millette** [beakerbrowser/beaker#591]
Currently, forks will leak the IDs of the parent dats. One might want to share a forked dat without revealing its origins.

Could be an option in the fork dialog and api method.

Question is, should it default to current behavior or is that a bad leak in a dat context?

See also #566 on naming (fork, clone).

**Comment by pfrazee** [comment]
We have a similar question about `createdBy` in https://github.com/beakerbrowser/beaker/issues/544, and I'm wondering in both cases if they're ever a good idea. We might need to just remove both.

**Comment by millette** [comment]
```forkOf``` and ```createdBy``` could probably be removed in favour of greater user control over the dat.json file.

**Comment by millette** [comment]
Oh, I missed #544. These issues could be merged, #591 (this) could be closed as a dupe.
