### ISSUE TITLE
Open a new window when clicking on the app icon 

### ISSUE THREAD

**Issue by bcomnes** [beakerbrowser/beaker#597]
Operation System: OSX
Beaker Version: 0.7.3

When clicking on the app icon, when all windows are closed, I would expect a new window to be created if all windows are closed.

e.g. 

```js
// Main thread
app.on('activate', function activate () {
  if (beaker.windows.length < 1) beaker.windows.push(new BeakerWindow())
})
```

**Comment by pfrazee** [comment]
Good idea. Added to the next milestone.
