### ISSUE TITLE
createFileActivityStream() gives limited information about deleted folders

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#607]
Operation System: ubuntu 17.04
Beaker Version: latest master

minimal test case: 

 - Take: https://self-mutating-site-pfrazee.hashbase.io/ 
 - fork it
 - copy paste the code below into index.js
 - open index.html
 - open dev-console
 - click "mutate" button
 - it will create 2 directories: /aaa/bbb/ and 
 - the file /aaa/bbb/hello.txt
 -  ----> output is OK
 - now open the OS file explorer
 - delete /aaa  with the file explorer .... it will delete the other stuff recursively. 
 - console output is wrong
 - it says: 

```
/aaa: has been updated!
/aaa/aaa: has been updated!
```

expected behaviour: 

 - It should tell `/aaa`, `/aaa/bbb` and `/aaa/bbb/index.html` have been modified. 

**index.js**

```
var selfArchive = new DatArchive('' + window.location)
setup()
activity()

async function activity () {
	var evts = selfArchive.createFileActivityStream('/**') // or...
	evts.addEventListener('invalidated', ({path}) => {
	  console.log( path + ': has been invalidated, downloading the update')
	})
	evts.addEventListener('changed', ({path}) => {
	  console.log( path + ': has been updated!')
	})
	// later:
//	evts.close()
}

async function setup () {
  // get info about self
  var info = await selfArchive.getInfo()
  console.log('About me', info)
  // setup the UI
  var mutateBtn = document.querySelector('#mutate-btn')
  document.querySelector('#site-state').textContent = (info.isOwner) ? 'editable' : 'read-only'
  if (!info.isOwner) {
    // not mutable, tell the user
    mutateBtn.classList.add('disabled')
    document.querySelector('#readonly-instructions').textContent = `
      Fork me to make a mutatable copy.
    `
  } else {
    // mutable, add mutate action
    mutateBtn.classList.remove('disabled')
    mutateBtn.addEventListener('click', onCreateDir)
  }
}

async function onCreateDir (e) {
  e.preventDefault()

  await selfArchive.mkdir('/aaa')
  await selfArchive.mkdir('/aaa/bbb')
  await selfArchive.writeFile('/aaa/bbb/hello.txt', 'hello world')
}
```

**Comment by pfrazee** [comment]
Thanks for such a detailed report. I'll try to reproduce this afternoon.

**Comment by pmario** [comment]
... yea, I know you have a mac to test with. :) ... It's possible, it's an electron OS related problem and not necessarily the beaker/dat API. ...

**Comment by pfrazee** [comment]
Ok I just tested this. It is as you say, but I'm not sure it's something I can change. At a glance, we're using node's fs.watch() with the recursive flag, which I'm sure is doing (as much as possible) whatever the OS provides.

So the event we're getting is just 'a change occurred at /aaa'. For us to be able to say what changed, we'd need a record of what *used* to be there, so we could do a diff. We'd probably need to create that record manually, and store it in memory or in a disk cache. I'm not sure it's worth the overhead.

**Comment by pmario** [comment]
Probably outdated. So I'll close it.
