### ISSUE TITLE
Fork results in missing files

### ISSUE THREAD

**Issue by rjsteinert** [beakerbrowser/beaker#608]
Operation System: macOS 10.12.5
Beaker Version: 0.7.3

![screen shot 2017-07-18 at 3 59 12 pm](https://user-images.githubusercontent.com/156575/28337146-9a574cea-6bd2-11e7-8556-578081c4e005.png)

Try forking dat://5476da55da9f261b5e9ac2bf486fe3cf44f699b2e252accd16f25b03c416247d/

**Comment by rjsteinert** [comment]
Hashbase is a peer on that dat now. Should be available if I'm offline, but of course you know that ;).

**Comment by rjsteinert** [comment]
Oh, I didn't capture it but I noticed on fork i was just making it notified me that not all files had yet been downloaded. I clicked the button to download the rest of them, continued with the fork and voila!

**Comment by pfrazee** [comment]
@rjsteinert ok cool, that makes sense. Do you think the UI needs to be updated to be more obvious? (Closing this issue, but feel free to reply to it.)

**Comment by rjsteinert** [comment]
I'm blazing through this stuff so maybe it is obvious. But if the button was red, then maybe I would have been more likely to have noticed. I'd be happy to send a PR for that but the last time I tried to dive into Beaker Browser development the learning curve was a little too high for me to make a quick tweak like that. Perhaps a code walk through screencast could help someone like me be able to feel comfortable diving in and working on some of that cosmetic UX stuff?

**Comment by pfrazee** [comment]
> Perhaps a code walk through screencast could help someone like me be able to feel comfortable diving in and working on some of that cosmetic UX stuff?

That's a good idea, I'll put that on my todo list

> But if the button was red, then maybe I would have been more likely to have noticed.

Could do something like that, or maybe make the primary action "finish downloading" instead of the secondary action.

**Comment by pfrazee** [comment]
Video made: https://www.youtube.com/watch?v=YuE9OO-ZDYo
