### ISSUE TITLE
Permissions dropdown doesn't scroll

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#611]
For apps that have been granted access to write to many archives, the permissions prompt overflows the screen and can't be scrolled.

<img width="404" alt="screen shot 2017-07-18 at 11 00 17 pm" src="https://user-images.githubusercontent.com/7584833/28350221-093c7272-6c0d-11e7-8bfc-3936e4b9b91d.png">

Also we should handle archives that don't have titles

**Comment by cdaringe** [comment]
> Also we should handle archives that don't have titles

almosted missed that little guy!  move it to the top! :)

**Comment by pfrazee** [comment]
Fixed the scrolling problem. If no-titles still persist we should open a separate issue.
