### ISSUE TITLE
Beaker offline not discovering peer on LAN?

### ISSUE THREAD

**Issue by rjsteinert** [beakerbrowser/beaker#614]
Operation System: Mac OS 10.12.3
Beaker Version: 0.7.3

Use case: 
When deploying an app to hundreds of computers in an environment where bandwidth is constrained or non-existent, it helps to only have to download an application update once and then have that one computer distribute the update to the hundreds of computers over a LAN.

Current behavior:
Two macs, on a LAN, no Internet connection. Sharing DATs back and forth from the command line works like a charm! So stoked about that. When trying to access that same Dat from the Beaker Browser, it times out. 

Also...

Current behavior:
One Mac, on a LAN with no Internet connection. On the command line `dat share`, go to that Dat address in Beaker, Beaker times out. Turn off the Mac's wifi adapter, reload that dat URL in Beaker and it works.

**Comment by pfrazee** [comment]
@rjsteinert does it work when accessing the Dat that's being hosted from the current machine? Remote one? What about 2 beakers on the same LAN?

**Comment by rjsteinert** [comment]
My LAN has no internet connection but I'm on talky over cellphone. Wanna see what I'm trying? https://talky.io/beaker

**Comment by pfrazee** [comment]
We did a debug session and found that Beaker was failing to make Dat connections (and other things) when wifi was enabled but no WAN connection existed.

**Comment by rjsteinert** [comment]
@pfrazee That's great you were able to reproduce, too bad it's an issue :P. If you have a feature branch with a fix, I'd be more than happy to test.

**Comment by pfrazee** [comment]
Thanks, I'll keep you in the loop

**Comment by rjsteinert** [comment]
@pfrazee Added a second current behavior mentioning that behavior where you need to turn off your wifi adapter for Beaker to connect to the Dat being shared on the same computer.

**Comment by pfrazee** [comment]
We've done a bit more discovery debugging since this issue was filed. We have found that, on our home router, multicast can sometimes totally stop working and we have to restart the router. We'll have to see if any of our software can improve on that.

**Comment by rjsteinert** [comment]
Thanks for the heads up @pfrazee

**Comment by oleometal** [comment]
Ya puedes cerrar este problema, lo probé y funciona bien.
