### ISSUE TITLE
Loading large files that are not in a local dat is causing Beaker to crash

### ISSUE THREAD

**Issue by rjsteinert** [beakerbrowser/beaker#616]
Operation System: macOS
Beaker Version: 0.7.3 and built from master 273a7574e3f58b63daf45445079effe46483ff6f

I shared a blog page with a large (250MB) mp4 file. When navigating to that page in Beaker, the Beaker browser will exit with no warning. Then dat clone on the command line that same dat archive and open the same page in Beaker browser and it does not crash. We replicated this on two different machines. 

What the command to start Beaker with log output? I'll upload the log output on crash.

**Comment by rjsteinert** [comment]
Thanks @chrisekelley for helping reproduce this.

**Comment by rjsteinert** [comment]
Here's the dat dat://blog-rjsteinert.hashbase.io/. Click on the first link to start loading up that troubled page or go straight to it at dat://blog-rjsteinert.hashbase.io/#!2017-07-22/p2p-sharing-of-live-notes-during-a-metting-with-beaker-browser-and-dat.md

**Comment by rjsteinert** [comment]
Also, an issue we're seeing with hashbase's bridge to https, this file is causing a 500 error. 

![screen shot 2017-07-22 at 5 22 55 pm](https://user-images.githubusercontent.com/156575/28494654-8dce8848-6f02-11e7-97ee-ce973c061ba6.png)

**Comment by rjsteinert** [comment]
Oops, changed the link that explodes to dat://blog-rjsteinert.hashbase.io/#!2017-07-22/real-time-decentralized-P2P-sharing-of-notes-using-beaker-browser.md

**Comment by pfrazee** [comment]
The hashbase bug is new so I'll look into that, but the Beaker bug is a known and long-standing problem with electron. I've been lobbying them to fix it for us. See also https://github.com/beakerbrowser/beaker/issues/474 and https://github.com/beakerbrowser/beaker/issues/576

Sorry for the crash :( Hopefully we'll get this nipped soon. Closing as a duplicate.

**Comment by rjsteinert** [comment]
Bummer about that Electron bug. Thanks for the info @pfrazee !

**Comment by rjsteinert** [comment]
@pfrazee Hm, actually, maybe that electron bug isn't the issue here because of the fact that after you `dat clone ...` that archive locally, the video file does load in Beaker.

<img width="1232" alt="screen shot 2017-07-22 at 5 49 33 pm" src="https://user-images.githubusercontent.com/156575/28494785-73afc50e-6f06-11e7-850c-760d2dfe057e.png">

**Comment by rjsteinert** [comment]
Actually, if I reload the page a couple of times it does eventually crash.
