### ISSUE TITLE
Logging in on YouTube

### ISSUE THREAD

**Issue by jamen** [beakerbrowser/beaker#618]
Operation System: Linux Mint
Beaker Version: latest on master

Whenever I try signing into YouTube, it redirects me to this page:

![image](https://user-images.githubusercontent.com/6251703/28496665-ed5e0b74-6f36-11e7-882d-d53ea8ad60e4.png)

Strange enough, after retrying multiple times, I was finally able to log in despite being redirected there every time.

**Comment by pfrazee** [comment]
Thanks for reporting, I'll look into it.

**Comment by jamen** [comment]
I'm still getting this, but its not consistent.  I'll close this as wontfix, since this is more of an issue with YouTube than Beaker probably, and I'm not sure how Beaker would even patch it.
