### ISSUE TITLE
bug with url bar + backspace

### ISSUE THREAD

**Issue by ralphtheninja** [beakerbrowser/beaker#626]
Operation System: Ubuntu 17.04
Beaker Version: 00113ba1

If I click in the url browser field and hit backspace I eventually end up with the same url I had and if I press backspace and hold it will loop forever:

Backspace until one character left:

![beaker-url-backspace](https://user-images.githubusercontent.com/308049/28620805-d9163076-720e-11e7-9834-594909770d63.png)

Hit backspace again and the original url comes back:

![beaker-url-backspace2](https://user-images.githubusercontent.com/308049/28620806-d919e608-720e-11e7-8f34-1b911100b8c3.png)

**Comment by taravancil** [comment]
Possibly related to #620
