### ISSUE TITLE
Folders of sites created with "New site" button don't contain a dat.json file

### ISSUE THREAD

**Issue by lachenmayer** [beakerbrowser/beaker#627]
**To reproduce**
1. Click on the "New site" button in the right menu
2. Create a new site
3. Navigate to the newly created folder

**Expected**
The folder should contain a dat.json file

**Actual**
The folder is empty

OS: macOS 10.11.6
Beaker version: GitHub master 00113ba

**Comment by pfrazee** [comment]
I'll look into it, thanks for reporting

**Comment by fredhampton** [comment]
I will give it a try 


Thank !!!!

**Comment by pfrazee** [comment]
@lachenmayer Tara and I are not able to reproduce this bug. Can you double check it for me?

**Comment by pfrazee** [comment]
Code is all new here, going to assume fixed
