### ISSUE TITLE
Updated version of dat site shared with Beaker not showing up correctly in datproject/view

### ISSUE THREAD

**Issue by kaosat-dev** [beakerbrowser/beaker#629]
Operation System: MacOs Sierra
Beaker Version: 0.7.3
Hello !
Perhaps I am missing something obvious, but I did the following:
* created a site with Beaker (with Beaker 0.7.1, around 2 months ago)
* updated one of the files (& comited) yesterday
* checked the dat with https://datproject.org/view

Issue: 
- I am still seeing the date of the old changes in the modification date 
- none of the file contents can be retrieved : attempts to retrieve it until I get the following error in the console: ```Failed to load resource: the server responded with a status of 504 ()```
- if I fork the site however, the fork behaves as expected

Thanks in advance , and thanks for the great work !

**Comment by pfrazee** [comment]
This *might* be a problem with datproject.org instead of with Beaker. I just tried opening an archive of my own in datproject.org and it didn't load. Then I uploaded the same archive to hashbase and it worked fine.

Does that sound like it could be the same issue that you had, or am I missing something?

**Comment by kaosat-dev** [comment]
@pfrazee I did various tests in the last few days, and it does seem the same, but not 100% sure:
- dats reshared with hashbase + datproject works every time
- dats with Beaker only + datproject do not seem to work at all (never found)
- dats with Beaker + Dat app (adding a peer) + datproject : only work on certain networks it seems?

**Comment by pfrazee** [comment]
I'm going to do some debugging today. I'll let you know if I find a bug here.

**Comment by pfrazee** [comment]
We have a couple of issues already for the intermittent connectivity problems. (Did some debugging today, we have some leads.) Going to close as a duplicate.
