### ISSUE TITLE
Issue with download() and readFile() not timing out

### ISSUE THREAD

**Issue by millette** [beakerbrowser/beaker#645]
_I've been having issues with dat availability and datArchive.download() and .readFile() where the latter never ends, whatever the specified timeout, if the content isn't available yet but is not a 404 either._

That being said, a workaround for now is to add the target dat to my library. Being able to do this JS side would be helpful, even if it prompted the user to confirm.

**Comment by pfrazee** [comment]
Hey, sorry I missed this issue when you reported it.

Could probably just try to fix the problem with download or readFile. Is the issue that you're not getting a timeout when you should, or that the data isnt arriving unless you add its archive to your library?

**Comment by millette** [comment]
readFile() simply hangs there, doesn't timeout, and doesn't complete with data either.

But an API to add a dat to my library would be handy in any case.

**Comment by pfrazee** [comment]
> readFile() simply hangs there, doesn't timeout, and doesn't complete with data either.

I'll look into that. Do you have the issue if you run download() first?

> But an API to add a dat to my library would be handy in any case.

I'll open a separate issue for that.

**Comment by millette** [comment]
Running download() first, readFile() always finishes (I think...)

It's just that it _seemed_ to take much longer. I should write proper test cases... but my focus is rather lacking these days.

**Comment by pfrazee** [comment]
No worries. I'll look into it.

**Comment by pfrazee** [comment]
Ok I think I've made the timeout much more reliable in 0.8. Please reopen if you still experience issues.
