### ISSUE TITLE
Web API tutorials: no console output

### ISSUE THREAD

**Issue by sdockray** [beakerbrowser/beaker#646]
Operation System: OSX 10.11.6
Beaker Version: Version: 0.7.5 Electron: 1.7.4 - Chromium: 58.0.3029.110 - Node: 7.9.0

When I follow the Web API tutorials, I am not getting any of the expected console output. I added the extra `console.log('main()')` at the top of main() and that even isn't printing out. I don't understand the mousewheel event violation that is shown, but I'm assuming it's some related system problem.

<img width="1227" alt="screenshot 2017-08-07 16 30 21" src="https://user-images.githubusercontent.com/2905230/29054554-456f018c-7c3a-11e7-81e2-00c43e8fef56.png">

**Comment by pfrazee** [comment]
Oh this is a little confusing: There's actually 2 different devtools. There's devtools for the browser UI, and there's devtools for the current page.

You're in the browser's devtools, which is the wrong one.

Right click on the page and select "Inspect Element" to see the right one. I'm going to close this issue but reference it in another issue to address this confusing UI.
