### ISSUE TITLE
Website SVGS 404

### ISSUE THREAD

**Issue by ErwanLent** [beakerbrowser/beaker#648]
Unrelated to beaker app, but the landing page has 2 svgs that 404

https://beakerbrowser.com/img/features/self-hosting.svg
https://beakerbrowser.com/img/features/versioned-urls.svg

**Comment by taravancil** [comment]
Thanks for the heads up! Closing, this, it's fixed in master on the [beakerbrowser.com repo](https://github.com/beakerbrowser/beakerbrowser.com) and will be launched soon
