### ISSUE TITLE
Run in background / minimize to tray mode

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#650]
I've gotten a few requests to keep Beaker running in the tray after close, so that p2p sites stay available. Seems like a good idea to me. Anybody against?

**Comment by taravancil** [comment]
I'm on board!

I also love the idea of eventually being able to see which sites I'm hosting at any given moment, and to be able to toggle each one individually

**Comment by danrobi11** [comment]
Hello
Version: 1.0.0-prerelease.7  doesnt run in tray here
OS: MX x86_64
Kernel: 4.19.0-9-amd64 
WM: awesome

**Comment by aadilayub** [comment]
@danrobi11 I can confirm that this is fixed the next release. Typing this from the latest beaker build on i3wm. Can see Beaker in the system tray.

**Comment by danrobi11** [comment]
Beaker.Browser-1.0.0 systray working fine here. Thanks!
