### ISSUE TITLE
Clicking 'Load more' from sidebar reloads already visible revisions

### ISSUE THREAD

**Issue by emanuelfeld** [beakerbrowser/beaker#653]
Operation System: macOS 10.12.5
Beaker Version: v0.7.5

e.g. 
![screen shot 2017-08-10 at 8 08 58 pm](https://user-images.githubusercontent.com/4269640/29197211-c7095700-7e07-11e7-87eb-4fa6cac6444c.PNG)

**Comment by pfrazee** [comment]
We'll take care of that. Thanks for reporting.

**Comment by pfrazee** [comment]
We've removed the sidebar and the revision history from the `beaker-0.8` branch
