### ISSUE TITLE
Start Page blank

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#660]
Operation System: OSX Sierra 10.12.6
Beaker Version: 0.7.5

Fresh installed latest release version. Start pages are blank with below console output:

```
Failed to load resource: the server responded with a status of 404 (OK)
main.js:683 Uncaught (in promise) Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: bookmarks.profileId, bookmarks.url
    at loadBookmarks (main.js:886)
    at setup (main.js:649)
    at Object.1.builtin-pages-lib (main.js:647)
    at s (main.js:1)
    at e (main.js:1)
    at main.js:1
```

**Comment by pfrazee** [comment]
Ah that's no good at all. I think our new default bookmarks may have caused it. I'll get into it this afternoon.

**Comment by pfrazee** [comment]
@sull can you try the `remove-default-bookmarks` branch for me?

**Comment by sull** [comment]
I could not get it to run. Will try again later today.

`Error: Cannot find module 'pauls-electron-rpc' ... `

**Comment by pfrazee** [comment]
Bleh that may be some npm nonsense. You may have to burnthemall after checking out the branch.

**Comment by sull** [comment]
I cleared out my beaker applications directory and it looks good now. 
prob had overlap/corruption from a build i run sometimes and the released binary.
