### ISSUE TITLE
`Invalid URL: must be a dat:// URL` on `new DatArchive(window.location.href` using localhost

### ISSUE THREAD

**Issue by rjsteinert** [beakerbrowser/beaker#661]
Operation System: macOS 10.12.5
Beaker Version: v0.7.5

I created a new dat site in beaker, set the folder of the site to an app I'm working, ran `http-server` from that directory, brought it up in Beaker over localhost, and then no luck instantiating a new DatArchive. Am I using this incorrectly?

![screen shot 2017-08-15 at 3 41 26 pm](https://user-images.githubusercontent.com/156575/29333153-c2f34ad2-81d0-11e7-8287-67c3b76de163.png)

**Comment by pfrazee** [comment]
> ran http-server from that directory

That's the bit that you don't need. By doing that, you're hosting twice: once over http, and once over dat. Beaker hosts over dat for you, once you create the site. Go to your library, find the site you created for the folder, then click its title. You'll go to a `dat://` address. Once you do that, things should work as expected with `DatArchive`.

Closing, but feel free to reply with more questions.

**Comment by rjsteinert** [comment]
Hi @pfrazee - I was looking at https://github.com/beakerbrowser/beaker/pull/590/files and had misinterpreted it. I was thinking perhaps DatArchive was doing something like looking for `http://localhost/dat.json` to figure out the dat archive URL but if I use the dat URL directly now from http://localhost or https://anything... it now works where as it wouldn't before that PR.

![screen shot 2017-08-15 at 4 12 48 pm](https://user-images.githubusercontent.com/156575/29334262-d392203a-81d4-11e7-894e-a80ea23aee9b.png)

**Comment by rjsteinert** [comment]
@pfrazee Cool stuff!

**Comment by pfrazee** [comment]
Ok great! :)
