### ISSUE TITLE
Find in Page element could be more prominent

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#663]
Whenever I do a search in the page, I usually have trouble recognizing where the search box is.

We should consider making it more prominent, by either focusing the search element or overlaying it on the webview.

<img width="1121" alt="screen shot 2017-08-16 at 2 50 20 pm" src="https://user-images.githubusercontent.com/7584833/29382510-5e94523a-8292-11e7-8677-add538e4d6e9.png">

**Comment by pfrazee** [comment]
Done in `beaker-0.8` branch
