### ISSUE TITLE
Beaker tab bar has no background on macOS 10.13

### ISSUE THREAD

**Issue by thepatrick** [beakerbrowser/beaker#664]
Operation System: macOS 10.13 developer beta (all versions including 6)
Beaker Version: v0.7.5

<img width="1861" alt="screen shot 2017-08-21 at 1 24 03 pm copy" src="https://user-images.githubusercontent.com/7331/29502611-a33481d6-8674-11e7-9ed4-196071708715.png">

I know it's a beta OS, but I figured y'all might want to know about it anyway, especially as if it's an OS bug it's probably going to ship at least on 10.13.0 anyway.

**Comment by pfrazee** [comment]
Huh, yeah looks like they made transparency effects *really* transparent.

We've actually moved away from the transparency effect in the toolbar, so this is already fixed in master. Thanks for reporting though.
