### ISSUE TITLE
Linux doesn't support import both files & folders at the same time

### ISSUE THREAD

**Issue by alexandre1985** [beakerbrowser/beaker#668]
Operation System:
Manjaro Deepin (Linux x64)
Beaker Version:
0.7.5

When I click to create a new website I can't seem to import files.
It opens a dialog to import a file but all files are greyed out and I can't select them.

**Comment by pfrazee** [comment]
That's no good. I'll spin up my linux box soon and see if I can replicate the issue.

Sorry for the trouble.

**Comment by alexandre1985** [comment]
That's ok.
The interface is slightly different from the video.
It doesn't have the "add Files" or "open folder" links. I can only import files through the dropdown button.
I also haven't figured out a way to change the title, it remains "Untitled".
I also have deleted a website project, then closed beaker them open it and the deleted project appears on the left panel.
If you want to install my distro here it is the [Manjaro Deepin downloads](https://sourceforge.net/projects/manjarolinux-community/files/deepin/17.0.2/)

**Comment by pfrazee** [comment]
FYI If you're on the master branch, you may be getting some half-finished work that we're doing.

**Comment by alexandre1985** [comment]
so what git commands should I execute to get a stable release?
Thanks

**Comment by pfrazee** [comment]
Sorry, try this:

```
git checkout tags/0.7.5
rm package-lock.json # to battle npm's nonsense
rm app/package-lock.json
npm run burnthemall
npm start
```

**Comment by pfrazee** [comment]
(Not sure that'll solve your problem though)

**Comment by alexandre1985** [comment]
Now its better.
Everything is resolved except selecting the files which are still greyed out.
Here is a screenshot of what I get:
![deepinscreenshot_electron_20170824122345](https://user-images.githubusercontent.com/5586308/29664474-a138bb4a-88c7-11e7-9cbe-2171dd891d9c.png)

**Comment by pfrazee** [comment]
Great, I'm sure that's just a misconfigured param. I'll jump into my linux box soon.

**Comment by pfrazee** [comment]
Turns out, Linux and Windows aren't able to import files and folders at the same time. You have to choose one or the other. Very weak.

@alexandre1985 if you can wait for the next release, I'll put some time into a solution for this that deals with the folders/files situation.

**Comment by alexandre1985** [comment]
That's ok, I'll wait

**Comment by pfrazee** [comment]
Thanks Daniel, sorry about the wait.

**Comment by rh0** [comment]
This issue bit me today when I pulled master and rebuilt to update Beaker. Rolling back to 0.7.5 as you suggested seemed to fix it.  Just thought I'd chime in.
Arch Linux x64

**Comment by dwblair** [comment]
Also bitten on Ubuntu 16.10 :)  Wasn't able to import folders or files:  individual files are greyed out; folders allow import, but nothing happens.  But I also rolled back to 0.7.5, which is workable -- can import folders (but not individual files) ...

Cheers!

**Comment by cdaringe** [comment]
i also reproduced @dwblair's claim on my xubu vm tonight.  looks like [onImportFiles](https://github.com/beakerbrowser/beaker/blob/master/app/builtin-pages/views/library.js#L343) expects `archiveInfo`, but is not passed one.  therefore, `cannot read property 'url' of undefined` is yielded on [L643](https://github.com/beakerbrowser/beaker/blob/4cedb3d26a10ca2e15715291ce3ad2859a318788/app/builtin-pages/views/library.js#L643).  im not sure what the convention is in this codebase yet for binding that missing var.

> I'll put some time into a solution for this that deals with the folders/files situation

ya, it's a real bummer.  i see this documented in the electron docs too.  it's almost as though we need two seperate buttons--import files, import folders.  i'm not optimistic about other meaningful UX hacks that would meet the need.

**Comment by pfrazee** [comment]
We might need to consider a custom built file-picker modal

**Comment by micahscopes** [comment]
I'm also having this issue on arch linux

**Comment by TeddyDD** [comment]
I have the same issue both on master branch `91781b` and on stable release. I can't select files and directory import does not work. I'm on Arch Linux.

**Comment by pfrazee** [comment]
On the stable release you should be able to select files, I think.

I'm 99% sure we'll have to solve this with a custom files browser modal on
linux.

**Comment by TeddyDD** [comment]
![zrzut ekranu z 2017-10-12 17-07-35](https://user-images.githubusercontent.com/4397533/31503417-e3057d6e-af6f-11e7-8adf-62c91299fff0.png)

Unfortunately files are greyed out.

**Comment by pfrazee** [comment]
Bleh

**Comment by TeddyDD** [comment]
Sorry, I was wrong, `0.7.5` works pretty well with `change folder`

**Comment by sternj** [comment]
For everyone building from source on Linux-- removing the 'openDirectory' option from the line containing "showOpenDialog" in either beaker/app/builtin-pages/views/library.js or beaker/app/builtin-pages/com/files-list.js (depending on what branch you're in) and then rebuilding can provide a temporary fix to this issue.

**Comment by pfrazee** [comment]
Version 0.7.8 will have an "Add folder" btn that's separate from "Add file", if you're on linux
