### ISSUE TITLE
Uncaught exception when I click on dat links

### ISSUE THREAD

**Issue by curioussavage** [beakerbrowser/beaker#669]
Operation System: macOS
Beaker Version: Beaker v0.7.5

![screen shot 2017-08-23 at 4 55 07 pm](https://user-images.githubusercontent.com/7064600/29643500-4eb3c534-8824-11e7-9c55-7a594c30d5c4.png)

**Comment by pfrazee** [comment]
Woah that's new. Are you running the built binary, or from source?

**Comment by pfrazee** [comment]
Also, can you share the dat link that you're clicking on?

**Comment by curioussavage** [comment]
The binary. I don't think I ever ran from source on this machine since this its a mac. 

It has happened on multiple dat links. I will try again. Problem is it gets into a loop and just shows that dialog repeatedly until I kill the main beaker process.

**Comment by curioussavage** [comment]
The first one I clicked was on the WYSIWYWiki link dat://wysiwywiki-pfrazee.hashbase.io/

**Comment by curioussavage** [comment]
Also happens when I get a random dat url from https://datproject.org/explore without a domain name

eg: dat://43bafc583c0c42fcc712b35a5f6bce62cc92567a5c719d10ea6acfca4903b843

**Comment by pfrazee** [comment]
Ok I'll see what I can do, thanks for reporting.

**Comment by pfrazee** [comment]
Logging my investigation:

This error is occurring in sodium-javascript. Most OSX users should be able to run sodium-native, so 1) something prevented the user's computer from running native, and 2) sodium-javascript has a bug, and I'd probably be able to reproduce if I can force sodium-javascript locally.

**Comment by pfrazee** [comment]
Ok it turns out this is a bug in https://github.com/sodium-friends/sodium-javascript that was fixed about a month ago, but npm's baffling install rules hosed me again and the update didn't get included.

Unfortunately I think you'll have to build from source with latest deps for now to solve this. 0.8 is on the way but will still take a couple weeks.
