### ISSUE TITLE
website.com -> https://website.com redirect problem

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#670]
I typed google.com into the URL bar. Beaker loaded google.com as expected, but when I selected the text in the URL bar and pressed enter to reload the page, it 404ed.

I restarted Beaker, and the website.com -> https://website.com redirects started working as expected.

**Comment by taravancil** [comment]
Not *that* hard to reproduce. I do encounter this about 2-3 times/day, but it's tough to reproduce reliably.

**Comment by pfrazee** [comment]
Should be fixed in `beaker-0.8` branch
