### ISSUE TITLE
Typing in URL bar sometimes interrupted

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#671]
Sometimes when I'm typing in the URL bar, the URL input loses focus and interrupts my typing. I haven't figured out what triggers this, but it happens to me multiple times a day.

Does anyone else experience this?

**Comment by millette** [comment]
Related: #679 (for reference).

**Comment by taravancil** [comment]
Hi @Butterfly, this happens when I have multiple tabs open/loading, and then click `Cmd+T` to open a new tab and start typing. In Beaker (and every other browser afaik), opening a new tab automatically focuses the URL input. But in Beaker, this bug interrupts the element being focused while I'm typing.

The nice thing about it,  is that's it's defintely a bug. Typing in the URL input should *not* be interrupted. We'll fix it before the 0.8 release 😸
