### ISSUE TITLE
package.json: Add missing `license` field

### ISSUE THREAD

**Issue by d2s** [beakerbrowser/beaker#674]
Operation System: any
Beaker Version: fb5cff1da8ee8404ac907f23950d9b4c8df9f513

- Add missing `license` field to the `package.json` file, because it will help automated tools to find how the software is licensed. That will also make the license visible to the GitHub repository's header area.
- This change would also reduce amount of warning messages visible when running `npm install` as the `npm` process warns about missing `license` fields.

More details:
- https://docs.npmjs.com/files/package.json#license

**Comment by millette** [comment]
Regarding
> That will also make the license visible to the GitHub repository's header area.

I don't think github reads ```package.json``` at all. See [their article on Licensing a repository]( https://help.github.com/articles/licensing-a-repository/) for details.

Not saying adding a ```license``` field to package.json is a bad idea, but for it to show up in the header area, as you say, there needs to be a LICENSE.txt file (or similar) in the repo.
