### ISSUE TITLE
Progress tag position covers the toolbar dropdown after downloading a file

### ISSUE THREAD

**Issue by jafow** [beakerbrowser/beaker#675]
Operation System: Ubuntu 16.04
Beaker Version: v0.7.5 latest from master (4cedb3)

After downloading a file the `<progress>` tag covers part of the dropdown menu.  
![download_progress_tag](https://user-images.githubusercontent.com/6464919/29896452-e12a43b2-8d91-11e7-99c3-a32aa315bd62.png)

Only seeing this on my Linux machine. 

PS: thanks for making Beaker it's :100:

**Comment by pfrazee** [comment]
Thanks for reporting. That's not right!

**Comment by taravancil** [comment]
I'll take this one. I've been working on the downloads items in the dropdown menu so I can hit this at the same time.

**Comment by taravancil** [comment]
Fixed in the 0.8 branch
