### ISSUE TITLE
Find in page should not find elements with opacity: 0, visibility: hidden, display: none

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#677]
Is this possible? If so, it would be a nice enhancement.

**Comment by akoenig** [comment]
I investigated that on the current `beaker-0.8` branch and it seems that only `opacity: 0` is affected.

**Comment by akoenig** [comment]
Okay, that seems to be a Chromium bug, which can also be reproduced in Google Chrome itself. I created a issue for that case in the Chromium issue tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=767917

**Comment by pfrazee** [comment]
Thanks Andre!

**Comment by akoenig** [comment]
@pfrazee You're very welcome :) Hopefully that will get fixed soon.
