### ISSUE TITLE
User profile "other accounts"

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#680]
I think the profile.json spec should include referencing other 3rd party identities such as Twitter handle, email address, phone number etc.

```
{
 "@context": "http://schema.org",
  "@type": "Person",
  "name": "Alice Roberts",
  "image": "/profile.jpg",
  "description": "Finally trying out this 'Dat' thing!",
 "external_ids":[
   {"label": "twitter", "id": "sull"},
   {"label": "email", "id": "sull@my.email"},
   {"label": "skype", "id": "sullonskype"}
  ],
  "follows": [
    {"url": "dat://.../", name: "Bob"},
    {"url": "dat://.../", name: "Carla"},
    {"url": "dat://.../", name: "Dan"}
  ]
}
```
Alternatively, a new spec (identity.json) to hold all external IDs that is referenced from profile.json

This will eventually be useful for discovery engines that are allowed access to read profiles.
Verification layer should be added at some point too (a la keybase et all).

Is this too much for your strategy of p2p ID in beakerland?

**Comment by pfrazee** [comment]
> Is this too much for your strategy of p2p ID in beakerland?

Not too much at all. We talked about it earlier, and decided to defer while we work on other bits. But it'd be quite simple to have unverified handles, and then add verifications later. In fact, I think we 100% should do it!

Profile.json would probably be a fine place for that data. We'll leave this issue open and either get it done in 0.8, or soon after.

**Comment by roscoevanderboom** [comment]
could this (future) function be extended to creating a login for Beaker Bowser?

**Comment by pfrazee** [comment]
We're going to be putting together an identity system for sure, and I suspect it could be used to authenticate connections at some point. The ideal future is that a webserver will be able to say "paulfrazee.com is logging in!"
