### ISSUE TITLE
Add full-screen mode on MacOS

### ISSUE THREAD

**Issue by dwayneroberts** [beakerbrowser/beaker#681]
Operation System: macOS Sierra 10.12.6 (16G29)
Beaker Version: 0.7.5

The browser only maximises or minimises (see fig. 1) when clicking the green "zoom button", as it used to be prior to OS X Yosemite, but won't actually go into full screen mode.

In OS X Yosemite, the zoom button became a full screen button. The traditional zoom button can still be accessed by holding the Alt/Option key.

![ex 1](https://user-images.githubusercontent.com/5333985/30248202-40af2ac8-961b-11e7-8a95-572b986428f0.png)
_fig. 1 traditional_

![ex 2](https://user-images.githubusercontent.com/5333985/30248201-40ae68b8-961b-11e7-8c54-fd0b55d64e8d.png)
_fig. 2 new_

**Comment by pfrazee** [comment]
Added to the todos. Cheers.

**Comment by pfrazee** [comment]
Done in the beaker-0.8 branch
