### ISSUE TITLE
[question] How to handle auth?

### ISSUE THREAD

**Issue by corysimmons** [beakerbrowser/beaker#683]
Say I wanted to make an app with users and such, is there a flow + docs for that yet?

btw, cool project. Hope it takes off.

**Comment by pfrazee** [comment]
Hi Cory!

The simple answer is to use a Dat archive as a user identity. You can't use it to authenticate with services, but you *can* use it to distribute user data and identify the user.

In the next version (0.8), Beaker will have a builtin profile which does exactly that. There's a good chance that profile will be shared among applications.
