### ISSUE TITLE
Emoji characters slow down rendering in builtin pages

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#686]
Here's a fun performance bug:

It appears that emoji in the builtin pages slow down rendering to a crawl. You can see this in effect by adding an emoji to any builtin page, either via it's `.html` file or its `.js` file in `app/builtin-pages/views/`.

Currently we're working around this by stripping out non-ASCII characters, but that's not a long-term solution:

https://github.com/beakerbrowser/beaker/commit/f5eedbf0c70236f398679fa696bc557de21d9f96

**Comment by akoenig** [comment]
@taravancil I investigated this issue a little bit, but I'm not able to reproduce it. For me, the performance seems to be "okay", when the webview has to render Emojis:

![beaker-emoji-performance](https://user-images.githubusercontent.com/224910/30756671-f065021c-9fcb-11e7-91d1-f38fa46b9a07.gif)

**Comment by taravancil** [comment]
Hmm. Is performance still OK if you refresh that page after adding emoji in the timeline? @pfrazee and I are both able to reproduce that the timeline's initial rendering is markedly slower when posts have emoji.

**Comment by pfrazee** [comment]
Actually I dont get a noticeable delay there. I saw the slowdown in the
history page.

... actually though, that *may* have just been your computer. I can't
really remember now.

**Comment by akoenig** [comment]
@taravancil @pfrazee I tested both pages on my machine a couple of minutes ago and it scrolls butter smooth. :)

**Comment by pfrazee** [comment]
@taravancil didnt you find an issue somewhere saying this is a macos edgecase?

**Comment by taravancil** [comment]
Yeah it turns out there's a pretty nasty graphics bug that affects only a few Apple devices models (mine included) so this can be closed
