### ISSUE TITLE
"This site can’t be reached"

### ISSUE THREAD

**Issue by eklem** [beakerbrowser/beaker#689]
Operation System: mac OS Sierra 10.12.6 (16G29)
Beaker Version: v0.7.5

URL: https://www.git-awards.com/

```
This site can’t be reached
ERR_CONNECTION_TIMED_OUT
```
![screen shot 2017-09-26 at 09 07 01](https://user-images.githubusercontent.com/236656/30847041-57120908-a29a-11e7-92cb-3a3eb060163c.png)

**Comment by eklem** [comment]
![screen shot 2017-09-26 at 09 53 00](https://user-images.githubusercontent.com/236656/30848812-8b6bf104-a2a0-11e7-852c-82760cf9796a.png)

**Comment by taravancil** [comment]
That’s an issue with https://www.git-awards.com, not Beaker.

**Comment by pfrazee** [comment]
Yeah it doesnt open in other browsers either.

**Comment by eklem** [comment]
Sorry, my fault!
