### ISSUE TITLE
MacOS .dmg app fails on opening

### ISSUE THREAD

**Issue by Fraser-Greenlee** [beakerbrowser/beaker#690]
Operation System: macOS Sierra (version 10.12.6)
Beaker Version: 0.7.5

Installed the app but when I try to open it I get the error:

<img width="439" alt="screen shot 2017-09-26 at 16 18 37" src="https://user-images.githubusercontent.com/8402500/30868383-5e044f3c-a2d6-11e7-8b32-b2dd684d480a.png">

**Comment by pfrazee** [comment]
Hi @Fraser-Greenlee, sorry I just saw this.

I'm not quite sure how this is happening. It must be some kind of electron bug, because the stack trace you have suggests that the `screen` API is null. Doesn't seem possible.

Can you try building from source, at the `0.7.5` tag?

**Comment by pfrazee** [comment]
Confirmed this is still happening.

**Comment by natevw** [comment]
Note the `screen` API issue also causes an alert almost every time I scroll on a MacBook. Filed a new issue #753 for that.
