### ISSUE TITLE
JavaScript error when trying to open link from other programs

### ISSUE THREAD

**Issue by eklem** [beakerbrowser/beaker#692]
Operation System: macOS Sierra 10.12.6 (16G29)
Beaker Version: v0.7.5

If trying to open an http link from email (Outlook), Slack or Spotify, I get this error:

```
A JavaScript error occured in the main process
Uncaught Exception:
Error. Object ha ben destroyed at WebContents.send (/Applications/Beaker Browser.app/Contents/Resources/electron.asar/browser/api/web-contents.js:95:15) ...
```
![screen shot 2017-09-28 at 12 05 33](https://user-images.githubusercontent.com/236656/30961588-f40e8120-a446-11e7-8441-eda92f0857a9.png)

**To reproduce:**

1. I have set Beaker to be my default browser

2. Doesn't happen just after starting Beaker, but will appear after having the browser open for a while (some hours) and then trying to open a link from another program.

I now this is not at the core of the Beaker project, but trying to use it as my main browser to actually get to test it a lot.

And sorry for a false bug report earlier...

**Comment by eklem** [comment]
I'll see if I'll figure out what triggers the error to occur.

**Comment by pfrazee** [comment]
This is fixed in the upcoming release. It happens if you've closed a window and opened another, then click a link that opens in beaker

**Comment by pfrazee** [comment]
Thanks for reporting!

**Comment by eklem** [comment]
Cool, thanks for quick answer =)
