### ISSUE TITLE
Unselected tabs unreadable in macOS High Sierra

### ISSUE THREAD

**Issue by dwayneroberts** [beakerbrowser/beaker#693]
Operation System: macOS High Sierra 10.13 (17A365)
Beaker Version: 0.7.5

Since updating macOS from Sierra to High Sierra Beaker's tab bar is now transparent, making it hard to read unselected tabs.

<img width="1164" alt="screen shot 2017-10-01 at 15 31 48" src="https://user-images.githubusercontent.com/5333985/31055653-10ad4c0c-a6be-11e7-9bb1-9f7a8dcb1be3.png">

**Comment by pfrazee** [comment]
Oh bummer. Well, we've changed this in the `beaker-0.8` branch but it may still be a month or more before we release it. We might need to put out a quick patch.

**Comment by pfrazee** [comment]
Yeah turns out high sierra + electron = 😭  for transparency effects right now. I decided to just remove it for now. We have newly styled tabs coming in 0.8.
