### ISSUE TITLE
Beaker Post 

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#695]
We have a coop that we are testing Beaker with.
I just took a look at Rotonde and I'am trying to understand the how it is similar and or different from the posting feature that is a part of Beaker 0.8 ?

Thanks so much for all you are doing !

**Comment by pfrazee** [comment]
I'll copy a comment I made on the HN story:

> [Rotonde] using a pattern called the 'self mutating site'.
> 
> During setup, you git-clone the application code and put it into a dat site you create. The app code publishes by modifying files within its own dat. When you visit somebody's profile, you're actually visiting a new site, so there's no uniform software layer on the social network. A lot like indie Web software.
>
> There's a new 'application' pattern we're working on for the upcoming 0.8 release. In that pattern, the app dat and the data dat will be separated. This wont replace self-mutating sites, but it has some benefits as an alternative: apps will be able to update independently of the data, the browser will provide install and signin flows, and apps can provide persistent UIs.

So in addition to separating apps from data, we're building in some APIs to Beaker which will cover a core set of semantics, such as microblog posts. Should make building apps like Rotonde much easier.

**Comment by fredhampton** [comment]
Thanks for your reply....I understand much better now....our Coop has older and non tech members and the Beaker on boarding is easy for them to understand....Edit Profile ...Add Avatar and you are ready to post..!!

Thanks !!!

**Comment by fredhampton** [comment]
If our Coop begins to use Rotonde will we have compatibility issues when Beaker 0.8 arrives with Post and Timeline ?

**Comment by pfrazee** [comment]
If Rotonde doesnt change, it will work fine as its own app that isnt compatible with apps that use 0.8's Post and Timeline. But, Rotonde is also looking at switching over too.

**Comment by fredhampton** [comment]
Got it....Is there an ETA for 0.8 ?
Would it be possible for our Coop to being using the Beaker Post and Timeline in the current 0.8 branch ?

Thanks so much !

**Comment by pfrazee** [comment]
ETA, we're aiming for a pre-release in about a month, final release by the new year.

I don't think I'd jump on the 0.8 branch just yet. I'd wait for the prerelease to avoid pain.

**Comment by fredhampton** [comment]
Thanks so much for all you are doing !
