### ISSUE TITLE
Is there a way to test following in 0.8 ? 

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#696]
Is there a way to test following in 0.8 ?   Is it possible to test by creating another profile and then following it ? 
In 0.8 where is the location of the profile.json file ?
I see it in the beaker library but cannot seem to find it on disk.

Thanks !!!

**Comment by pfrazee** [comment]
> Is there a way to test following in 0.8 ? Is it possible to test by creating another profile and then following it ?

You can only create one profile at the moment. 

For following, there's a temporary solution: If you go to the profile app, you'll get a URL you can share: `beaker://profile/{your_dat_key}`. That page has a UI for following.

>  In 0.8 where is the location of the profile.json file ? I see it in the beaker library but cannot seem to find it on disk.

We got rid of the "staging area" which is where you used to be able to find the file on disk. There will be alternative flows in 0.8 and on:

 - Go to the beaker library and import/export manually
 - (not yet implemented) Go to the beaker library and open the file using another app
 - (not yet implemented) Create a workspace for a dat. This will be like the staging area, but you have to create it manually for each dat. It's being made mainly for app developers.

We liked having each file synced to a location on the disk but we ultimately felt like the staging area concept added too much complexity.

**Comment by fredhampton** [comment]
If I have someone in our Coop create a profile how would I follow them ?
Would I add the link to my instance of Beaker ?

Are the files and directories now data in a db and represented as files and directories in beaker ?

Thanks !!

**Comment by pfrazee** [comment]
>  If I have someone in our Coop create a profile how would I follow them ? Would I add the link to my instance of Beaker ?

Give us a little more time, we'll make this easier to do.

> Are the files and directories now data in a db and represented as files and directories in beaker ?

Yeah they're store in internal formats that shouldn't be modified directly.

**Comment by fredhampton** [comment]
Got it !!!

Thanks !!
