### ISSUE TITLE
Sub-directories use fallback_page

### ISSUE THREAD

**Issue by jondashkyle** [beakerbrowser/beaker#697]
Say I have `"fallback_page" : "/index.html"` defined in `dat.json`. When going to the url `/content`, I’d like to see my `fallback_page` if there isn’t an `index.html` file present within that directory. It’s also worth noting that the directory listing is currently displayed regardless of if the directory exists or not.

This is super useful for creating pseudo-static sites which reads content from files within sub-directories and displays it through a webapp.

Here is a funny little video giving an example:
http://drop.jon-kyle.com/beaker-example.mp4

**Comment by pfrazee** [comment]
Yeah we'll put this in 0.8, or 0.7.6 if we decide to do that.
