### ISSUE TITLE
MacOS: Cannot open any dat: URL

### ISSUE THREAD

**Issue by rtrvrtg** [beakerbrowser/beaker#698]
Operation System: MacOS 10.10.5
Beaker Version: 0.7.5

Every time I attempt to access any dat: URL using Beaker, the following JS alert pops up repeatedly until the tab is closed. To clarify; no actual content is displayed in the browser, just the alert popping up again and again.

![screen shot 2017-10-14 at 3 52 43 pm](https://user-images.githubusercontent.com/587242/31572725-fcf73224-b0f7-11e7-8c1c-68029509db58.png)

I might see if I can build from source to see if I can reproduce the issue.

**Comment by rtrvrtg** [comment]
OK this is a little baffling, but installing it from source worked fine.
Node: v7.10.0
NPM: 5.5.1

Maybe the DMG isn't up to date?

**Comment by pfrazee** [comment]
Yes - that was an upstream bug that got fixed after the 0.7.5 release. I'm thinking about a quick 0.7.6 to fix this and https://github.com/beakerbrowser/beaker/issues/699

**Comment by amatecha** [comment]
Happening for me (and a few others on twitter) as well.

**Comment by caseykahn** [comment]
Happening for me too. 

pfrazee, if you're still thinking about that quick 0.7.6 fix, I'd like to chime in and cast my vote as "yes please do, that would be awesome"

**Comment by pfrazee** [comment]
I think I can knock it out this evening.

**Comment by pfrazee** [comment]
Fixed in 0.7.6
