### ISSUE TITLE
Import an existing dat that I own

### ISSUE THREAD

**Issue by passcod** [beakerbrowser/beaker#701]
- Operation System: Linux
- Beaker Version: 0.7.5

This might be obvious, but I haven't been able to find a way.

I have an existing dat that I created with the CLI dat, like `dat share` in a directory. I want to import this dat to the Beaker Browser so that

1. the Beaker Browser can make it available for me (so I don't have to run `dat`), **and**
2. it runs in Write mode, not Read-only, so I can use [Rotonde](https://github.com/Rotonde/beaker)

and of course, I'd like to retain my _existing_ dat URL.

How can I achieve this?

**Comment by pfrazee** [comment]
We don't have a tool for it yet, I'm sorry to say. We'll try to get it done in the 0.8 release.

**Comment by passcod** [comment]
Can I do this manually? What files would I need to modify to make it work, if it's possible?

**Comment by pfrazee** [comment]
I don't know actually. I'll need to dig around in the dat CLI and our own internal formats. Let me do some research tomorrow afternoon and get back to you.

**Comment by tulsileathers** [comment]
@pfrazee is this possible manually now?

**Comment by pfrazee** [comment]
Not yet
