### ISSUE TITLE
Forking and dat.json options

### ISSUE THREAD

**Issue by jondashkyle** [beakerbrowser/beaker#702]
My application requires setting `fallback_page` inside `dat.json`, not including this breaks redirects. However, when forking the site, a fresh `dat.json` is created, which means `fallback_page` is not set and the app breaks!

Couple thoughts on how this could be addressed:

- Copy over any attributes from `dat.json` which aren’t sensitive
- Store all app attributes in something like `manifest.json`
- Expose toggling this on and off with the web api, for instance: `DatArchive.manifest({ 'fallback_page': '/index.html'})`

**Comment by pfrazee** [comment]
+1 We need to think this through.

**Comment by louiscenter** [comment]
@jondashkyle thanks for opening this issue! I came looking for a solution to this same problem, and it's good to see others have already started talking about it.

I know this other issue thread is a year old, but it does mention that `manifest.json` did exist at one point, but was then "hidden". I can't tell if this means the file still exists somewhere, or the concept was completely removed?

Where can I find this file?

**Comment by pfrazee** [comment]
It’s the dat.json file

**Comment by louiscenter** [comment]
@pfrazee thanks for clarifying! Was a decision ever made as to how developers would be able to retain settings like `fallback_page` during a fork, in future versions of Beaker?

**Comment by pfrazee** [comment]
I think we'll need to setup a whitelist of attrs to retain, which will include `fallback_page`. I'll have it sorted for 0.8.

**Comment by pfrazee** [comment]
Fixed in the `beaker-0.8` branch
