### ISSUE TITLE
MacOS access control blocks localhost traffic, breaking the beaker: and dat: protocols

### ISSUE THREAD

**Issue by AbhishekParadox** [beakerbrowser/beaker#708]
Operation System: macOS High Sierra, version 10.13
Beaker Version:0.7.5

not responding to any command and no toolbar.

<img width="1280" alt="screen shot 2017-10-18 at 1 03 13 am" src="https://user-images.githubusercontent.com/22846167/31685303-19959010-b3a0-11e7-96aa-f09753402ea1.png">

**Comment by pfrazee** [comment]
That is new. You have an admin control system that's blocking all localhost traffic, which beaker makes extensive use of.

I'll need to do some research to find alternative solutions.

**Comment by pfrazee** [comment]
My first glance wasn't encouraging. Electron doesnt have an alternative mechanism for handling a protocol with all the features we need, and nobody's filed this particular issue before.

Do you know what might be blocking that traffic?

**Comment by paul90** [comment]
Is it something simple? That error screen is coming from a remote proxy, which would suggest that proxy bypass is not configured correctly (or being ignored by beaker/electron). I notice on Sierra that going to the proxy settings in Chrome takes you to the macOS Network preferences, and these, at least by default, do not include `localhost`.

Possible solution, add `localhost` to the 'Bypass Proxy Settings', this is done in 'System Preferences' -> 'Network' -> 'Ethernet' (and/or maybe other interface) -> 'Advanced...' -> 'Proxies' and add `localhost` to list.

**Comment by pfrazee** [comment]
Yeah I wonder if we can configure Electron to bypass the proxy.

**Comment by paul90** [comment]
There is a document [Chrome Command Line Switches](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig-callback) that includes examples of setting bypass proxy.

**Comment by AbhishekParadox** [comment]
@pfrazee @paul90  thanks, adding localhost to exception solves the problem and launches browser properly. while will have to look how to work through a proxy network.

<img width="1229" alt="screen shot 2017-10-18 at 10 05 04 pm" src="https://user-images.githubusercontent.com/22846167/31730701-5b5b1dac-b450-11e7-9380-07e9d33f61ad.png">

**Comment by pfrazee** [comment]
@AbhishekParadox oh good! Was this done via MacOS settings?

**Comment by AbhishekParadox** [comment]
@pfrazee yeah through network settings as @paul90 had recommended. Though installing via jekyll 
`gem install jekyll bundler` is creating problem as access to ruby not given in macos. Will have to figure it out.

**Comment by pfrazee** [comment]
Ok thanks
