### ISSUE TITLE
Tags - What Do You Reckon?

### ISSUE THREAD

**Issue by tomatopeel** [beakerbrowser/beaker#710]
Right now we can bookmark regular sites and we can add (or fork) Dat sites into our library. I can search my library through the UI, that's good, presumably that will search the whole content of each site, perhaps even previous versions? I don't think I can query bookmarks through the UI right now but according to https://github.com/beakerbrowser/beaker/issues/311 most of the WebExtensions bookmarks API has been implemented behind the scenes.

https://github.com/beakerbrowser/beaker/issues/691 re: bookmarks import. An export from Firefox's Places database will export with tags currently; Beaker won't support those right now. I've written a summary and a case for tags for bookmark tags [on the Mozilla Discourse here](https://discourse.mozilla.org/t/webextensions-bookmarks-tags-annotations-come-on/20593).

I think ultimately I'd like to be able to query both my Beaker library _and_/or my bookmarks based on tags, times (of submission, last modified), and perhaps ultimately there could be some community metrics, e.g. 50 users have tagged this version of this site in the library or a bookmark of this URL with this tag. Is this the kind of thing that could be implemented in a ["Thick Web Application"](https://github.com/beakerbrowser/beaker/wiki/Thick-Applications:-Unifying-WebExtensions-with-the-Web-platform-and-moving-beyond-injections)?

I'll leave it at that for now, would love to hear the main devs thoughts, cheers!

**Comment by pfrazee** [comment]
Hey @tomatopeel. 

You should check out our dev branch for the next big release, `beaker-0.8`. We have a bookmarks feature there that supports tags and public bookmarking via dats.

In the short run, we're going to expose a basic `bookmarks` API for both private and public bookmarking. Some of that will be implemented, by necessity, in the browser, which will mean it has some rigidity to it. We will have tags, but maybe not other APIs that folks would want.

But in the long run, I think we can move the entire bookmarks implementation into userland. Here's what it requires:

 - A way to store bookmarks privately. Not too hard: just use a non-networked (or encrypted) Dat.
 - A way to store bookmarks publicly (if you want that feature). Already done in `beaker-0.8`, just use a networked Dat.
 - A way for an app to add a bookmark button to the browser window, and react to the current page. WebExtensions support that, so I imagine the Thick Apps APIs could support it too.
