### ISSUE TITLE
Add audio controls for individual tabs

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#711]
It would be great to be able to indicate which tabs are playing audio, and to be able to mute the audio from the tab:

![screen shot 2017-10-18 at 10 27 45 am](https://user-images.githubusercontent.com/7584833/31727480-43643226-b3ef-11e7-9282-619bc844657f.png)

Here are the isolated tasks we'll need to complete in order to make this happen:
- [ ] Detect when audio is being played, and identify which tab is playing it
- [x] Implement muting/unmuting audio in a given tab
- [ ] Wire up the tab UI

If anyone is interested in helping, [Brave's codebase](https://github.com/brave/browser-laptop) might be helpful. They implemented this feature and they also use Electron.

**Comment by pfrazee** [comment]
We need to update electron to support telling us when audio is playing.
