### ISSUE TITLE
Beaker Browser as a Tiling Window Manager + API ?

### ISSUE THREAD

**Issue by serapath** [beakerbrowser/beaker#712]
The https://github.com/beakerbrowser/beaker/issues/666 issue got me thinking again...

**Maybe:** The main `browser window` should be just one of many possible browser windows that tile the available screen space as necessary.
* This would enable a `bookmark bar app` to occupy a small browser window on top of the regular main browser window.

Thinking a bit further :-) maybe it could even mean, that:
**Beaker Browser itself should be just a tiling window manager and an API**
* so by default, when you start beaker browser - out of the box, it will contain only at least 2 default windows:
    1. the tabs & address bar window on top of the
    2. main browser window that displays web pages

**Then:**
If there was a way to **fork**: "a tiled window of apps"
* It would make it pretty easy to iterate on different versions of the browser itself.
* It would also help to outsource a lot of upcoming issues by people requesting certain features to userland :-)

Would that make sense?

---
**Example App:** `Bookmarkbar`
*(I know a bookmark folder dropdown could overlay an iframe, but to overlay the main browser window probably requires a webview in a webview?)*

**Comment by pfrazee** [comment]
Interesting idea. If we manage to put everything into userland, this would make sense.

**Comment by serapath** [comment]
If electron allows it, I imagine an outer <webview> that contain inner <webview>s and would have control over them (unlike iframes).

Basically Browsers in HTML so they can be forked an customized like rotonde

So different browser con contain features like:
* a `bookmarkbar` https://github.com/beakerbrowser/beaker/issues/666
* or an `ad blocker`
* ... and more
