### ISSUE TITLE
Display Private Key Upon Site Creation

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#721]
Feature Request:

Optionally display the dat/site private key upon creation/fork. This let's the user manage an alternative backup storage for it without digging into beaker app storage and pulling it out.

**Comment by pfrazee** [comment]
Yeah we're going to try to hit this in 0.8

**Comment by sull** [comment]
Still not comfortable with it?

**Comment by pfrazee** [comment]
Yeah not until we have a solution hypercore split-recovery.
