### ISSUE TITLE
Is Beaker using a javascript/html framework?

### ISSUE THREAD

**Issue by JoshZeidner** [beakerbrowser/beaker#723]
Hello,

 I'm trying to familiarize myself with the Beaker Browser codebase. Is Beaker using some kind of framework such as React or Angular? The structure of the project isn't really standard as far as Electron goes. 

 Are there any guides to getting involved with the code?

thanks!

**Comment by jafow** [comment]
There's a really helpful video guide here: [Beaker's Internals: A Developer's Guide](https://youtu.be/YuE9OO-ZDYo).  
It has a high level overview and details on the majors parts of the codebase.

**Comment by JoshZeidner** [comment]
thanks @jafow.

I did manage to get the [Javascript debugger working with Beaker Browser.](https://joshuazeidnerjavascript.wordpress.com/2017/10/25/how-to-use-the-chrome-javascript-debugger-with-beaker-browser-an-electron-based-application/)

**Comment by JoshZeidner** [comment]
just as a note to anyone who may run across this issue, I learned the project uses two lightweight frameworks- [co](https://github.com/tj/co) and [yo yo](https://github.com/maxogden/yo-yo)

**Comment by pfrazee** [comment]
We're transitioning the `co` usage out, since JS has async/await now.

We do use yoyo pretty heavily. We're going to do a refactor soon of the builtin pages (turning them into apps) and we *might* switch over to choo.io when we do, but for now it'll just be yo.

**Comment by JoshZeidner** [comment]
I am actually looking to repurpose the application. I need a customizable browser(I did see your other project @pfrazee). One thing I'm learning is the sheer levels of overhead in maintaining these Javascript based applications. Just a simple application like the Beaker Browser uses a maze of hard to track JS code(what you did there with the `loadURL("beaker://shell-window")` comes to mind), whereas if I used JavaFX the GUI code is very simple and clean, highly maintainable and others can easily customize it. Of course the drawback is the app looks "old fashioned" and it's deployment characteristics are different, however it does exactly what I need it do.

I am interested in Dat and Beaker applications. My goals are similar and perhaps complementary. I suppose there is an advantage in using the same platform, and I would make concessions given that but the levels of overhead in using Electron and this particular codebase is very high. Another consideration is I'm using Neo4j which is built in Java.

**Comment by JoshZeidner** [comment]
Also another note: there is a great deal of hype surrounding these javascript frameworks. They rarely live up to their promises. The Java world is in general more predictable and reliable. Something about this class of developers makes them want to exaggerate everything.

**Comment by pfrazee** [comment]
Beaker isn't as elegant as I want it to be, but please keep your "maze of hard to track JS code" jabs to yourself next time.

**Comment by JoshZeidner** [comment]
I don't think it's really due to your own fault, so no insult intended. I don't think Electron is as wonderful as they're making it out to be. It seems to be about stretching the value of Javascript developers. I notice there is an IPC mechanism in there so the browser process can communicate with the application process? that's basically client-server so why would you do that on the desktop? makes absolutely no sense. Add to this that most Javascript libraries are immature and buggy. Of course you could use something like SemanticUI but I suspect it's no where near as easy as they make it out on the site. Most of these frameworks are really a cleverly disguised way to sell development services.

For an interesting contrast here [is a Java project that uses JavaFX Webview](https://github.com/brunoborges/webfx/tree/master/webfx-browser) (embedded browser in a window app). The code is concise and highly readable. Downside is it's not so slick. There is a(potentially) open source way to embed a full-fledged Chrome browser in a Java application.

**Comment by JoshZeidner** [comment]
consider how narrow your Use Cases are at this point and weigh that against the complexity of the code. That's going to get really unwieldy as it grows.

I was really hoping I could use this and develop my concept in parallel to yours.
