### ISSUE TITLE
Windows Build Instructions 

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#726]
Will there be Windows build instructions ?

Thanks !

**Comment by pfrazee** [comment]
Yeah. Will be an installer as well. Just wrapping up the code needed.

**Comment by fredhampton** [comment]
Great !!!!

**Comment by fredhampton** [comment]
Can you point me in the direction of a resource that I can follow for building for windows via vm on osx ?

Thanks !

**Comment by pfrazee** [comment]
@fredhampton Take a look at https://beakerbrowser.com/docs/install/

https://github.com/beakerbrowser/beaker/issues/55 is a good resource if it turns out our instructions dont work right. And, feel free to LMK if you have issues.

**Comment by fredhampton** [comment]
Thanks I will give it a try ....
