### ISSUE TITLE
How to safely uninstall from MacBook Pro?

### ISSUE THREAD

**Issue by KnowledgeGarden** [beakerbrowser/beaker#728]
Operation System: MacOS
Beaker Version: recent, not sure.
Concern is about the fact that the system auto-boots on startup, with no obvious way to turn that off.

**Comment by pfrazee** [comment]
Does beaker automatically start on boot for you? It definitely should not!

I *believe* you can uninstall by dragging the app icon from your launcher into the trash. I dont have my mac with me atm so I cant confirm

**Comment by KnowledgeGarden** [comment]
It always starts on boot. That's the reason I don't just drag the app to the trash. I have no clue how the platform will behave if the app is gone and it is rebooting.

**Comment by KnowledgeGarden** [comment]
My bad! Yup. it's the notebook. Sorry about that.

**Comment by pfrazee** [comment]
Hah no worries
