### ISSUE TITLE
error on adding folder with 100+ files [windows]

### ISSUE THREAD

**Issue by noformnocontent** [beakerbrowser/beaker#731]
Operation System: Windows 10 x64
Beaker Version: 0.7.7

![capture](https://user-images.githubusercontent.com/23745012/32137907-37dac05e-bc29-11e7-9045-ffed5f5207ab.PNG)

happened when i added a folder with 100+ files in it
dat://dym.sh/i/matrix-reflex/

otherwise works normally

**Comment by pfrazee** [comment]
Ok thanks for filing, we'll check into this.
