### ISSUE TITLE
Subresource Integrity

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#732]
Edited:

Fix handling of CORS in Dat sites so that SRI is allowed. Currently, this erroneously is shown:

![screen shot 2017-11-03 at 11 46 04 am](https://user-images.githubusercontent.com/1270099/32385565-9a9c4d36-c08c-11e7-87ab-fb444adfd794.png)

Bottom error is correct, top error is not.

---

Original issue:

Can Beaker support Subresource Integrity with dat:// protocol?

https://w3c.github.io/webappsec-subresource-integrity/

Thanks.

**Comment by pfrazee** [comment]
That's a good question. Have you tried it?

**Comment by pfrazee** [comment]
I'd expect it to just work if it's implemented in chromium, but it's possible there will be something we have to do.

**Comment by sull** [comment]
seems to only work with https. thought it would be interesting to use over dat:// protocol.

**Comment by pfrazee** [comment]
@sull I agree, what have you found when you try it? Does it just ignore the SRI?

**Comment by sull** [comment]
dat://060224c73a4dbf414cdeff3b94e50e716e7d173d0bb9593f11a94fc33a43203c/
https://subresourceintegritytest-sull.hashbase.io/

Seems to work fine except for CORS issue when pulling from a different dat archive.
Remind me... how does Beaker deal with CORS?

**Comment by pfrazee** [comment]
Ok interesting. That's probably a bug or a bad setting somewhere.

We're working on the cross-origin policy. What we're thinking is:

 - By default, dat sites are going to be permissive (can make requests to anywhere). 
 - In the future: a UI similar to adblockers in the browser UI which (by user choice) can default no requests, and then can selectively enable them.
 - Separately: The dat apps which request elevated API access will have their remote access disabled, and will have to request that access specially during install.

**Comment by pfrazee** [comment]
I'm editing this issue to become a TODO

**Comment by sull** [comment]
Good plan, ok thanks for the info!

**Comment by pfrazee** [comment]
It doesn't look like electron is honoring the CORS config. Need to debug against a custom build
