### ISSUE TITLE
Uncaught exception every other time I scroll a page (screen.getCursorScreenPoint)

### ISSUE THREAD

**Issue by natevw** [beakerbrowser/beaker#735]
I am getting very frequent modal alerts regarding the same uncaught exception:

<img width="532" alt="screen shot 2017-10-31 at 2 57 26 pm" src="https://user-images.githubusercontent.com/265902/32251074-a2bec62a-be4c-11e7-99ed-471049df8d4f.png">

I seem to be able to reproduce it on purpose by setting two fingers down close to each other, not quite simultaneously. It usually happens whenever I start scrolling, but not always. (**UPDATE**: actually it's seemingly like *every other time* I scroll, I get the error?)

Operation System: macOS 10.11.6
Beaker Version: "v0.7.7 is up-to-date"
Hardware: "Early 2015" MBP, builtin touchpad

> **A JavaScript error occurred in the main process**
> 
> Uncaught Exception:
> TypeError: Cannot read property 'getCursorScreenPoint' of null
>     at BrowserWindow.sendScrollTouchBegin (/Volumes/Beaker Browser 0.7.7/Beaker Browser.app/Contents/Resources/app/background-process.build.js:4007:34)
>     at emitOne (events.js:96:13)
>     at BrowserWindow.emit (events.js:191:7)

Thus the error seems to be emanating from https://github.com/beakerbrowser/beaker/blob/ce61aeb7b0a11d2ff104119139e348d6577b1adf/app/background-process/ui/windows.js#L237 — I see the one other use of `screen` in that file is guarded with a fallback and a note referencing #690.

**Comment by pfrazee** [comment]
Hmmm wtf is up with this...

Thanks for filing, will look into it

**Comment by natevw** [comment]
Yeah, the odd bit is the "every other" — is the module somehow getting loaded twice and only one gets the screen?On Oct 31, 2017 6:48 PM, Paul Frazee <notifications@github.com> wrote:Hmmm wtf is up with this...
Thanks for filing, will look into it

**Comment by pfrazee** [comment]
Committed a fix
