### ISSUE TITLE
Redirect dat://path to dat://path/ when it's a directory

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beaker#736]
Operation System: all
Beaker Version: v0.7.7

### currently, Beaker doesn't handle relative URLs from an index file

Say `dat://path/index.html` exists

Then, loading `dat://path` and `dat://path/` in Beaker will both display that file.
In the first case, though, relative links are broken.

### example 1 (works)

dat://dcpos.ch/yimby/zoning/

![image](https://user-images.githubusercontent.com/169280/32302288-2290c498-bf1f-11e7-80fb-afa08ba6c0ab.png)

### example 2 (broken)

dat://dcpos.ch/yimby/zoning

![image](https://user-images.githubusercontent.com/169280/32302312-3f757036-bf1f-11e7-9906-18d196b2ff5e.png)

### old web solution

on the centralized web, people usually fix this problem via server configuration. for example, i have Nginx configured to redirect `/foo` to `/foo/` when foo is a folder

the following works: https://dcpos.ch/yimby/zoning

(it's a server side redirect to https://dcpos.ch/yimby/zoning/ )

### proposed Beaker solution (A)

Beaker could canonicalize dat URLs so that directories always end in a `/`. in other words, `dat://example.com/foo` would join the swarm, start downloading--then once it sees that `foo` is a folder (vs, say, `foo.html`), it changes the URL to `dat://example.com/foo/` and renders the index.

### alternate solution (B)

it is possible to work around this now, via a client-side redirect -- but that's kind of ugly.

i think it should be possible to host plain HTML via dat, including `index.html` and relative links.

for that to work correctly without adding Javascript, i think we need solution A.

**Comment by pfrazee** [comment]
Solution A seems reasonable to me. Does anybody object to that?

**Comment by pfrazee** [comment]
(Thanks for the detailed writeup!)

**Comment by pfrazee** [comment]
🤦‍♂️ So, electron doesn't currently support redirect responses in the custom protocols. But! There's a new way to do custom protocols which will be in the next release, so let's watch for that and see if we can get redirects to work there. (https://github.com/electron/electron/pull/11008)

**Comment by pfrazee** [comment]
Fixed in 0.8
