### ISSUE TITLE
Feature Request/Idea: Pluggable transports

### ISSUE THREAD

**Issue by HughIsaacs2** [beakerbrowser/beaker#738]
This might belong under issue #230 I'm unsure honestly.

The idea I have is an API that lets extensions (or whatever fills this space) add peers and provide alternate transports for a Dat.

It sounds super basic, but it would be useful for providing support for types of networks that Beaker doesn't support or might require too much maintenance to code right into Beaker itself.

So devices, platforms and transports like [goTenna](gotenna.com), [Bramble](https://briarproject.org/), WebRTC, Bluetooth, etc... could be plugged right into Beaker, extending functionality for Dat sites without the site owners, web app developers and users needing to do anything different.

I think this would be useful in a lot of edge cases where people would need to communicate over custom hardware or a custom protocol (like for boating, climbing mountains or space travel).

I feel this would be done best as a Web Extension API (paired with Native Messaging, the Proxy and VPN APIs would be useful too) but with Beaker being a new paradigm I wouldn't be surprised if someone has a better more fitting idea here.

**Comment by pfrazee** [comment]
Note- what this is discussing is pluggable *transports*, which is not the same as pluggable *protocols*. Transports exist underneath the protocol layer.

Interesting possibility. In the meantime, I think we could probably bake in the transports we want to support.
