### ISSUE TITLE
beaker-0.8 branch: confusing icons in left sidebar

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#739]
Operation System: win10
Beaker Version: latest: beaker-0.8

## Existing behaviour

The left sidebar shows: 

![beaker-icons-timeline](https://user-images.githubusercontent.com/374655/32370149-4d64098c-c08c-11e7-8fd9-f41f8674d9a7.gif)

The "Timeline" icon is a speech bubble. I personally have no idea, what a speech bubble has to do with a timeline. ... I don't understand this icon. 

 - If the "Timeline" is selected, there is no visual indication, that it is selected. 
 - And it shows the wrong icon ... a star!

![beaker-icons-timeline-selected](https://user-images.githubusercontent.com/374655/32370289-c52d6e04-c08c-11e7-80ed-08e026203a3e.gif)

## Expected behaviour

 - There should be visual clue, which sidebar element is selected, if the sidebar is visible on the page. 

A google search for "timeline icon" gives me: Where I do like the second and the first one.

![google-timeline](https://user-images.githubusercontent.com/374655/32370227-883f9d64-c08c-11e7-9660-79d910e6131b.gif)

A search for history gives me: Where I like the 1st, 3rd and the last one

![google-history](https://user-images.githubusercontent.com/374655/32370373-148e111a-c08d-11e7-9a77-d3a5789f70a2.gif)

**Comment by taravancil** [comment]
Hi @pmario,

As you probably know, the beaker-0.8 branch is a work in progress, and nothing in that branch is in a final state. The timeline icon is a placeholder we're using because we haven't yet created a timeline icon that we liked.
