### ISSUE TITLE
Running Headless Beaker

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#740]
Has Beaker ever been run in a headless mode by anyone?
Mostly curious but wanted to experiment and this would be useful.
It's technically possible (Electron), just wanted to get any info from you folks first before I delve.

![24be1b1fb758b8bd078d728593a93152--old-cartoons-the-muppets](https://user-images.githubusercontent.com/6834/32384282-ca76701e-c090-11e7-8d51-d9efa74c5bea.jpg)

**Comment by pfrazee** [comment]
I haven't tried it yet
