### ISSUE TITLE
After installing beaker, npm fails at everything

### ISSUE THREAD

**Issue by jabozzo** [beakerbrowser/beaker#741]
Operation System: Ubuntu 16.04 LTS (Linux 4.10.0-38-generic)
Beaker Version: 0.7.8-prerelease.1-8-ge2d40d1

After a fresh npm install, I can't do any following npm operation (rebuild, start, etc...)

Steps:
1) git clone https://github.com/beakerbrowser/beaker.git .
2) npm install  // Output 0
3) npm run rebuild  // Fails, Output 1
4) npm start  // Fails, Output 2
5) npm run burnthemall  // Fails, Ouptut 3

[output_0.txt](https://github.com/beakerbrowser/beaker/files/1441988/output_0.txt)
[output_1.txt](https://github.com/beakerbrowser/beaker/files/1441989/output_1.txt)
[output_2.txt](https://github.com/beakerbrowser/beaker/files/1441990/output_2.txt)
[output_3.txt](https://github.com/beakerbrowser/beaker/files/1441991/output_3.txt)

I've attached the npm-debug.log associated with each npm fail.

[npm-debug_output_1.log](https://github.com/beakerbrowser/beaker/files/1441966/npm-debug_output_1.log)
[npm-debug_output_2.log](https://github.com/beakerbrowser/beaker/files/1441967/npm-debug_output_2.log)
[npm-debug_output_3.log](https://github.com/beakerbrowser/beaker/files/1441968/npm-debug_output_3.log)

Mi node version is 4.2.6 and my npm version is 3.5.2

EDIT:
- Moved output of each command to files.
- Added node and npm versions

**Comment by pfrazee** [comment]
Yeah sorry, I'm using async/await in those commands and that requires node 8. Let me update the commands to work on older node versions, one moment...

**Comment by pfrazee** [comment]
Ok give it a shot on master. Pull latest, then `npm run burnthemall && npm start`

**Comment by jabozzo** [comment]
I've tried npm run burnthemall after a git pull (4 files changed), but I got the attached output and npm-debug.
[npm-debug.log](https://github.com/beakerbrowser/beaker/files/1442682/npm-debug.log)
[output.txt](https://github.com/beakerbrowser/beaker/files/1442683/output.txt)

I've also tried deleting the whole repo, running npm install again and tried to do a burnthemall, but I got the same result.

**Comment by pfrazee** [comment]
Ack sorry, it's been a while since I used an old node version. I dont notice when I use es6 features. 1 sec.

**Comment by pfrazee** [comment]
Ok try again for me. I tested on an older version of node this time so
hopefully we're good

**Comment by jabozzo** [comment]
Now it works, I've used npm run burnthemall, npm run rebuild and npm start without problems

**Comment by pfrazee** [comment]
Great. Sorry for the issue
