### ISSUE TITLE
Window resizing

### ISSUE THREAD

**Issue by hinell** [beakerbrowser/beaker#743]
The window doesn't resize when dragged by top edge. The cursor won't show if there is no tab or **[+]** around:

![gif](https://user-images.githubusercontent.com/8136158/32406992-c404e82a-c192-11e7-83a7-17ab22cd0061.gif)

Platform: Win10 x64
Beaker Version:
Version: 0.7.7 Electron: 1.7.4 - Chromium: 58.0.3029.110 - Node: 7.9.0

**Comment by pfrazee** [comment]
Thanks for reporting. We'll look into it

**Comment by pfrazee** [comment]
Fixed!
