### ISSUE TITLE
Cannot add AppImage files to my site

### ISSUE THREAD

**Issue by probonopd** [beakerbrowser/beaker#745]
Operation System: Ubuntu 16.04.1 LTS
Beaker Version: beaker-browser-0.7.8-prerelease.1-x86_64.AppImage

Cannot add [AppImage](https://appimage.org/) files to my site. AppImage files are greyed out in the file selection dialog.

**Comment by pfrazee** [comment]
This is an obnoxious issue caused by Linux's inability to select both files and folders in a picker. https://github.com/beakerbrowser/beaker/issues/668

**Comment by pfrazee** [comment]
I'll try to get a solution in soon, either with 0.8 or something temporary in the 0.7.x series
