### ISSUE TITLE
open-url handler error

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beaker#746]
Operation System: macOS High Sierra 10.13
Beaker Version: 0.7.7

I'm clicking on the a link to the following Dat site in Chrome: dat://portal-thedailydescent.hashbase.io/

Specifically, I opened this page in Chrome, then clicked the Dat Protocol link: http://wiki.xxiivv.com/The+Daily+Descent

In the past, other dat:// links have worked for me--they open Beaker correctly. Now, I reliably get the following error:

![image](https://user-images.githubusercontent.com/169280/32526176-cbcee640-c3dc-11e7-8494-f88e3a2ff04c.png)

**Comment by dcposch** [comment]
*Update:* quitting Beaker Browser (Cmd+Q),then clicking on the link again in Chrome works

It looks like Beaker just got into a bad state

(The link still doesn't load, but that's because Hashbase is down. Separate issue :) @pfrazee  )

**Comment by dcposch** [comment]
![image](https://user-images.githubusercontent.com/169280/32526266-47c8a1c8-c3dd-11e7-8fe0-b41d4689a568.png)

**Comment by pfrazee** [comment]
I'm looking into where the daily descent disappeared to. We had to restore from our daily backups recently after a bad crash. (We may need to move past leveldb sooner than later.)

We have a fix for this bug in 0.8. I'll backport it to the 0.7.x branch.

**Comment by pfrazee** [comment]
Fix is merged into master. Will release in next 0.7.x version
