### ISSUE TITLE
Last tab becomes unresponsive on Linux

### ISSUE THREAD

**Issue by theorangepotato** [beakerbrowser/beaker#747]
Operation System: Linux (Debian Stretch)
Beaker Version: 0.7.7

If I open enough tabs such that they span the window, then the right-most tab loses some functionality. Clicking the X will not close the tab (and hovering over the X does not make the red circle appear), dragging the tab does not work, and oftentimes, clicking on the right-most tab does not even switch to it. CTRL+TAB does work, and another tab can be dragged to the right-most slot, locking this new tab, but freeing the previously locked tab to be deleted or moved. This behavior is only observed when the right-most tab touches the edge of the window.

**Comment by pfrazee** [comment]
Thanks for reporting, we'll look into it.

**Comment by pfrazee** [comment]
Confirmed and fixed. The region for the windows titlebar controls was incorrectly present on linux.

Thanks for reporting!!
