### ISSUE TITLE
[feature] fix `document.referrer == ""` for following dat:// links

### ISSUE THREAD

**Issue by composition4** [beakerbrowser/beaker#749]
Operation System: any, I think, but ubuntu zesty 16.04 x32
Beaker Version: 0.7.7

I propose addition of `document.referrer` functionality for clicking on links, to refer to originating `dat://` address when arriving on a page.

I was working on a project where it would have been nice to use this to add users to a user directory (auto-add user to directory when visiting if non-duplicate), however with this lack of a fairly standard feature in browser protocols I had to consider using kludgy work-arounds like querystrings or anchors that'd be snarfed from JS. 

These solutions are ugly, kludgy, and aren't congenial to developers who like to slam out a quick protoype.

Would it be too involved (e.g.: getting deep into the bowels of Electron/Chromium's network stack) to add this feature, so that upon arrival to a new page, scripters can get that referring URI?

### Options
- **At header:** `<meta name="referrer" content="no-referrer" />` 
- **Inline:** `<a href="dat://foo.bar" send_referrer="false">follow this link!</a>`
    * **Inline (HTML5):** `<a href="dat://foo.bar" rel="noreferrer">follow this link!</a>`

### Header Spec
- [Specification Reference](https://w3c.github.io/webappsec/specs/referrer-policy/)

**NOTE**: If this feature addition wouldn't be too involved, I'd be happy to fork and work on it myself, providing a PR

**Comment by composition4** [comment]
**NOTE**: If this feature addition wouldn't be too involved, I'd be happy to fork and work on it myself, providing a PR

**Comment by pfrazee** [comment]
I'm not sure why it's not populated already; it might just be that the dat:// protocol handler needs to set the [Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), or it might be an internal chromium flag that we need to get exposed via electron.

I don't personally get excited about populating document.referrer but I can understand the use-case. If anybody wants to make an argument for/against, this issue is your opportunity.

**Comment by composition4** [comment]
Alternatively, this could be done in inverse, where:
- **Header:** `<meta name="referrer" content="refer" />`
- **Inline:** `<a href="dat://foo.bar" referrer="">follow this link!</a>`

...which would require the developer to actually set it, rather than referrer being `true` by default. That may be a better compromise... 🤔

**Comment by pfrazee** [comment]
One consideration with Dats was pointed out by fugi on IRC:

> I'm not sure I like referrer being set for me when my dat's security is based on not leaking the URL. Instead I'd expect the profile editor app to make use of the DatArchive.selectArchive API

**Comment by composition4** [comment]
This is a good compromise, so I'll close.
