### ISSUE TITLE
Inconsistent events with createFileActivityStream

### ISSUE THREAD

**Issue by saranrapjs** [beakerbrowser/beaker#750]
Operation System: MacOS Sierra 10.12.3
Beaker Version: Tested on both 0.7 and master

I'm working on a project which makes lots of little writes to a DatArchive and almost always publishes/commits them immediately (it's a collaborative text editor - hope to have something to show soon!). To "confirm" when these writes have been propagated to the dat, I've been using `DatArchive.createFileActivityStream()` to listen for changes (this unifies some logic for clients which pull changes locally vs. those that pull them across the network).

Because I'm in development, there are often unrelated file changes in the dat which makes it a "staging" dat (until the next write is committed). Tracing some of the logic of how `createFileActivityStream` is implemented for _staging_ dats, under the hood it looks like it feeds from a stream wrapped around an event emitter, which is triggered (ultimately) by `recursive-watch`, which uses an [FSWatcher](https://github.com/mafintosh/recursive-watch/blob/master/index.js#L46). What I'm seeing, though, is that under some circumstances (often it's when I'm creating a `createFileActivityStream` on load, in multiple tabs, and reloading one of the tabs during development) the staging dat watcher will stop firing change events. I'm not honestly sure why — there may be some limit to file watchers for a path that I'm unaware of? Maybe it's unrelated to the watcher(s), and has to do with how these streams are tracked across tabs?

At any rate, what I'm curious about: right now, the `createActivityStream` function will [always use the local fs.watcher for a staging dat](https://github.com/beakerbrowser/beaker/blob/79ae5d1b770e79d487cb0163e62941ef087f230c/app/background-process/web-apis/dat-archive.js#L274-L281). Could that be made configurable? e.g. if I'm only concerned with the changes that _have_ been published, even for a local/staging dat, would there be any merit in some kind of options hash (`{ watchStaging: true}`) where you could configure whether or not you care about staging updates? 
I'd be happy to mock something like this up in a PR if this seems like a worthwhile direction, but curious to hear what you think either way 😄  & thanks for all your hard work on Beaker! It's really cool!

**Comment by pfrazee** [comment]
@saranrapjs so this is all really good analysis and that's a good suggestion. But we actually have removed the staging area from dats in version 0.8 -- mainly because it was complex to work with, and didn't really give us the value we wanted.

For making applications or sites, we're adding a "workspace" concept, which has a similar flow, but isn't integrated into the entire Dat Web API. So, no more commit() method, and no more changes to the workspace causing change events to be emitted.

Closing. Feel free to continue conversation here.
