### ISSUE TITLE
crashing when visiting #rotonde profiles

### ISSUE THREAD

**Issue by seekr** [beakerbrowser/beaker#753]
Operation System: macOS Sierra
Beaker Version: 0.7.7

Suddenly beaker is crashing whenever I visit rotonde profiles (mine or others) as soon as the profile seems to finish loading.

I'm not sure what I should provide to help identify the problem, I could share the info that appears when a mac app crashes.

**Comment by pfrazee** [comment]
Thanks for reporting! This is a known issue. We'll have the fix out this week (if all goes to plan) https://github.com/beakerbrowser/beaker/issues/474#issuecomment-343279333
