### ISSUE TITLE
New tab doesn't work when no window

### ISSUE THREAD

**Issue by eklem** [beakerbrowser/beaker#754]
Operation System: macOS 10.13.1
Beaker Version: v0.7.7

<img width="595" alt="screen shot 2017-11-14 at 14 56 39" src="https://user-images.githubusercontent.com/236656/32783487-3735d03c-c94c-11e7-8bc0-d10b7b681cd0.png">

To reproduce possible bug: Close all windows and click `cmd` + `t` or use the menu as shown in screenshot. New window with one tab should appear?

**Comment by pfrazee** [comment]
Thanks for reporting, you're right. We'll fix this up.

**Comment by eklem** [comment]
Keep up the good work :+1:

**Comment by pfrazee** [comment]
Thanks!
