### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by 0x0ade** [beakerbrowser/beaker#758]
Operation System: Windows 10
Beaker Version: v0.7.8

Beaker is unable to create notifications on my system.
* `Notification.permission` is always `"granted"`, no matter if the permission has been requested.
* Trying to create a new `Notification` for the first time shows a banner:
  >This site would like to create desktop notifications.
  * Denying it doesn't change `Notification.permission`. Trying to create another notification after pressing "Don't Allow" shows the banner again.
  * Pressing "Allow" never shows the banner again on that domain.
* The notification doesn't show up.

I'm testing it with the following code in the console: 
```js
function notify() { return new Promise((resolve, reject) => {
  if (!window['Notification']) {
    reject();
    return;
  }

  if (Notification.permission === 'denied') {
    reject();
    return;
  }
  if (Notification.permission !== 'granted') {
      // If not explicitly denied, request.
      Notification.requestPermission(permission => {
        if (permission !== 'granted')
          reject();
        else
          resolve(new Notification('Hello, World!'));
      });
    return;
  }

  resolve(new Notification('Hello, World!'));
})};
notify();
```

The promise resolves immediately in another Electron app and when granting the permission in Chrome, just as it should.  
A minor detail regarding Chrome: When requesting the permission and denying it, all further invocations fail (permission stays "denied").

**Comment by pfrazee** [comment]
Thanks for the detailed report. We'll get into it soon.

**Comment by pfrazee** [comment]
The `Notification.permission` issue is an Electron bug. I've filed an issue https://github.com/electron/electron/issues/11221, and will see if I can't fix it myself in a bit.

Notifications otherwise worked for me on MacOS, so I'll test on Windows in a moment.

**Comment by pfrazee** [comment]
Notifications work on Ubuntu. They kind of suck, but they do work.
