### ISSUE TITLE
Adding an exectuable file to a site overwrites the site with the executable 

### ISSUE THREAD

**Issue by probonopd** [beakerbrowser/beaker#762]
Operation System: `ubuntu-17.10-desktop-amd64.iso`
Beaker Version: `beaker-browser-0.7.8-x86_64.AppImage`

* Launch `beaker-browser-0.7.8-x86_64.AppImage`
* Click on "add files" and add the `beaker-browser-0.7.8-x86_64.AppImage` as the file to be added to the site, this only results in

> No unpublished changes

* Navigate to `$HOME/Sites`, you will see that the directory(!) of the site has been replaced with the `beaker-browser-0.7.8-x86_64.AppImage` rather than it having been copied into the site directory

**Comment by pfrazee** [comment]
Woah that's funky. I'll check into this. Thanks for reporting.

**Comment by probonopd** [comment]
Hiere's a short video to illustrate it:
[https://www.youtube.com/embed/tawA8V_CdIk](https://www.youtube.com/embed/tawA8V_CdIk)

**Comment by pfrazee** [comment]
Yeah I think there's code that is confusing the appimage file with a directory, and that's leading to an inplace import. I'll try to hit this in the next release.

**Comment by pfrazee** [comment]
There's a good chance this was a cross-platform bug, also reported https://github.com/beakerbrowser/beaker/issues/776.

I have a fix that works for MacOS. I'll check on Linux and Windows next.

**Comment by probonopd** [comment]
Let me know if there is an AppImage available that you would like me to test on Linux. Thanks!

**Comment by pfrazee** [comment]
Ok I just confirmed this is fixed in master. You'll need to update all deps (run burnthemall to be sure).

**Comment by probonopd** [comment]
...or just wait for the next AppImage ;-)
