### ISSUE TITLE
Improvement: Make fullscreen take up the entire screen

### ISSUE THREAD

**Issue by cblgh** [beakerbrowser/beaker#766]
The current behaviour of clicking fullscreen in a HTML5 video, or on youtube, is that it fills up beaker's available area. The desired behaviour would be to take up the screen's entire area.

What it looks like currently: 
![screen shot 2017-11-18 at 15 25 57](https://user-images.githubusercontent.com/3862362/32981294-fbc4268a-cc74-11e7-879b-cec88bd4f1a4.png)

**Comment by frabrunelle** [comment]
This is fixed on the `beaker-0.8` branch 🙂

See #687

**Comment by cblgh** [comment]
oh fantastic! major props to mix for taking the step of fixing it!
