### ISSUE TITLE
Add a "clear cache" option.

### ISSUE THREAD

**Issue by peregrinogris** [beakerbrowser/beaker#768]
It'd be quite useful to have an option to force run the garbage collector and remove all the cached dats, akin to what other browsers have to clear the cache.

**Comment by peregrinogris** [comment]
If it's not too difficult, and/or pointed in the right direction, would be willing to contribute with actual code for this :)

**Comment by pfrazee** [comment]
Yeah sounds good. I think it'd make a lot of sense to add this to the settings page somewhere. We'll need to add a method, probably to the `beaker.archives` Web API, to empty the garbage. Feel free to give it a shot, though I think we can probably knock it out as part of 0.8.

**Comment by peregrinogris** [comment]
Well, I'm in the mood of contributing to something new and thise seemed a good(-ish) first bug. Will look into that and report back if I'm stuck ;)

**Comment by pfrazee** [comment]
Ping me on IRC (freenode, #beakerbrowser) if you need help. This may not be
easy to figure out without help.

**Comment by pfrazee** [comment]
I'm on a small-task and bugfixing kick so I just knocked this out. Hope you don't mind!
