### ISSUE TITLE
Electron version 1.8.2--beta breaks socket.io 

### ISSUE THREAD

**Issue by d4tocchini** [beakerbrowser/beaker#769]
Operation System: MacOS 10.13.1 
Beaker Version: 0.8

Causes [this err](https://github.com/socketio/engine.io/issues/536), ie the native module uws (dep of engineio) does not build correctly.

Reverting to electron 1.7.9 fixes this issue.  @pfrazee, any particular reason to not stick with electron's latest stable release?

**Comment by pfrazee** [comment]
@d4tocchini Are you trying to fork beaker? If not, this shouldn't be relevant (you cant use native modules in web apps).

To answer your questions, 1.8.2 has a crash fix that I implemented, and which we need.
