### ISSUE TITLE
High CPU usage on loading a large file

### ISSUE THREAD

**Issue by Danmou** [beakerbrowser/beaker#770]
Operation System: Ubuntu 16.04
Beaker Version: 0.7.9

I have a [large TiddlyWiki file](https://www.dropbox.com/s/fzf67dpktmfau0d/notes.html?dl=1) (55MB due to a lot of embedded images) that I want to open using Beaker. Opening the HTML file works as expected, but if I add it as a site's index.html and open the site, I get some problems: The page shows up and behaves as expected, but the loading indicator continues indefinitely, and meanwhile Beaker uses all of my CPU.

I do not experience these problems with a fresh TiddlyWiki, so the problem must be something with this specific file. Does Beaker have a problem with large files in general?

My next step is to try gradually importing the content into a new TiddlyWiki to see when the problem begins to occur, but this would take ages, so if anyone can help me figure out what is causing Beaker to get stuck like this, it would be greatly appreciated.

**Comment by pfrazee** [comment]
I've got a performance tweak on the master branch that might help. Is it convenient to try to build from master and see if that helps with the CPU usage?

I also think the non-stop loading is a bug in the UI. I've noticed it elsewhere and have a todo to fix it. Maybe I'll hit that today.

**Comment by pfrazee** [comment]
I split out the spinner issue in another issue, because (afaict) it's a UI bug rather than a performance issue. https://github.com/beakerbrowser/beaker/issues/772
