### ISSUE TITLE
"Modal already active" error

### ISSUE THREAD

**Issue by bgcarlisle** [beakerbrowser/beaker#774]
Operation System: Ubuntu 16.04
Beaker Version: 0.7.9

If I click the "new site" button or fork a site, and I dismiss the modal window using the window's red X rather than clicking the "cancel" button, the window goes away, but it's impossible to open the fork / new site window again button until I have restarted Beaker entirely.

When I try clicking the "new site" button after dismissing a previous one with the X rather than "cancel," I get the following error in the console:

```
Uncaught (in promise) ModalActiveError: Modal already active
    at forkNumbat (dat://063ce091a4f34a3df85b6f397de4bd12e51dfb701ff866b0168c884ebe3bfe2e/numbat.js:192:34)
    at <anonymous>
```

**Comment by pfrazee** [comment]
Thanks for reporting. I'll look into it.

**Comment by pfrazee** [comment]
Silly bug. Fixed. Thanks for reporting.
