### ISSUE TITLE
Windows version is not forking folders within archives

### ISSUE THREAD

**Issue by bgcarlisle** [beakerbrowser/beaker#775]
Operation System: Windows 7
Beaker Version: 0.7.9

When I try to fork an archive using the Windows version of Beaker e.g. dat://numbat-3-bgcarlisle.hashbase.io/ , Windows Beaker copies the files in the root directory, but fails to copy anything from folders.

Forking of folders on Mac and Linux, but does not on Windows.

**Comment by pfrazee** [comment]
Hey @bgcarlisle, can you double check whether the target dat was fully downloaded before forking? (The fork modal should tell you this.)

**Comment by bgcarlisle** [comment]
Yes, tried it on a Windows machine of a lab-mates, and also got a helpful librarian to do it too; same result.

I made sure that the little green bar went all the way, so the archive was downloaded entirely.

Tried forking from hashbase, tried forking from a local dat on my desktop, same result.

Downloading as a zipped file gets everything, though!

**Comment by pfrazee** [comment]
Ok thanks very much for reporting! I'll look into it for the next 0.7.x release.

**Comment by bgcarlisle** [comment]
You're the best :)

**Comment by pfrazee** [comment]
Fixed! We'll get a new release out soon. Thanks for reporting!

**Comment by bgcarlisle** [comment]
Wow, speedy!
