### ISSUE TITLE
Attempting to add file or folder fails, then yields "Beaker cannot find the folder for these files" error

### ISSUE THREAD

**Issue by dwblair** [beakerbrowser/beaker#776]
Operation System: Lubuntu
Beaker Version: 0.7.9

Hi Folks!  (I'm so excited about Beaker I can't even tell you.  Thanks so much for all this awesome.)

I'm having trouble getting Beaker to work on Lubuntu.  After I create a new site, I then attempt to add a file or folder to it -- and a) this attempts to fail, and b) when I refresh the new site, I get a "Beaker cannot find the folder for these files" error.  

(Aside: I checked in the ~/Sites folder, and the new site is indeed intact there.  So somehow I'm overriding Beaker's record of where the site lives, maybe?)

It is happening both with new sites, and when I attempt to add a file or folder to an existing site.

In case it helps, I made a (terribly executed, apologies) screencast of my experience, here:

https://www.youtube.com/watch?v=7-h1qBKLit8

Cheerio!
DB

**Comment by pfrazee** [comment]
Thanks for the report! I'm doing a round of bugfixing today, so I'll see if I can solve this today.

**Comment by dwblair** [comment]
Wow -- that'd be awesome! Thanks!!

**Comment by chartgerink** [comment]
Just confirming that this is an issue after I downgraded to 0.7.9 from 0.8. I'm on Fedora 26. 

Welcome to Beaker @dwblair! 🥂

**Comment by pfrazee** [comment]
Yeah I'm not sure when this got introduced, but I don't think it's platform specific either.

**Comment by pfrazee** [comment]
Ok I found a fix for MacOS. Testing across platforms now.

**Comment by dwblair** [comment]
@chartgerink  --  Thanks very much for the welcome!

@pfrazee -- Cool!  Let me know if there's something I can help to test?  Cheerio!

**Comment by pfrazee** [comment]
@dwblair if it's not too much trouble, you can pull latest on master, run `npm run burnthemall`, and then `npm start` and see if it's solved.

No need to though, I can test myself. Up to you!

**Comment by dwblair** [comment]
-- I'll give that a shot right now!

**Comment by dwblair** [comment]
.... and .... itworks on Ubuntu!

I'm now able to create a new site, and add both files and folders to the site.  Note sure what magic you wrought, but things seem very smooth now.  Fantastic -- now I get to play with Beaker, too :)

Thanks so much for the super-rapid response!

**Comment by pfrazee** [comment]
Great! Thanks for testing. I'll test it on windows, but marking closed for now.
