### ISSUE TITLE
Devtools keyboard shortcut brings up Beaker Devtools instead

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#777]
**Operation System:** Mac OS High Sierra
**Beaker Version:** 0.8 branch

Normally in other browsers I'm quickly able to bring up the Devtools for a site with `Cmd`+`alt`+`I` on my mac. However, whenever I try this with 0.8, it brings up the shell-window devtools instead (although weirdly, I can hit it again and get the webview devtools as well).

![devtools-bug](https://user-images.githubusercontent.com/916253/33413206-df746190-d555-11e7-9a91-10388cf23838.gif)

**Comment by pfrazee** [comment]
I'd bet this is a bug related to which webContents is currently focused.

**Comment by pfrazee** [comment]
Fixed. Thanks for filing. Turns out we had a bug in the keybinding code.
