### ISSUE TITLE
Partitions and rendering static pages

### ISSUE THREAD

**Issue by RyanQuey** [beakerbrowser/beaker#780]
Operation System: Ubuntu Xenial
Beaker Version: 0.7.9

So this isn't a bug per se, more just me breaking stuff and wondering why it's breaking.  But I am trying to get it so each window can have its  own session using partitions  (don't ask me why).  I have  already got that part working, adding a  partition property to every webview.  But now beaker protocol pages ( e.g.,  `beaker://start`, `beaker://history`)  won't open up (other web pages work fine). 

 Other  requests to the `beakerServer`  also work ( e.g., `beaker://shell-window`, `beaker://assets/icons.css`), but the request for the start page, history page etc aren't even seen by the `beakerServer` (I added some logging, and nothing comes up when going to those pages). It seems that anything to the beaker protocol requested from the address bar fails, but requests from an html file work??

Everything is failing silently though. Any guesses on what could be going wrong?

Thanks!

**Comment by pfrazee** [comment]
Yeah, IIRC the protocols are registered on individual sessions. Check the electron docs on custom protocols.

**Comment by RyanQuey** [comment]
@pfrazee perfect, thanks for the tip!

**Comment by pfrazee** [comment]
👍  Going to close, reopen if you need more help!
