### ISSUE TITLE
Profile Partitions

### ISSUE THREAD

**Issue by carsonwright** [beakerbrowser/beaker#781]
Operation System: macOs Sierra
Beaker Version: 0.7.9
I'm having trouble with partitioning the webview, it is necessary for true profile support. 

This is the relevant code
```
 var el = document.createElement('webview')
  el.dataset.id = id
  el.setAttribute('partition', `persist:profile-${profiles.currentProfile}`)
  el.setAttribute('preload', 'file://' + path.join(APP_PATH, 'webview-preload.build.js'))
  el.setAttribute('webpreferences', 'allowDisplayingInsecureContent,contentIsolation')
  // TODO re-enable nativeWindowOpen when https://github.com/electron/electron/issues/9558 lands
  el.setAttribute('src', url || DEFAULT_URL)
  return el

```

This is the relivent code for registering the protocol I believe, any ideas?
```
protocol.registerHttpProtocol('beaker',
    (request, cb) => {
      // send requests to the protocol server
      console.log(`http://localhost:${serverPort}/?url=${encodeURIComponent(request.url)}&nonce=${requestNonce}`)
      cb({
        method: request.method,
        url: `http://localhost:${serverPort}/?url=${encodeURIComponent(request.url)}&nonce=${requestNonce}`,
      })
    }, err => {
      if (err) {
        throw new Error('Failed to create protocol: beaker. ' + err)
      }
    }
  )
```

**Comment by pfrazee** [comment]
That's funny, are you working with @ryanquey ? Just answered https://github.com/beakerbrowser/beaker/issues/780#issuecomment-348620375

**Comment by carsonwright** [comment]
I am actually ha, we've talked about it, and have both reviewed your pointer but are still struggling with the issue, so we decided to ping you back again.

**Comment by pfrazee** [comment]
So the problem is that the custom protocols aren't available on the non default session, right?

I do know that session objects have their own protocol objects https://electronjs.org/docs/api/session#sesprotocol. You might need to register the protocol on each session.

**Comment by carsonwright** [comment]
Thank you @pfrazee we did end up being able to do that, Thank you!
