### ISSUE TITLE
dat:HASH (instead of dat://HASH) will not resolve, but still show correct url

### ISSUE THREAD

**Issue by noformnocontent** [beakerbrowser/beaker#783]
Operation System: any
Beaker Version: 0.7.10

`dat:HASH` (instead of `dat://HASH`)
will not resolve, but still show correct url (`dat://HASH`)

clicking the address bar (will show `dat:HASH`) and hitting `Enter` the second time -- will resolve correctly

**Comment by pfrazee** [comment]
Ok thanks for filing. We'll check into it.

**Comment by specious** [comment]
Operation System: macOS Sierra 10.12.6 (16G29)
Beaker Version: git commit a44d4272cc3fa817c2b3b31d6ac69a74c19fbb10

Confirmed in case of domain literals as well.  First submit translates `dat:<addr>` to `dat://<addr>`.  Subsequent submit works as expected.

**Comment by pfrazee** [comment]
Fixed. It now explains the URL is incorrect and doesnt show a 'corrected' form of it. That corrected form was accidental. If the user inputs `dat:foo` that's like inputting `https:github.com`. It's a malformed URL. Either we can use it as the query to a search engine, or we complain that's a bad URL.

**Comment by pfrazee** [comment]
We *could* try to autocorrect this but the logic is already pretty complex.

**Comment by noformnocontent** [comment]
chrome and firefox auto-correcting `http(s):URL` to add the missing `//`, so idunno
