### ISSUE TITLE
Shouldn't browsing to non-existant folder give the fallback / 404 page instead of an empty listing?

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#787]
Operation System:
Windows 10
Beaker Version: 
Version: 0.7.10 Electron: 1.8.2 - Chromium: 59.0.3071.115 - Node: 8.2.1

When browsing to a folder that doesn't exist in my archive, I get a directory listing of an empty folder.

I would have expected to get the fallback (404) page instead, because the directory does not exist.

Could you confirm if my expectation is the correct behaviour?

The behaviour originates from this piece of code, where it will give a folder view if the requested path looks like a folder (because it ends in a slash), of if it looks like a file but exists as a folder in the archive.

https://github.com/beakerbrowser/beaker/blob/e9f326145c22ef648dda55a3cfc8cb37f191c252/app/background-process/protocols/dat.js#L264

I think if the check for a fallback page:
https://github.com/beakerbrowser/beaker/blob/e9f326145c22ef648dda55a3cfc8cb37f191c252/app/background-process/protocols/dat.js#L279-L282

is done just a bit earlier to just before the folder handling, it will give this exact behaviour because 'entry' will get a value from the fallback page (if it exists), but keep the currect behaviour if no fallback page is given.

**Comment by pfrazee** [comment]
You're correct, this is a bug. We'll get a fix done soon.

**Comment by pfrazee** [comment]
I believe the `(!entry && isFolder)` logic clause is outdated and can be removed.
