### ISSUE TITLE
Restore the window menu on Linux and Windows (perhaps as an option)

### ISSUE THREAD

**Issue by probonopd** [beakerbrowser/beaker#788]
Please give us, at least as an option, a menu bar instead of the "hamburger menu".

Rationale:
https://medium.com/@probonopd/make-it-simple-linux-desktop-usability-part-1-5fa0fb369b42

**Comment by pfrazee** [comment]
You're talking about the window menu, right?

I do believe we have that hidden on Linux and Windows for aesthetic reasons, but I can see why that's a drag. We'll give this some thought. Thanks for the issue.

**Comment by despens** [comment]
The menu bar appears when pressing the left alt key. I believe this is how Firefox does it as well.

**Comment by probonopd** [comment]
Thanks for letting me know, but this is hardly "discoverable". What is so wrong about having a standard menu bar visible all the time, with the option to hide it?

**Comment by pmario** [comment]
IMO default "always on" menu bars will be the minority in the future, because they are wasting vertical screen space, that can be better used.

With version 0.8.0-prerelease-7 the "left-Alt" key doesn't work for me on windows 10.

**Comment by pfrazee** [comment]
In the 1.0 release the hamburger menu now includes almost every menubar item

**Comment by probonopd** [comment]
Thanks @pfrazee but if I read it correctly it still won't give us a real menu bar instead of that hamburger...

**Comment by pfrazee** [comment]
That's accurate IIRC but I haven't tried linux recently, it may still have the menu bar. Give the 1.0 beta a try, if you don't like what we got, open an issue?

**Comment by probonopd** [comment]
Yes, I'll do that once it's available for download. Thank you.
