### ISSUE TITLE
web3 integration

### ISSUE THREAD

**Issue by amexperts** [beakerbrowser/beaker#790]
Operation System: All
Beaker Version: Latest

I see an old thread regarding ethereum integration. Has there been any further thoughts on this? The more I am forced to use passwords the more I want to see web3 integrated as an easy way to verify myself using blockchain technologies. Am happy to work with others on trying to integrate this.
Cheers
Adam

**Comment by pfrazee** [comment]
Hi @amexperts! No change. We're still using Dat for all of our protocol needs.
