### ISSUE TITLE
Flawed install? no 'devtools" unable to edit files, explorer opens instead

### ISSUE THREAD

**Issue by JonVO20** [beakerbrowser/beaker#795]
Operation System: win8.1
Beaker Version: 0.7

**Comment by pfrazee** [comment]
Hi @JonVO20. Sorry you're having trouble!

Can you be more specific about what's going wrong? Where did you expect to see the devtools but didnt? What files were you trying to edit? Etc

**Comment by JonVO20** [comment]
Followed the video on building a website. also the api on writing files. I can create a website, but "opening the website" , and using "devtools" has me stopped. I can view the files in explorer, but no tools to edit as explorer does not recognize a program to use the files.  When opening a folder on the newly created website in Beaker, a see the files but no way to edit or use them. I would need to locate individual programs for the java, html, files.

**Comment by pfrazee** [comment]
> using "devtools" has me stopped

Have you tried right clicking on the web page and selecting "Inspect element"?

>  I can view the files in explorer, but no tools to edit as explorer does not recognize a program to use the files. When opening a folder on the newly created website in Beaker, a see the files but no way to edit or use them. I would need to locate individual programs for the java, html, files.

Yeah, Beaker doesn't provide tools to edit html and other files. You'll need to install an editor. I suggest https://www.sublimetext.com/ !
