### ISSUE TITLE
Arabic text rendered with incorrect encoding

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#797]
**Operation System:** Ubuntu 16.04
**Beaker Version:** 7.10

## Summary

A simple html file containing Arabic text like this:
```html
<!DOCTYPE HTML>
<html>
<body>
بسم الله الرحمن الرحيم
</body>
</html>
```

renders as:
```
Ø¨Ø³Ù… Ø§Ù„Ù„Ù‡ Ø§Ù„Ø±Ø­Ù…Ù† Ø§Ù„Ø±Ø­ÙŠÙ…
```

**Checking the file encoding with `file -i index.html` outputs:**
`index.html: text/html; charset=utf-8`

**Screenshot of rendering:**
![image](https://user-images.githubusercontent.com/6719916/34300885-eff48d44-e732-11e7-8767-2365647e6a7c.png)

**Screenshot of view-source:**
![image](https://user-images.githubusercontent.com/6719916/34300962-2dad9da6-e733-11e7-9118-d7d4096b2735.png)

## Debugging

Hosted the file on hashbase:
dat://hossameldeen.hashbase.io+4/arabic-test-github-beaker-issue-797.html
https://hossameldeen.hashbase.io/arabic-test-github-beaker-issue-797.html

Tried opening the file locally, from hosted dat, and from hosted https, from beaker & chrome. The cell in each column below is &lt;Render text>/&lt;view-source text>

|   | Beaker | Chrome |
| ------------- | ------------- | ------------- |
| Local  | render:Scrambled/view-source:Arabic  | render:Arabic/view-source:Arabic |
| Dat  | render:Scrambled/view-source:Arabic  | N/A  |
| Https  | render:Scrambled/view-source:Arabic  | render:Scrambled/view-source:Scrambled  |

Note: The file was named `index.html` but I then copied it to `arabic-test-github-beaker-issue-797.html`. That's why you see the 2 names in the issue; sorry about the confusion.

**Comment by hossameldeen** [comment]
Tried hosting the file on hashbase:
dat://hossameldeen.hashbase.io+3/index.html
https://hossameldeen.hashbase.io/index.html

On beaker: The behaviour of rendering & source-viewing is the same, regardless of whether I'm opening it with the dat or https url.

On chrome: (ofc, using the https url only) Renders the same but view-source returns:
```html
<!DOCTYPE HTML>
<html>
<body>
Ø¨Ø³Ù… Ø§Ù„Ù„Ù‡ Ø§Ù„Ø±Ø­Ù…Ù† Ø§Ù„Ø±Ø­ÙŠÙ…
</body>
</html>
```

**Comment by pfrazee** [comment]
Thanks for reporting. We'll check into this.

**Comment by hossameldeen** [comment]
For some reason, it's now working. Feel free to close, @pfrazee , if your mileage is the same. Perhaps #831 solved it (didn't A/B test to check).

**Comment by pfrazee** [comment]
Good deal!
