### ISSUE TITLE
'cannot set property 'domain' of null'

### ISSUE THREAD

**Issue by NicksWorld** [beakerbrowser/beaker#799]
Operation System: Mac OSX
Beaker Version: current version (can't get into beaker).

I am getting errors from electron when I attempt to open beaker.

The error was not allowing me to copy it but I got a screenshot of it:
<img width="446" alt="error" src="https://user-images.githubusercontent.com/29175042/34330109-ab9ef6fc-e8e5-11e7-9f2c-9bac558f2adb.png">

**Comment by pfrazee** [comment]
Ah that's no good! Are you getting this from the last build release, or from building from source?

**Comment by NicksWorld** [comment]
I was running from the last release, not from source. I had just restarted my computer and no windows were currently open.

**Comment by pfrazee** [comment]
Are you sure you're on the latest version? If you're not sure, could you try redownloading?

(This is a bug we've been battling with for a while, and this will help me figure out if it's still an issue or if you're just experiencing the old bug.)

**Comment by NicksWorld** [comment]
I could not recreate the problem, although it could have been the result of a memory leak that it experienced prior to me restarting my computer. In case the console's log from the memory leak may help I will include it:
```internal/process/warning.js:28 (node:18142) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 set-active listeners added. Use emitter.setMaxListeners() to increase limit```

**Comment by pfrazee** [comment]
Nah that warning's about having a lot of event emitter handlers set.

This bug is basically something that electron does temperamentally. I've been trying to guard against it in Beaker's code, with varying levels of success. Going to close for now. If it happens again, please reopen!

**Comment by pashvin** [comment]
We have one new recent report from our customer about this issue.

Electron version is 2.x

Tue Dec 04 2018 12:05:37 GMT-0500 (EST)    TypeError: Cannot set property 'domain' of null
    at EventEmitter.init (events.js:63:15)
    at EventEmitter (events.js:28:21)
    at Object.<anonymous> (/Applications/Mitel Teamwork.app/Contents/Resources/electron.asar/browser/api/screen.js:7:14)
    at Object.<anonymous> (/Applications/Mitel Teamwork.app/Contents/Resources/electron.asar/browser/api/screen.js:19:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
