### ISSUE TITLE
Adding files to new site creates empty files

### ISSUE THREAD

**Issue by bdionne** [beakerbrowser/beaker#800]
Operation System: OS X High Sierra
Beaker Version: 0.7.10

When I add an existing file to a web site, it creates a zero length file. 

I happened to have an emacs buffer open with the newly created file and noticed it warned that the file changed on disk. I wrote it again from emacs, which created a `"~"` file with the original empty one, and then I added the backup in Beaker and it all worked.

**Comment by pfrazee** [comment]
That's odd. Was it when you published that this happened?

This is odd enough that I might just leave this until 0.8 comes out, which puts in a new workspace system (and so shouldn't have the same bugs).

**Comment by bdionne** [comment]
Yes, on publishing, though it stop happening since I've turned on the live update thingy tp immediately push changes..

For sure, let's wait for 0.8 and a possibly new crop of bugs, it's easy enough to get past. 

As an aside, I'm really loving this tool, wery well done!

**Comment by pfrazee** [comment]
Thanks! Glad it is working for you. I'm going to close the issue for now since it stopped happening, but feel free to reopen if it happens again, and then we can evaluate again with 0.8.
