### ISSUE TITLE
Don't try to run a second Beaker instance

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#801]
Beaker bombs out with errors if you try to run it while an instance is already running. We should put in some coordinating code so that the already-running instance is brought to the foreground, to avoid confusing errors.

**Comment by specious** [comment]
I just got two instances running side by side:

![beakers-two-instances](https://user-images.githubusercontent.com/451178/34464114-af82ec3c-ee40-11e7-8c8f-ab087177319a.png)

On the left is git commit a44d4272cc3fa817c2b3b31d6ac69a74c19fbb10 compiled from source and started with `npm run start`, and on the right is Beaker 0.7.10 installed with `brew cask install beaker-browser` and launched from `/Applications/Beaker Browser.app`.

They immediately found each other and one can load dats from the other. To my surprise, it also appears to have solved the situation I had in #802 and https://datbase.org was finally able to show me the contents of the archive I shared from my browser which it couldn't reach when I only had one of them running.

**Comment by pfrazee** [comment]
A list of observations/responses:

 - I'm pretty shocked you didn't see errors! SQLite should give "failed to open" errors on the instance opened second. 🤷‍♂️ 
 - It's actually possible to use env-vars to specify separate user-data directories. However we fix this, we should try to make it possible to run extra instances when the user-data dirs are different, for testing.
 - How interesting that this solved your connectivity problem. I wonder -- is it possible the MacOS firewall is a factor?

**Comment by specious** [comment]
> How interesting that this solved your connectivity problem

To be clear, it didn't totally solve it, but for a short moment I was able to see 3 peers on the counter for my dat in the sidebar, and datbase.org was able to load the manifest and showed 1 source available:

https://datbase.org/dat://dbfd9a74d014399bdcd04ea6a9fce0c675661bd8800ae024f6a76a118a910349/

![side-by-side-datbase-and-local-library](https://user-images.githubusercontent.com/451178/34464214-f693ad9c-ee44-11e7-900c-3791d282529b.png)

**Comment by pfrazee** [comment]
Ok noted

**Comment by specious** [comment]
Maybe I saw 3 peers because I got datbase to query my dat.  That would make sense.  I was so excited that my memory is not completely reliable on that aspect.

**Comment by specious** [comment]
I'm pretty sure that my macOS firewall is turned off:

![macos-firewall-is-off](https://user-images.githubusercontent.com/451178/34464317-9d630850-ee47-11e7-8987-e2080a0d7760.png)

**Comment by pfrazee** [comment]
@0x00A I appreciate the offer. If you're up for it, sure! If not, I should hit it in a few days.

(Be sure to work on the `beaker-0.8` branch. That's our next release.)

**Comment by pfrazee** [comment]
Done, just pushed this to the 0.8 branch.
