### ISSUE TITLE
Can't run Beaker by doing npm start

### ISSUE THREAD

**Issue by illuminati-RV** [beakerbrowser/beaker#804]
Operation System:Manjaro Linux (Arch)
Beaker Version:0.7.10

I tried to build beaker from source using npm install and then npm start
But it showed an error that "Unable to find Electron app in ~/beaker/app

![2017-12-31-231404_1366x768_scrot](https://user-images.githubusercontent.com/20295778/34463401-ef22a824-ee80-11e7-9e50-a670ba32fb92.png)

**Comment by pfrazee** [comment]
Hi @illuminati-RV.

Based on that screenshot, it looks like you ran `npm install electron` and the command is `npm install`. Then, you call `npm start`.

**Comment by illuminati-RV** [comment]
oh my bad...
I had tried something more to see if anything works

**I actually did npm install 1st**
 you can see that here, the results' the same...

![2017-12-31-232429_1366x768_scrot](https://user-images.githubusercontent.com/20295778/34463439-ecc31cfc-ee81-11e7-93b0-3def53f93f88.png)

**Comment by pfrazee** [comment]
Wait a minute! Your directory listing *is* missing the `app` folder. Any idea how that could have happened? Try a fresh checkout.

**Comment by illuminati-RV** [comment]
Uhhh... I just did a fresh clone... its all present ryt here

![2017-12-31-233002_1366x768_scrot](https://user-images.githubusercontent.com/20295778/34463456-8f55819e-ee82-11e7-9dd9-537eb8d0784d.png)

**Comment by illuminati-RV** [comment]
Are'nt these the supposed files?

**Comment by pfrazee** [comment]
Lol sheesh. Your file listing ignores the `.`, so it puts `.git` beneath `app`. I assumed I was seeing the top of the listing in your screenshot.

I notice that the build outputs are missing, so I rechecked the install process. You need to run `npm run rebuild` before `npm start`.

**Comment by pfrazee** [comment]
Reopen if it's still not working.

**Comment by illuminati-RV** [comment]
Hey, thank you for your assistance.
I just presumed it works as in other electron apps and forgot to do npm run rebuild
Happy new year and cheers bro...

**Comment by pfrazee** [comment]
Thanks, same to you

**Comment by illuminati-RV** [comment]
hey, can I ask u a little bit more on this browser u've developed?
I want to customize this browser for my B.tech project, Which IDE do u use to test this? do  u use electron to test it and then make its binary?

**Comment by pfrazee** [comment]
I don't use an IDE for testing. We have the automated tests (`npm test`) and then use the builtin devtools when possible. The final binary bundles electron with it (`npm run release`).

**Comment by illuminati-RV** [comment]
Okay thank you for your help 😄

**Comment by illuminati-RV** [comment]
Okay thank you for your help :smi

**Comment by pfrazee** [comment]
Sure thing!
