### ISSUE TITLE
<object> embedded PDFs aren't displayed on macOS High Sierra

### ISSUE THREAD

**Issue by dwayneroberts** [beakerbrowser/beaker#808]
Operation System: macOS High Sierra 10.13.2
Beaker Version: 0.7.10

Beaker won't display <object> embedded PDF files on macOS High Sierra. It only returns error messages. It works however locally in Firefox and Safari.

`<object data="example.pdf" type="application/pdf" width="100%"></object>`

**Comment by pfrazee** [comment]
I'll check into this in a bit. Thanks for reporting.

**Comment by pfrazee** [comment]
For the moment, we're not going to support PDFs because we don't support OS-native plugins like adobe. Closing in favor of a new issue about adding support for PDF.js

**Comment by pfrazee** [comment]
https://github.com/beakerbrowser/beaker/issues/821
