### ISSUE TITLE
It's too difficute to get touch with another user behind NAT

### ISSUE THREAD

**Issue by LifeNT** [beakerbrowser/beaker#810]
Operation System: windows/mac
Beaker Version:0.7.1

I tried fritter today with many friends, but is't not happy because beaker can't link to the one who behind NAT. 
If user1 and user2 both in same local network, such as user1 is 192.168.1.4, user2 is 192.168.1.5, the beaker and fritter work well 
if user1 and user2 are behind two NAT device, such as both use a router, then they can't open each other's  fritter site.

**Comment by pfrazee** [comment]
We have an ongoing issue for this https://github.com/beakerbrowser/beaker/issues/802. There are issues in the Dat protocol which are currently being debugged. I'm going to close this as a duplicate, please follow https://github.com/beakerbrowser/beaker/issues/802.
