### ISSUE TITLE
[rotonde] Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by noformnocontent** [beakerbrowser/beaker#811]
Operation System: Arch Linux
Beaker Version: 0.7.10

leaving open a rotonde instance ( dat://2f21e3c122ef0f2555d3a99497710cd875c7b0383f998a2d37c02c042d598485/ )
for a couple of minutes, will result first in a single system popup:

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: EMFILE: too many open files, open '/home/dym/.config/Beaker Browser/Dat/Archives/Meta/2c/edfd..dbd2d/metadata/bitfield'

then rendering of that page and of tab bar stops.
a bit later a flock of similar messages appear on top of each other

setting `sudo fs.inotify.max_user_watches=1000000` did not fixed the problem, but only delayed it.

**Comment by pfrazee** [comment]
Yeah this has been reported a couple times. The new version of Beaker will dramatically reduce the file-watchers but it may not totally solve this problem. We'll see what happens.
