### ISSUE TITLE
Reloading library doesn't detect manually created sites

### ISSUE THREAD

**Issue by SaFrMo** [beakerbrowser/beaker#812]
Operation System: OSX Sierra 10.12.6
Beaker Version: 0.7.10

Steps to reproduce:
1. Add a new directory to the Sites folder from which Beaker pulls the Library.
2. Add a `dat.json` to the new directory with a `url`, `title`, and `description`.
3. Navigate to beaker://library/ and hit Refresh.

Expected behavior: New, manually-created site appears in Library.

Actual behavior: No visible change to Library occurs.

I'm wondering if this is by design, hasn't been implemented yet, or is a mistake on my end? If it hasn't been implemented, I'd be happy to work on it. I know you can create a new site or fork an existing site from the Beaker UI, but I've run into a couple situations where it'd be useful to set up new sites manually. Thanks!

**Comment by pfrazee** [comment]
That's a pretty reasonable expectation but we didn't write the 0.7 library that way.

Version 0.8 changes how the library works with a more explicit workspaces concept. We had to do that to improve performance and solve some logical edgecases that our magical 0.7 library introduced.

If you don't mind, I'm going to close this as a wontfix, and 🤞  hopefully you'll like what we come up with for the next version. If not, please open an issue (even if it's a similar question) and we'll try to improve.

Thanks for filing.

**Comment by SaFrMo** [comment]
Works for me! Thanks!
