### ISSUE TITLE
random-access-file JS error

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#813]
![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/2a3I1S2i0q391N0S1H1X/Image%202018-01-10%20at%2011.16.22%20AM.png?X-CloudApp-Visitor-Id=403280ad867d5f3b84e56e5fa5cfa870&v=dade0f65)

**Comment by pfrazee** [comment]
Hey @aaronshaf thanks for reporting. What version of Beaker are you using? I thought we solved the error boxes coming up by 0.7.10.

**Comment by aaronshaf** [comment]
I'm on 0.7.10

**Comment by pfrazee** [comment]
Ok thanks. We'll try to figure this out.

**Comment by aaronshaf** [comment]
Totally unable to visit any sites in Beaker. Should I blow out my application settings folder? Hesitant to low my existing data :(

**Comment by pfrazee** [comment]
Shoot, that happens on *every* dat site you visit?

**Comment by aaronshaf** [comment]
Nothing works, not even the local stuff: `beaker://bookmarks/`, etc

**Comment by pfrazee** [comment]
Ok try going to `beaker://settings` and hitting "Clear Dat Cache"

**Comment by aaronshaf** [comment]
Not seeing it.
