### ISSUE TITLE
Why using Electron as base?

### ISSUE THREAD

**Issue by geovanisouza92** [beakerbrowser/beaker#816]
Instead of building on top of Chromium?

**Comment by joehand** [comment]
It is! Electron is built on Chromium =)

**Comment by pfrazee** [comment]
Yeah Electron has let us build much more quickly, and made it easy to bundle dat's current implementation (which is built for nodejs).

We're planning to switch to Muon in the near future, which is a fork of Electron with better security.

**Comment by geovanisouza92** [comment]
@joehand I mean in a way that we can simply pull from Chromium upstream and built beaker right away.

@pfrazee is too difficult to port Dat implementation to run on C++, Go, or whatever?

**Comment by pfrazee** [comment]
There's a rust implementation being worked on at https://github.com/bnewbold/geniza.

Electron/Muon have also made development somewhat easier for us, so I'm not inclined to ditch them any time soon -- but we'll see.
