### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by 0x00A** [beakerbrowser/beaker#819]
Operation System: macOS
Beaker Version: 0.7.10

I get this error when I try to start the app.

![image](https://user-images.githubusercontent.com/136109/34914511-84b4e56c-f914-11e7-859f-200fd5e99069.png)

**Comment by pfrazee** [comment]
This is a bug in electron. We have an issue going (https://github.com/beakerbrowser/beaker/issues/819). Closing as a duplicate.

Same advice as in the other thread: lmk if it keeps happening. I'm trying to get it fixed upstream.

**Comment by 0x00A** [comment]
Ah! ok, I'll look at #819 and see if I can help.
