### ISSUE TITLE
Add support for rendering PDFs with PDF.js

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#821]
We're not going to support OS-native plugins, so Flash and Adobe's PDF viewer are out, but PDFs are pretty nice so maybe PDF.js can be used.

**Comment by webdesserts** [comment]
Heads up, I'm going to start looking into this.

**Comment by webdesserts** [comment]
@pfrazee Right now it looks like `.md` files are only formatted over the `dat://` and `http://` protocols. However they are not formatted over the `file://` protocol. Is this intended, or should markdown and pdf files display a "viewer" over the `file://` protocol as well?

**Comment by pfrazee** [comment]
@webdesserts what makes you say `file://` isnt supported by markdown rendering?

**Comment by webdesserts** [comment]
@pfrazee Here was when I encountered the issue: https://clips.twitch.tv/SpineyBreakableYakinikuYouWHY?tt_medium=creation

You can see I drag and dropped a file into 0.8 and it was rendered raw.

**Comment by pfrazee** [comment]
Ah! Well that's a bug. Give me a few moments, I'll see if I can diagnose it.

**Comment by pfrazee** [comment]
Ok fixed. The issue was that the `file://` protocol doesn't give a mimetype

**Comment by webdesserts** [comment]
@pfrazee ahh, Ok. Thanks! I'll keep this in when I work on the pdf detection.

**Comment by pfrazee** [comment]
Cool. Here's how I fixed it: https://github.com/beakerbrowser/beaker/commit/284e3361ac0749ce8a72a1f1e513b3c8e8a6ef39
