### ISSUE TITLE
Modal UI blocks use of Beaker

### ISSUE THREAD

**Issue by saibotsivad** [beakerbrowser/beaker#823]
First time user of Beaker, very excited to get involved in making it awesome.

One thing that prevents me from using Beaker as my "main browser" is that, whenever I try to do operations like "Fork this site", I am presented with a modal which blocks access to other tabs.

This interface action prevents me from going to some other tab, for example to look at a reference page that will help me understand what I should be doing next, so inevitably I need to run Beaker _and_ some other browser.

What I am wondering is whether there have been discussions yet about improving that UI? I would love to read up on those discussions, and/or get involved in them! Blocking modal interfaces are a very draconian way to handle user input, and they keep me from using Beaker as my main browser.

---

Operation System:

macOS High Sierra 10.13.2

Beaker Version:

0.7.10

**Comment by pfrazee** [comment]
This is an interesting point (cc @taravancil). I simply hadn't considered that those modals would be problematic but I can see how it would be when you need to reference other data.

It wouldn't be terribly difficult to switch to non-modal flows (implemented in HTML/CSS within the shell window code). It would also improve performance a little bit (modals take a solid second to setup, which kind of sucks). WDYT tara?
