### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by heapwolf** [beakerbrowser/beaker#824]
Operation System: macOS
Beaker Version: 0.7.10

Left Beaker open all night and opened my laptop the window was blank. Trying to reproduce.

![image](https://user-images.githubusercontent.com/136109/35149806-cb97044a-fd17-11e7-939f-40cdba3bddc2.png)

**Comment by pfrazee** [comment]
Well that's new. Did you happen to catch any errors, in the devtools for the shell window or in the CLI?

Beaker tends to behave pretty badly when left open overnight but that's more due to some issues in the dat stack (oy). I've never seen this though.

**Comment by 0x00A** [comment]
I've been able to reproduce it by leaving it open. But no stack trace / errors (since the process is detached from the debugger). I've learned from working on Voltra that this usually means C/C++. Hope that's helpful.
