### ISSUE TITLE
Support HEAD requests

### ISSUE THREAD

**Issue by dcposch** [beakerbrowser/beaker#826]
Operation System: all
Beaker Version: 0.7.10

## it looks like dat:// doesn't currently support HTTP HEAD requests

GET requests to `dat` URLs work well, using the fetch API

for datpedia, we have a large file we're serving in a dat where we need to find the length ahead of time (before loading small chunks of the file via range requests; that second part works)

**currently HEAD doesn't work**, as far as we can tell

![image](https://user-images.githubusercontent.com/169280/35181774-29b344f2-fd96-11e7-9794-006e9d9e6fa8.png)

our workaround is to hardcode the zip-file length in JS, but HEAD would be better :p

**Comment by pfrazee** [comment]
Yeah that sounds good, I'll add it to 0.8. Any thoughts on which headers we should be sure to include?

**Comment by pfrazee** [comment]
Added to the `beaker-0.8` branch
