### ISSUE TITLE
Angular/React APPs

### ISSUE THREAD

**Issue by rrubio** [beakerbrowser/beaker#828]
Hi Guys,

Just curious. Is it possible to deploy webAPP via beaker? there's plenty of mention about websites/blogs but not much about apps?

Cheers, Rodrigo

**Comment by taravancil** [comment]
Hi Rodrigo,

You can deploy apps in Beaker just like you would in other browsers.

**Comment by whiteyhat** [comment]
How is this possible @taravancil ? 

I have been trying to deploy a nodejs application (backend and frontend) but it has been an unsuccessful operation. I reached the point to use Homebase, but no success at all. https://github.com/beakerbrowser/homebase/issues/40

**Comment by RangerMauve** [comment]
You can't deploy servers inside Beaker. You need to create static single page applications that are stored in a Dat, and have them talk to your oserver using HTTP requests.

**Comment by jmojico** [comment]
It would be really nice to have this feature in Beaker.
I don't think the browser architecture supports webapps though.
