### ISSUE TITLE
requestPointerLock not working

### ISSUE THREAD

**Issue by AlbertoElias** [beakerbrowser/beaker#830]
Operation System: Windows 10
Beaker Version: v0.7.10

This API isn't working. It's available, but it doesn't capture the cursor. [Brave](https://github.com/brave/browser-laptop/issues/12668) have the same issue, so may be Electron related

**Comment by pfrazee** [comment]
Yeah, known issue ☹️  https://github.com/beakerbrowser/beaker/issues/210
