### ISSUE TITLE
UTF-8 in markdown rendering

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#831]
Reported by CrypticDat on Fritter:

dat://fritter.hashbase.io/thread/dat://aba60ff4e2a47e318e793c2b0475c4574ebb7dfa7bd5fd9fd5fb5695a1a195b0/posts/0jct5dk8s.json

**Comment by pfrazee** [comment]
> Is there a way to force the website Beaker automatically creates from markdown files to use UTF8 formatting? I'm having trouble with umlauts and other special characters not displaying correctly.

**Comment by cryptowyrm** [comment]
Thanks for filing the issue for me!

I played a bit around with the code trying to fix this, my first attempt was to add a meta tag with charset set to utf-8 to the page in https://github.com/beakerbrowser/beaker/blob/master/app/markdown-renderer.js, but that doesn't work, has to be done before the page is loaded it seems.

What did work is adding the defaultEncoding parameter to the list of webpreferences and setting it to utf-8 in https://github.com/beakerbrowser/beaker/blob/master/app/shell-window/pages.js:

    el.setAttribute('webpreferences', 'allowDisplayingInsecureContent,contentIsolation,defaultEncoding=utf-8')

But you probably don't want that to be the default for all pages, just for markdown pages, not sure how to do that. Hope that helps in figuring this out!

**Comment by pfrazee** [comment]
Nice, I think we do actually want that setting for all pages. Make a PR on the beaker-0.8 branch!

**Comment by pfrazee** [comment]
Wait no don't make a PR, I'll do it myself!

**Comment by pfrazee** [comment]
@cryptowyrm what's the URL of the markdown site that had the issue?

**Comment by cryptowyrm** [comment]
Great!

I uploaded a simple test page here: dat://cryptic.hashbase.io/utf8.md

Should display the German umlauts ÄÖÜ, but displays Ã„Ã–Ãœ instead.

**Comment by pfrazee** [comment]
That solved it. Thanks!!
