### ISSUE TITLE
Back gesture makes it hard to scroll

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#832]
**Operation System:** Mac OS 10.13.2 (High Sierra)
**Beaker Version:** 0.7.10 & 0.8 branch

I've ran into this several times and it's starting to get annoying so I thought I'd post an issue. Right now there's a "back gesture" where if you scroll fast enough in the left direction, it sends you back a page. At the very least, the feature is a bit sensitive, so I accidentally trigger it all the time. I'd argue that maybe this feature is more disruptive than helpful? This feature exists in safari, but I've disabled it at the OS level, so it was kind of surprising to see it appear again here.

![back-gesture-makes-it-hard-to-scroll](https://user-images.githubusercontent.com/916253/35348882-0da6eaf4-00ff-11e8-9aea-a14911393739.gif)

The left-scroll here is a bit exaggerated, but not unreasonable for returning back to the beginning of... say... a trello board.

**Comment by pfrazee** [comment]
Yeah I run into this sometimes myself. I have the same problem on Chrome in fact.

Maybe we need it to be a setting you can disable in Beaker?

**Comment by webdesserts** [comment]
@pfrazee I'd be happy with an option to disable it, I understand that people have probably grown reliant on this gesture. I kind of find these gestures a little unfortunate though. As touchpads have gotten better and touch devices have become common place, horizontal scrolling has become more realistic, but little overrides like this help keep it as a second-class interaction (that and no one's figured out how to make a better mouse wheel).

**Comment by pfrazee** [comment]
@taravancil do you have any opinions about this?

**Comment by pfrazee** [comment]
Yeah. It's not very easy to get this gesture right with the tools we have.

**Comment by taravancil** [comment]
Wdyt, since we can't get it quite right, does doing it wrong cause more problems than removing it entirely?

**Comment by pfrazee** [comment]
Well, you use the gesture. I've stopped using my trackpad. Would you be sorry to lose it?

**Comment by taravancil** [comment]
Let me try disabling it tomorrow and seeing how it feels.

**Comment by webdesserts** [comment]
After trying the Mac shortcut on safari again, it seems this feature's sensitivity isn't far off. So I wouldn't say that the feature is implemented "wrong", just that not everybody will enjoy this feature. An option to disable in settings seems fine to me. For Mac specifically, it would be neat if there was a way to derive the option from the mac settings.
