### ISSUE TITLE
Add builtin asciidoc rendering (on .adoc pages)

### ISSUE THREAD

**Issue by leroycep** [beakerbrowser/beaker#833]
Since rendering markdown files to html was added, I was wondering if similar support could be added for asciidoc? Is this a feature that should be added?

Link to relevant library: http://asciidoctor.org/docs/asciidoctor.js/

**Comment by pfrazee** [comment]
Hey @Geemili. We're thinking about adding an API that lets the user specify apps that get loaded automatically for pages based on certain rules. So, for instance, if the mimetype matches asciidoc, your asciidoctor app would load and render it. Then we can move opinions like this out of the core.
