### ISSUE TITLE
Question: Is possible to add TCP / UDP Web API for Beaker?

### ISSUE THREAD

**Issue by carloslfu** [beakerbrowser/beaker#835]
The main use case is for custom apps / protocols that make use of raw TCP / UDP sockets. I know there are many security implications, but why can't we build a secure low level networking Web API? Would be awesome to have this for Beaker.

**Comment by JerryGreen** [comment]
Bring on `udp` to browsers - that's a good thing. A lot of potential to the game industry

P.S. sorry for little necroing... but it needs a bump anyway
