### ISSUE TITLE
Please make the docs clearer on whether TCP ports need to be open for dat publishing

### ISSUE THREAD

**Issue by Michael-S** [beakerbrowser/beaker#836]
Hi Beaker Browser team,
If I create a page in Beaker Browser and I want it available to other people with the URL, do I need to allow incoming requests to my machine with port 8080? 3282?  Something else?

Even if the protocol uses some other mechanism and no ports need to be open, I think it would be helpful to state that fact in the README or other documentation.  If it's already in there, I could not find it with git clone + grep.

Edit: or is the assumption that any serious publishing will be done using the instructions at https://beakerbrowser.com/docs/tutorials/host-outside-of-beaker.html  and publishing inside Beaker Browser itself is only for rapid prototyping?

**Comment by pfrazee** [comment]
@Michael-S We do want publishing inside Beaker to be feasible. Do you have a firewall that needs to open specific ports? I haven't had any reports for needing to know the individual ports yet (usually device firewalls are per-app) so if you did, could you describe your setup so I know how to document for it?

3282 is the default port for listening to the swarm, yes.

**Comment by Michael-S** [comment]
I am sorry, I guess I'm approaching this from a power user perspective and not as a typical end user (and no disrespect or condescension intended towards typical end users).  I run Linux and set up my firewalls on my PCs and router to block all traffic except for the ports I explicitly open.  

If I was running Beaker Browser on Windows I suppose Windows would prompt me to allow traffic for it, and I'm less familiar with Macs but imagine they have a similar mechanism.  Plus, default UPnP settings on consumer routers would open the corresponding TCP port and set up port forwarding.  So everything would just work by default, which is exactly what we all want.

With that in mind, maybe this isn't something that needs to be in the documentation, because it's not a setting the great majority of Beaker Browser users need to worry about.   Should the issue just be closed?

**Comment by pfrazee** [comment]
@Michael-S No need to apologize, you're a power user and you needed that info. We should document it somewhere for other power users. Maybe a note in the readme?

**Comment by Michael-S** [comment]
Sounds good, thank you.

**Comment by pfrazee** [comment]
👍  We'll get it in the 0.8 release. Thanks for filing!

**Comment by pfrazee** [comment]
Going to keep this open as a reminder, thanks though.

**Comment by alexandre1985** [comment]
I use Linux iptables as firewall. What ports do I need to open in simple terms?
