### ISSUE TITLE
Allow to set home page

### ISSUE THREAD

**Issue by despens** [beakerbrowser/beaker#837]
It is possible only to set a background image for the page shown when beaker starts up, but not a URL. There also doesn't seem to be a command line option to load a certain page on startup. Would be a nice feature to  have.

Operation System: Linux
Beaker Version: 0.7.10

**Comment by pfrazee** [comment]
We'll get this on the roadmap!

**Comment by pfrazee** [comment]
This is done in the upcoming 1.0 release
