### ISSUE TITLE
Consider choosing different ports for ipfs?

### ISSUE THREAD

**Issue by jbenet** [beakerbrowser/beaker#84]
Operation System: all
Beaker Version: 0.3.0

I'm not sure this is a good idea. But perhaps beaker should set different ports for the ipfs api + gateway, so that they dont clash with local defaults? beaker should be hiding all the ports anyway so i dont think it impacts users? (im not sure)

**Comment by pfrazee** [comment]
That would allow 2 daemons to run at once, right? Other than overhead, that shouldn't blow anything up.
