### ISSUE TITLE
Support UTF-8 for markdown

### ISSUE THREAD

**Issue by Ravenbird** [beakerbrowser/beaker#845]
I'm experimenting with beaker and markdown. I noticed that the umlauts in Markdown documents which were saved in the formatting ISO-8859-15 are displayed correctly, those which were saved in the format UTF-8 but not.

I don't know if I did anything wrong. But so far it looks like the Markdown interpreter can't handle UTF-8.

**Comment by brechtpm** [comment]
This seems to be fixed on the 0.8 branch already: https://github.com/beakerbrowser/beaker/issues/831

**Comment by Ravenbird** [comment]
Perfect! Thank you! :-)

**Comment by pfrazee** [comment]
👍
