### ISSUE TITLE
Installing Beaker Browser on Gallium OS

### ISSUE THREAD

**Issue by mroberts1** [beakerbrowser/beaker#847]
Operation System: Gallium OS
Beaker Version: current

Hi, I'm trying to install Beaker Browser on Gallium OS, a lightweight Xubuntu distro optimized for Chromebooks. I initially got a module error saying that the electron-update module wasn't found;  then when I ran npm burnthemall for a reinstall I got a new error saying that the <gulp build> module was failing and that the problem was probably in the beakerbrowser package itself. My versions of Node.js and npm are up to date, so I'm not sure what else to do at this stage other than refer the matter to you.

**Comment by pfrazee** [comment]
Hi @mroberts1, sorry for the delay

That's unusual. Could you tell me your node and npm versions, and also share the error? (You might try burnthemall again.)

**Comment by brechtpm** [comment]
@mroberts1 Are you by any chance using Node 9.x on a 32bit system? 

I mainly work on a 32bit Linux system myself, and I often have trouble compiling native extensions against Node 9.x. For me just using Node 8.x solves most of these problems though.
