### ISSUE TITLE
Beaker crashes when typing in the developer tools console

### ISSUE THREAD

**Issue by poef** [beakerbrowser/beaker#848]
Operation System: Windows 10, Linux (Elementary OS 0.4.1)
Beaker Version: 7.11 (just downloaded)

When you open beaker and right-click inspect element, even on the beaker://start/ page, beaker crashes as soon as you try to type in the console. There might be a bug in the autocomplete code, but that is just conjecture.

**Comment by pfrazee** [comment]
That's a new one. We'll look into it, thanks for filing.

**Comment by DakshMiglani** [comment]
this is happening on windows.

**Comment by pfrazee** [comment]
@DakshMiglani try updating to the latest beta build. If you go into settings and click the try beta releases option, it'll do that. I would bet this was a bug in Electron that's been resolved in recent builds.

**Comment by DakshMiglani** [comment]
Confirmed, Fixed in latest beta build. @pfrazee please close this issue.

**Comment by pfrazee** [comment]
@DakshMiglani thanks for confirming
