### ISSUE TITLE
fallback_page in dat.json is lost on fork

### ISSUE THREAD

**Issue by poef** [beakerbrowser/beaker#849]
Beaker Version: 7.11

When you fork a site, beaker won't copy the value for fallback_page in the new dat.json.

We're trying to build a user friendly CMS system for dat/beaker. We've got it working pretty nicely, you can just fork a website and start editing it, except for the fallback_page. 

The user experience, especially for less technically inclined people, would be immensely improved if they only needed to fork the site and everything would work out of the box. Right now we need to explain that you'll need to find a dat.json file, open it in a text editor and add a specific line, without breaking the json syntax. I think this is likely too technical for most people.

To see an example of what we've got working, take a look at dat://spectral-auke.sharespace.nl/
Fork it, update the dat.json to add:

```
"fallback_page": "/index.html"
```

and you should be able to edit the forked site and save changes, add pages, etc. without needing any technical stuff.

**Comment by taravancil** [comment]
Thanks for reporting! This is fixed in the 0.8 branch
