### ISSUE TITLE
PDFs fail to download over dat://

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#853]
**Operation System**: macOS High Sierra 10.13.3
**Beaker Version**: v0.7.11 & v0.8

Currently when visiting a pdf in Beaker Browser via the `http://` or `file://` protocol, it downloads like expected. However, when you attempt to download it via the `dat://` protocol, you receive the following error: 

> **Download Error**
> The download of test.pdf was interrupted

This seems to be specific to PDFs. If I try to download other binary-like, beaker handles it just fine. Here's an example pdf you can try it out on:

**http test:** https://test-pdf-webdesserts.hashbase.io/test.pdf
**dat test:** dat://test-pdf-webdesserts.hashbase.io/test.pdf

**Comment by taravancil** [comment]
There's a bug in Electron with downloads over custom protocols. Paul submitted a PR a while ago and just added tests to that PR today, so hopefully that will help it get merged soon🤞

**Comment by pfrazee** [comment]
It's merged! Just need the next Electron release
