### ISSUE TITLE
Issues setting up beaker dev env

### ISSUE THREAD

**Issue by zeke** [beakerbrowser/beaker#856]
Operation System: macOS
Beaker Version: master branch

I have a fresh clone of this repo. I ran `npm install && npm start` and saw this:

<img width="532" alt="screen shot 2018-02-17 at 6 28 23 pm" src="https://user-images.githubusercontent.com/2289/36347636-e47f2522-1410-11e8-97a0-842aba90a3df.png">

So I ran `npm run build`, then saw this:

<img width="532" alt="screen shot 2018-02-17 at 6 28 52 pm" src="https://user-images.githubusercontent.com/2289/36347642-0217c90e-1411-11e8-8276-b68fd3039147.png">

Then I ran `cd app && npm install && cd ..` Same errors from `start` and `build` scripts.

Then `npm run rebuild && npm run start` and now I'm good.

So... let's document the right incantation in CONTRIBUTING.md. Does the following represent the current reality?

```sh
git clone https://github.com/beakerbrowser/beaker
cd beaker
npm install
npm run build
npm run rebuild
npm start
```

**Comment by zeke** [comment]
> we have a “building from source” section in the readme

Ah oops I jumped straight to the existing CONTRIBUTING.md and didn't bother looking in the README.

I see a few paths forward:

- Move the dev setup instrucutions from README to CONTRIBUTING, and add a link to the README

or

- Leave instructions where they are, and link to them from CONTRIBUTING

**Comment by pfrazee** [comment]
Ok should be much clearer now. Thanks!

**Comment by zeke** [comment]
Bravo! Grazie!
