### ISSUE TITLE
Auto-generated manifest.json has surprised users. Does something need to change?

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#86]
In dat sites, Beaker uses `manifest.json` to store metadata, such as the site's name and description. This file is generated automatically when you create a dat.

Seeing `manifest.json` surprised a user (https://github.com/pfrazee/beaker/issues/81#issuecomment-245026437).

Questions I have:

 - Is the existence of manifest.json a problem, or is it just surprising?
 - Should manifest.json be hidden, by default? In that case, should it be a .dot file?
 - Is the solution (also) to include an explanation in the UI?

**Comment by fredhampton** [comment]
I think it is surprising. I was showing my partner the new flow for adding and sharing files and when  the file was added my partner thought that something was wrong because the manifest file was there. Once I opened the manifest file I understood why it was there but I do not think non technical user will without an explanation.

**Comment by pfrazee** [comment]
Yeah, that makes sense. How does your partner feel about it, now that you explained what it is? For that matter, how do you feel about it? Does it bother you to see it? (I'm trying to decide whether to hide it, or even remove it if necessary.)

**Comment by fredhampton** [comment]
I think it should be hidden or removed. My partner understands what the file is but 
feels that it is possible that non technical users will become confused 

 

On September 7, 2016 at 6:45:32 AM, Paul Frazee (notifications@github.com) wrote:

Yeah, that makes sense. How does your partner feel about it, now that you explained what it is? For that matter, how do you feel about it? Does it bother you to see it? (I'm trying to decide whether to hide it, or even remove it if necessary.)

**Comment by pfrazee** [comment]
The manifest files are now hidden
