### ISSUE TITLE
Odd Back Button Behavior on Settings Page

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#868]
Beaker Version: 0.8 pre-release.2

![back-button-behavior](http://public-webdesserts.hashbase.io/weird-back-button-behavior.gif)

For most internal pages, if you navigate to them from say... the start page, you'll be able to get to use the back button to get back where you came from. However, on the settings page, even though the button indicates that there is previous navigation history, the back button does nothing.

**Comment by pfrazee** [comment]
We can fix this using `history.replaceState` on first load
