### ISSUE TITLE
0.8 Issue Template not working

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#869]
Beaker Version: 0.8 pre-release.2

If I create a new issue with the "Report an Issue" button it opens github with the following url: `https://github.com/beakerbrowser/beaker/issues/new?labels=0.8-beta-feedback&template=ISSUE_TEMPLATE_0.8_BETA.md`. The template seems empty and a label is never applied. For example: [this issue](https://github.com/beakerbrowser/beaker/issues/868) was created with the "Report an Issue" button.

**Comment by pfrazee** [comment]
Yeah we can't figure this out, because it's actually [there](https://github.com/beakerbrowser/beaker/blob/master/.github/ISSUE_TEMPLATE_0.8_BETA.md). Github

**Comment by paul90** [comment]
I'm also not seeing a template, or label, when visiting that link - though they are in the URL.

I think it may be that you need to create an 'ISSUE_TEMPLATE' subdirectory - see https://help.github.com/articles/creating-an-issue-template-for-your-repository/#adding-multiple-issue-templates

**Comment by taravancil** [comment]
@paul90 that worked! I read that doc but for some reason thought it would work if I put my issue template in the .github/ directory.

Still not sure why you two aren't seeing the label with that link. Works for both @pfrazee and I 🤷‍♀️
