### ISSUE TITLE
Library is currently a bit confusing

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#870]
Operation System: Mac OSX
Beaker version: 0.8 pre-release.2

Currently, If you navigate to the library page, you are shown all the sites you are currently seeding and are able to look at the files with one click. However, if you reseed sites often, most of these sites will end up not being sites you own. This is a bit confusing because I rarely want to look at the files of sites I don't own, I generally just want to _visit_ them, yet the only way to visit those seeded sites is two clicks away: **1.** click on the item in the library to view their files, and **2.** click on the dat url in the top right corner.

Once I became familiar with the new Library screen, I began to just treat it as "a place to go to view and edit sites I've created". However, by default, when I visit the Library I have to sift through seeded sites to find my personal sites. I found myself quickly building the habit of clicking "Your Archives" every time I hit the Library page.

Some possible improvements:

- Make "Your Archives" the default Library tab
- Anywhere there's a dat url on the Library page, I should be able to click it and go there.
- Sort the "All" page so that your archives are always on top, possibly with a seperator.
- Increase the size of each item in the list and provide large clickable action button/link for "Visit Site" and "View Files"
- Eventually allow users to manually sort their library how they want to.

Further thoughts:

This is more an observation than a recommendation, but it seems like the line between "bookmarks" and "library" is a bit blurry for me. One is a quick list of sites that I care about and the other is... a quick list of sites that I care about. They both have some form of site categorization, its just on one page I can easily view the site and on the other page I can easily view the site's files (s/can/can't/g). I think it would be interesting to see any attempt to merge the two. I like the idea of one day having something like the list of apps we have on our phones, only this time you made some of those apps. On the other hand, it also kind of feels like the current Library is essentially a view of the File System. Food for thought.

**Comment by taravancil** [comment]
@mekarpeles suggested this when we visited SF a while back, and he made such a compelling case that we've been on board with the idea since.

We spent about a half a day trying to figure out how we'd approach it, but we realized it was going to require quite a bit of work, and we couldn't justify doing the merge before putting out 0.8. Maybe 0.8.1.
