### ISSUE TITLE
Beaker Homepage bookmark points to http version of site

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#871]
Operation System: Mac OSX
Beaker version: v0.8 pre-release.2

On a fresh install the "Beaker Homepage" bookmark points to the `http://` version of the site even though of the other bookmarks provide the `dat://` version.

**Comment by pfrazee** [comment]
I'm not seeing this on a fresh install.

**Comment by pfrazee** [comment]
I'm going to close as can't reproduce unless somebody else runs into this.
