### ISSUE TITLE
Workspace URL Concerns

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#872]
Beaker version: v0.8 pre-release.2

As a continuation of the discussion we had in irc. I was a bit confused when I found out that my workspace url was `workspace://dusty-shop/`. As you said, this `dusty-shop` url is auto-generated and is intended as a fun way of naming your workspaces. Some of the concerns with this workspace naming scheme were:

1. Will people want to rename the workspace?
2. Rather than act as an easy way to remember the workspace, will this just be "something else to remember"?
3. Because it looks so much like a normal url, will people try to share it?

One alternative would be to use `workspace://${dat_hash}` instead. This has the advantage that if it is shared, the receiver of the shared url could at least be redirected to a view of the site's files (given it has enough peers).

This issue is intended as a place to continue that discussion

**Comment by pmario** [comment]
>1. Will people want to rename the workspace?

definitely

**Comment by pmario** [comment]
> ... One alternative would be to use `workspace://${dat_hash}` instead.

:/   Then the local workspace is "as unfriendly" as the dat hash. ... I personally prefer a "friendly" URL

`dusty-shop` is much easier to remember as a dat-hash

**Comment by taravancil** [comment]
> 1. will people want to rename the workspace?

We actually had this tool at one point. I forgot why we took it out, but we'll re-instate it. Super easy to do.

> 2. Rather than act as an easy way to remember the workspace, will this just be "something else to remember"?

This is still unclear to me. This question is a large part of why we put a beta release out, because we want to get a better sense of how the workspace tool feels to people who haven't been thinking about it for months :smile:

**Comment by taravancil** [comment]
Update: I just added a tool in the library settings tab to edit the workspace name

**Comment by davidar** [comment]
Looks like the input needs to be validated - if you enter a name with fullstops the change is accepted, but next time you go to the library page the content of all of the tabs is replaced with an "Error: Invalid workspace name" message (making it impossible to fix from the UI).

**Comment by pmario** [comment]
Especially for windows `.dirname` may be a problem. ...

**Comment by pfrazee** [comment]
@despens We ended up agreeing that workspace URLs were hard to understand, and we decided to remove them entirely https://github.com/beakerbrowser/beaker/pull/954. I think we'll get this out as a new beta this week.

I made a video to explain the changes [here](https://www.youtube.com/watch?v=ZMkF0i_bOxQ&feature=youtu.be)

Closing this issue!
