### ISSUE TITLE
Auto Publish changes to a workspace

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#873]
Beaker version: v0.8 pre-release.2

It would be nice if there was a way to "auto-publish" file changes, similar to how dat normally functions. You could technically do this right now by creating the dat outside of Beaker Browser and using dat normally, but I would have to know what the dat protocol is first. I could see this feature manifest in several ways but I think the ultimate desire is this: I want to have a folder somewhere on my system, that Beaker rehosts as a normal dat, that I can then quickly point friends to. A folder for sharing screenshots might be a good example.

**Comment by taravancil** [comment]
Do you mean like a way to toggle the workspace publishing flow on/off?

**Comment by webdesserts** [comment]
@taravancil maybe, the problem there is that if we toggled off the worspace workflow, you would still not be able to edit/remove/move files at will on the "Files" tab. What I'm really asking for is a way for people to use dat as it was originally inteded, as a p2p "dropbox". I think this brings up some questions of scope, but I think that as Beaker continues to improve, users will hear about Beaker first, and dat second (or maybe dat will just be an implementation detail).

Only a select few people can take advantage of Beaker's ability to quickly publish a website. However, everyone I know could take advantage of the ability to quickly publish a folder. The dat project does have their own "Dat" app that does this, but there's no tie in with Beaker. Beaker has the "share files" command, but it's more of a "one and done" share because it operates seperately from the user's file system and consiquentially loses all of its advantages. 

This mostly concerns me because even if you had use the "Dat" app to publish, I would probably use Beaker to browse and download those files. Browsing those "dat folders" through Beaker allows me to take a sneek peek without permantantly downloading those files to my system. It would also allow me to grab the one specific file that I need. If I'm already using Beaker to browse those folders, why not also use beaker to publish them as well?

I would love to see something along the lines of a "Publish folder" or "create Public Folder" command that allows users to select a folder on their system and publish it, just like they could via the Dat app. This could manfest as a "tie-in" with the Dat app where clicking the link opens the Dat app or prompts you to download it. Though I think the Dat app is small enough that I'd also consider the possibility of Beaker having an equivilant built in. I'm sure the dat team would have some opinions here.

This could become confusing however with workspaces being "fake dats" and these published folders being "real dats" that both live on your system. You could also argue that both of these use cases could take advantage of "paused syncing" like we have with workspaces. This conversation could also open up the can of worms of what's the long term vision of Beaker's relationship with the native FS. Is Beaker going to build on top of the native fs or replace it? Where do we draw the line? etc.. etc..

**Comment by taravancil** [comment]
If I'm understanding what you're asking for, we actually do have that!

Dropdown menu -> Create new -> From folder

**Comment by pfrazee** [comment]
> Dropdown menu -> Create new -> From folder

Yeah I don't think it's too much of a stretch to have that do auto-publishing from the workspace, so the question is really just how we build the UI and flows around it.

**Comment by taravancil** [comment]
Yeah if any of the flows were to do auto-publishing from the workspace, I think we'd want that to be a toggeable option for every workspace. Otherwise the user would need to keep track of which flows auto publish and which ones don't.

**Comment by webdesserts** [comment]
@taravancil @pfrazee Ahh! I missed, that. But right, it doesn't auto-publish automatically, so it's not quite there. This seems heavily related to https://github.com/beakerbrowser/beaker/issues/883

**Comment by taravancil** [comment]
Yeah, we'll have to think about how to handle auto-publishing of workspaces. I'm starting to think it could be pretty useful.

**Comment by webdesserts** [comment]
I think "Create New From Folder" is a bit confusing. Maybe "Create New Public Folder" or "Create New Shared Folder"?

**Comment by webdesserts** [comment]
I think I'm mostly excited for the possibility of `~/Public` folders actually being _useful_ for once.

**Comment by taravancil** [comment]
Eh, public and shared aren't accurate though. Public might make me think "The whole can see this" and shared would make me ask "Who is this shared with? The whole world?"

**Comment by webdesserts** [comment]
"Create New Dropbox" 🙃

You're right though, the naming is a bit difficult. You could say "Share Folder", but that doesn't imply that you're sharing a "live view" of that folder and we already have "Share Files". You could say "Shareable Folder", but ugh. It seems like this is a reacurring issue really. It would be nice if it could fit in the current naming scheme:

- web app
- web site
- web ________

But yeah "web folder" is also a little ugh as well. It would be nice if we could just do:

- web app
- web site

Where "web app" is anything that has an index.html and a "web site" is anything that just has files, but Zeldman would probably burn me alive in my sleep for recommending that.

**Comment by webdesserts** [comment]
Sky Drive -> Google Drive ->  Web Drive 🤔?

**Comment by pfrazee** [comment]
Maybe something like autoshare or autopublish. Im not worried. We’ll figure it out.

**Comment by pmario** [comment]
@webdesserts Is this issue (OP) still valid? The mechanism has changed quite a bit.

**Comment by webdesserts** [comment]
Yeah, the current implementation pretty much resolves all my concerns. I'll close this unless y'all can think of any other reason to leave this open.

cc @pfrazee @taravancil
