### ISSUE TITLE
Fork archive screen is too small

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#874]
Operation System: Windows 10
Beaker version: Beaker v0.8.0-prerelease.2

When forking an archive in Beaker, the popped up window is a bit too small so the buttons at the bottom are clipped.

As a workaround it can be resized to be the correct size, but I expected it to fit.

This problem was also in 0.7.

![fork screen too small](https://user-images.githubusercontent.com/10849937/37510198-ab64358a-28fa-11e8-94ac-456cdfbf5d79.PNG)

**Comment by taravancil** [comment]
Ah yeah, we wrote code to automatically resize those windows, but it looks
like it’s not working on your email platform. Thanks for the catch!
