### ISSUE TITLE
Favicon list is very limited, maybe add an upload/choose button?

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#875]
Operation System: Windows 10
Beaker version: Beaker v0.8.0-prerelease.2

The favicon selection screen has quite a limited selection, so I expected a button to add my own icon and use that instead.

**Comment by taravancil** [comment]
Good suggestion! We’ll think about that.

**Comment by Septimus** [comment]
Working on this now.

**Comment by Septimus** [comment]
Related PR #1215

**Comment by pfrazee** [comment]
Closed thanks to @Septimus
