### ISSUE TITLE
What is the favicon for? The library? Or the site?

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#876]
Operation System: Windows 10
Beaker version: Beaker v0.8.0-prerelease.2

This applies to a site which has all its files in a directory and uses the webroot directive in dat.json.

After adding a favicon, a new favicon.ico file popped up in my library in the root. However, my site is under /public within the archive (using the webroot directive in dat.json). So, the only place the favicon is used is in the library and not in the website, because the website expects it under /public

The explanation link goes on to explain how a favicon is used in a website, but I actually like the current setup - I have a favicon for my site, and possibly another one to find the library.

If the aim is to add/replace the favicon for the site, then it should follow the webroot directive in dat.json.

**Comment by taravancil** [comment]
The favicon is for the website, just like a traditional website works. We use it in the Library as well to make it easier to distinguish between Library tabs.

We probably won't enable multiple favicons (this is just meant to be a simple helper tool), but we should respect the webroot specified in dat.json.
