### ISSUE TITLE
If adding a favicon is easy, removing it should be too.

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#877]
Operation System: Windows 10
Beaker version: Beaker v0.8.0-prerelease.2

Its quite easy to add a favicon to a project now, but I had to guess that clicking the button actually just placed a file in my archive and that I could delete that file.

I would expect a 'remove the favicon' button (somewhere in the selection list popout?) to revert it back to its original state without a favicon.

**Comment by pfrazee** [comment]
Done!
