### ISSUE TITLE
Archive history button should be named

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#878]
Operation System: Windows 10
Beaker version: Beaker v0.8.0-prerelease.2

The archive history button should have a named title instead of just an icon, to make it more clear what the icon does. I did discover what it was for after clicking on it, but I could not have guessed it by just looking at the icon.

![archive history button should be named](https://user-images.githubusercontent.com/10849937/37510764-88fc82c0-28fc-11e8-8451-5f84b74f8ae6.PNG)

**Comment by pfrazee** [comment]
We've decided to go with an icon and tooltip (on hover) for now
![screen shot 2018-09-04 at 4 01 16 pm](https://user-images.githubusercontent.com/1270099/45057659-cf3a0a00-b05b-11e8-8593-7d200175bbd1.png)
