### ISSUE TITLE
Learn more link for hashbase is broken

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#879]
Operation System: Windows 10
Beaker version: Beaker v0.8.0-prerelease.2

The 'learn more' link for hashbase looks like it points to #todo. I expect it should point to a link on hashbase with more information.

![broken learn more link](https://user-images.githubusercontent.com/10849937/37510814-b519f928-28fc-11e8-8b33-a8408e6930a3.PNG)

**Comment by taravancil** [comment]
Yeah that’s a todo for the final release. We’re overhauling our docs and
guides right now, so some of the things we’ll link to aren’t written yet :)

**Comment by taravancil** [comment]
Closing this since I have it tracked as a todo elsewhere.
