### ISSUE TITLE
Tab separator shape is unusual

### ISSUE THREAD

**Issue by staltz** [beakerbrowser/beaker#881]
Operation System: macOS 10.12.6
Beaker version: 0.8 beta

I noticed a small *curve* near the top end of the tab separator.

<img width="165" alt="screen shot 2018-03-16 at 13 21 06" src="https://user-images.githubusercontent.com/90512/37518299-45a00be8-291d-11e8-8aee-30bf16f6bc88.png">
<img width="27" alt="screen shot 2018-03-16 at 13 21 12" src="https://user-images.githubusercontent.com/90512/37518300-45be162e-291d-11e8-87f7-ff4dfa8234eb.png">

Is this intentional? Looks funny, specially before I zoomed in to figure out why it felt funny.

By the way, great job so far!

**Comment by taravancil** [comment]
Not intentional. Thanks for the catch!
