### ISSUE TITLE
Unable to compile source in Linux

### ISSUE THREAD

**Issue by chakrihacker** [beakerbrowser/beaker#882]
Operation System:Ubuntu
Beaker version:0.8.0 pre release 2

Error: throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

I tried torching node_modules it didn't work

**Comment by pfrazee** [comment]
Did you try running `npm run burnthemall` ?

**Comment by chakrihacker** [comment]
yes, sorry for the late reply I forgot to comment

**Comment by pmario** [comment]
I did a test with: master 774aca080c835f4

 - ubuntu 17.10
 - node v8.9.1
 - npm 5.6.0
 - completely deleted node_modules 
 - run: `npm i`
 - run: `npm start` -> no problems 

did the same thing with `tests` directory

 - 18 passed
 - 10 failed

If you need more info about the test run, let my know.

**Comment by pfrazee** [comment]
@pmario Yeah those tests wouldn't explain why electron fails to install though.

@chakrihacker Try out some of the advice in https://github.com/electron/electron/issues/8466. What version of node & npm are you using?

**Comment by chakrihacker** [comment]
node - 8.5.0
npm - 5.5.1

and will try beaker after some time
