### ISSUE TITLE
Workspaces created for data dats are a problem

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#883]
Dats don't always need workspaces (especially data dats).

 - [x] We should remove the autocreation of workspaces for the 0.7 migration, because the mechanics changed. Dats previously had workspaces created automatically, now they don't (and shouldn't).
 - [ ] Should we always prompt people to create workspaces?
 - [ ] Should it be possible for a Dat to indicate that it's a data dat and thus shouldn't have a workspace?
 - [ ] Or, perhaps dats created by websites dont do the "Getting started" flow?

**Comment by pfrazee** [comment]
Observation from IRC: having a workspace, but not knowing its purpose, is actually really confusing to people. We optimized very heavily to make it easy to create workspaces, because we were thinking about the "create site/app" flows. In the case of data dats, we might need to optimize heavily in the exact opposite direction.

**Comment by pmario** [comment]
> Should it be possible for a Dat to indicate that it's a data dat and thus shouldn't have a workspace?

What is so special about a "data dat" that a user should avoid to duplicate it?

**Comment by pfrazee** [comment]
Workspaces are intended for when you want to edit the files prior to publishing them. We can assume the users want to do that when they create a new website; if it's a data dat, there's an app (ie fritter) writing files directly and you may not want a workspace. It's not that you'd *never* want a workspace, it's that users don't need to be prompted to make one as the library-view currently does.

**Comment by pmario** [comment]
ok. I see.

**Comment by pfrazee** [comment]
Closing, we removed workspaces
