### ISSUE TITLE
Invalid workspace name

### ISSUE THREAD

**Issue by sull** [beakerbrowser/beaker#887]
Operation System: OSX 10.13.3
Beaker version: 0.8.0 pre

Initial site creation, viewing preview workspace page, clicked "view the source"

<img width="479" alt="screen shot 2018-03-16 at 2 18 01 pm" src="https://user-images.githubusercontent.com/6834/37537762-eb7dda8e-2924-11e8-900b-5ccf5f7ead2b.png">

<img width="558" alt="screen shot 2018-03-16 at 2 18 15 pm" src="https://user-images.githubusercontent.com/6834/37537843-21994680-2925-11e8-9dde-8054706d84a7.png">

**Comment by taravancil** [comment]
Well that's new! Let me see if I can reproduce...

**Comment by taravancil** [comment]
Oh right, duh. That's because I use window.location to form that link. I'll fix that ASAP. @pfrazee is going to cut another release this afternoon. Thanks for the catch!

**Comment by sull** [comment]
yeah minor bug just a heads up. ;)
