### ISSUE TITLE
Improve tab controls

### ISSUE THREAD

**Issue by taravancil** [beakerbrowser/beaker#894]
We need to improve the tab controls when there are a bunch of tabs. This is non-trivial to do well, and is a longstanding issue, just adding this as a formal reminder and place for discussion.

![dyhwiyhxcae4ash](https://user-images.githubusercontent.com/7584833/37561156-83a34880-2a15-11e8-8147-f49482a35fe1.jpg)

**Comment by noformnocontent** [comment]
maybe just hide the close button if tab-bar tabs width is less than ~240px?
firefox does that:
![ok-amount-of-tabs](https://user-images.githubusercontent.com/23745012/37561259-826e0812-2a4a-11e8-83bf-518f4604e657.png)
![too-many-tabs](https://user-images.githubusercontent.com/23745012/37561260-85a84d26-2a4a-11e8-847a-9584660c39c0.png)

**Comment by DTV96Calibre** [comment]
Looking at Chrome and Firefox, I kinda like the way Firefox handles crowded tabs:
![image](https://user-images.githubusercontent.com/10363350/37561235-100727f6-2a20-11e8-8a5a-558e6748b5d2.png)

- Tabs shrink in width after there are too many to show without scrolling
- Tabs have a minimum width before scrolling is enabled
- Scrolling can be done with the mousewheel or buttons to the left and right of the tabs

**Comment by despens** [comment]
Would be great if tabs could be dragged from one Beaker window into another, too.
