### ISSUE TITLE
Annoying text selection behaviour in the address bar

### ISSUE THREAD

**Issue by instantname** [beakerbrowser/beaker#896]
Operation System: Windows 7
Beaker version: v0.8.0-prerelease.3

When I click on the text in the address bar (after clicking on things outside the bar), the whole address gets selected. Good! However, when I then click again to place the cursor somewhere in the text, that doesn't work and all the text remains selected. The same issue arises when you try to select part of the address by first clicking on the text, and then click without releasing to start a selection.

I think a behaviour similar to other browsers would be better:
- Text selection that behaves as in usual text fields
- Except: when the address bar gets the focus via a click, the whole text should be selected.

**Comment by DTV96Calibre** [comment]
I seem to be able to replicate this (Windows 10) by clicking in the white space between the text and the line immediately below it. Clicking on the actual text doesn't cause me issues though.

**Comment by pfrazee** [comment]
Yeah this has been annoying me too. What I tend to see is, if I'm trying to select a region, it'll select from the beginning of the bar to the point that I started dragging (rather than starting to select from where I started dragging).

I'll try to get this in our TODOs for the 0.8-final release. PRs welcome as well!

**Comment by pfrazee** [comment]
This one was tricky but I think I got it. The URL bar selection now behaves like you'd expect (like other browsers). One click, select all. Double click, select word. Drag, select custom region.
