### ISSUE TITLE
import files breaks folder hierarchy

### ISSUE THREAD

**Issue by zamrokk** [beakerbrowser/beaker#897]
as in the title

After importing the root folder, I have all my files "flat" on the website

**Comment by pfrazee** [comment]
Right, so you imported a set of files and folders, and all the files inside the folders were pulled out?

**Comment by zamrokk** [comment]
i selected all files/folders from the root folder and it has been flatten.
When I did it folder by folder, no problem. The website works here :
dat://426c383f2968f5b97d61573c75f06529a4c77186d5b37f6c5095a00488574bdd/

2018-03-19 14:45 GMT+01:00 Paul Frazee <notifications@github.com>:

**Comment by pfrazee** [comment]
Yeah, ok we'll get that fixed.

**Comment by pfrazee** [comment]
What operating system are you using?

**Comment by pfrazee** [comment]
Yeah I'm having trouble reproducing this issue. Can you describe it in full detail for me? What tool you're using, what you expect to happen, etc? A recording would be useful.

**Comment by zamrokk** [comment]
Mac os high Sierra

Select all files from a directory

Le ven. 23 mars 2018 à 23:38, Paul Frazee <notifications@github.com> a
écrit :

**Comment by pfrazee** [comment]
Yeah I tried that and couldn't reproduce it, so I need more information. Can you step me through the entire process, from starting beaker to the end?

**Comment by zamrokk** [comment]
It is what I did. If you could not reproduce it. You can close it. No
worries

Le sam. 24 mars 2018 à 16:57, Paul Frazee <notifications@github.com> a
écrit :

**Comment by pfrazee** [comment]
I'm just trying to make sure I understand the issue. We have multiple file-importing tools, and I may be testing the wrong one.

**Comment by zamrokk** [comment]
It is through the bearer browser file uploader

Le sam. 24 mars 2018 à 22:29, Paul Frazee <notifications@github.com> a
écrit :
