### ISSUE TITLE
Doesn't open link first time if beaker is not running already

### ISSUE THREAD

**Issue by mblarsen** [beakerbrowser/beaker#903]
Operating system: macOS High Sierra 

This is:

- [x] a bug
- [ ] general feedback

Exepcted:

As the default browser it a system request to open a link should open the browser app then load the link.

What happens:

If the browser is closed and you click some link somewhere, e.g. in my code editor it opens the browser, however, it doesn't open the link.

If I click the link again the an new tab is opened in Beaker with that link. This is what I expected to happen the first time around.

**Comment by pfrazee** [comment]
Thanks for reporting! We'll check into that.

**Comment by pfrazee** [comment]
Got a fix tested and committed, thanks again for reporting

**Comment by mblarsen** [comment]
Cool, thanks 👍

**Comment by DTV96Calibre** [comment]
Was the fix tested on Windows? I'm using a build from the latest source and it seems to be broken (on Windows)

**Comment by pfrazee** [comment]
Are you sure your custom build was being used? On OSX it was tricky to verify this without doing to full install flow, I had to use `open -a $CUSTOM_BUILD dat://.../` to specify which version to open with.

I'll double check after release to be sure.

**Comment by DTV96Calibre** [comment]
I had built the installer and installed over the existing beta install. I pulled the latest from master just now and rebuilt and installed and the most recent commit fixing data: urls to be treated as urls seems to be in effect (I generated a data: url and beaker uses it as a url instead of search it as text) but beaker still doesn't load the link that opened the browser.

**Comment by pfrazee** [comment]
Ok thanks, good way to check that. I'll do some windows testing.

**Comment by pfrazee** [comment]
Fix pushed 57615ff77a256e810668122ec1dd2bb8629ef5a9
