### ISSUE TITLE
Site Title / Favicon POST btn mixup

### ISSUE THREAD

**Issue by mediacobbler** [beakerbrowser/beaker#906]
Operation System:
Beaker version:
![beeker_ui_posttotitlefield_cr](https://user-images.githubusercontent.com/1202223/37745449-482526aa-2d4b-11e8-9df8-d03013d58974.png)

just a little something that had me going in circles. prolly a quick fix. cheers!

**Comment by taravancil** [comment]
Thanks for the feedback. We'll look into how to make that more clear.

**Comment by pfrazee** [comment]
This has been reworked, let us know if you still find it confusing
