### ISSUE TITLE
windows: tests fail -12 passed, 19 failed - prerelease 3

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#908]
Operation System: Windows 10
Beaker version: prerelease-3 1f29d3538cb4228a89a645d5b114cad6835cefdc

tests
 - 12 passed
 - 19 failed

 - node version 8.9.3
 - npm version 5.5.1
 - powershell  5.1.17123.1
 - I did start form `git clone <repo>`
 - `npm i`
 - `npm run rebuild` .. still needed
 - `npm start` -> OK

in tests dir
 - `npm i`  -> went ok
 - `npm test`

If you need more info, let me know.

**Comment by pmario** [comment]
testrun with ubuntu: https://github.com/beakerbrowser/beaker/issues/882#issuecomment-375210186

**Comment by pfrazee** [comment]
Ok, I rewrote our test runner and fixed some path normalization issues, and now I get all tests passing. Reopen if you find otherwise, and thanks for reporting!

**Comment by pmario** [comment]
62 passed
  2 skipped

looks good now win10
