### ISSUE TITLE
Image preview in library breaks when web_root directive is set in dat.json

### ISSUE THREAD

**Issue by ylebre** [beakerbrowser/beaker#909]
Operating system:
Windows 10, Beaker v0.8.0-prerelease.3

This is:
- [x] a bug
- [ ] general feedback

I'm using the web_root directive in dat.json in my setup. When I open the site in the library and browse to an image within the site, it will result in a broken image:

![image](https://user-images.githubusercontent.com/10849937/37770157-bd4a67fa-2dd3-11e8-9416-22b9d7a9f405.png)

It looks to me as if the image src url points to /public/imgs/... while it should be pointing to /imgs/... instead.

As a bonus: the 'open file' link also points to the wrong url, but that probably uses the same URL.

**Comment by taravancil** [comment]
Yeah it looks like we're not respecting the web_root. Thanks for reporting!

**Comment by pfrazee** [comment]
🤦‍♂️
