### ISSUE TITLE
Intro Tour: second image has a "warning" color

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#911]
Operation System: all
Beaker version: prerelease 3

I personally like the color of the second Tour dialog. 

The only problem I had the very first time, when I saw it. ... I was "alerted" ... uuups I have done something wrong. ... because of the "red-ish" color. .. 

Imo it should be "different to red"

![02-tour-image_](https://user-images.githubusercontent.com/374655/37774625-084275a6-2de1-11e8-8f69-65627a88e468.gif)

**Comment by todrobbins** [comment]
I see it as more of a pink, but I agree with @pmario.

**Comment by pmario** [comment]
>I see it as more of a pink, but I agree with @pmario.

:) .. As I wrote, it was only the very first time I saw it. ... The first dialog is blue. Then I clicked "next", and what I saw was a dialog with an "alert" color. .. So I thought, I broke it ... With the second "look" I saw, that it still is the intro with a new color. ...

**Comment by pfrazee** [comment]
Oh yeah that's a shame, it's a beautiful color but I can see why that'd be confusing.

**Comment by pfrazee** [comment]
We removed this screen because people found it confusing in general
