### ISSUE TITLE
"Create from folder" autopublishing can cause problems

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#917]
When you create a new dat "From folder", it automatically publishes the files to the dat for convenience. While that's nice, the user may need to review before publishing for two reasons:

 - There may be secrets in the folder which need to be datignored
 - There may be large files/folders (eg node_modules) which need to be datignored

So we need to review whether automatically publishing is a good idea

**Comment by joehand** [comment]
I've been working with this and Enoki panel. Definitely some confusion around it:

* I can't tell if updates to the folders are published ( I wasn't sure if it was a one-time import or something that happens automatically).
* Enoki panel writes to archive but that doesn't seem to write back to the folder
* Got very confused with the workspace and conflicts and what was happening where (changes were coming both from the folder and from Enoki panel)
* I created from the same folder a few times. I'm not sure if when I delete it from my library it'll delete my folder (see screenshot).

<img width="798" alt="screen shot 2018-03-26 at 10 19 26 am" src="https://user-images.githubusercontent.com/684965/37921640-40a1ebec-30df-11e8-9c64-aae027fa8054.png">

**Comment by pfrazee** [comment]
@joehand those are all UX issues but not 100% related to this issue.

 - The Enoki panel issue is known. The problem is that Enoki doesnt have a way to write to the workspace yet. We've got plans to solve that in the API layer before 0.8 final
 - Deleting a Dat/Workspace from Beaker doesnt delete the folder, so no need to worry about that

**Comment by pmario** [comment]
Is this still an issue? ... Latest UI changes from 2018.08.31 seem to have fixed this one?

**Comment by pfrazee** [comment]
Almost! We have the tools to fix this but I haven't tested the flow yet. Let me take a pass at it and make sure it feels good. (Thanks for bumping.)

**Comment by pfrazee** [comment]
Sites created by "From folder" now have preview-mode enabled by default. This will give users a chance to review the files before they're published, thus solving our problem.

Closing!
