### ISSUE TITLE
Question: How do I link to a snapshot of a site?

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#920]
I'd like to link to a specific version / snapshot of a Dat archive.

**Comment by joehand** [comment]
Hi @aaronshaf! You can add a `+12` to the Dat link, where `12` is the version:

```
dat://datproject.org+12/
```

**Comment by pfrazee** [comment]
@aaronshaf if you go to the library view of a website and click on the box icon above the files, you'll get a dropdown of the history and you can find snapshot links there too.

Eventually Dat will get the ability to label versions and we'll add more powerful UI tools for it.
