### ISSUE TITLE
first click on reordered bookmarks opens "old" link

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#924]
Operation System: win10
Beaker version: prerelease 4

to reproduce: 

 - open new tab
 - take the very last bookmark and 
   - drop it at the very first position top left
 - click any other bookmark to open it
 - It will open an "old" link

**Comment by pfrazee** [comment]
Whoops, yes you're right. I blame... our cat sasha 🐈 I'll reprimand her and get it fixed

**Comment by pfrazee** [comment]
Fixed in master

**Comment by pmario** [comment]
:) .. cool new stuff. grats!
