### ISSUE TITLE
Changing the favicon from Settings: Tab leads to a confusing workflow

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#925]
Operation System: win 10 
Beaker version: prerelease 4

To reproduce

 - open a library, that has an active workspace.
 - make sure that workspace is published
 - make sure the dat has a favicon
 - make sure the favicon is the same in dat:// and local workspace
 - open Settings tab
 - change favicon
 - Select the Workspace tab
    - It shows "1 modification"
 - Local preview shows the "old" favicon -> OK
 - "Publish All" ... will publish the "old" favicon -> ISSUE
 - "Revert All" ... will activate the "new" favicon -> ISSUE

I know, that's technically it is ok. ... But it's confusing for the user.

**Comment by pfrazee** [comment]
I'll need to check into this but it may actually be a bug. Our policy is to update the workspace and the published dat at the same time when settings are changed.

**Comment by pfrazee** [comment]
Did some testing, happens in Windows but not OSX. Diagnosing now!

**Comment by pfrazee** [comment]
Good old path normalization solved it
