### ISSUE TITLE
request: more visual "differences" between DAT:// and workspace: tabs, if they are not selected

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#926]
Operation System: win 10
Beaker version: prerelease 4

If tabs are selected, there is a good visual difference between dat:// page and workspace ... __but__ if a new tab is active there are 2 identical tabs

New Tab ... The 2 open tabs look identical, but they are not!

![05-new-tab-visual](https://user-images.githubusercontent.com/374655/38030141-18a97348-3298-11e8-855c-ba67ed77790a.gif)

## requested:

![05-new-tab-visual_](https://user-images.githubusercontent.com/374655/38030645-74e5a9a0-3299-11e8-96bf-313dc064207e.gif)

or something similar

workspace selected -> OK

![03-workspace-visual](https://user-images.githubusercontent.com/374655/38030097-f4dc3144-3297-11e8-9d0e-bfc07fd9b243.gif)

Dat selected -> OK

![04-dat-visual](https://user-images.githubusercontent.com/374655/38030083-eceeef6c-3297-11e8-8117-90fe2bc64a48.gif)

**Comment by pfrazee** [comment]
Oh yeah that's an interesting idea, I'll discuss it with @taravancil. Thanks for filing it.

**Comment by pmario** [comment]
Yea. ... The tab UI is very "minimalistic" now. .. So it's hard to place a visual indicator, without ruining the design.

**Comment by pfrazee** [comment]
Solved: we got rid of workspaces
