### ISSUE TITLE
seeding info can only be seen at 1 place ... at least I didn't find it

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#928]
Operation System: win 10 & Ubuntu 17.10
Beaker version: prerelease 4

When I do enable seeding for a remote dat:/.. from the URL it looks like this: 

![beaker-seed-from-url](https://user-images.githubusercontent.com/374655/38079286-d3476c2c-333e-11e8-9d62-12cb7075d25b.png)

That's ok.... but this info can't be found anywhere else. 

I did expect the info to be at: Network   or   Info tab in the Library view

![seeding-info-expected](https://user-images.githubusercontent.com/374655/38080183-07e7dd5c-3341-11e8-8b5d-909b833f2b89.gif)

**Comment by pfrazee** [comment]
Yeah that's been on our TODOs

**Comment by pfrazee** [comment]
This has been added to the network tab

**Comment by pmario** [comment]
looks good :)
