### ISSUE TITLE
Behavior on "make copy"

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#929]
Currently when you make a copy of a dat site using the URL bar's page menu, it automatically redirects you to the library interface. We made that decision for two reasons: 

 1. Redirecting to the live instance of the copy might be unclear. The URL would be the only thing that changes, which is a bit too subtle.
 2. It's likely that you'll want to start editing the site, and the library is the place to do that!

However, I've noticed on more than one occasion that making a copy is being used to just create a writable version of the site, so that the app can self-modify with its own interfaces ([example](https://twitter.com/YvoBrevoort/status/979249985622609920)).

My thought- perhaps, instead of redirecting to the library, we redirect to the site, but add something to the URL bar which indicates your ownership, similar to the workspace's path badge?

**Comment by ylebre** [comment]
A possible approach could be to just give an indication/popup screen ('your copy is ready!') with links/buttons to either option.

**Comment by asteres** [comment]
Is it possible for more than one machine to own a url?

**Comment by pfrazee** [comment]
@asteres we're working toward that
