### ISSUE TITLE
File drag / drop bug

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/beaker#931]
Operation System: Ubuntu with i3wm
Beaker version: prerelease.1

Dragging a file onto a page most of the time works, but when dragging it out or moving it crazy on the page, the page crashes. It goes black and the console says "DevTools was disconnected from the page". It only happens on ```dat://``` sites and never on ```http://```. 

Does this only happen to me?

**Comment by pfrazee** [comment]
Sounds like an electron bug. It might be fixed in the latest builds because we upgraded electron (and thus chromium).

**Comment by kodedninja** [comment]
Allright, thanks! Waiting for a Linux build then :smile: lol

**Comment by pfrazee** [comment]
Haha yeah, I'll jump on my linux box in a bit to fix some bugs and I'll cut a build then

**Comment by pfrazee** [comment]
Linux build is out now

**Comment by kodedninja** [comment]
Thanks @pfrazee, you're the best! :smile:
