### ISSUE TITLE
Expose DatArchive to WorkerGlobalScope

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#932]
Operating system: Mac OS X

This is:

- [ ] a bug
- [x] general feedback

It looks like `DatArchive` is currently inaccessible from the [WorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope). I could imagine that someone might want to someday offload some of the heavier io work to a web worker and right now they would have to write a DatArchive "shell" that posts requests to the main thread.

---

After a quick look through the electron documentation, I'm not sure if this is currently possible? Also one counter argument against this is that as of right now I have complete control over what type of access my worker has to the DatArchive. If I want the worker to only have read access I can limit that in the API. This is great when using Web Workers as a sandbox like I am, but probably not-as-great when using web workers as an extension to the main program (which I assume will be the main use case).

**Comment by pfrazee** [comment]
This is related to https://github.com/beakerbrowser/beaker/issues/863

**Comment by pfrazee** [comment]
Waiting on https://github.com/electron/electron/issues/12505

**Comment by pfrazee** [comment]
Word on the street is that this isn't going to be easy to implement in Electron. The recent Electron feature doesn't add support for iframes or workers. This may be a long way off.
