### ISSUE TITLE
Can't toggle to fullscreen mode

### ISSUE THREAD

**Issue by UgoTurner** [beakerbrowser/beaker#933]
Operation System: Linux (Ubuntu 16.04.4)
Beaker version: 0.7.11

Hi ! Is it possible to show the content of a page in fullscreen mode ? I've tried the Chrome shortcut `F11` (or `Fn+F11` on my laptop) but nothing happens.
Am I missing something (another shortcut/button somehere) or it's not implemented yet ?

**Comment by pfrazee** [comment]
Yeah we have fullscreen mode implemented when apps ask for it, but not as something users can do. We should add that.

**Comment by pfrazee** [comment]
I was able to do this using `document.documentElement.webkitRequestFullscreen()` in the web contents of the active page. The trouble is, the current fullscreen rendering doesnt provide any way to see other tabs. That's fine when it's a fullscreened video but not for fullscreen browsing. This will need more work.

**Comment by jraspiprojects** [comment]
You could attach a keybinding to f11 which would execute <code>document.documentElement.webkitRequestFullscreen();</code> and by the way, if you are in full screen in chrome, you can't switch to other tabs execpt with Ctrl+Tab

**Comment by pfrazee** [comment]
Done
