### ISSUE TITLE
New tab search bar doesn't work

### ISSUE THREAD

**Issue by dangreco** [beakerbrowser/beaker#934]
Operating system: Ubuntu 17.10 x86_64, Kernel 4.13.0-37

This is:

- [x] a bug
- [ ] general feedback

The search bar on the new tab / start page does nothing on enter or on click.
Input on the bar throws an uncaught error:

> Uncaught (in promise) Error: SQLITE_ERROR: duplicate column name: pinOrder
    at onUpdateSearchQuery (main.js:1010)
    at onInputSearch (main.js:998)

Hitting enter throws this error:

> Uncaught TypeError: Cannot read property 'targetUrl' of undefined
    at onInputSearch (main.js:978)
onInputSearch @ main.js:978
setTimeout (async)
delay @ main.js:1248
yo.update.yo @ main.js:1125

**Comment by pfrazee** [comment]
I screwed up the rollout of the last DB update. Basically a fresh install doesnt set the schema version to latest, so an incremental DB update is being applied that doesnt need to be (an ALTER TABLE which adds the `pinOrder` column).

Latest master solves this but I'm going to need to deploy a new version soon to deal with this

**Comment by ideocrat** [comment]
I have to add that Beaker browser for Windows (downloaded on 10/04/2018 from Beaker Browser website) doesn't have the next and previous buttons in the search bar.

**Comment by taravancil** [comment]
@ideocrat which version of Beaker are you using? Can you share a screenshot?

**Comment by taravancil** [comment]
Ah, we’re no longer actively developing that version. We have a prerelease
for a new version available at:

https://github.com/beakerbrowser/beaker/releases/tag/0.8.0-prerelease.5

I recommend giving it a spin!
