### ISSUE TITLE
Feature: Switch by default to P2P version of web site when available

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#937]

**Comment by todrobbins** [comment]
👍 👍 👍

**Comment by pfrazee** [comment]
Okay here's how I propose we do this:

 - [ ] Add a global setting to "Automatically redirect to dat:// when available", default on (`auto_redirect_to_dat`)
 - When a dat:// version is detected...
   - [ ] ...If `auto_redirect_to_dat=1`, then immediately redirect to the dat:// version
   - [ ] ...else, show the current "P2P version available" badge
 - [ ] After an auto-redirect to dat://, show a new badge that says "HTTPS version available" which will redirect to the https:// version. When clicked, the auto-redirect-to-dat for that site should be disabled for the browsing session.

**Comment by pfrazee** [comment]
Feature merged! Thanks to @Septimus for doing this!
