### ISSUE TITLE
Question: How does one add the "P2P version available" tag to a standard website?

### ISSUE THREAD

**Issue by ChildishGiant** [beakerbrowser/beaker#938]
I have a standard website that I want to mirror on Beaker. How do I point from a hosted website to a beaker version?

![image](https://user-images.githubusercontent.com/13716824/38385546-0e1b01f8-390a-11e8-880c-1a2dd9bd022d.png)

This should probably be in the docs of how to run a beaker site 😄

**Comment by ylebre** [comment]
If I'm not mistaken, the banner appears when the file https://{site}/.well-known/dat is available and points to a dat archive. This also makes the dat version of the site available under the same url as the site as dat://{site}

You can read a bit more about it here: https://medium.com/offline-camp/beaker-browser-f460cb40c4b4 
in the section 'Addresses'.

**Comment by taravancil** [comment]
Hi! We’re currently revamping our docs. Until then, my blog post about how I publish my website might be helpful. 

https://taravancil.com/blog/how-i-publish-taravancil-com/

The key takeaway is that you need to publish a file at https://yourwebsite.com/.well-known/dat that looks like this one (but actually points to the dat:// url for your website)

https://taravancil.com/.well-known/dat

**Comment by ChildishGiant** [comment]
My website is currently hosted on in a folder (https://childishgiant.github.io/perdola/). Do I have to put it at https://childishgiant.github.io/ or https://childishgiant.github.io/perdola/ ? Thanks :)

**Comment by taravancil** [comment]
Hm, I didn't know you could do that with github pages. I *think* you'd put it under https://childishgiant.github.io, but I could be wrong.

@pfrazee wrote a small guide about putting a github.io website on dat a while back

https://gist.github.com/pfrazee/8eb85d7bb33efb52c7d6d1a2e639d979

**Comment by ChildishGiant** [comment]
Yea, you get a page for your user (user.github.io) and pages for each repo (user.github.io/repo)
