### ISSUE TITLE
"Create archive" dialog's default size is too small

### ISSUE THREAD

**Issue by toolness** [beakerbrowser/beaker#940]
Hi!  I am using Beaker v0.7.11 on Windows 10 and I noticed that the "Create archive" dialog is a bit too small to show the ok/cancel buttons at the bottom:

![2018-04-07_6-52-12](https://user-images.githubusercontent.com/124687/38454330-747054e2-3a33-11e8-8a57-8724859e5503.png)

At first I thought this might be because of Windows display scaling, which always seems to mess up things like this, but then I looked at my display properties and saw that my scaling is set to 100%, so I guess it's not that...

If nobody else knows what is going on, I could try investigating further, just let me know.  Thanks again for making this great tool!

**Comment by taravancil** [comment]
This should be fixed in the 0.8 prerelease 

https://github.com/beakerbrowser/beaker/releases/tag/0.8.0-prerelease.5
