### ISSUE TITLE
Accessing internal variables & tab events in new web-api

### ISSUE THREAD

**Issue by cadorn** [beakerbrowser/beaker#943]
I am building a new web-api to control `docker` from a page here: https://github.com/OpenGinseng/beaker/pull/1

I am not sure how to get:

  * Host OS file path to root of site: https://github.com/OpenGinseng/beaker/blob/7a39930a8a9dabb79bfd54082c5375011a57bf18/app/lib/web-apis/docker.js#L24

  * Beaker internal file path: https://github.com/OpenGinseng/beaker/blob/7a39930a8a9dabb79bfd54082c5375011a57bf18/app/lib/web-apis/docker.js#L27

  * `process.env` variables: https://github.com/OpenGinseng/beaker/blob/7a39930a8a9dabb79bfd54082c5375011a57bf18/app/lib/web-apis/docker.js#L103

  * A place to store objects for the duration of an *origin* being loaded in one or more tabs as well as getting access to tab events for lifecycle management all accessible from the web-api module.

Otherwise it is working beautifully! In a beaker site you can:

```javascript
// '/docker' is a directory in a beaker site and contains a Dockerfile
var docker = new window.Docker("/docker", {
  debug: true
});
var proc = docker.run("node boot.js");
```

Sample devtools console output:

![screen shot 2018-04-07 at 1 56 16 pm](https://user-images.githubusercontent.com/18679/38460292-825a350e-3a6b-11e8-900a-424525c48b61.png)

I am thinking about prompting the user to **trust the Dockerfile** by displaying its content once before allowing it to be run.

  * Has the idea of running `docker` via a web-api come up before?
  * Are there discussions on how to enable/load additional web-apis into beaker (when a site/page requests them) so I can package this nicely as an opt-in feature?
  * Is there interest to land this (`docker` API and/or ability to load *privileged code* for a page/site) in beaker?

**Comment by pfrazee** [comment]
Hey @cadorn. Appreciate the thought but we're not interested in integrating Docker into Beaker or supporting Web Extensions. We're pretty picky about what we're integrating into Beaker. If you're looking for an open platform for customization, I suggest using Firefox, since they support extensions.

**Comment by cadorn** [comment]
> not interested in integrating Docker into Beaker or supporting Web Extensions. We're pretty picky about what we're integrating into Beaker. If you're looking for an open platform for customization, I suggest using Firefox, since they support extensions.

I get it but I want to build on top of `beaker`! ;) I am planning to ship my own builds.

How about  *Beaker Plugins* with capabilities to hook into internals to arrive at a stable extension API?

In that light, are you interested in collaborating on a clean internal boundary for my additions to beaker or should I take the *wild west* approach and try and keep up with your internal structural changes?

**Comment by pfrazee** [comment]
@cadorn yeah I'm sorry but we don't have the resources to architect for downstream. You'll have to maintain your fork separately.
