### ISSUE TITLE
`env.beaker_no_welcome_tab` does not seem to be working

### ISSUE THREAD

**Issue by cadorn** [beakerbrowser/beaker#944]
Setting
```
beaker_no_welcome_tab=1
beaker_open_url="workspace://test/"
```
before starting beaker **still opens a `beaker://start/`** tab.

I tried tracing this a bit but it seems tricky. There is various half completed code that touches `beaker_no_welcome_tab`.

**Comment by cadorn** [comment]
I am looking to have it only open the tab specified with:
```
beaker_open_url="workspace://test/"
```

**Comment by pfrazee** [comment]
That makes sense. How about I update `beaker_open_url` to just open that URL and not start.

**Comment by pfrazee** [comment]
Okay fixed!
