### ISSUE TITLE
Alt + num to change tab

### ISSUE THREAD

**Issue by kodedninja** [beakerbrowser/beaker#945]
It's a pretty general way to change tab with ```Alt + num``` and I miss it sometimes.

Don't know if it was already mentioned.

Operation System: Ubuntu 14.04
Beaker version: Beaker pre-release .4

**Comment by kodedninja** [comment]
Oh, sorry, I come from Firefox and it uses Alt, but Chrome uses Ctrl too.

**Comment by jraspiprojects** [comment]
Ctrl is (pretty much) the Cmd key on windows.
