### ISSUE TITLE
Error in visualizing some unicode characters

### ISSUE THREAD

**Issue by elaspog** [beakerbrowser/beaker#948]
Operation System: Windows 10
Beaker version:  v0.7.11

Some unicode characters (e.g.: áéíóöőúű) are not properly visualized when a markdown site is created:

![capture2](https://user-images.githubusercontent.com/7151214/38638703-6612f28e-3dcf-11e8-8dae-7a9504c8225a.PNG)

![capture](https://user-images.githubusercontent.com/7151214/38638709-6a22b026-3dcf-11e8-9721-7462be8e542a.PNG)

**Comment by brechtpm** [comment]
This has been fixed in v0.8 already. The beta version right now seems pretty stable, so you might want to consider making the switch already :)
