### ISSUE TITLE
Invalid index error on app launch

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#951]
Operation System: macOS 10.13.4
Beaker version: v0.8.0-prerelease.5

I get this error occasionally on app launch:

![screen shot 2018-04-09 at 4 57 44 pm](https://user-images.githubusercontent.com/158590/38760342-f03363d6-3f37-11e8-84b9-c7d734e3a8a7.png)

I forgot to copy/paste the actual text instead of taking the screen grab this time. Sorry!

**Comment by pfrazee** [comment]
No worries about the screen grab. Thanks for filing, I'll check into it.

**Comment by pfrazee** [comment]
PR which doesn't solve the core error but keeps it from causing an uncaught exception: https://github.com/mafintosh/append-tree/pull/13

**Comment by pfrazee** [comment]
Ok that got merged, we'll deploy the fixed version in next release
