### ISSUE TITLE
Exception: cannot read property 'data' of null

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#953]
Operation System: MacOS
Beaker version: 0.8.0-prerelease.5

![image](https://user-images.githubusercontent.com/1270099/38828116-a15b5350-417a-11e8-8c6e-f3a4d70789fc.png)

Happened while Tara was idling on Fritter

**Comment by taravancil** [comment]
thx for showing the whole world that I was searching "destiny's child best outfits"

**Comment by pfrazee** [comment]
Fix is upstream https://github.com/mafintosh/hypercore/pull/156
