### ISSUE TITLE
discussion: auto-sync instead of workspace is errorprone and imo dangerous.

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#955]
Operation System: all
Beaker version: https://github.com/beakerbrowser/beaker/commit/5290571710e9e686adbd13dce6adf9d1726b3717

Hmm, Now the user has no control, when changes in the local folder are synced to the "live version". ... 

IMO that's extremely inconvenient, since what ever is stored in .dat can't be removed. ... 

eg: 

 - I have a file, that contains some "private" data. 
 - I want to send a modified version to a friend
 - Since I don't want to loose my original I do create a temporary copy
 - I modify the temporary copy. 
 - I copy the "modified version" to the "auto-sync" folder
 - I read the "modified version" one more time (just to be sure) and find out that I did forget to remove  - some compromising info. 
--- BUT it's too late. The stuff is synced all over the world _and_ it can't be deleted. 

I know, that's my fault. ... 

But for me this means: **The first thing to do, if I discover a new dat archive, is to study the history. There will be a lot of interesting stuff, that's there by accident.**

just some thoughts.

**Comment by webdesserts** [comment]
To quote @pfrazee from the PR https://github.com/beakerbrowser/beaker/pull/954

>This new solution solves requirements 1, 3, 5, and 6, but it needs a solution for handling the "published" version. To do that:
>    - Dats will be able to diff and merge between each other.
>    - The user will be able to set a dat as the "publish target" of another dat.
>    - As a result, the user will get a diffing UI that's similar to the current workspaces UI, but it will be from the "draft dat" to the "published dat" instead of from a workspace folder to the published dat.
>    - (Possibly) there will be metadata indicating when a dat is a draft or the publish target.

and

> This PR will only include the syncing folder. The publish target controls need a little more thought, and so we'll handle them in a subsequent PR.

This followup PR will be replacing the "publish" step that workspaces previously had, allowing you to queue up changes in another dat. With that in mind, do you think this solves the above issues, and if it doesn't, where do you think it could improve?

It also seems that @pfrazee has [played around](https://github.com/beakerbrowser/beaker/commit/f910b676adef6ff03cbab75ae8acd10abc4eaf05) with a "stop syncing" control, though to be honest, I couldn't find it in the interface. I'm also not sure if this dissociates the folder or if it temporarily "pauses" syncing to that folder.

**Comment by pmario** [comment]
Thx for the info. I didn't click the #954 link. ... I should have :) ... I'll have closer look now.

**Comment by pmario** [comment]
>@pmario This followup PR will be replacing the "publish" step that workspaces previously had, allowing you to queue up changes in another dat. With that in mind, do you think this solves the above issues, and if it doesn't, where do you think it could improve?

I think, it will solve my concerns, for now. ... If the UI can effectively protect users against publishing draft DATs.

**Comment by pmario** [comment]
Is there a "whitepaper" about the planned workflow? ... because I don't think, that it will remove much complexity. ...

**Comment by pfrazee** [comment]
@pmario #954 is about as detailed as a formal writeup will get
