### ISSUE TITLE
Suggestions needed from developer

### ISSUE THREAD

**Issue by hammad786** [beakerbrowser/beaker#960]
Operation System: Windows
Beaker version: 0.7

Dear developer,

Hope you're doing well :)

I was wondering if we can make portables using Beaker. Actually, I'm creating an Electron-based app where I need the proper browser functionalities and to me, Beaker looks perfect in UI and pretty light-weight too.

**This is what I'm trying to achieve with my app;**

there will be few sites in the portable with saved cookies so the user will be served pre-login sites (in short I don't want to share credentials with them). 

**The problem I'm facing;**

I need a ready-made browser for this purpose so I don't have to focus on browser functionalities and Beaker looks perfect to me but I'm not sure whether achieving this with Beaker will be complex or not. 

**Beaker UI**

Did you use any ready-made UI components to achieve chrome like UI or its all designed by you? Anyway, UI is too good. I wish If you could public the UI components with us.

Please let me know your thoughts on this. If you have any better suggestion based on my scenario, please share.

Any help on this would be highly appreciated.

Thanks in advance!

**Comment by DakshMiglani** [comment]
+1

**Comment by pfrazee** [comment]
Hi @hammad786. Sorry but I'm not totally sure what you're asking for. We don't currently have any interest in making Beaker a generic set of components, or a generic repackageable browser. Beaker is purpose-built to move the Web platform in a new direction. The source is open so you can extract any code you like (please do!).
