### ISSUE TITLE
DatArchive Feature Request: application support for SQLite files

### ISSUE THREAD

**Issue by tswast** [beakerbrowser/beaker#963]
I'm working on a custom pixel art (distributed) web application and am thinking about how I want to store the custom file format. A directory with some JSON files plus some PNG files would probably work, but it's nice to have a single file representing an artifact.

I believe [SQLite could be great for custom file types](https://www.sqlite.org/affcase1.html) and since dat is able to efficiently share partial updates to files, I think it'd be a good fit for the protocol, too.

Without native browser support, I believe I can use a [JavaScript port of SQLite](https://github.com/kripken/sql.js/) which works in-memory and occasionally serialize the whole thing to DatArchive, but this loses much of the benefits of SQLite's ability to do partial updates. It'd be lovely if I could use SQLite directly with data in the staging area.

**Comment by tswast** [comment]
Looks like [hyperdb will be coming soon](https://mobile.twitter.com/pfrazee/status/977214312258433026). Possibly that will cover the same niche, but also support multi-writers, which SQLite would not.

**Comment by pfrazee** [comment]
@tswast yeah hyperdb will be the solution we recommend. Especially because: 

> I believe SQLite could be great for custom file types and since dat is able to efficiently share partial updates to files

That's not actually true. Dat doesn't do partial-updates/diffs to files. Each new version of a file is synced in full right now.

FWIW the original plan was to add SQLite support for the reasons you say, so I agree it's a great solution. (I love SQLite.) But I think hyperdb is going to be a much more powerful *core* toolset and we'll be able to produce strong interfaces on top of it.

**Comment by tswast** [comment]
> That's not actually true. Dat doesn't do partial-updates/diffs to files. Each new version of a file is synced in full right now.

Good point. I got confused by the [content defined chunking](https://github.com/datproject/docs/blob/master/docs/how-dat-works.md#phase-3-data-exchange) for syncing (not versioning) partial files.

**Comment by pfrazee** [comment]
Bleh yeah, I hate to say it but that document isn't accurate right now either. CDC got removed because the performance was not great and we weren't getting a huge benefit from it. It might come back in the future but it's not a priority atm.
