### ISSUE TITLE
Network tab (under Library) gives error on not fully downloaded site

### ISSUE THREAD

**Issue by djbacon** [beakerbrowser/beaker#967]
Operating system: Ubuntu MATE 18.04 LTS (64-bit)

This is:

- [ x ] a bug
- [ ] general feedback
When i enter NETWORK tab  on website that is not fully downloaded i tab is not activated, but if i click Network tab and then refresh page, then i get error (see attachment).

![screenshot at 2018-04-26 15-21-09](https://user-images.githubusercontent.com/4469641/39305502-ffc79cb2-4965-11e8-86ae-e35370d4c882.png)

**Comment by pfrazee** [comment]
Ouch thanks for reporting, I'll hit that now.

**Comment by pfrazee** [comment]
Should be fixed in latest master
