### ISSUE TITLE
Svg object's data isn't loaded with CSP errors

### ISSUE THREAD

**Issue by icarito** [beakerbrowser/beaker#968]
Operation System: Debian GNU/Linux
Beaker version: 0.8 development (tried 0.8 prerelease and git sources)

Console error:
```
(index):228 Refused to load plugin data from 'dat://butterfly68-icarito.hashbase.io/mariposa68.svg' because it violates the following Content Security Policy directive: "object-src 'none'".
```

Looks related to #497 and #498 but couldn't find a specific issue about it.

**Comment by icarito** [comment]
Oh the issue can be seen at:

[dat://butterfly68-icarito.hashbase.io/](dat://butterfly68-icarito.hashbase.io/)

Please compare with:
https://butterfly68-icarito.hashbase.io/

**Comment by pfrazee** [comment]
Newest release has custom CSPs (set [content_security_policy](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy) on the dat.json). Until then, it should be possible to do SVGs in an `<img>` tag, right?

**Comment by icarito** [comment]
Hey @pfrazee thanks for your response! Sadly `<img>` doesn't work in this case because then Svg is opaque, versus as `<object>` it is possibly to manipulate the Svg's DOM, which is what we used to flap the butterfly's wings. I'll look at the right _content_security_policy_ to set in this case. Thanks!

**Comment by icarito** [comment]
Following up @pfrazee , I did find the fix for `content_security_policy` header. I was confused because of the syntax seen in #497 but finally I added: `"content_security_policy": "object-src *;"` and it worked with Beaker master git development version (but not in the 0.8.0-prerelease.5) !

**Comment by icarito** [comment]
Thanks!
