### ISSUE TITLE
Why not make a Chrome Extension?

### ISSUE THREAD

**Issue by zyl550** [beakerbrowser/beaker#970]
There are too many tools that can not leave on Chrome

**Comment by RangerMauve** [comment]
Check out [this thread](https://github.com/datproject/discussions/issues/84) for efforts on getting Dat to work in other browsers. There's already a [firefox extension](https://github.com/sammacbeth/dat-fox), and it should be easy enough to make a chrome one by looking at what [ipfs-companion](https://github.com/ipfs-shipyard/ipfs-companion/blob/1d537c78b2d81fae8abc2c995c517205287b2c64/add-on/src/lib/ipfs-request.js#L21) did.

**Comment by HughIsaacs2** [comment]
If you want a Chrome extension for viewing Dat sites, I've made one some time ago (I honestly prefer Beaker Browser though, extensions are limited).

https://github.com/hughisaacs2/datpart
