### ISSUE TITLE
Markdown renderer is adding opening spaces to <pre> blocks

### ISSUE THREAD

**Issue by todrobbins** [beakerbrowser/beaker#973]
**Operation System: macOS High Sierra 10.13.4 (17E199)**
**Beaker version: v0.8.0-prerelease.5**

I've noticed the Markdown renderer adds a space to `<pre>` blocks, but I could't find where it might be happening within [markdown.less](https://github.com/beakerbrowser/beaker/blob/54ee1f19d8b988ffceab6481f9feaf91f6e46418/app/stylesheets/com/markdown.less) or [markdown-renderer.js](
https://github.com/beakerbrowser/beaker/blob/54ee1f19d8b988ffceab6481f9feaf91f6e46418/app/markdown-renderer.js):

<img width="340" alt="screen shot 2018-04-26 at 5 52 03 pm" src="https://user-images.githubusercontent.com/158590/39478831-bb718794-4d20-11e8-8ca1-7a208c537c50.png">
<img width="347" alt="screen shot 2018-04-26 at 5 52 10 pm" src="https://user-images.githubusercontent.com/158590/39478832-bb8b32de-4d20-11e8-82cf-4d6d7754ef1a.png">
<img width="243" alt="screen shot 2018-04-26 at 5 52 18 pm" src="https://user-images.githubusercontent.com/158590/39478833-bba040de-4d20-11e8-87c1-71e8056f63fc.png">
<img width="155" alt="screen shot 2018-04-26 at 5 52 24 pm" src="https://user-images.githubusercontent.com/158590/39478834-bbb9bef6-4d20-11e8-9068-05b162cdc06f.png">

Is this behavior intentional?

**Comment by pfrazee** [comment]
Fixed in master!
