### ISSUE TITLE
Question: Does fetch works for dat request ?

### ISSUE THREAD

**Issue by Evanlai8** [beakerbrowser/beaker#979]
I use fetch to get remote dat://  sites, get the error

>Refused to connect to 'dat://b86748ff5891b0a2c40e7297d6ca2724c3efb9ec90e8ee3e673fede5f9631d84/index.html' because it violates the following Content Security Policy directive: "connect-src 'self' ebooker: http: https".

if fetch doesn't work , is there any way to get the remote dat contents ?

**Comment by RangerMauve** [comment]
That's what the [DatArchive API](dat://beakerbrowser.com/docs/apis/by-example.html) is for.

It lets you read files from a dat:// site, as well as create new dat sites and look at history / react to changes.

**Comment by pfrazee** [comment]
@Evanlai8 what version of Beaker are you using, and was this on a dat site?

**Comment by Evanlai8** [comment]
@RangerMauve  I can use DatArchive API to read dat files which I have sync in my local computer, but can't read files in remote dat (my situation is I don't want to sync all dat sites, just want to get content of a file in remote source)
I have tried to use DatArchive to read remote dat file, response is file not found
the code is:
```
url = '924404e7b802ccc0c7f98eb8c93d49cc8df3a3727489fca30b88b9be0cfdc72f/public/test.html'
let parseUrl = parseDatURL(url)
let newArchive = new DatArchive(parseUrl.origin)
let html = await newArchive.readFile(parseUrl.pathname, 'utf8')
```

I saw @pfrazee  have add Fetch api to beaker in  #114  , so I try to use fetch, but didn't work
@pfrazee I use beaker v0.7.11, 

This is my code
```
      let op = {
          headers: {
          'Accept': 'text/html',
          'Content-Type': 'text/html',
          'Access-Control-Allow-Origin': '*',
          },
          method: 'GET'
      }
      fetch('url', op).then(res => { return res.text() }).then(data => {console.log('data',data)})
```

**Comment by RangerMauve** [comment]
What errors are you seeing in the developer console?

Are you sure that `parseURL.origin` is the dat key?

I think that DatArchive requries the argument to be an actual URL, so you'll want `new DatArchive('dat://' + parseUrl.origin)`

What library are you using for `parseDatURL`? I've had trouble using [parse-dat-url](https://www.npmjs.com/package/parse-dat-url) in the browser and have been using [url-parse](https://www.npmjs.com/package/url-parse) in the meantime.

**Comment by pfrazee** [comment]
> I can use DatArchive API to read dat files which I have sync in my local computer, but can't read files in remote dat (my situation is I don't want to sync all dat sites, just want to get content of a file in remote source)

The `DatArchive` API only fetches the files you access. It will behave 100% the same way as `fetch()` would.

**Comment by Evanlai8** [comment]
@RangerMauve I use parse-dat-url, and its fine for me,  parseUrl.origin contains 'dat://' prefix,
 
DatArchive works,  Thanks, it could be my network problems, but the fetch() is still not work, even thought fetch my local dat content. 

I just want to get the content of a file , but the whole dat content will be downloaded to my computer. 
if the dat site have many files and large data, is there a way to just get a certain file rather than download the dat site？

**Comment by pfrazee** [comment]
`fetch()` does work for Dat sites but the Content-Security-Policy of @Evanlai8's site doesn't include the `dat:` protocol. In the latest version of Beaker, you can control dat sites' CSPs in the dat.json but Im sort of confused by @Evanlai8's situation because his CSP includes `ebooker:` and I have no idea where that comes from.

**Comment by Evanlai8** [comment]
@pfrazee  It is the  Content-Security-Policy problem, 
I add "connect-src 'self' beaker: dat:"   to  "BEAKER_CSP' at protocols/beaker.js and fetch() works

**Comment by pfrazee** [comment]
👍
