### ISSUE TITLE
Configurable caps on the bandwidth used by dat (up and down)

### ISSUE THREAD

**Issue by nintha** [beakerbrowser/beaker#980]
Operation System: win10  1709
Beaker version: Beaker v0.8.0-prerelease.5 

Beaker upload file use too much bandwidth. I can't do another things. However, I still want to share files to my friends.
How can I limit it? Have any settings to do it?
THX.

**Comment by pfrazee** [comment]
Not possible yet but needed. We'll put this on the roadmap! Thanks for asking.

**Comment by RangerMauve** [comment]
I think that in addition to setting caps on seeding, there should be caps on how much an app can upload to a dat.

Most web APIs have restrictions on data storage, and I think that will be needed eventually if mainstream browsers are going to adopt this.

Maybe there could be a small default cap, and user input for asking for more storage?

**Comment by pfrazee** [comment]
@RangerMauve there already is

**Comment by pfrazee** [comment]
@RangerMauve https://beakerbrowser.com/docs/apis/dat.html#disk-usage-and-quotas

**Comment by RangerMauve** [comment]
Thank you!

**Comment by pfrazee** [comment]
Added in a feature branch, will be in the next release
![screen shot 2018-07-19 at 1 59 10 pm](https://user-images.githubusercontent.com/1270099/42964211-f9fc2e14-8b5b-11e8-87f3-a58318e720c9.png)
