### ISSUE TITLE
The watch-build tool needs to be reworked if it's going to be enabled

### ISSUE THREAD

**Issue by paul90** [beakerbrowser/beaker#982]
Operation System: macOS
Beaker version: github master branch

Using fritter as an example...
https://github.com/beakerbrowser/fritter/blob/46866621f23e0219d1a9ac6466fb4eace8bc344a/package.json#L12

If you have beaker 0.8 open when you run `npm run build-prod`, the change in the folder will be detected and `build-watch`. 

So, if you want to create a production build you would need to:
1. Exit beaker,
1. run `npm run build-prod`, and
1. copy the files generated by the build process elsewhere, probably to a prerelease dat
before you reopen beaker.
If you don't exit beaker first, you will see the output from `npm run build-prod` be generated only to be replaced moments later by `watch-build` being run.

It would be more natural, and in line with other watch processes, if `build-watch` was only run when a change in the source files was detected. This will need some configuration by the user, to specify a pattern for the source files.

**Comment by pfrazee** [comment]
Good catch. We might need something more sophisticated to configure this. I'll think about this and see what other toolsets do.

**Comment by pfrazee** [comment]
One option is to use some `dat.json` fields:

```js
{
  "build": {
    "watch": true,
    "exec": "npm run build", // whatever shell command you need
    "filter": "*.build.js\n*.css" // optional newline separated list of files that should not trigger build (if not specified uses dat.json)
  }
}
```

**Comment by paul90** [comment]
Not sure, wouldn't it be more natural to define a pattern of what to watch?

Rather than using a string with `\n` to separate values, use an list/array (a single value could still be a string)? The filter example would become `"filter": ["*.build.js", "*.css"]`. Maybe use minimatch to do the filtering?

**Comment by webdesserts** [comment]
Another pitfall that I'm worried about is malicious script execution. I could easily imagine someone duplicating a site, reading the readme, hitting the "build button" (or triggering a watch) without ever actually opening up the dat.json.

**Comment by pfrazee** [comment]
@webdesserts You're right, an open `exec` field could do damage. Hum. I'm going to have to think about that.

**Comment by pfrazee** [comment]
I decided to disable this feature until we have a safe exec environment for build scripts. Good catch @webdesserts

**Comment by webdesserts** [comment]
@pfrazee That will make me feel a bit better. For reference, what reasons where you wanting to implement this? From the outside I can see two reasons:

1. To avoid the need to implement a "watch" task and just reuse the "build" task for most projects
2. To tell Beaker to wait for the build task to complete before reload, rather than reloading multiple times as a project is building.

**Comment by pfrazee** [comment]
@webdesserts Right on both points. It's not vital but I wanted to make the DX as good as possible
