### ISSUE TITLE
Manually adding a file to the folder works properly, but using archive.writeFile() works in the opposite way

### ISSUE THREAD

**Issue by bgcarlisle** [beakerbrowser/beaker#985]
Operation System: Mac OS
Beaker version: 0.8.0

If I copy test.txt to my site's folder, I get a green unpublished file and when I click Publish, everything works as expected.

If I use archive.writeFile() to make a new file, it appears as a red deletion. When I click "Publish," it deletes the new file. When I click "Revert," it publishes it.

**Comment by pfrazee** [comment]
Hey @bgcarlisle 

Long story short, this is one of many problems that workspaces have. We're reworking them to fix this. You can read the details at https://github.com/beakerbrowser/beaker/issues/957

**Comment by bgcarlisle** [comment]
Great, thanks!
