### ISSUE TITLE
Create archive directly from local directly via Dat Application

### ISSUE THREAD

**Issue by joehand** [beakerbrowser/beaker#990]
A group built `dat://trackbook.hashbase.io/start` during a hackathon last week. The goal is to add a user interface to files in a local directory to encourage certain behavior, e.g. *when X file updates, made sure you update documentation in Y file*. This assumes:

1. Users will mostly be looking/working at files in their local folder, not beaker
2. There will be a two way sync between Beaker and local folders

`2.` is solved by the latest update removing workspaces. 

---

`1.` is still a bit tricky. We assume users will *always* be importing a local folder into Beaker. This means that to add an archive to trackbook is always a two step process:

1. Import local folder into Beaker
2. Add archive to trackbook

It'd be great to simplify this to one step, with two potential methods:

1a. `DatArchive.create({path:/existing/local/folder/path})`
1b.  Provide the local folder import menu on the `Create new Archive` button after using `DatArchive.selectArchive()`

**Comment by karissa** [comment]
@pfrazee curious why you can't expose local paths to approved apps?

It would be pretty interesting to see Beaker be able to have an 'app-store' interaction where we can have at least access to dat ecosystem that is available to electron applications also available in Beaker.

**Comment by pfrazee** [comment]
We're trying to follow existing browser policy, which doesn't ever expose file paths from the local FS.

The current security model is that all filesystem access is sandboxed to Dat archives. We could someday have apps with elevated permissions but that's going to have to be an explicit choice sometime down the road.
