### ISSUE TITLE
Download Percentage only shows currently viewed version

### ISSUE THREAD

**Issue by webdesserts** [beakerbrowser/beaker#997]
**Operating system**: Mac OS 10.13
**Version**: master f88eef153f3ce1fc78a3722444a570ebc454dd79

This is:

- [ ] a bug
- [x] general feedback

If I visit the Network tab of a site in the latest version, it displays the percent of files downloaded for that entire archive. However, if I view a previous version of the archive and visit the network tab again, it will show me a different percentage. I assume that this is because it is now representing the number of files that I've downloaded from that specific version. This wasn't immediately clear to me the first time I ran into it.

![changing-download-percentage](https://user-images.githubusercontent.com/916253/40396211-58e52b44-5df1-11e8-8f7d-200cee59d28e.gif)

On a similar note, is the network activity also version specific? Is it only showing the peers that are also hosting that specific version of the archive? Or are those peers still global to the archive?

**Comment by webdesserts** [comment]
Interestingly, if I click "delete downloaded files" it will delete **all** downloaded files rather than just data specific to that version.

**Comment by pfrazee** [comment]
Ah, good catch. It should probably show progress for all history (for now) in all cases. I'll fix that up.

**Comment by webdesserts** [comment]
@pfrazee I'm fine with only showing progress for all files relevant to the current version, but from what I can tell that's not exactly what's going on right now. Currently the bar is showing download progress for the current version and all previous versions as well. So if the argument is that history doesn't matter to most users, then we probably shouldn't be displaying the download progress of irrelivant files from history.

**Comment by pfrazee** [comment]
I'll check this again

**Comment by pfrazee** [comment]
I just double checked this. I'm pretty sure the download progress bar only shows progress for latest files.
